import { useEffect, useRef, useState } from 'react'
import fieldLabels from '../../../shared/ai-business-field-labels.json'
import { BottomSheetSurface, HohoButton } from '../../components/design-system'
import type { JournalMetadata } from '../../types/journal'
import './aiBusiness.css'
import { AIResultPreview, type AIUnverifiedPreview } from './AIResultPreview'
import { QuickVoiceRecordFlow } from '../../pages/HealthEventDetail/components/QuickVoiceRecordFlow'
import { quickRecordService } from '../../services/quickRecords'
import { recordingToWav } from './recordingAudio'
import { AudioRequestError, audioErrorMessage } from './audioErrors'
import { useAppStore } from '../../store/useAppStore'
import { CaseCaptureWorkspace } from './CaseCaptureWorkspace'
type Field={name:string;value:string;editedBy:string;sources:{sourceId:string;page:number;quote:string}[]}
type Item={id:string;category:string;title:string;timeText:string|null;fields:Field[];journal:JournalMetadata;time:{resolvedStart:string|null;precision:string};archiveCategory:string|null;originText?:string}
type Draft={id:string;version:number;state:string;preview?:AIUnverifiedPreview|null;inputText:string;conflicts:{itemId:string;text:string}[];confirmConflicts:boolean;documentWarnings:string[];confirmPageWarnings:boolean;unmappedRows:{sourceId:string;page:number;text:string}[];items:Item[];questions:{id:string;itemId:string;field:string;label:string}[];sources:{id:string;page:number;text:string;status:string}[];pages:{id:string;page:number;name:string}[];result:{count:number;records:{eventId:string;recordId:string}[]}|null}
const labels:Record<string,string>={...fieldLabels,relationship:'亲属关系',vaccineName:'疫苗名称',manufacturerName:'生产企业',batchNumber:'批号'}
const archiveLabels:Record<string,string>={allergy:'过敏史',chronic:'慢性病史','family-history':'家族史',surgery:'手术史',vaccination:'疫苗接种记录',examination:'检查／就诊资料',medication:'长期用药'}
const categoryLabels:Record<string,string>={diet:'饮食',sleep:'睡眠',elimination:'排便',activity:'活动',emotion:'情绪',social:'社交',symptom:'症状',measurement:'测量',growth:'成长',injury:'受伤',medication:'用药',care:'护理',vaccination:'接种',environment:'环境',visit:'就诊',examination:'检查',other:'其他'}
const dataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('文件读取失败'));r.readAsDataURL(blob)})
type ComposerProps = {memberId:string;token:string;onClose:()=>void;onSaved?:(message:string)=>void;onApply?:(item:Item)=>void;initialTask?:'record'|'report'|'visit'|'archive';profileMode?:boolean;memberName?:string;eventId?:string;taskId?:string;onCaptured?:(eventId:string)=>void;structuredReview?:boolean;initialText?:string;initialFiles?:File[];sourceIdentity?:string;initialDraftId?:string}
export function AIBusinessComposer(props: ComposerProps) {
  const accountId = useAppStore(s => s.authUser?.id ?? 'guest')
  return props.profileMode || props.structuredReview ? <StructuredBusinessComposer {...props}/> : <CaseCaptureWorkspace key={`${accountId}:${props.memberId}:${props.eventId ?? ''}:${props.taskId ?? ''}`} memberId={props.memberId} token={props.token} onClose={props.onClose} onSaved={props.onSaved} initialEventId={props.eventId} taskId={props.taskId} onCaptured={props.onCaptured}/>
}
function StructuredBusinessComposer({memberId,token,onClose,onSaved,onApply,initialTask='record',profileMode=false,memberName='',eventId,initialText='',initialFiles=[],sourceIdentity,initialDraftId}:ComposerProps){
  const accountId=useAppStore(state=>state.authUser?.id??''),credentials=useRef({accountId,token});credentials.current={accountId,token}
  const [phase,setPhase]=useState('正在处理…')
  const [transcribing,setTranscribing]=useState(false),[voiceError,setVoiceError]=useState(''),[ttsConfigured,setTtsConfigured]=useState(false),[canRetryVoice,setCanRetryVoice]=useState(false)
  const pendingAudio=useRef<Blob|null>(null)
  const [previewText,setPreviewText]=useState(''),[manualText,setManualText]=useState<string|null>(null),manualKey=useRef('')
  const [text,setText]=useState(initialText),[task,setTask]=useState(initialTask),[files,setFiles]=useState<File[]>(initialFiles),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[voiceReply,setVoiceReply]=useState(false)
  const draftRef=useRef<Draft|null>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),abort=useRef<AbortController|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),audio=useRef<HTMLAudioElement|null>(null),audioUrl=useRef(''),cancelled=useRef(false),session=useRef(0),operationPending=useRef<number|null>(null),operationSequence=useRef(0),permissionPending=useRef(false),recordingGeneration=useRef(0)
  const url=`/api/members/${encodeURIComponent(memberId)}/ai-drafts`
  useEffect(()=>{let active=true;setTtsConfigured(false);void fetch('/api/ai/audio/capabilities',{headers:{Authorization:`Bearer ${token}`}}).then(async response=>{if(!response.ok)return;const capabilities=await response.json();if(active)setTtsConfigured(capabilities.tts?.configured===true)}).catch(()=>undefined);return()=>{active=false}},[memberId,token])
  const [originals,setOriginals]=useState<Record<string,string>>({}),originalUrls=useRef<string[]>([])
  const audioContext=useRef<AudioContext|null>(null),audioSampler=useRef<ReturnType<typeof setInterval>|null>(null),audioPeak=useRef<number|null>(null)
  useEffect(()=>()=>{originalUrls.current.forEach(url=>URL.revokeObjectURL(url))},[])
  const current=(d:Draft|null)=>{draftRef.current=d;setDraft(d);setPreviewText(d?.preview?.text??'')}
  const stopPlayback=()=>{audio.current?.pause();audio.current=null;if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current=''}
  const stopTracks=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(timer.current)clearInterval(timer.current);timer.current=null;if(audioSampler.current)clearInterval(audioSampler.current);audioSampler.current=null;void audioContext.current?.close().catch(()=>undefined);audioContext.current=null}
  const interrupt=()=>{stopPlayback();session.current++;recordingGeneration.current++;cancelled.current=true;abort.current?.abort();if(recorder.current?.state==='recording')recorder.current.stop();recorder.current=null;stopTracks();permissionPending.current=false;operationPending.current=null;setRecording(false);setBusy(false);setTranscribing(false);if(pendingAudio.current){setVoiceError(audioErrorMessage({code:'ASR_CANCELLED'}));setCanRetryVoice(true)}}
  useEffect(()=>{const hide=()=>{if(document.visibilityState==='hidden')interrupt()};document.addEventListener('visibilitychange',hide);return()=>document.removeEventListener('visibilitychange',hide)},[])
  // Token refresh is not a change of data owner. Only owner/member/closure
  // ends this recording session; normal resume must retain retryable audio.
  useEffect(()=>{session.current++;return()=>{session.current++;recordingGeneration.current++;cancelled.current=true;abort.current?.abort();if(recorder.current?.state==='recording')recorder.current.stop();stopTracks();stopPlayback();pendingAudio.current=null;const d=draftRef.current,cleanupToken=credentials.current.accountId===accountId?credentials.current.token:token;if(d&&d.state!=='saved'&&!profileMode&&!eventId)void fetch(`${url}/${d.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${cleanupToken}`}}).catch(()=>undefined)}},[memberId,accountId,profileMode,eventId])
  async function request<T>(path:string,method:string,input?:unknown):Promise<T>{const turn=session.current,controller=new AbortController();abort.current=controller;const response=await fetch(path,{method,headers:{Authorization:`Bearer ${credentials.current.token}`,'Content-Type':'application/json'},body:input===undefined?undefined:JSON.stringify(input),signal:controller.signal});const isAudio=path==='/api/ai/audio/transcriptions';let result;try{result=await response.json()}catch{if(isAudio)throw new AudioRequestError('ASR_OUTPUT_INVALID',response.status);throw new Error('服务响应无法读取，原稿仍保留')}if(turn!==session.current)throw new DOMException('Cancelled','AbortError');if(!response.ok){if(isAudio)throw new AudioRequestError(result.error?.code??'ASR_UPSTREAM_UNAVAILABLE',response.status,result.error?.requestId??null);throw new Error(result.error?.message||result.message||'操作暂时失败，原稿仍保留')}return result as T}
  const run=async(operation:()=>Promise<void>,status='正在处理…')=>{if(operationPending.current!==null)return;const operationId=++operationSequence.current;operationPending.current=operationId;const turn=session.current;setPhase(status);setBusy(true);setError('');try{await operation()}catch(e){if(turn===session.current&&!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'操作失败，请重试')}finally{if(operationPending.current===operationId)operationPending.current=null;if(turn===session.current)setBusy(false)}}
  useEffect(() => { if (initialDraftId) void run(async () => { let retained = await request<Draft>(`${url}/${initialDraftId}`,'GET'); if (retained.state !== 'saved' && (eventId || sourceIdentity)) retained = await request<Draft>(`${url}/${retained.id}`,'PATCH',{version:retained.version,eventId,sourceIdentity}); current(retained); setText(initialText || retained.inputText); setFiles([]); setNotice('已恢复同一份识别草稿，核对后才保存'); }) }, [initialDraftId])
  async function playReply(d:Draft){if(!voiceReply)return;const turn=session.current;stopPlayback();try{const result=await request<{mimeType:string;data:string}>(`${url}/${d.id}/speech`,'POST');const blob=await(await fetch(`data:${result.mimeType};base64,${result.data}`)).blob();if(turn!==session.current||cancelled.current)return;audioUrl.current=URL.createObjectURL(blob);audio.current=new Audio(audioUrl.current);await audio.current.play()}catch{if(turn===session.current&&!cancelled.current)setNotice('语音回复暂不可用，文字结果仍可查看')}}
  async function prepareText(raw=text){stopPlayback();const d=draftRef.current;const inputFiles=await Promise.all(files.map(async f=>({name:f.name,mimeType:f.type,dataUrl:await dataUrl(f)})));try{const next=await request<Draft>(url,'POST',{id:d?.id,version:d?.version,text:raw,task,eventId,sourceIdentity,reviewArchives:profileMode,files:inputFiles,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});current(next);setFiles([]);setNotice('已整理，核对后才会保存');await playReply(next)}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError')){try{const retained=await request<Draft|null>(d?`${url}/${d.id}`:url,'GET');if(retained){current(retained);if(retained.pages.length)setFiles([])}}catch{/* Keep the local previous version if recovery is unavailable. */}}throw e}}
  const prepare=()=>void run(()=>prepareText(),'上传／识别中，请稍候…')
  const edit=(input:Record<string,unknown>)=>void run(async()=>{if(!draft)return;current(await request<Draft>(`${url}/${draft.id}`,'PATCH',{version:draft.version,...input}))})
  async function saveCurrent(){const d=draftRef.current;if(!d?.items.length||d.state!=='ready')throw new Error('请先成功整理并核对记录');if(text!==d.inputText||files.length)throw new Error('原文或资料已有修改，请先继续整理');const saved=await request<Draft>(`${url}/${d.id}/save`,'POST',{version:d.version,confirmed:true});current(saved);setNotice(`已保存 ${saved.result?.count??0} 条记录`);onSaved?.(`已保存 ${saved.result?.count??0} 条记录`);await playReply(saved)}
  async function cancelCurrent(){interrupt();pendingAudio.current=null;setCanRetryVoice(false);setVoiceError('');const d=draftRef.current;if(d&&d.state!=='saved')await fetch(`${url}/${d.id}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});current(null);setText('');setFiles([]);setNotice('已取消，未保存资料');setError('')}
  async function transcribeRecording(){
    const blob=pendingAudio.current;if(!blob||operationPending.current!==null)return
    const turn=session.current,operationId=++operationSequence.current;operationPending.current=operationId;setTranscribing(true);setBusy(true);setVoiceError('');setPhase('录音已停止，正在转写为文字…')
    try{
      const wav=await recordingToWav(blob)
      if(turn!==session.current||cancelled.current)return
      const result=await request<{transcript:string}>('/api/ai/audio/transcriptions','POST',{memberId,mimeType:wav.type,dataUrl:await dataUrl(wav),name:'recording.wav'})
      if(turn!==session.current||cancelled.current)return
      if(typeof result.transcript!=='string'||!result.transcript.trim())throw new AudioRequestError('ASR_NO_SPEECH',422)
      setText(previous=>previous?`${previous}\n${result.transcript}`:result.transcript)
      pendingAudio.current=null;setCanRetryVoice(false);setNotice('转写完成，请先编辑核对文字，再点击整理；不会自动保存')
    }catch(e){if(turn===session.current){setVoiceError(audioErrorMessage(e));setCanRetryVoice(true)}}
    finally{if(operationPending.current===operationId)operationPending.current=null;if(turn===session.current){setTranscribing(false);setBusy(false)}}
  }
  const toggleRecording=async()=>{
    stopPlayback();if(recording){if(recorder.current?.state==='recording')recorder.current.stop();return}if(busy||operationPending.current!==null||permissionPending.current)return
    if(!navigator.mediaDevices?.getUserMedia||!globalThis.MediaRecorder){setVoiceError('当前浏览器不支持录音，请使用文字输入');return}
    const turn=session.current,generation=++recordingGeneration.current;cancelled.current=false;setVoiceError('');pendingAudio.current=null;setCanRetryVoice(false);permissionPending.current=true
    const active=()=>turn===session.current&&generation===recordingGeneration.current&&!cancelled.current
    try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!active()){media.getTracks().forEach(t=>t.stop());return}stream.current=media;audioPeak.current=null
      try{const context=new AudioContext(),source=context.createMediaStreamSource(media),analyser=context.createAnalyser(),samples=new Uint8Array(1024);audioContext.current=context;analyser.fftSize=1024;source.connect(analyser);audioPeak.current=0;void context.resume();audioSampler.current=setInterval(()=>{analyser.getByteTimeDomainData(samples);const rms=Math.sqrt(samples.reduce((sum,v)=>sum+((v-128)/128)**2,0)/samples.length);audioPeak.current=Math.max(audioPeak.current??0,rms)},100)}catch{/* Empty/short transcript validation remains available without Web Audio. */}
      const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(m=>MediaRecorder.isTypeSupported(m)),r=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:Blob[]=[],started=Date.now();setSeconds(0)
      r.ondataavailable=e=>{if(active()&&e.data.size)chunks.push(e.data)};r.onerror=()=>{if(!active())return;cancelled.current=true;stopTracks();recorder.current=null;setRecording(false);setVoiceError('录音中断，请重新录音或改用文字')}
      r.onstop=async()=>{if(!active()){chunks.length=0;media.getTracks().forEach(t=>t.stop());return}stopTracks();recorder.current=null;setRecording(false);const blob=new Blob(chunks,{type:r.mimeType.split(';')[0]});chunks.length=0;if(blob.size<300||Date.now()-started<500||(audioPeak.current!==null&&audioPeak.current<0.001)){setVoiceError('录音太短或没有声音，请重试');return}if(blob.size>15*1024*1024){setVoiceError('录音超过15 MB，请缩短后重试');return}pendingAudio.current=blob;setCanRetryVoice(true);await transcribeRecording()}
      r.start(250);setRecording(true);timer.current=setInterval(()=>{if(!active())return;const s=Math.floor((Date.now()-started)/1000);setSeconds(s);if(s>=90&&r.state==='recording')r.stop()},250)
    }catch(e){if(active()){stopTracks();setRecording(false);setVoiceError(e instanceof DOMException&&e.name==='NotAllowedError'?'麦克风未获授权，请在浏览器的网站权限中允许麦克风，或继续文字输入':'麦克风暂不可用，请检查设备或输入文字')}}finally{if(generation===recordingGeneration.current)permissionPending.current=false}
  }
  const toManual=(value:string)=>{if(!value.trim()||value.length>5000){setError('手动记录每条最多5000字，请在预览中分条核对，不会截断原稿');return}manualKey.current=crypto.randomUUID();setManualText(value)}
  if(manualText!==null)return <BottomSheetSurface open label="手动核对AI内容" title="手动核对后保存" onClose={()=>setManualText(null)} className="ai-business-sheet"><p>此内容尚未通过 AI 校验，请对照原输入核对事实、否定和发生时间。按手动记录保存，不自动归档、修改医嘱或覆盖摘要。原件请在此表单重新选择。</p><QuickVoiceRecordFlow open forceManual presentation="nurse-inline" initialInputChannel="text" initialText={manualText} photoMemberId={memberId} photoToken={token} onClose={()=>setManualText(null)} onSaved={message=>{setNotice(message);onSaved?.(message);onClose()}} onConfirm={async(content,occurredAt,_candidates,inputChannel,photos)=>{await quickRecordService.create({memberId,content,rawText:text||undefined,occurredAt,inputChannel,idempotencyKey:manualKey.current,title:'人工核对记录',journal:{categories:['other']},...(photos.photoIds.length?{photoDraftId:photos.draftId,photoIds:photos.photoIds}:{})},token);return '已按手动记录保存，未自动归档'}}/></BottomSheetSurface>
  return <BottomSheetSurface open label="智能整理记录" title={profileMode?'智能记录':'智能整理记录'} onClose={onClose} className="ai-business-sheet"><div className="ai-business-composer">
    {profileMode&&<p role="status">资料归属：{memberName}。核对并确认后才会写入正式档案。</p>}
    {busy&&<p role="status">{phase}</p>}
    <label>资料类型<select value={task} disabled={busy||recording} onChange={e=>setTask(e.target.value as typeof task)}><option value="record">健康随记</option><option value="report">检查报告</option><option value="visit">就诊资料</option><option value="archive">历史档案</option></select></label>
      <label>文字输入（可直接填写）<textarea aria-label="原始记录内容" value={text} maxLength={15000} disabled={(busy&&!transcribing)||draft?.state==='saved'} placeholder="在这里输入记录；录音转写后也可编辑。语音失败不影响文字或图片。" onChange={e=>setText(e.target.value)}/></label>
    {!draft&&<button disabled={busy} type="button" onClick={()=>void run(async()=>{const d=await request<Draft|null>(url,'GET');if(d){current(d);setText(d.inputText);setNotice('已恢复当前人物的未保存草稿')}else setNotice('没有可恢复的未保存草稿')})}>恢复未保存草稿</button>}
    <div className="ai-business-actions"><HohoButton variant="secondary" disabled={busy||draft?.state==='saved'} onClick={()=>void toggleRecording()}>{recording?`停止录音 ${seconds}秒`:'开始录音'}</HohoButton><label>上传资料<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" disabled={(busy&&!transcribing)||recording||draft?.state==='saved'} onChange={e=>{const chosen=Array.from(e.target.files??[]);if(chosen.length>12||chosen.reduce((n,f)=>n+f.size,0)>15*1024*1024){setError('一次最多12份文件，总大小15 MB');return}setFiles(chosen);setError('')}}/></label></div>
    {!!files.length&&<p>{files.length} 份待整理资料 <button disabled={busy} type="button" onClick={()=>setFiles([])}>移除</button></p>}
    {profileMode&&<><label>拍照<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy||draft?.state==='saved'} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label><small>可上传体检报告、检查报告、医疗回执、病历及接种凭证。相册图片和多页 PDF 共用现有识别流程。</small></>}
    <small>录音最长90秒，停止后先转写，再由你核对文字并整理。失败录音仅暂存当前窗口供手动重试，关闭或取消后清理；资料最多12页、15 MB。只整理当前人物，不会自动保存。</small>
    <label className="ai-business-voice-reply"><input type="checkbox" checked={ttsConfigured&&voiceReply} disabled={!ttsConfigured} onChange={e=>setVoiceReply(e.target.checked)}/>对话式记录（AI 合成语音）{!ttsConfigured&&' · 尚未接通'}</label>
    {voiceError&&<section role="alert"><p>{voiceError}。文字输入、图片及已有结果仍可使用。</p>{canRetryVoice&&<HohoButton variant="secondary" disabled={busy||recording} onClick={()=>{cancelled.current=false;void transcribeRecording()}}>重试语音转写</HohoButton>}</section>}
    <div className="ai-business-actions"><HohoButton disabled={busy||recording||draft?.state==='saved'||(!text.trim()&&!files.length&&!draft?.pages.length)} onClick={prepare}>{busy?'正在处理…':draft?'继续整理这份草稿':'整理成待确认记录'}</HohoButton><button type="button" onClick={interrupt}>打断</button><button type="button" onClick={()=>void cancelCurrent()}>取消草稿</button></div>
    {error&&<p role="alert">{error}。未保存新结果，原稿与上一版仍保留，可继续查看。<button disabled={busy||recording} onClick={prepare} type="button">重试整理</button></p>}{notice&&!busy&&<p role="status">{notice}</p>}
    {draft?.preview&&<AIResultPreview preview={draft.preview} value={previewText} onChange={setPreviewText}>{!eventId&&!sourceIdentity&&<HohoButton variant="secondary" disabled={busy||!previewText.trim()} onClick={()=>toManual(previewText)}>带入手动表单核对</HohoButton>}</AIResultPreview>}
    {!eventId&&!sourceIdentity&&draft?.state!=='saved'&&<HohoButton variant="secondary" disabled={busy||!text.trim()} onClick={()=>toManual(text)}>原文带入手动记录</HohoButton>}
    {draft?.state==='failed'&&draft.sources.some(s=>s.id!=='input'&&s.text.trim())&&<section aria-label="已识别资料原文"><h3>已识别资料原文，需对照原件核对</h3><p>后续整理未通过，识别文字仍可查看；不会自动保存。</p>{draft.sources.filter(s=>s.id!=='input').map(s=><p style={{whiteSpace:'pre-wrap'}} key={`${s.id}:${s.page}`}>第{s.page}页：{s.text}</p>)}</section>}
    {(profileMode||!!eventId)&&draft?.state==='failed'&&draft.pages.length>0&&<HohoButton disabled={busy} variant="secondary" onClick={()=>void run(async()=>{const next=await request<Draft>(`${url}/${draft.id}`,'PATCH',{version:draft.version,manualOriginal:true,note:text});current(next);setText(next.inputText);setFiles([]);setNotice('智能识别未成功。可核对后仅保存原件，再手动补充档案，不会生成诊断。')})}>保留原件，手动补充</HohoButton>}
    {!!draft?.unmappedRows?.length&&<section role="alert"><h3>这些原文行尚未完整进入记录</h3>{draft.unmappedRows.map((row,i)=><p key={i}>第{row.page}页：{row.text}</p>)}<small>请核对识别原文并重新整理；不会保存为完整报告。</small></section>}
    {!!draft?.documentWarnings?.length&&<section role="alert"><h3>原件页码待核对</h3>{draft.documentWarnings.map((warning,i)=><p key={i}>{warning}</p>)}<label><input type="checkbox" checked={draft.confirmPageWarnings} disabled={busy||draft.state==='saved'} onChange={e=>edit({confirmPageWarnings:e.target.checked})}/>已核对，仅按现有不完整材料保存，不标记整份齐全</label></section>}
    {!!draft?.conflicts?.length&&<section><h3>已有相关档案，请核对差异</h3>{draft.conflicts.map((conflict,i)=><details key={i}><summary>查看已有内容与来源</summary><p>{conflict.text}</p></details>)}<label><input type="checkbox" checked={draft.confirmConflicts} disabled={busy||draft.state==='saved'} onChange={e=>edit({confirmConflicts:e.target.checked})}/>已核对，保留既有内容并关联本次来源</label></section>}
    {draft?.pages.length&&!draft.documentWarnings?.length?<small>本批上传页均已处理；未读到原文页码时，无法判断上传前是否缺页，请对照原件。</small>:null}
    {draft?.sources.filter(s=>s.status==='uncertain').map(s=><label key={`${s.id}:${s.page}`}><input type="checkbox" disabled={busy} onChange={e=>edit({confirmPage:`${s.id}:${s.page}`,confirmed:e.target.checked})}/>第{s.page}页有不清楚内容，我已对照原件核对</label>)}
    {draft?.pages.map(p=><details key={`${p.id}:${p.page}:${draft.version}`}><summary>{p.name} · 第{p.page}页原文与核对</summary><textarea aria-label={`第${p.page}页识别原文`} defaultValue={draft.sources.find(s=>s.id===p.id&&s.page===p.page)?.text??''} disabled={busy||draft.state==='saved'} onBlur={e=>{if(e.target.value!==draft.sources.find(s=>s.id===p.id&&s.page===p.page)?.text)edit({sourceId:p.id,page:p.page,text:e.target.value})}}/><button type="button" disabled={busy} onClick={()=>void run(async()=>{const turn=session.current,controller=new AbortController();abort.current=controller;const response=await fetch(`${url}/${draft.id}/files/${p.id}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});if(!response.ok)throw new Error('原件暂不可用');const blob=await response.blob();if(turn!==session.current)return;const objectUrl=URL.createObjectURL(blob);originalUrls.current.push(objectUrl);setOriginals(old=>({...old,[p.id]:objectUrl}))})}>读取原件</button>{originals[p.id]&&<a href={originals[p.id]} target="_blank" rel="noreferrer">查看原件</a>}<button type="button" disabled={busy||draft.state==='saved'} onClick={()=>void run(async()=>{const next=await request<Draft>(url,'POST',{id:draft.id,version:draft.version,text,task,reprocessPages:[`${p.id}:${p.page}`]});current(next);setNotice('仅重新识别所选页，并重新整理草稿')})}>只重新识别这一页（2次请求）</button></details>)}
    {draft?.questions.map(q=><div className="ai-business-question" key={q.id}><label>{q.label}<input aria-label={q.label} disabled={busy} onBlur={e=>{if(e.target.value.trim())edit({itemId:q.itemId,field:q.field,value:e.target.value})}}/></label><button disabled={busy} type="button" onClick={()=>edit({skipQuestion:q.id})}>不记得 / 跳过</button></div>)}
    {draft?.items.map(item=><section className="ai-business-item" key={`${item.id}:${draft.version}`}><div className="ai-business-actions"><h3>{item.title}</h3><button type="button" disabled={busy||draft.state==='saved'} onClick={()=>edit({deleteItem:item.id})}>删除这条</button></div><label>记录类型<select value={item.category} disabled={busy||draft.state==='saved'} onChange={e=>edit({itemId:item.id,category:e.target.value})}>{Object.entries(categoryLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label>发生时间<input defaultValue={item.timeText??''} placeholder="未知时间" disabled={busy||draft.state==='saved'} onBlur={e=>{if(e.target.value!==(item.timeText??''))edit({itemId:item.id,field:'time',value:e.target.value})}}/></label><small>{item.time.precision==='unknown'?'发生时间未明确，不等于录入时间':item.time.precision==='exact'?'已按原话定位时间':'时间范围，未补成精确时刻'}</small>
      {profileMode&&<><label>归档位置<select value={item.archiveCategory??''} disabled={busy||draft.state==='saved'} onChange={e=>edit({itemId:item.id,archiveCategory:e.target.value||null})}><option value="">仅保留检查／就诊资料</option>{Object.entries(archiveLabels).map(([value,label])=><option key={value} value={value} disabled={['chronic','surgery','family-history'].includes(value)&&!item.fields.some(f=>f.name==='historyName')||value==='family-history'&&!item.fields.some(f=>f.name==='relationship')||value==='vaccination'&&!item.fields.some(f=>f.name==='vaccineName')||value==='allergy'&&!item.fields.some(f=>f.name==='allergen')}>{label}</option>)}</select></label><small>不确定内容标为待确认，检查指标不会自动生成诊断。重复资料复用来源，差异内容分别保留，不覆盖已有内容。</small></>}
      {item.fields.map((f,i)=><label key={`${f.name}:${i}`}>{labels[f.name]??f.name}<input defaultValue={f.value} disabled={busy||draft.state==='saved'} onBlur={e=>{if(e.target.value!==f.value)edit({itemId:item.id,field:f.name,value:e.target.value})}}/><details><summary>{f.editedBy==='user'?'已手动修改 · 查看原话':'查看原话与来源'}</summary>{f.sources.map((s,n)=><p key={n}>来源 {s.sourceId==='input'?'本次输入':'资料'} · 第{s.page}页：{s.quote}</p>)}</details></label>)}
      {onApply&&draft.state==='ready'&&!draft.pages.length&&(item.journal.sleep||item.journal.bowel||item.journal.outdoorActivity)&&item.time.resolvedStart&&draft.items.length===1&&<HohoButton variant="secondary" disabled={busy} onClick={()=>onApply({...item,originText:draft.inputText})}>放入原有表单继续编辑</HohoButton>}
    </section>)}
    {!!draft?.items.length&&draft.state!=='saved'&&<HohoButton disabled={busy||recording||draft.state!=='ready'||text!==draft.inputText||files.length>0} onClick={()=>void run(saveCurrent,'保存中，请稍候…')}>已核对，一次保存 {draft.items.length} 条</HohoButton>}
    {draft?.state==='saved'&&<div className="ai-business-actions"><HohoButton onClick={onClose}>完成</HohoButton><button disabled={busy} type="button" onClick={()=>void run(async()=>{current(await request<Draft>(`${url}/${draft.id}/undo`,'POST'));setNotice('本次保存已撤销');onSaved?.('本次保存已撤销')})}>撤销本次保存</button></div>}
  </div></BottomSheetSurface>
}
