import { useEffect, useState } from 'react'
type Ref={recordId:string;eventId:string;quote:string;occurredAt:string|null}
type Insights={intakeObservations:{food:string[];amount:string|null;observation:string;sources:Ref[]}[];foodAssociations:{food:string[];amount:string|null;symptom:string;handling:string|null;relation:string;sources:Ref[]}[];boundary:string}
export function HealthInsights({memberId,token}:{memberId:string;token:string}){
  const [value,setValue]=useState<Insights|null>(null),[error,setError]=useState(''),[open,setOpen]=useState(false),[retry,setRetry]=useState(0)
  useEffect(()=>{setValue(null);setError('');if(!open)return;const c=new AbortController();fetch(`/api/members/${encodeURIComponent(memberId)}/health-insights`,{headers:{Authorization:`Bearer ${token}`},signal:c.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error?.message||v.message||'读取失败');setValue(v)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'读取失败')});return()=>c.abort()},[memberId,token,open,retry])
  const refs=(sources:Ref[])=>sources.map(s=><details key={s.recordId}><summary>查看原话 · {s.occurredAt?new Date(s.occurredAt).toLocaleString('zh-CN'):'时间未明确'}</summary><p>{s.quote}</p><a href={`/health-events/${encodeURIComponent(s.eventId)}`}>打开来源随记</a></details>)
  return <section><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open}>查看食物与症状记录</button>{open&&<>{error?<p role="alert">{error}<button type="button" onClick={()=>setRetry(n=>n+1)}>重试读取</button></p>:!value?<p role="status">正在读取当前人物资料…</p>:<><p>{value.boundary}</p><h3>食物与症状时间线</h3>{!value.foodAssociations.length&&<p>暂无可关联的已保存记录；不等于没有反应。</p>}{value.foodAssociations.map((v,i)=><article key={i}><p>{v.food.join('、')||'食物未明确'} · 数量 {v.amount??'未明确'} · {v.relation}</p><p>{v.symptom} · 处理 {v.handling??'未记录'}</p>{refs(v.sources)}</article>)}<details><summary>全部已记录摄入与观察（含未记录反应）</summary>{value.intakeObservations.map((v,i)=><article key={i}><p>{v.food.join('、')||'食物未明确'} · {v.amount??'量未知'} · {v.observation}</p>{refs(v.sources)}</article>)}</details></>}</>}</section>
}
