import { useEffect, useRef, useState } from 'react'
import { useAppStore } from '../../store/useAppStore'
import type {MediaReview} from '../../services/quickRecords'
export function RecordOriginals({eventId,attachmentIds=[],recordId}:{eventId:string;attachmentIds?:string[];recordId?:string}){
 const token=useAppStore(s=>s.authToken),[links,setLinks]=useState<Record<string,string>>({}),[metadata,setMetadata]=useState<{id:string;name:string;mimeType:string;recordId?:string;mediaReview?:MediaReview}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),controller=useRef<AbortController|null>(null),urls=useRef<string[]>([]),generation=useRef(0)
 useEffect(()=>{generation.current++;setLinks({});setError('');setMetadata([]);let alive=true;if(token)void fetch(`/api/events/${encodeURIComponent(eventId)}/attachments`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(list=>{if(alive)setMetadata(list)}).catch(()=>{if(alive)setError('原始资料列表暂不可用，请重新打开记录重试')});return()=>{alive=false;generation.current++;controller.current?.abort();urls.current.forEach(URL.revokeObjectURL);urls.current=[]}},[eventId,token])
 async function read(id:string,variant='content'){if(!token||busy)return;const turn=generation.current,c=new AbortController();controller.current=c;setBusy(true);setError('');try{const r=await fetch(`/api/events/${encodeURIComponent(eventId)}/attachments/${encodeURIComponent(id)}/${variant}`,{headers:{Authorization:`Bearer ${token}`},signal:c.signal});if(!r.ok)throw new Error('原件暂不可用，请重试');const blob=await r.blob();if(turn!==generation.current)return;const objectUrl=URL.createObjectURL(blob);urls.current.push(objectUrl);setLinks(v=>({...v,[id+variant]:objectUrl}))}catch(e){if(!c.signal.aborted&&turn===generation.current)setError(e instanceof Error?e.message:'原件暂不可用')}finally{if(turn===generation.current)setBusy(false)}}
 const ids=recordId?[...new Set([...metadata.filter(m=>m.recordId===recordId).map(m=>m.id),...attachmentIds])]:attachmentIds
 if(!ids.length)return error?<p role="alert">{error}</p>:null
 return <section><h3>原始资料</h3>{ids.map((id,i)=>{const item=metadata.find(m=>m.id===id),review=item?.mediaReview;return <div key={id}>{links[id+'content']?<a href={links[id+'content']} target="_blank" rel="noreferrer">查看原件 {i+1}</a>:<button type="button" disabled={busy} onClick={()=>void read(id)}>读取原件 {i+1}</button>}{item?.mimeType.startsWith('video/')&&<>{links[id+'preview']?<a href={links[id+'preview']} target="_blank" rel="noreferrer">查看兼容视频预览</a>:<button type="button" disabled={busy} onClick={()=>void read(id,'preview')}>读取兼容预览</button>}</>}{review&&<details><summary>资料 {i+1} · 来源与核对结果</summary><p>{item?.name} · 原件参考日期：{review.referenceDate??'未知'}</p>{review.confirmedText?<p>用户核对内容：{review.confirmedText}</p>:<p>媒体草稿未核对，不作为已确认病史</p>}{review.audio?.text&&<p>家长描述（原转写）：{review.audio.text}</p>}{review.vision?.observations?.map((o,n)=><p key={n}>画面可见（{o.seconds===null?'当前照片':`${o.seconds}秒采样`}，待核对）：{o.text}</p>)}{review.audio?.message&&<p>口述：{review.audio.message}</p>}{review.vision?.message&&<p>画面：{review.vision.message}</p>}{review.sound?.message&&<p>{review.sound.message}</p>}</details>}</div>})}{error&&<p role="alert">{error}</p>}</section>
}
