import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { addOpsFeedbackMessage, feedbackCategories, feedbackStatusLabels, getOpsFeedback, listOpsFeedback, updateOpsFeedback, type FeedbackPriority, type FeedbackStatus, type OpsFeedbackOverview, type OpsFeedbackRecord } from '../../services/feedback'
import { useAppStore } from '../../store/useAppStore'
import './ops.css'
import './ops-feedback.css'

const emptyOverview: OpsFeedbackOverview = { new: 0, pendingView: 0, viewed: 0, evaluating: 0, improving: 0, resolved: 0, duplicates: 0, withSupplements: 0, averageFirstViewMs: null }
const statuses = Object.entries(feedbackStatusLabels) as [FeedbackStatus, string][]
const time = (value: string) => new Date(value).toLocaleString('zh-CN')
const priorityLabels: Record<FeedbackPriority, string> = { low: '低', normal: '普通', high: '高', urgent: '紧急' }

export function OpsFeedbackPage() {
  const token = useAppStore((state) => state.authToken)!, [records, setRecords] = useState<OpsFeedbackRecord[]>([]), [overview, setOverview] = useState(emptyOverview), [selected, setSelected] = useState<OpsFeedbackRecord | null>(null)
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [filters, setFilters] = useState({ status: '', category: '', sourcePath: '', appVersion: '', deviceType: '', from: '', to: '', hasAttachments: '', hasSupplements: '', duplicate: '' })
  const params = useMemo(() => { const value = new URLSearchParams(); Object.entries(filters).forEach(([key, item]) => item && value.set(key, item)); return value }, [filters])
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); listOpsFeedback(token, params, controller.signal).then((data) => { setRecords(data.feedback); setOverview(data.overview) }).catch((cause) => { if (cause.name !== 'AbortError') setError(cause.message) }).finally(() => setLoading(false)); return () => controller.abort() }, [params, token])
  const open = async (id: string) => { try { const detail = await getOpsFeedback(token, id); const next = detail.status === 'received' ? await updateOpsFeedback(token, id, { status: 'viewed' }) : detail; setSelected(next); const data = await listOpsFeedback(token, params); setRecords(data.feedback); setOverview(data.overview) } catch (cause) { setError(cause instanceof Error ? cause.message : '反馈详情读取失败') } }
  return <main className="ops-page ops-feedback-page"><header className="ops-topbar"><div><Link to="/ops">← Operations</Link><h1>Feedback（反馈管理）</h1><p>用户反馈、处理状态、用户可见回复与内部备注</p></div></header>{error && <div className="ops-error" role="alert">{error}</div>}
    <section className="ops-summary" aria-label="反馈概览"><Summary label="新反馈" value={overview.new}/><Summary label="待查看" value={overview.pendingView}/><Summary label="评估中" value={overview.evaluating}/><Summary label="改进中" value={overview.improving}/><Summary label="已处理" value={overview.resolved}/><Summary label="重复反馈" value={overview.duplicates}/><Summary label="包含用户补充" value={overview.withSupplements}/>{overview.averageFirstViewMs !== null && <Summary label="平均首次查看" value={`${Math.round(overview.averageFirstViewMs / 60_000)} 分钟`}/>}</section>
    <section className="ops-panel ops-feedback-filters"><h2>筛选</h2><div><Filter label="状态" value={filters.status} onChange={(status) => setFilters((value) => ({ ...value, status }))} options={[['', '全部状态'], ...statuses]}/><Filter label="类型" value={filters.category} onChange={(category) => setFilters((value) => ({ ...value, category }))} options={[['', '全部类型'], ...feedbackCategories.map((item) => [item, item] as [string, string])]}/><label>来源页面<input value={filters.sourcePath} onChange={(event) => setFilters((value) => ({ ...value, sourcePath: event.target.value }))}/></label><label>产品版本<input value={filters.appVersion} onChange={(event) => setFilters((value) => ({ ...value, appVersion: event.target.value }))}/></label><Filter label="设备" value={filters.deviceType} onChange={(deviceType) => setFilters((value) => ({ ...value, deviceType }))} options={[["", '全部设备'], ['mobile', '手机'], ['desktop', '电脑'], ['tablet', '平板']]}/><label>开始日期<input type="date" value={filters.from} onChange={(event) => setFilters((value) => ({ ...value, from: event.target.value }))}/></label><label>结束日期<input type="date" value={filters.to} onChange={(event) => setFilters((value) => ({ ...value, to: event.target.value }))}/></label><Filter label="图片" value={filters.hasAttachments} onChange={(hasAttachments) => setFilters((value) => ({ ...value, hasAttachments }))} options={[["", '不限图片'], ['true', '包含图片']]}/><Filter label="用户补充" value={filters.hasSupplements} onChange={(hasSupplements) => setFilters((value) => ({ ...value, hasSupplements }))} options={[["", '不限补充'], ['true', '有用户补充']]}/><Filter label="重复" value={filters.duplicate} onChange={(duplicate) => setFilters((value) => ({ ...value, duplicate }))} options={[["", '不限重复'], ['true', '重复反馈']]}/></div></section>
    <section className="ops-panel ops-feedback-table"><h2>反馈列表</h2>{loading ? <p>正在读取真实反馈数据…</p> : records.length === 0 ? <p className="ops-empty-inline">没有符合条件的真实反馈。</p> : <div className="ops-table-wrap"><table><thead><tr><th>摘要</th><th>类型</th><th>来源</th><th>提交用户</th><th>提交时间</th><th>状态</th><th>内部优先级</th><th>附件</th><th>补充 / 合并</th></tr></thead><tbody>{records.map((item) => <tr key={item.id} onClick={() => void open(item.id)}><td><button type="button">{item.summary}</button></td><td>{item.category}</td><td>{item.sourceName ?? item.sourcePath ?? '直接提交'}</td><td>{item.accountId}</td><td>{time(item.createdAt)}</td><td>{feedbackStatusLabels[item.status]}</td><td>{priorityLabels[item.priority]}</td><td>{item.attachmentCount}</td><td>{item.supplementCount} / {item.mergedCount}</td></tr>)}</tbody></table></div>}</section>
    {selected && <FeedbackDrawer item={selected} token={token} onClose={() => setSelected(null)} onChange={(item) => { setSelected(item); void listOpsFeedback(token, params).then((data) => { setRecords(data.feedback); setOverview(data.overview) }).catch((cause) => setError(cause instanceof Error ? cause.message : '反馈列表刷新失败')) }}/>}</main>
}

function FeedbackDrawer({ item, token, onClose, onChange }: { item: OpsFeedbackRecord; token: string; onClose: () => void; onChange: (item: OpsFeedbackRecord) => void }) {
  const [status, setStatus] = useState(item.status), [priority, setPriority] = useState(item.priority), [handledVersion, setHandledVersion] = useState(item.handledVersion ?? ''), [noActionReason, setNoActionReason] = useState(item.noActionReason ?? ''), [mergedIntoId, setMergedIntoId] = useState(item.mergedIntoId ?? ''), [messageKind, setMessageKind] = useState<'user-reply' | 'internal-note'>('user-reply'), [message, setMessage] = useState(''), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { onChange(await updateOpsFeedback(token, item.id, { status, priority, handledVersion, noActionReason, mergedIntoId })) } catch (cause) { setError(cause instanceof Error ? cause.message : '保存失败') } finally { setSaving(false) } }
  const send = async () => { if (!message.trim()) return; setSaving(true); setError(''); try { onChange(await addOpsFeedbackMessage(token, item.id, { kind: messageKind, text: message.trim() })); setMessage('') } catch (cause) { setError(cause instanceof Error ? cause.message : '发送失败') } finally { setSaving(false) } }
  return <div className="ops-feedback-drawer-layer" role="dialog" aria-modal="true" aria-label="反馈详情"><button className="ops-feedback-backdrop" type="button" aria-label="关闭" onClick={onClose}/><aside><header><div><span>{item.id}</span><h2>{item.summary}</h2></div><button type="button" onClick={onClose}>关闭</button></header><div className="ops-feedback-drawer-body"><section><h3>用户反馈</h3><p>{item.description || '仅提交图片'}</p><dl><dt>用户</dt><dd>{item.accountId}</dd><dt>来源</dt><dd>{item.sourceName ?? '直接提交'} · {item.sourcePath ?? '-'}</dd><dt>环境</dt><dd>{item.appVersion ?? '-'} · {item.device.type} · {item.device.os} · {item.device.browser} · {item.device.screen}</dd><dt>时间</dt><dd>{time(item.createdAt)}</dd></dl><div className="ops-feedback-images">{item.attachments?.map((attachment) => <a key={attachment.id} href={attachment.url} target="_blank" rel="noreferrer"><img src={attachment.url} alt={attachment.name}/></a>)}</div></section><form onSubmit={save}><h3>处理</h3><Filter label="状态" value={status} onChange={(value) => setStatus(value as FeedbackStatus)} options={statuses}/><Filter label="内部优先级" value={priority} onChange={(value) => setPriority(value as FeedbackPriority)} options={Object.entries(priorityLabels)}/><label>关联上线版本<input value={handledVersion} onChange={(event) => setHandledVersion(event.target.value)}/></label><label>合并到反馈 ID<input value={mergedIntoId} onChange={(event) => setMergedIntoId(event.target.value)}/></label><label>暂不处理原因（用户可见）<textarea value={noActionReason} onChange={(event) => setNoActionReason(event.target.value)}/></label><button className="hoho-button" data-variant="primary" disabled={saving}>保存处理状态</button></form><section><h3>沟通与备注</h3><div className="ops-feedback-messages">{item.messages?.map((entry) => <article key={entry.id} data-kind={entry.kind}><strong>{entry.kind === 'internal-note' ? '内部备注（用户不可见）' : entry.kind === 'user-reply' ? '回复用户' : '用户补充'}</strong><p>{entry.text}</p><span>{time(entry.createdAt)}</span></article>)}</div><Filter label="消息类型" value={messageKind} onChange={(value) => setMessageKind(value as 'user-reply' | 'internal-note')} options={[["user-reply", '回复用户（用户可见）'], ['internal-note', '内部备注（用户不可见）']]}/><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder={messageKind === 'internal-note' ? '仅内部人员可见' : '这段内容会展示给用户'}/><button className="hoho-button" data-variant="secondary" disabled={saving || !message.trim()} onClick={() => void send()}>添加{messageKind === 'internal-note' ? '内部备注' : '用户回复'}</button>{error && <p className="ops-error">{error}</p>}</section></div></aside></div>
}

function Summary({ label, value }: { label: string; value: number | string }) { return <article><span>{label}</span><strong>{value}</strong></article> }
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][] }) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}>{options.map(([key, text]) => <option value={key} key={key}>{text}</option>)}</select></label> }
