import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowUp, CheckCircle2, CircleHelp, CloudCog, Plus, RefreshCw, Search, Settings2, ShieldAlert, X } from 'lucide-react'
import { useAppStore } from '../../store/useAppStore'
import { getOpsResources, syncOpsResources, updateOpsResource, type OpsAccessMode, type OpsResource, type OpsStatus } from '../../services/ops'
import { createOpsResource } from '../../services/opsMutations'
import './ops.css'
import './ops-release.css'
import './ops-responsive.css'

const statusMap:Record<OpsStatus,{label:string;detail:string;rank:number}> = {
  normal:{label:'Normal（正常）',detail:'当前数据没有显示需要处理的风险。',rank:3}, warning:{label:'Warning（需要注意）',detail:'当前还能运行，但已经出现需要提前处理的问题。',rank:1},
  critical:{label:'Critical（需要立即处理）',detail:'如果不尽快处理，可能导致正式用户无法使用。',rank:0}, unknown:{label:'Unknown（未知）',detail:'当前没有可靠数据，不能判断是否安全。',rank:2}, disabled:{label:'Disabled（未启用）',detail:'当前 Hoooho 尚未使用该服务。',rank:4}
}
const sourceMap = { api:'API（系统自动同步）', manual:'Manual（人工维护）', mixed:'Mixed（部分自动、部分人工）' }
const criticalityMap = { P0:'P0 · Production Critical（生产关键）', P1:'P1 · Important（重要）', P2:'P2 · Internal（内部工具）' }
const categoryMap:Record<string,string> = {production:'生产关键服务',reliability:'运行可靠性',development:'内部开发工具',future:'未来可能增加',other:'其他'}
const costCategoryMap:Record<string,string> = { railway:'Infrastructure（服务器与基础设施）','railway-volume':'Infrastructure（服务器与基础设施）',database:'Infrastructure（服务器与基础设施）','file-storage':'Infrastructure（服务器与基础设施）',openai:'AI（人工智能接口费用）',resend:'Email（邮件服务）',chatgpt:'Development Tools（开发工具）',github:'Development Tools（开发工具）',figma:'Development Tools（开发工具）',domain:'Domain（域名）',cloudflare:'Domain（域名）',uptime:'Monitoring（监控）',errors:'Monitoring（监控）',logs:'Monitoring（监控）',backup:'Monitoring（监控）'}
const money = (value:number|null) => value ? `$${value.toFixed(2)}` : '未录入 / 免费'
const dateDays = (value:string) => value ? Math.ceil((new Date(`${value}T00:00:00`).getTime()-Date.now())/86400000) : null
const Tooltip = ({text}:{text:string}) => <span className="ops-tooltip" tabIndex={0} aria-label={text}>?<span role="tooltip">{text}</span></span>
type SortKey='name'|'criticality'|'monthlyCost'|'date'|'status'|'source'

export function OpsPage() {
  const token=useAppStore((s)=>s.authToken)!
  const [resources,setResources]=useState<OpsResource[]>([]),[accessMode,setAccessMode]=useState<OpsAccessMode>('allowlist'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[syncing,setSyncing]=useState(false)
  const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[source,setSource]=useState('all'),[editing,setEditing]=useState<OpsResource|null>(null),[creating,setCreating]=useState(false)
  const [sort,setSort]=useState<{key:SortKey;direction:'asc'|'desc'}>({key:'status',direction:'asc'})
  useEffect(()=>{const controller=new AbortController();getOpsResources(token,controller.signal).then((d)=>{setResources(d.resources);setAccessMode(d.accessMode)}).catch((e)=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>setLoading(false));return()=>controller.abort()},[token])
  const visible=useMemo(()=>resources.filter((r)=>(status==='all'||r.status===status)&&(category==='all'||r.category===category)&&(source==='all'||r.source===source)&&(`${r.name} ${r.plan} ${r.nextAction}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>compare(a,b,sort.key)*(sort.direction==='asc'?1:-1)),[resources,status,category,source,query,sort])
  const active=resources.filter((r)=>r.enabled&&r.category!=='future'),risks=active.filter((r)=>['warning','critical','unknown'].includes(r.status)),knownRenewals=active.flatMap((r)=>[{resource:r,date:r.renewalDate,event:'Renewal（续费扣款）'},{resource:r,date:r.expirationDate,event:'Expiration（服务到期）'}]).filter((item)=>item.date&&(dateDays(item.date)??-1)>=0).sort((a,b)=>a.date.localeCompare(b.date)),missingRenewals=active.filter((r)=>!r.expirationDate&&!r.renewalDate)
  const monthly=active.reduce((sum,r)=>sum+(r.monthlyCost||0),0),unknownCosts=active.filter((r)=>r.monthlyCost===null||(r.monthlyCost===0&&!/Free|免费|Built-in|内置/.test(r.plan))).length,critical=resources.filter((r)=>r.criticality==='P0'&&r.enabled)
  const costs=Object.entries(active.reduce<Record<string,number>>((all,r)=>{const key=costCategoryMap[r.id]||'Other（其他）';all[key]=(all[key]||0)+(r.monthlyCost||0);return all},{})).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1])
  const sync=async()=>{setSyncing(true);setError('');try{setResources((await syncOpsResources(token)).resources)}catch(e){setError(e instanceof Error?e.message:'同步失败，仍显示最近一次有效数据')}finally{setSyncing(false)}}
  const saved=(item:OpsResource)=>{setResources((all)=>all.map((r)=>r.id===item.id?item:r));setEditing(null)}
  const toggle=async(item:OpsResource)=>{try{const saved=await updateOpsResource(token,item.id,{enabled:!item.enabled});setResources((all)=>all.map((r)=>r.id===saved.id?saved:r))}catch(e){setError(e instanceof Error?e.message:'状态更新失败')}}
  const changeSort=(key:SortKey)=>setSort((current)=>current.key===key?{key,direction:current.direction==='asc'?'desc':'asc'}:{key,direction:'asc'})
  return <main className="ops-page">
    <header className="ops-topbar"><div><h1>Hoooho · Operations & Billing（运营与费用总控台）</h1><p>Infrastructure, subscriptions, capacity and renewal overview（基础设施、订阅、容量与续费总览）</p></div><div className="ops-actions"><button className="hoho-button" data-variant="secondary" onClick={()=>setCreating(true)}><Plus size={16}/>Add Resource（新增服务）</button><button className="hoho-button" data-variant="primary" onClick={sync} disabled={syncing}><RefreshCw size={16} className={syncing?'ops-spin':''}/>{syncing?'正在同步…':'Sync Now（立即同步）'}</button></div></header>
    {accessMode==='temporary-authenticated'&&<div className="ops-access-mode" role="status"><ShieldAlert size={18}/><span><strong>Temporary Access Mode（临时内部访问模式）</strong> 当前未配置 Ops allowlist，仅已登录用户可访问；未登录请求仍会被拒绝。</span></div>}
    {error&&<div className="ops-error" role="alert"><AlertTriangle size={18}/><span>{error}。页面继续显示 Last Known Data（最近一次有效数据）。</span><button onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}
    <section className="ops-summary" aria-label="核心汇总"><Summary label="Monthly Estimated Cost（预计每月总成本）" value={loading?'正在读取…':error&&resources.length===0?'Unknown（无法判断）':money(monthly)+(unknownCosts?' + 部分未录入':'')} help="仅统计当前已经启用且录入月费用的服务；未来服务不计入。"/><Summary label="Production Health（正式环境运行情况）" value={loading?'正在读取…':error&&resources.length===0?'Unknown（无法判断）':critical.some((r)=>r.status==='critical')?'存在关键风险':critical.length>0&&critical.every((r)=>r.status==='normal')?'关键系统正常':`${critical.filter((r)=>r.status!=='normal').length} 项待确认`} help="正式用户依赖的关键系统整体是否正常。" tone={critical.some((r)=>r.status==='critical')?'critical':'default'}/><Summary label="Capacity Alerts（额度 / 容量预警）" value={`${active.filter((r)=>r.status==='warning'||r.status==='critical').length} 项`} help="接近余额、预算、存储空间或使用量上限的服务。"/><Summary label="Upcoming Renewals（近期续费与到期）" value={`${knownRenewals.filter((r)=>{const d=dateDays(r.date);return d!==null&&d>=0&&d<=30}).length} 项`} help="未来 30 天内需要续费、到期或结束试用的项目。"/><Summary label="Attention Required（需要我处理）" value={`${risks.length} 项`} help="当前真正需要项目负责人确认或手动处理的事项。" tone={risks.some((r)=>r.status==='critical')?'critical':'default'}/></section>
    <div className="ops-grid"><section className="ops-panel"><SectionTitle title="Production Safeguards（生产运行安全检查）" text="一旦被忽略，可能导致 Hoooho 正式用户无法使用的问题。" icon={<ShieldAlert size={22}/>}/><div className="ops-safeguards">{critical.map((r)=><button key={r.id} onClick={()=>setEditing(r)}><StatusIcon status={r.status}/><span><strong>{r.name}</strong><small>{r.impact}</small></span><em data-status={r.status}>{statusMap[r.status].label}</em></button>)}</div></section><section className="ops-panel"><SectionTitle title="Attention Required（需要我处理）" text="按风险优先级列出下一步，不使用运维黑话。" icon={<AlertTriangle size={22}/>}/><div className="ops-attention">{risks.slice().sort((a,b)=>statusMap[a.status].rank-statusMap[b.status].rank).slice(0,8).map((r)=><button key={r.id} onClick={()=>setEditing(r)}><span className="ops-dot" data-status={r.status}/><span><strong>{r.name}</strong><small>{r.status==='unknown'?'当前缺少可靠数据，无法确认是否安全。':r.impact}</small><b>{r.nextAction}</b></span></button>)}</div></section></div>
    <div className="ops-insights"><section className="ops-panel ops-renewals"><SectionTitle title="Upcoming Costs & Renewals（近期费用与续费）" text="按日期查看未来已录入的扣费、续费和服务到期；未知日期不会被编造。"/><div className="ops-renewal-list">{knownRenewals.length?knownRenewals.slice(0,8).map(({resource:r,date,event})=><div className="ops-renewal-row" key={r.id}><strong>{date}</strong><span><strong>{r.name}</strong><small>{event}</small></span><span>{money(r.monthlyCost)}</span><span className="ops-days">{dateDays(date)} 天</span></div>):<div className="ops-empty-inline">尚未录入任何可靠日期。</div>}</div>{missingRenewals.length>0&&<div className="ops-missing">Missing Data（缺少数据）：{missingRenewals.length} 项启用中的服务尚未录入续费或到期日期。</div>}</section><section className="ops-panel ops-costs"><SectionTitle title="Cost Breakdown（费用构成）" text="Future（未来服务）与 Disabled（未启用）不计入当前真实月费用。"/><div className="ops-cost-list">{costs.length?costs.map(([label,value])=><div className="ops-cost-row" key={label}><strong>{label}</strong><div className="ops-cost-track" aria-label={`${label} 占比 ${monthly?Math.round(value/monthly*100):0}%`}><span style={{width:`${monthly?value/monthly*100:0}%`}}/></div><em>${value.toFixed(2)}</em></div>):<div className="ops-empty-inline">尚未录入可计入的月费用。</div>}</div></section></div>
    <section className="ops-table-section"><SectionTitle title="Services（服务总表）" text={`${visible.length} / ${resources.length} 项服务；点击列名排序，Edit（编辑）维护人工字段。`} icon={<CloudCog size={22}/>}/><div className="ops-filters"><label><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="搜索服务、套餐或下一步"/></label><Filter value={category} onChange={setCategory} options={[['all','全部分类'],...Object.entries(categoryMap)]}/><Filter value={status} onChange={setStatus} options={[['all','全部状态'],...Object.entries(statusMap).map(([k,v])=>[k,v.label])]}/><Filter value={source} onChange={setSource} options={[['all','全部数据来源'],...Object.entries(sourceMap)]}/></div><div className="ops-table-wrap">{loading?<div className="ops-loading">正在读取运营数据…</div>:<table><thead><tr><SortTh label="Service（服务）" sortKey="name" sort={sort} onSort={changeSort}/><th>Category（分类）</th><SortTh label="Criticality（重要程度）" sortKey="criticality" sort={sort} onSort={changeSort}/><th>Plan（套餐）</th><SortTh label="Monthly Cost（月费用）" sortKey="monthlyCost" sort={sort} onSort={changeSort}/><th>Balance / Usage（余额 / 使用量）</th><SortTh label="Renewal / Expiry（续费 / 到期）" sortKey="date" sort={sort} onSort={changeSort}/><th>Runway（预计可维持时间）<Tooltip text="根据当前余额、额度、容量和消耗速度估算；不能可靠计算时显示暂无数据。"/></th><SortTh label="Source（数据来源）" sortKey="source" sort={sort} onSort={changeSort}/><SortTh label="Status（状态）" sortKey="status" sort={sort} onSort={changeSort}/><th>Next Action（下一步）</th><th/></tr></thead><tbody>{visible.length===0?<tr><td colSpan={12}><div className="ops-empty-inline">没有符合当前筛选条件的服务，请调整筛选或搜索内容。</div></td></tr>:visible.map((r)=><tr key={r.id} data-disabled={!r.enabled}><td><strong>{r.name}</strong><small>Impact（不可用影响）：{r.impact}</small><button className="ops-toggle-action" data-disabled={!r.enabled} onClick={()=>toggle(r)}>{r.enabled?'Disable（停用）':'Enable（启用）'}</button></td><td>{categoryMap[r.category]||r.category}</td><td><span className="ops-criticality">{criticalityMap[r.criticality]}</span></td><td>{r.plan}</td><td>{r.category==='future'?'Future（不计入当前费用）':r.enabled?money(r.monthlyCost):'Disabled（不计入）'}</td><td>{r.balance||r.usage||'未录入'}</td><td>{r.renewalDate||r.expirationDate||'未录入'}</td><td>{r.runway}</td><td>{sourceMap[r.source]}<small>Last Sync（上次同步）：{r.lastSyncAt?new Date(r.lastSyncAt).toLocaleString('zh-CN'):'尚未同步'}</small></td><td><span className="ops-status" data-status={r.status}>{statusMap[r.status].label}</span><small>{statusMap[r.status].detail}</small></td><td>{r.nextAction}</td><td><button className="ops-edit" onClick={()=>setEditing(r)}><Settings2 size={15}/>Edit（编辑）</button></td></tr>)}</tbody></table>}</div></section>
    {editing&&<EditDrawer resource={editing} token={token} onClose={()=>setEditing(null)} onSaved={saved}/>} {creating&&<CreateDrawer token={token} onClose={()=>setCreating(false)} onCreated={(item)=>{setResources((all)=>[...all,item]);setCreating(false)}}/>}
  </main>
}

function compare(a:OpsResource,b:OpsResource,key:SortKey){if(key==='criticality')return Number(a.criticality.slice(1))-Number(b.criticality.slice(1));if(key==='monthlyCost')return(a.monthlyCost||0)-(b.monthlyCost||0);if(key==='date')return(a.expirationDate||a.renewalDate||'9999').localeCompare(b.expirationDate||b.renewalDate||'9999');if(key==='status')return statusMap[a.status].rank-statusMap[b.status].rank;return String(a[key]).localeCompare(String(b[key]),'zh-CN')}
function Summary({label,value,help,tone='default'}:{label:string;value:string;help:string;tone?:string}){return <article data-tone={tone}><span>{label}<Tooltip text={help}/></span><strong className="ops-live">{value}</strong></article>}
function SectionTitle({title,text,icon}:{title:string;text:string;icon?:React.ReactNode}){return <div className="ops-section-title"><div><h2>{title}</h2><p>{text}</p></div>{icon}</div>}
function StatusIcon({status}:{status:OpsStatus}){return status==='normal'?<CheckCircle2/>:status==='unknown'||status==='disabled'?<CircleHelp/>:<AlertTriangle/>}
function Filter({value,onChange,options}:{value:string;onChange:(v:string)=>void;options:string[][]}){return <select value={value} onChange={(e)=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}
function SortTh({label,sortKey,sort,onSort}:{label:string;sortKey:SortKey;sort:{key:SortKey;direction:'asc'|'desc'};onSort:(key:SortKey)=>void}){const active=sort.key===sortKey;return <th aria-sort={active?(sort.direction==='asc'?'ascending':'descending'):'none'}><button className="ops-sort" onClick={()=>onSort(sortKey)}>{label}{active?(sort.direction==='asc'?<ArrowUp/>:<ArrowDown/>):null}</button></th>}

function EditDrawer({resource,token,onClose,onSaved}:{resource:OpsResource;token:string;onClose:()=>void;onSaved:(r:OpsResource)=>void}){const[form,setForm]=useState(resource),[saving,setSaving]=useState(false),[error,setError]=useState('');const field=(key:keyof OpsResource,value:unknown)=>setForm((f)=>({...f,[key]:value}));const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{onSaved(await updateOpsResource(token,resource.id,form))}catch(err){setError(err instanceof Error?err.message:'保存失败')}finally{setSaving(false)}};return <Drawer title="Manage（维护）" subtitle={resource.name} onClose={onClose}><form onSubmit={save}><div className="ops-form-grid"><Field label="Plan（当前套餐）" help="当前购买或使用的服务套餐"><input value={form.plan} onChange={(e)=>field('plan',e.target.value)}/></Field><Field label="Monthly Cost（月费用）" help="预计每月需要支付的费用"><input type="number" min="0" step="0.01" value={form.monthlyCost??''} onChange={(e)=>field('monthlyCost',e.target.value)}/></Field><Field label="Billing Period（计费周期）" help="按月、按年或按实际使用量计费"><input value={form.billingPeriod} onChange={(e)=>field('billingPeriod',e.target.value)}/></Field><Field label="Balance（账户余额）" help="当前账户中还可以使用的金额或额度"><input value={form.balance} onChange={(e)=>field('balance',e.target.value)}/></Field><Field label="Usage（当前使用量）" help="本计费周期已经使用的数量"><input value={form.usage} onChange={(e)=>field('usage',e.target.value)}/></Field><Field label="Usage Limit（使用上限）" help="当前套餐最多允许使用多少"><input value={form.usageLimit} onChange={(e)=>field('usageLimit',e.target.value)}/></Field><Field label="Renewal Date（续费日期）" help="下一次需要续费或扣款的日期"><input type="date" value={form.renewalDate} onChange={(e)=>field('renewalDate',e.target.value)}/></Field><Field label="Expiration Date（到期日期）" help="超过该日期后服务、域名或资源可能失效"><input type="date" value={form.expirationDate} onChange={(e)=>field('expirationDate',e.target.value)}/></Field><Field label="Source（数据来源）" help="API 自动、Manual 人工或 Mixed 混合维护"><select value={form.source} onChange={(e)=>field('source',e.target.value)}>{Object.entries(sourceMap).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Alert Threshold（预警阈值）" help="达到什么程度后需要提醒"><input type="number" min="0" max="100" value={form.alertThreshold} onChange={(e)=>field('alertThreshold',e.target.value)}/></Field><Field wide label="Next Action（下一步建议）" help="用自然中文说明负责人现在应该做什么"><textarea value={form.nextAction} onChange={(e)=>field('nextAction',e.target.value)}/></Field><Field wide label="Notes（备注）" help="不填写 API Key、Secret、Token 或数据库连接地址"><textarea value={form.notes} onChange={(e)=>field('notes',e.target.value)}/></Field></div>{error&&<p className="ops-form-error">{error}</p>}<DrawerFooter saving={saving} onClose={onClose}/></form></Drawer>}
function CreateDrawer({token,onClose,onCreated}:{token:string;onClose:()=>void;onCreated:(r:OpsResource)=>void}){const[name,setName]=useState(''),[category,setCategory]=useState('other'),[criticality,setCriticality]=useState<'P0'|'P1'|'P2'>('P2'),[impact,setImpact]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');try{onCreated(await createOpsResource(token,{name,category,criticality,impact}))}catch(err){setError(err instanceof Error?err.message:'新增失败')}finally{setSaving(false)}};return <Drawer title="Add Resource（新增服务）" subtitle="新增后保存到服务端持久化数据，不使用 LocalStorage。" onClose={onClose}><form className="ops-create-form" onSubmit={save}><Field label="Service Name（服务名称）" help="填写平台或资源名称，并提供中文解释"><input required maxLength={120} value={name} onChange={(e)=>setName(e.target.value)}/></Field><Field label="Category（分类）" help="选择该服务属于哪一组"><select value={category} onChange={(e)=>setCategory(e.target.value)}>{Object.entries(categoryMap).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Criticality（重要程度）" help="P0 会直接影响用户，P1 影响稳定性，P2 主要影响内部工作"><select value={criticality} onChange={(e)=>setCriticality(e.target.value as 'P0'|'P1'|'P2')}>{Object.entries(criticalityMap).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="Impact（服务不可用时的影响）" help="用普通中文说明这个服务坏了会发生什么"><textarea maxLength={300} value={impact} onChange={(e)=>setImpact(e.target.value)}/></Field>{error&&<p className="ops-form-error">{error}</p>}<DrawerFooter saving={saving} onClose={onClose} saveLabel="Create（新增）"/></form></Drawer>}
function Drawer({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){return <div className="ops-drawer-layer"><button className="ops-backdrop" onClick={onClose} aria-label="关闭编辑"/><aside className="ops-drawer" role="dialog" aria-modal="true" aria-labelledby="ops-drawer-title"><header><div><h2 id="ops-drawer-title">{title}</h2><p>{subtitle}</p></div><button onClick={onClose} aria-label="关闭"><X/></button></header>{children}</aside></div>}
function DrawerFooter({saving,onClose,saveLabel='Save（保存）'}:{saving:boolean;onClose:()=>void;saveLabel?:string}){return <footer><button type="button" className="hoho-button" data-variant="secondary" onClick={onClose}>Cancel（取消）</button><button className="hoho-button" data-variant="primary" disabled={saving}>{saving?'正在保存…':saveLabel}</button></footer>}
function Field({label,help,children,wide=false}:{label:string;help:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'ops-field ops-field-wide':'ops-field'}><span>{label}<Tooltip text={help}/></span>{children}</label>}
