import { expect,test } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'
import { PDFDocument } from 'pdf-lib'
const token=new TokenService('visit-sheet-e2e-secret',3600000).create({id:'visit-test'})
const headers={Authorization:`Bearer ${token}`}
test.beforeEach(async({page,request})=>{await request.get('http://127.0.0.1:4198/success');await request.post('http://127.0.0.1:4198/draft-data',{data:{items:null}});await page.addInitScript(token=>{sessionStorage.setItem('hoooho-auth-token',token);localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'visit-test'},currentMemberId:'child-a',members:[],profile:null},version:5}))},token);await page.goto('/health-events')})
async function open(page:any){await page.getByRole('button',{name:'记一下',exact:true}).click();await page.getByRole('button',{name:'说一说 / 上传资料整理',exact:true}).click();return page.getByRole('dialog',{name:'智能整理记录',exact:true})}
test('文字草稿真实保存、429保留、无自动重试、成员隔离与撤销',async({page,request})=>{const sheet=await open(page);await sheet.getByLabel('原始记录内容').fill('今天没有呕吐，只是恶心');await sheet.getByRole('button',{name:'整理成待确认记录',exact:true}).click();await expect(sheet.getByRole('button',{name:'已核对，一次保存 1 条'})).toBeEnabled();await sheet.getByRole('button',{name:'已核对，一次保存 1 条'}).scrollIntoViewIfNeeded();await page.screenshot({path:'outputs/ai-business/iphone-se-draft.png'});const before=await(await request.get('http://127.0.0.1:4198/status')).json();await request.get('http://127.0.0.1:4198/failure');await sheet.getByLabel('原始记录内容').fill('今天没有呕吐，只是恶心，补充观察');await sheet.getByRole('button',{name:'继续整理这份草稿',exact:true}).click();await expect(sheet.getByRole('alert')).toContainText('仍保留');await expect(sheet.getByRole('button',{name:'已核对，一次保存 1 条'})).toBeDisabled();const failed=await(await request.get('/api/members/child-a/ai-drafts',{headers})).json();expect(failed.state).toBe('failed');expect(failed.items[0].fields[0].value).toBe('今天没有呕吐，只是恶心');expect((await(await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(before.calls+1);await page.screenshot({path:'outputs/ai-business/iphone-se-failure.png'});await request.get('http://127.0.0.1:4198/success');await sheet.getByRole('button',{name:'重试整理',exact:true}).click();await expect(sheet.getByRole('button',{name:'已核对，一次保存 1 条'})).toBeEnabled();await sheet.getByRole('button',{name:'已核对，一次保存 1 条'}).click();await expect(sheet.getByRole('status')).toContainText('已保存 1 条');const saved=await(await request.get(`/api/members/child-a/ai-drafts/${failed.id}`,{headers})).json();expect(saved.result.count).toBe(1);expect((await request.get(`/api/members/empty-child/ai-drafts/${failed.id}`,{headers})).status()).toBe(404);await page.screenshot({path:'outputs/ai-business/iphone-se-saved.png'});await sheet.getByRole('button',{name:'撤销本次保存',exact:true}).click();await expect(sheet.getByRole('status')).toContainText('已撤销');for(const width of [320,375,390]){await page.setViewportSize({width,height:568});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}})
test('实际音频采集经过服务端转写；多轮纠正、语音保存与语音反馈',async({page,request})=>{
  const sheet=await open(page),before=await(await request.get('http://127.0.0.1:4198/status')).json()
  await sheet.getByRole('checkbox',{name:/对话式记录/}).check()
  const speak=async(text:string)=>{
    await request.get(`http://127.0.0.1:4198/voice?text=${encodeURIComponent(text)}`)
    await sheet.getByRole('button',{name:'开始录音',exact:true}).click()
    await expect(sheet.getByRole('button',{name:/停止录音/})).toBeVisible()
    await page.waitForTimeout(900)
    await sheet.getByRole('button',{name:/停止录音/}).click()
    if(text!=='保存')await expect(sheet.getByRole('button',{name:'开始录音',exact:true})).toBeEnabled()
    else await expect(sheet.getByRole('button',{name:'撤销本次保存',exact:true})).toBeEnabled()
  }
  await speak('昨天没有呕吐，只是恶心')
  await expect(sheet.getByRole('button',{name:'已核对，一次保存 1 条'})).toBeEnabled()
  await speak('不是昨天，是前天')
  await expect(sheet.getByLabel('原始记录内容')).toHaveValue('昨天没有呕吐，只是恶心\n不是昨天，是前天')
  await sheet.getByRole('button',{name:'已核对，一次保存 1 条'}).scrollIntoViewIfNeeded();await page.screenshot({path:'outputs/ai-business/iphone-se-voice.png'})
  await speak('保存')
  await expect(sheet.getByRole('status')).toContainText('已保存 1 条')
  const status=await(await request.get('http://127.0.0.1:4198/status')).json()
  expect(status.asrCalls-before.asrCalls).toBe(3);expect(status.speechCalls-before.speechCalls).toBe(3)
})
test('两页PDF逐页核对、局部重识别、实际检查记录与原件回看',async({page,request})=>{
  const fields=(page:number)=>[['institution','测试机构'],['testName','红细胞'],['result','4.2'],['unit','mmol/L'],['referenceRange','3.5-5.5']].map(([name,value])=>({name,value,quote:value,page,sourceId:'@first'}))
  await request.post('http://127.0.0.1:4198/draft-data',{data:{items:[1,2].map(page=>({category:'examination',title:'合成报告',timeText:'2026-09-29',archiveCategory:'examination',subject:'current',relationKey:null,fields:fields(page)}))}})
  const sheet=await open(page);await sheet.getByLabel('资料类型').selectOption('report')
  const pdf=await PDFDocument.create();pdf.addPage([300,200]);pdf.addPage([300,200])
  await sheet.locator('input[type=file]').setInputFiles({name:'synthetic-two-page.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())})
  const before=await(await request.get('http://127.0.0.1:4198/status')).json()
  await sheet.getByRole('button',{name:'整理成待确认记录',exact:true}).click()
  await expect(sheet.getByRole('button',{name:'已核对，一次保存 1 条'})).toBeEnabled()
  expect((await(await request.get('http://127.0.0.1:4198/status')).json()).calls-before.calls).toBe(3)
  await sheet.getByText('synthetic-two-page.pdf · 第2页原文与核对',{exact:true}).click()
  await expect(sheet.getByLabel('第2页识别原文')).toHaveValue(/红细胞 4.2 mmol\/L/)
  await sheet.getByRole('button',{name:'只重新识别这一页（2次请求）',exact:true}).last().click()
  await expect(sheet.getByRole('status')).toContainText('仅重新识别')
  expect((await(await request.get('http://127.0.0.1:4198/status')).json()).calls-before.calls).toBe(5)
  await sheet.getByRole('button',{name:'已核对，一次保存 1 条'}).scrollIntoViewIfNeeded();await page.screenshot({path:'outputs/ai-business/iphone-se-pdf.png'})
  const draft=await(await request.get('/api/members/child-a/ai-drafts',{headers})).json()
  await sheet.getByRole('button',{name:'已核对，一次保存 1 条'}).click()
  await expect(sheet.getByRole('status')).toContainText('已保存 1 条')
  const saved=await(await request.get(`/api/members/child-a/ai-drafts/${draft.id}`,{headers})).json(),ref=saved.result.records[0]
  await page.goto(`/health-events?eventId=${ref.eventId}&recordId=${ref.recordId}`)
  await page.getByRole('button',{name:'读取原件 1',exact:true}).click()
  await expect(page.getByRole('link',{name:'查看原件 1',exact:true})).toBeVisible()
  await page.screenshot({path:'outputs/ai-business/iphone-se-original.png'})
})
test('麦克风拒绝与静音不发转写请求；取消不创建记录',async({page,request})=>{
  const sheet=await open(page),before=await(await request.get('http://127.0.0.1:4198/status')).json()
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError')}})
  await sheet.getByRole('button',{name:'开始录音',exact:true}).click()
  await expect(sheet.getByRole('alert')).toContainText('麦克风未获授权')
  await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{const context=new AudioContext(),source=context.createConstantSource(),destination=context.createMediaStreamDestination();source.offset.value=0;source.connect(destination);source.start();return destination.stream}})
  await sheet.getByRole('button',{name:'开始录音',exact:true}).click()
  await expect(sheet.getByRole('button',{name:/停止录音/})).toBeVisible()
  await page.waitForTimeout(800);await sheet.getByRole('button',{name:/停止录音/}).click()
  await expect(sheet.getByRole('alert')).toContainText('没有声音')
  expect((await(await request.get('http://127.0.0.1:4198/status')).json()).asrCalls).toBe(before.asrCalls)
  await sheet.getByRole('button',{name:'取消草稿',exact:true}).click()
  await expect(sheet.getByRole('status')).toContainText('未保存资料')
  await page.screenshot({path:'outputs/ai-business/iphone-se-cancelled.png'})
})
test('问诊问题模板及可编辑复制提示词无需模型调用',async({page,request})=>{
  const before=await(await request.get('http://127.0.0.1:4198/status')).json()
  await page.goto('/visit-summary');await expect(page.getByRole('heading',{name:'病情数据',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'编辑本次想问',exact:true}).click()
  const editor=page.getByRole('dialog',{name:'编辑本次想问',exact:true})
  await editor.getByText('这些记录中，哪些信息需要再核对或补充？',{exact:true}).click()
  await editor.getByRole('button',{name:'保存并更新情况单',exact:true}).click()
  await page.getByRole('button',{name:'导出情况单',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'导出情况单',exact:true})
  await dialog.getByText('核对 / 编辑问诊提示词',{exact:true}).click()
  const prompt=dialog.getByLabel('问诊提示词');await expect(prompt).toHaveValue(/这些记录中，哪些信息需要再核对或补充/)
  await expect(prompt).toHaveValue(/Hoooho 本身不输出分诊结论/)
  await prompt.fill((await prompt.inputValue())+'\n人工补充：希望核对时间。')
  await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new DOMException('Denied','NotAllowedError')}},configurable:true})})
  await dialog.getByRole('button',{name:'复制给 AI',exact:true}).click()
  await expect(dialog.getByRole('status')).toContainText('浏览器未允许复制')
  await expect(dialog.getByLabel('可复制的完整情况单')).toHaveValue(/人工补充：希望核对时间/)
  await page.screenshot({path:'outputs/ai-business/iphone-se-consultation.png'})
  expect((await(await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(before.calls)
})
test('过敏事实、ABC、自然搜索、排敏摘要和双语卡复用原页面且不调用模型',async({page,request})=>{
  const before=await(await request.get('http://127.0.0.1:4198/status')).json()
  await page.goto('/health-profile/allergy')
  await page.getByRole('button',{name:'查看食物关联经过 / ABC 原始输入',exact:true}).click()
  await expect(page.getByText('本地事实投影，不是 AI 诊断；时间关联不代表因果。不建议自行复食或调整剂量。',{exact:true})).toBeVisible()
  await page.getByRole('heading',{name:'ABC 待核对输入',exact:true}).scrollIntoViewIfNeeded()
  await page.screenshot({path:'outputs/ai-business/iphone-se-insights.png'})
  await page.goto('/health-events/search');await page.getByLabel('搜索健康随身记',{exact:true}).fill('上次皮肤发红')
  await expect(page.getByText(/找到 \d+ 条相关随记/)).toBeVisible()
  await page.screenshot({path:'outputs/ai-business/iphone-se-search.png'})
  const tasks=await(await request.get('/api/desensitization-tests?memberId=child-a',{headers})).json()
  expect(tasks.tasks.length).toBeGreaterThan(0)
  await page.goto(`/desensitization-tests?desensitization=${tasks.tasks[0].id}`)
  await page.getByText('查看给医生复核的排敏资料摘要',{exact:true}).click()
  await expect(page.getByLabel('排敏资料摘要')).toHaveValue(/本地事实/)
  await page.getByLabel('排敏资料摘要').scrollIntoViewIfNeeded()
  await page.screenshot({path:'outputs/ai-business/iphone-se-desensitization.png'})
  const food={id:'synthetic-milk',accountId:'visit-test',memberId:'child-a',category:'food',name:'牛奶',customName:'',currentStatus:'confirmed',createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-30T00:00:00Z',reactions:[],tests:[],evidenceLinks:[],history:[]}
  const saved=await page.request.post('/api/auth/profile-sections',{headers,data:{memberId:'child-a',sectionId:'allergy',records:[food],revision:0}})
  expect(saved.ok()).toBe(true)
  await page.goto('/dietary-card');await expect(page.getByText('Milk / 牛奶',{exact:true})).toBeVisible()
  await page.screenshot({path:'outputs/ai-business/iphone-se-dietary.png'})
  for(const width of [320,375,390]){await page.setViewportSize({width,height:568});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
  expect((await(await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(before.calls)
})
