import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import path from 'node:path'
import {Readable} from 'node:stream'
import {randomUUID} from 'node:crypto'
import sharp from 'sharp'
import {QuickRecordPhotoService} from './quick-record-photo-service.mjs'
import {FamilyMemberService} from '../members/family-member-service.mjs'
import {uploadSymptomMedia} from './symptom-media-upload.mjs'
import {SymptomMediaJobs} from '../ai/symptom-media-jobs.mjs'
test('stream size limit and corrupt iPhone HEIC return explicit recoverable errors',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'hoooho-limit-test-'));try{const members=new FamilyMemberService({dataDirectory:directory}),m=await members.create('limits',{name:'合成孩子',relationship:'child',birthday:'2024-01-01',gender:'female'}),photos=new QuickRecordPhotoService({dataDirectory:directory});const request=(type,length)=>{const r=Readable.from([Buffer.from('not media')]);r.headers={'content-type':type,'content-length':String(length),'x-hoooho-upload-id':randomUUID()};return r};await assert.rejects(()=>uploadSymptomMedia(photos,request('video/mp4',100*1024*1024+1),'limits','draft_limits',m.id),{status:413,code:'MEDIA_SIZE_LIMIT'});await assert.rejects(()=>uploadSymptomMedia(photos,request('image/heic',9),'limits','draft_limits',m.id),e=>e.code==='IMAGE_DECODE_FAILED'&&e.message.includes('JPG'));assert.equal((await photos.list('limits',m.id,'draft_limits')).length,0)}finally{await rm(directory,{recursive:true,force:true})}})
test('raw image upload retains originals, deduplicates retry, scopes ownership and persists reviewed draft',async()=>{const directory=await mkdtemp(path.join(tmpdir(),'hoooho-raw-test-'));try{const members=new FamilyMemberService({dataDirectory:directory}),m=await members.create('test-account',{name:'合成孩子',relationship:'child',birthday:'2024-01-01',gender:'female'}),photos=new QuickRecordPhotoService({dataDirectory:directory}),buffer=await sharp({create:{width:24,height:24,channels:3,background:'#dd9988'}}).png().toBuffer(),uploadId=randomUUID();const req=()=>{const r=Readable.from([buffer]);r.headers={'content-type':'image/png','x-hoooho-file-name':encodeURIComponent('合成.png'),'x-hoooho-upload-id':uploadId};return r};const a=await uploadSymptomMedia(photos,req(),'test-account','draft_test123',m.id);assert.equal(a.mimeType,'image/png');assert.deepEqual((await photos.read('test-account',m.id,'draft_test123',a.id)).buffer,buffer);assert.equal((await uploadSymptomMedia(photos,req(),'test-account','draft_test123',m.id)).id,a.id);await assert.rejects(()=>photos.getOwnedPhoto('other',m.id,'draft_test123',a.id));const repeated=req();repeated.headers['x-hoooho-upload-id']=randomUUID();assert.equal((await uploadSymptomMedia(photos,repeated,'test-account','draft_test123',m.id)).id,a.id);let calls=0;const jobs=new SymptomMediaJobs(photos,{provider:{name:'fixture',apiKey:'fixture-only',baseUrl:'https://fixture.invalid',fetch:async()=>{calls++;return Response.json({output:[{content:[{type:'output_text',text:JSON.stringify({observations:[{frame:0,text:'局部发红'}],questions:['时间未知']})}]}]})}},audio:{},logger:{info(){}}});await jobs.start('test-account',m.id,'draft_test123',a.id);while(jobs.active.size)await new Promise(r=>setTimeout(r,30));const saved=await photos.getOwnedPhoto('test-account',m.id,'draft_test123',a.id);assert.equal(saved.review.confirmed,false);assert.equal(saved.review.vision.observations[0].sourceId,a.id);assert.equal(saved.review.referenceDate,null);assert.equal(calls,1);const attached=await photos.attach('test-account','event','record',m.id,[saved]);assert.equal(attached[0].mediaReview.confirmed,false);assert.equal(attached[0].mimeType,'image/png')}finally{await rm(directory,{recursive:true,force:true})}})
