import { apiRequest } from './apiClient'

export type DesensitizationSymptom = '红疹' | '瘙痒' | '风团' | '肿胀' | '腹痛' | '呕吐' | '腹泻' | '便血' | '咳嗽' | '喘鸣' | '呼吸困难' | '喉咙紧'
export interface DesensitizationRecordDto { id:string; taskId:string; status:'draft'|'effective'; symptomAnswer:'present'|'absent'|null; exposureAnswer:'eaten'|'not_eaten'|null; symptoms:DesensitizationSymptom[]; note:string; actualFood:string; preparation:string; amount:string; occurredAt:string; source:'caregiver_record'; planVersion:number|null; version:number; createdAt:string; updatedAt:string; withdrawnAt:string|null }
export interface DesensitizationPlanDto { id:string; version:number; sourceType:'caregiver_transcription'|'verified_source'; sourceName:string; visitDate:string; food:string; preparation:string; firstAmount:string; unit:string; location:string; frequency:string; observationPeriod:string; progressionCondition:string; stopRule:string; reviewDate:string; complete:boolean; createdAt:string }
export interface LinkedDietRecordDto { recordId:string; eventId:string; occurredAt:string; sourceText:string|null; content:string; foods:string[]; matchedFoods:string[]; amount:string; preparation:string; reactions:string[]; relation:'confirmed'|'pending' }
export interface DesensitizationTaskDto { id:string; memberId:string; displayName:string; categoryKey:string; categoryLabel:string; confidence:'confirmed'|'custom'; status:'active'|'archived'; version:number; progressionPaused:boolean; pausedAt?:string|null; records:DesensitizationRecordDto[]; linkedRecords:LinkedDietRecordDto[]; trend:Array<{day:string;state:'symptom'|'clear'|'unknown';recordIds:string[]}>; latestSummary:string; nextStep:string; currentPlan:DesensitizationPlanDto|null; createdAt:string; updatedAt:string; archivedAt?:string|null }
export interface FrequentFoodSuggestion { name:string; count:number; latestAt:string }
export interface DesensitizationListDto { tasks:DesensitizationTaskDto[]; suggestions:FrequentFoodSuggestion[] }

export interface ObservationInput { status:'draft'|'effective'; symptomAnswer:'present'|'absent'|null; exposureAnswer:'eaten'|'not_eaten'|null; symptoms:DesensitizationSymptom[]; note:string; actualFood:string; preparation:string; amount:string; occurredAt:string; idempotencyKey?:string; version?:number }
export interface PlanInput { sourceType:'caregiver_transcription'|'verified_source'; sourceName:string; visitDate:string; food:string; preparation:string; firstAmount:string; unit:string; location:string; frequency:string; observationPeriod:string; progressionCondition:string; stopRule:string; reviewDate:string; resumeProgression?:boolean }

export const desensitizationTestService = {
  list(memberId:string, token:string, signal?:AbortSignal) { return apiRequest<DesensitizationListDto>(`/api/desensitization-tests?memberId=${encodeURIComponent(memberId)}`, { token, signal }) },
  create(memberId:string, displayName:string, token:string) { return apiRequest<{task:DesensitizationTaskDto;existing:boolean;restoredArchived?:boolean}>('/api/desensitization-tests', { method:'POST', token, body:{memberId,displayName} }) },
  updateName(id:string, displayName:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}`, { method:'PATCH', token, body:{displayName,version} }) },
  archive(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/archive`, { method:'POST', token, body:{version} }) },
  restore(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/restore`, { method:'POST', token, body:{version} }) },
  delete(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}`, { method:'DELETE', token, body:{version} }) },
  undoDelete(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/undo-delete`, { method:'POST', token, body:{version} }) },
  saveRecord(id:string, input:ObservationInput, token:string) { return apiRequest<{record:DesensitizationRecordDto;task:DesensitizationTaskDto;idempotent:boolean}>(`/api/desensitization-tests/${encodeURIComponent(id)}/records`, { method:'POST', token, body:input }) },
  updateRecord(id:string, recordId:string, input:ObservationInput, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}`, { method:'PATCH', token, body:input }) },
  withdrawRecord(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/withdraw`, { method:'POST', token, body:{version} }) },
  restoreRecord(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/restore`, { method:'POST', token, body:{version} }) },
  undoRecordUpdate(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/undo-update`, { method:'POST', token, body:{version} }) },
  savePlan(id:string, input:PlanInput, taskVersion:number, token:string) { return apiRequest<{task:DesensitizationTaskDto;plan:DesensitizationPlanDto}>(`/api/desensitization-tests/${encodeURIComponent(id)}/plan`, { method:'PUT', token, body:{...input,taskVersion} }) }
}
