import { apiRequest } from './apiClient'

export type DesensitizationSymptom = '红疹' | '瘙痒' | '风团' | '肿胀' | '腹痛' | '呕吐' | '腹泻' | '便血' | '咳嗽' | '喘鸣' | '呼吸困难' | '喉咙紧'
export interface DesensitizationRecordDto { id:string; taskId:string; originTaskId?:string; sourceEventId?:string; scopeEntityId?:string; focusEntityIds?:string[]; status:'draft'|'effective'; symptomAnswer:'present'|'absent'|null; exposureAnswer:'eaten'|'not_eaten'|null; symptoms:DesensitizationSymptom[]; note:string; actualFood:string; preparation:string; amount:string; occurredAt:string; source:'caregiver_record'; planVersion:number|null; version:number; createdAt:string; updatedAt:string; withdrawnAt:string|null }
export interface DesensitizationPlanDto { id:string; version:number; sourceType:'caregiver_transcription'|'verified_source'; sourceName:string; visitDate:string; food:string; preparation:string; firstAmount:string; unit:string; location:string; frequency:string; observationPeriod:string; progressionCondition:string; stopRule:string; reviewDate:string; complete:boolean; createdAt:string }
export interface LinkedDietRecordDto { recordId:string; eventId:string; occurredAt:string; sourceText:string|null; content:string; foods:string[]; matchedFoods:string[]; amount:string; preparation:string; reactions:string[]; relation:'confirmed'|'pending' }
export type FoodEntityType='food'|'source'|'component'|'unknown'
export interface FoodRelationshipNode { id:string; label:string; type:FoodEntityType; relation:string; relationLabel:string; certainty:'known'|'confirmed'|'pending' }
export interface FoodEntityDto { id:string; type:FoodEntityType; label:string; categoryLabel:string; confidence:'confirmed'|'custom'; sourceIds:string[]; description:string; relations:FoodRelationshipNode[] }
export interface DesensitizationScopeDto { entityId:string; entityType:FoodEntityType; label:string; sourceIds:string[]; originalInput:string; knowledgeVersion:string }
export interface DesensitizationTaskDto { id:string; memberId:string; displayName:string; categoryKey:string; categoryLabel:string; confidence:'confirmed'|'custom'; status:'active'|'archived'; version:number; scope:DesensitizationScopeDto; foodLinks:Array<{entityId:string;label:string;evidenceStatus:'confirmed'|'pending';evidenceSource?:'knowledge'|'user';brand?:string;formula?:string;validFrom?:string;validTo?:string|null;addedAt:string}>; componentFocus:Array<{entityId:string;label:string;addedAt:string}>; mergedFrom:Array<{taskId:string;displayName:string;previousStatus:'active'|'archived';scope:DesensitizationScopeDto;mergedAt:string}>; mergedPlans:Array<{sourceTaskId:string;sourceDisplayName:string;plan:DesensitizationPlanDto}>; relatedTaskIds:string[]; associationSummary:{foods:string[];components:string[];mergedSources:string[];confirmedRecordCount:number;pendingRecordCount:number;componentRecordCounts:Array<{entityId:string;label:string;applicableRecordCount:number}>}; progressionPaused:boolean; pausedAt?:string|null; records:DesensitizationRecordDto[]; linkedRecords:LinkedDietRecordDto[]; trend:Array<{day:string;state:'symptom'|'clear'|'unknown';recordIds:string[]}>; latestSummary:string; nextStep:string; currentPlan:DesensitizationPlanDto|null; createdAt:string; updatedAt:string; archivedAt?:string|null }
export interface FrequentFoodSuggestion { name:string; count:number; latestAt:string }
export interface DesensitizationListDto { tasks:DesensitizationTaskDto[]; suggestions:FrequentFoodSuggestion[]; redirects:Array<{taskId:string;targetTaskId:string;filterLabel:string}> }
export interface DesensitizationMatchDto { taskId:string;displayName:string;status:'active'|'archived';version:number;relation:'same'|'component_focus'|'shared_source'|'partial_overlap'|'possible';certainty:'known'|'confirmed'|'pending';reason:string;recordCount:number;confirmedRecordCount:number;pendingRecordCount:number;scope:DesensitizationScopeDto }
export interface DesensitizationResolutionDto { originalInput:string;entity:FoodEntityDto;ambiguity:Array<{id:string;label:string}>;knowledgeVersion:string;resolutionVersion:string;matches:DesensitizationMatchDto[];selectedTaskIds:string[];historyRecords:LinkedDietRecordDto[];expectedVersions:Record<string,number>;action:{mode:'new'|'continue'|'restore'|'join'|'merge'|'linked';label:string;targetName:string;description:string;canObserveSeparately:boolean};preview:{selectedCount:number;recordCount:number;confirmedRecordCount:number;pendingRecordCount:number;deduplicatedCount:number;historyRecordCount:number} }
export interface ResolutionInput { memberId:string;input:string;focusId?:string;selectedTaskIds?:string[];resolutionVersion?:string;operationId?:string;separate?:boolean }

export interface ObservationInput { status:'draft'|'effective'; symptomAnswer:'present'|'absent'|null; exposureAnswer:'eaten'|'not_eaten'|null; symptoms:DesensitizationSymptom[]; note:string; actualFood:string; preparation:string; amount:string; occurredAt:string; idempotencyKey?:string; version?:number }
export interface PlanInput { sourceType:'caregiver_transcription'|'verified_source'; sourceName:string; visitDate:string; food:string; preparation:string; firstAmount:string; unit:string; location:string; frequency:string; observationPeriod:string; progressionCondition:string; stopRule:string; reviewDate:string; resumeProgression?:boolean }

export const desensitizationTestService = {
  list(memberId:string, token:string, signal?:AbortSignal) { return apiRequest<DesensitizationListDto>(`/api/desensitization-tests?memberId=${encodeURIComponent(memberId)}`, { token, signal }) },
  resolve(input:ResolutionInput, token:string, signal?:AbortSignal) { return apiRequest<DesensitizationResolutionDto>('/api/desensitization-tests/resolve', { method:'POST', token, body:input, signal }) },
  commitResolution(input:ResolutionInput & {operationId:string;resolutionVersion:string}, token:string) { return apiRequest<{task:DesensitizationTaskDto;operationId:string|null;undoable:boolean;idempotent:boolean;message:string}>('/api/desensitization-tests/commit', { method:'POST', token, body:input }) },
  undoOperation(operationId:string,token:string) { return apiRequest<{tasks:DesensitizationTaskDto[];focusTaskId:string;message:string}>(`/api/desensitization-tests/operations/${encodeURIComponent(operationId)}/undo`, { method:'POST', token, body:{} }) },
  manageAssociation(id:string,input:{action:'remove-food'|'remove-component'|'restore-merged';entityId?:string;sourceTaskId?:string;version:number},token:string) { return apiRequest<{task:DesensitizationTaskDto|null;tasks:DesensitizationTaskDto[]}>(`/api/desensitization-tests/${encodeURIComponent(id)}/associations`, { method:'POST', token, body:input }) },
  create(memberId:string, displayName:string, token:string) { return apiRequest<{task:DesensitizationTaskDto;existing:boolean;restoredArchived?:boolean}>('/api/desensitization-tests', { method:'POST', token, body:{memberId,displayName} }) },
  updateName(id:string, displayName:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}`, { method:'PATCH', token, body:{displayName,version} }) },
  archive(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/archive`, { method:'POST', token, body:{version} }) },
  restore(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/restore`, { method:'POST', token, body:{version} }) },
  delete(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}`, { method:'DELETE', token, body:{version} }) },
  undoDelete(id:string, version:number, token:string) { return apiRequest<DesensitizationTaskDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/undo-delete`, { method:'POST', token, body:{version} }) },
  saveRecord(id:string, input:ObservationInput, token:string) { return apiRequest<{record:DesensitizationRecordDto;task:DesensitizationTaskDto;idempotent:boolean}>(`/api/desensitization-tests/${encodeURIComponent(id)}/records`, { method:'POST', token, body:input }) },
  updateRecord(id:string, recordId:string, input:ObservationInput, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}`, { method:'PATCH', token, body:input }) },
  withdrawRecord(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/withdraw`, { method:'POST', token, body:{version} }) },
  restoreRecord(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/restore`, { method:'POST', token, body:{version} }) },
  undoRecordUpdate(id:string, recordId:string, version:number, token:string) { return apiRequest<DesensitizationRecordDto>(`/api/desensitization-tests/${encodeURIComponent(id)}/records/${encodeURIComponent(recordId)}/undo-update`, { method:'POST', token, body:{version} }) },
  savePlan(id:string, input:PlanInput, taskVersion:number, token:string) { return apiRequest<{task:DesensitizationTaskDto;plan:DesensitizationPlanDto}>(`/api/desensitization-tests/${encodeURIComponent(id)}/plan`, { method:'PUT', token, body:{...input,taskVersion} }) }
}
