import { expect,test,type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'
const accountId='time-view-test-account'
const token=new TokenService('time-view-e2e-local-only-secret',60*60_000).create({id:accountId})
async function prepare(page:Page,member='child-one') {
  page.on('pageerror',error=>{throw error})
  await page.addInitScript(({token,member,accountId})=>{
    sessionStorage.setItem('hoooho-auth-token',token)
    if(!sessionStorage.getItem('entry-test-initialized')){
      localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:accountId},currentMemberId:member,members:[],profile:null},version:5}))
      sessionStorage.setItem('entry-test-initialized','true')
    }
  },{token,member,accountId})
  await page.goto('/health-events')
  await expect(page.getByRole('button',{name:'记录日常',exact:true})).toBeEnabled()
}
async function diet(page:Page) {
  await page.getByRole('button',{name:'记录日常',exact:true}).click()
  await page.getByRole('group',{name:'记录日常选项'}).getByRole('button',{name:'喂养/饮食'}).click()
  return page.getByRole('dialog',{name:'喂养/饮食',exact:true})
}
async function shot(page:Page,name:string) {await mkdir('outputs/record-entry',{recursive:true});await page.screenshot({path:`outputs/record-entry/${name}.png`})}
async function save(page:Page,form:ReturnType<Page['getByRole']>) {
  const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/quick-records'&&r.request().method()==='POST')
  await form.getByRole('button',{name:'保存记录',exact:true}).click()
  // The original duplicate decision is preserved.
  await Promise.race([page.getByRole('button',{name:'仍然新增一条'}).waitFor().then(()=>page.getByRole('button',{name:'仍然新增一条'}).click()),response]).catch(()=>undefined)
  const result=await response;expect(result.status()).toBe(201)
  const ids=await result.json()
  const records=await (await page.request.get(`/api/events/${ids.eventId}/records?view=time`,{headers:{Authorization:`Bearer ${token}`}})).json()
  await expect(form).toHaveCount(0)
  return {ids,record:records.find((r:any)=>r.id===ids.recordId)}
}
for(const width of [375,390,430,1280]) test(`entry layout, anchored routine and direct flows at ${width}`,async({page})=>{
  await page.setViewportSize({width,height:width===1280?900:667});await prepare(page)
  const footer=page.locator('.journal-record-actions')
  await expect(footer.locator('.record-entry-grid button')).toHaveText(['记录症状','记录日常','记录补剂','记录用药'])
  for(const button of await footer.locator('button').all())await expect(button).toBeInViewport()
  expect(await footer.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
  await expect(footer.locator('.record-entry-grid img,.record-entry-grid svg,.record-smart-action svg,.record-smart-action img')).toHaveCount(0)
  expect(await footer.locator('.record-entry-grid button').evaluateAll(buttons=>buttons.map(button=>button.getBoundingClientRect().height))).toEqual([44,44,44,44])
  expect(await footer.locator('.record-smart-action .hoho-button__content').evaluate(el=>getComputedStyle(el).justifyContent)).toBe('center')
  const geometry = await page.evaluate(() => {
    const year = document.querySelector('.journal-year-picker')!.getBoundingClientRect()
    const marker = document.querySelector('.journal-timeline-row--now .journal-timeline-marker')!.getBoundingClientRect()
    const now = document.querySelector('.journal-now-cell')!.getBoundingClientRect()
    const date = document.querySelector('.journal-date-navigation')!.getBoundingClientRect()
    const subject = document.querySelector('.journal-subject-row')!.getBoundingClientRect()
    const summary = getComputedStyle(document.querySelector('.journal-subject-summary')!)
    return { axisDifference: Math.abs(marker.x + marker.width / 2 - (year.right - .5)), nowHeight: now.height, above: date.top - subject.bottom, below: now.top - date.bottom, border: summary.borderTopWidth, style: summary.borderTopStyle, overflow: document.documentElement.scrollWidth > innerWidth }
  })
  expect(geometry.axisDifference).toBeLessThanOrEqual(.6)
  expect(geometry.nowHeight).toBe(26)
  expect(geometry.above).toBe(6)
  expect(geometry.below).toBe(6)
  expect(geometry.border).toBe('1px'); expect(geometry.style).toBe('solid'); expect(geometry.overflow).toBe(false)
  await shot(page,`home-${width}`)
  const daily=page.getByRole('button',{name:'记录日常',exact:true})
  await daily.click();const options=page.getByRole('group',{name:'记录日常选项'})
  await expect(options.getByRole('button')).toHaveText(['喂养/饮食','睡眠','排便','户外活动'])
  await expect(daily).toHaveAttribute('aria-pressed','true')
  expect((await options.boundingBox())!.y+(await options.boundingBox())!.height).toBeLessThan((await daily.boundingBox())!.y)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await shot(page,`daily-open-${width}`)
  await daily.click();await expect(options).toHaveCount(0)
  await daily.click();await page.getByRole('heading',{name:'健康随记',exact:true}).click();await expect(options).toHaveCount(0)
  for(const [button,title] of [['记录症状','记录症状'],['记录补剂','记录补剂'],['记录用药','记录用药']]) {
    await daily.click();await footer.getByRole('button',{name:button,exact:true}).click()
    const form=page.getByRole('dialog',{name:title,exact:true});await expect(form).toBeVisible();await expect(options).toHaveCount(0)
    if(title==='记录症状')await form.getByRole('button',{name:'关闭',exact:true}).click();else await form.getByRole('button',{name:/返回/,exact:true}).click()
  }
  for(const [option,title] of [['喂养/饮食','喂养/饮食'],['睡眠','记录睡眠'],['排便','记录排便'],['户外活动','记录户外活动']]){
    await daily.click();await options.getByRole('button',{name:option,exact:true}).click()
    const form=page.getByRole('dialog',{name:title,exact:true});await expect(form).toBeVisible();await expect(options).toHaveCount(0)
    await form.getByRole('button',{name:/返回/,exact:true}).click()
  }
  await footer.getByRole('button',{name:'智能记录',exact:true}).click()
  await expect(page.getByRole('dialog',{name:/整理/})).toBeVisible()
})
test('drafts, common food fields, timer pause, reload and no automatic saves',async({page})=>{
  await prepare(page);const form=await diet(page)
  expect(await form.locator('.diet-category-switches').evaluate(el=>el.scrollWidth<=el.clientWidth && [...el.querySelectorAll('button')].every(b=>b.getBoundingClientRect().right<=innerWidth && b.getBoundingClientRect().height>=44))).toBe(true)
  let posts=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/quick-records'&&r.method()==='POST')posts++})
  await form.getByLabel('左侧手填分钟').fill('3')
  await form.getByRole('button',{name:'左侧开始计时'}).click();await page.waitForTimeout(1200)
  await form.getByRole('radio',{name:'配方奶',exact:true}).click();await form.getByLabel('喂奶量').fill('120')
  await form.getByRole('button',{name:'吐奶',exact:true}).click()
  await form.getByRole('radio',{name:'瓶喂母乳',exact:true}).click();await expect(form.getByLabel('喂奶量')).toHaveValue('')
  await form.getByLabel('喂奶量').fill('90')
  await form.getByRole('radio',{name:'母乳',exact:true}).click();await expect(form.getByLabel('左侧手填分钟')).toHaveValue('3')
  await expect(form.getByRole('button',{name:'左侧停止计时'})).toHaveCount(0)
  const duration=await form.locator('.diet-total-duration strong:visible').textContent();await page.waitForTimeout(1100);await expect(form.locator('.diet-total-duration strong:visible')).toHaveText(duration!)
  await form.getByRole('radio',{name:'食物饮食',exact:true}).click();await form.getByLabel('输入食物名称').fill('香蕉');await form.getByRole('button',{name:'添加食物'}).click()
  await form.getByRole('button',{name:'皮肤',exact:true}).click();await form.locator('input[aria-label="记录时间"]').fill('2026-09-25T12:00')
  await form.getByLabel('输入食物名称').fill('尚未添加的苹果')
  for(const name of ['正餐','零食','辅食']){await form.getByRole('radio',{name,exact:true}).click();await expect(form.getByLabel('已添加食物')).toContainText('香蕉');await expect(form.getByLabel('输入食物名称')).toHaveValue('尚未添加的苹果');await expect(form.locator('input[aria-label="记录时间"]')).toHaveValue('2026-09-25T12:00');await expect(form.getByRole('button',{name:'皮肤',exact:true})).toHaveAttribute('aria-pressed','true')}
  await shot(page,'food-filled-375')
  await form.getByRole('radio',{name:'奶类喂养'}).click();await form.getByRole('radio',{name:'配方奶',exact:true}).click();await expect(form.getByLabel('喂奶量')).toHaveValue('120')
  await page.reload();const restored=await diet(page);await expect(restored.getByLabel('喂奶量')).toHaveValue('120')
  await restored.getByRole('radio',{name:'食物饮食'}).click();await expect(restored.getByLabel('已添加食物')).toContainText('香蕉');await expect(restored.locator('input[aria-label="记录时间"]')).toHaveValue('2026-09-25T12:00')
  expect(posts).toBe(0)
  await expect(restored.getByLabel('备注')).toHaveCount(0);await expect(restored.getByText('吃了多少', {exact:true})).toHaveCount(0)
  await restored.getByRole('radio',{name:'奶类喂养'}).click();await shot(page,'milk-filled-375')
})
for(const [kind,label] of [['breast','母乳'],['formula','配方奶'],['expressed','瓶喂母乳'],['mixed','混合喂养'],['complementary','辅食'],['meal','正餐'],['snack','零食']]) test(`save and historical editor restores ${kind}`,async({page})=>{
  await prepare(page,'routine-child');const form=await diet(page)
  const milk=['breast','formula','expressed','mixed'].includes(kind)
  if(!milk)await form.getByRole('radio',{name:'食物饮食'}).click()
  await form.getByRole('radio',{name:label,exact:true}).click()
  if(kind==='breast'||kind==='mixed')await form.getByLabel('左侧手填分钟').fill('4')
  if(milk&&kind!=='breast')await form.getByLabel('喂奶量').fill('110')
  if(!milk){await form.getByLabel('输入食物名称').fill(`合成食物${kind}`);await form.getByRole('button',{name:'添加食物'}).click();await form.getByRole('button',{name:'消化',exact:true}).click()}
  await form.locator('input[aria-label="记录时间"]').fill('2026-09-25T13:10')
  const {ids,record}=await save(page,form)
  expect(record.journal.diet.kind).toBe(milk?'feeding':kind)
  expect(record.journal.diet.feedingMethod).toBe(milk?kind:undefined)
  expect(record.journal.diet.foods).toEqual(milk?undefined:[`合成食物${kind}`])
  expect(record.journal.diet.breastSeconds!==undefined).toBe(kind==='breast'||kind==='mixed')
  expect(record.journal.diet.bottleMl).toBe(milk&&kind!=='breast'?110:undefined)
  await page.locator(`[data-record-id="${ids.recordId}"]`).click()
  await page.getByRole('button',{name:'编辑喂养/饮食'}).click()
  const editor=page.getByRole('dialog',{name:'喂养/饮食',exact:true})
  await expect(editor.getByRole('radio',{name:milk?'奶类喂养':'食物饮食',exact:true})).toHaveAttribute('aria-checked','true')
  await expect(editor.getByRole('radio',{name:label,exact:true})).toHaveAttribute('aria-checked','true')
  await expect(editor.locator('input[aria-label="记录时间"]')).toHaveValue('2026-09-25T13:10')
  if(milk&&kind!=='breast')await expect(editor.getByLabel('喂奶量')).toHaveValue('110')
  if(!milk)await expect(editor.getByLabel('已添加食物')).toContainText(`合成食物${kind}`)
  const update=page.waitForResponse(r=>new URL(r.url()).pathname.endsWith(`/records/${ids.recordId}`)&&r.request().method()==='PATCH')
  await editor.locator('input[aria-label="记录时间"]').fill('2026-09-25T13:00');await editor.getByRole('button',{name:'保存记录',exact:true}).click();expect((await update).ok()).toBe(true)
  await expect(editor).toHaveCount(0)
})
test('save failure and repeated click keep one record, drafts are member isolated',async({page})=>{
  await prepare(page);const form=await diet(page)
  await form.getByRole('radio',{name:'配方奶',exact:true}).click();await form.getByLabel('喂奶量').fill('123')
  await form.locator('input[aria-label="记录时间"]').fill('2026-09-24T10:00')
  await page.route('**/api/quick-records',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'合成保存失败'}})}),{times:1})
  await form.getByRole('button',{name:'保存记录'}).click();await expect(form.getByRole('alert')).toContainText('合成保存失败');await expect(form.getByLabel('喂奶量')).toHaveValue('123')
  const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/quick-records'&&r.request().method()==='POST')
  await form.getByRole('button',{name:'保存记录'}).dblclick();expect((await response).status()).toBe(201)
  await expect(form).toHaveCount(0)
  await diet(page);await page.getByRole('dialog',{name:'喂养/饮食',exact:true}).getByLabel('喂奶量').fill('88')
  await page.getByRole('dialog',{name:'喂养/饮食',exact:true}).getByRole('button',{name:'返回',exact:true}).click()
  await page.evaluate(()=>{const stored=JSON.parse(localStorage.getItem('hoooho-app')!);stored.state.currentMemberId='child-two';localStorage.setItem('hoooho-app',JSON.stringify(stored))});await page.reload()
  const other=await diet(page);await expect(other.getByRole('radio',{name:'母乳',exact:true})).toHaveAttribute('aria-checked','true');await other.getByRole('radio',{name:'配方奶',exact:true}).click();await expect(other.getByLabel('喂奶量')).toHaveValue('')
})

test('short screen anchoring, resize and keyboard segmented navigation',async({page})=>{
  await page.setViewportSize({width:375,height:360});await prepare(page)
  const daily=page.getByRole('button',{name:'记录日常',exact:true})
  await daily.click()
  for(const button of await page.locator('.journal-record-actions button').all())await expect(button).toBeInViewport()
  await page.setViewportSize({width:390,height:667})
  await expect(page.getByRole('group',{name:'记录日常选项'})).toBeInViewport()
  await page.keyboard.press('Escape');await expect(daily).toBeFocused()
  const form=await diet(page)
  const breast=form.getByRole('radio',{name:'母乳',exact:true})
  await breast.focus();await page.keyboard.press('ArrowRight')
  await expect(form.getByRole('radio',{name:'配方奶',exact:true})).toBeFocused()
  await expect(form.getByRole('radio',{name:'配方奶',exact:true})).toHaveAttribute('aria-checked','true')
  await page.keyboard.press('End');await expect(form.getByRole('radio',{name:'混合喂养',exact:true})).toBeFocused()
  await page.setViewportSize({width:375,height:360})
  await form.getByLabel('喂奶量').fill('100')
  await form.getByRole('button',{name:'保存记录'}).scrollIntoViewIfNeeded()
  await expect(form.getByRole('button',{name:'保存记录'})).toBeInViewport()
  expect(await form.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
})

test('direct supplement preserves dose, saves supplement type and restores edit fields',async({page})=>{
  await prepare(page,'routine-child')
  await page.getByRole('button',{name:'记录补剂',exact:true}).click()
  const form=page.getByRole('dialog',{name:'记录补剂',exact:true})
  await form.getByLabel('输入补剂名称').fill('合成补剂');await form.getByRole('button',{name:'添加补剂'}).click()
  await form.getByLabel('用量',{exact:true}).fill('2')
  await form.getByRole('button',{name:'粒',exact:true}).click()
  await form.locator('input[aria-label="记录时间"]').fill('2026-09-25T14:10')
  const {ids,record}=await save(page,form)
  expect(record.journal.diet).toMatchObject({kind:'supplement',supplementNames:['合成补剂'],supplementAmount:'2',supplementUnit:'粒'})
  await page.locator(`[data-record-id="${ids.recordId}"]`).click();await page.getByRole('button',{name:'编辑喂养/饮食'}).click()
  await expect(form.getByLabel('用量',{exact:true})).toHaveValue('2')
  await expect(form.getByRole('button',{name:'粒',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(form.getByLabel('已添加补剂')).toContainText('合成补剂')
})
