import { expect, test, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'
const accountId = 'daily-e2e-account', token = new TokenService('daily-e2e-local-only-secret', 3600_000).create({ id: accountId })
const headers = { Authorization: `Bearer ${token}`, 'X-Hoooho-Timezone': 'Asia/Shanghai' }
const localDay = (delta = 0) => { const d = new Date(); d.setDate(d.getDate() + delta); return new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai' }).format(d) }
async function prepare(page: Page, name: string, width: number, existing = false) {
  await page.setViewportSize({ width, height: 667 }); page.on('pageerror', error => { throw error })
  const member = existing ? (await (await page.request.get('/api/members', { headers })).json()).find((value: any) => value.name === name) : await (await page.request.post('/api/members', { headers, data: { name, birthday: '2025-01-01', gender: 'female', relationship: 'child' } })).json()
  expect(member.id).toBeTruthy()
  await page.addInitScript(({ token, accountId, memberId }) => { sessionStorage.setItem('hoooho-auth-token', token); if (!sessionStorage.getItem('daily-test-init')) { localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: accountId }, currentMemberId: memberId, members: [], profile: null }, version: 5 })); sessionStorage.setItem('daily-test-init', 'true') } }, { token, accountId, memberId: member.id })
  await page.goto('/health-events'); await expect(page.getByRole('button', { name: '记录日常', exact: true })).toBeEnabled()
  return member.id as string
}
test('all existing daily forms expose one starter without writing on cancellation, and corrupt drafts/load errors do not silently activate rules', async ({ page }) => {
  const memberId = await prepare(page, '取消与加载验收', 375)
  const settings = () => page.getByRole('region', { name: '每天自动记录设置' })
  let writes = 0
  page.on('request', request => { if (new URL(request.url()).pathname === '/api/quick-records' && request.method() === 'POST') writes++ })
  for (const [entry, title] of [['补剂', '记录补剂'], ['记录用药', '记录用药']]) {
    await page.getByRole('button', { name: entry, exact: true }).click()
    const form = page.getByRole('dialog', { name: title, exact: true })
    await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toBeEnabled()
    await settings().getByRole('switch', { name: '每天自动记录', exact: true }).click(); await expect(settings().locator('.daily-record-slot')).toHaveCount(1)
    await form.getByRole('button', { name: /^返回/ }).click(); await expect(form).toHaveCount(0)
  }
  for (const [choice, title] of [['睡眠', '记录睡眠'], ['排便', '记录排便'], ['身体涂抹', '记录身体涂抹']]) {
    await page.getByRole('button', { name: '记录日常', exact: true }).click(); await page.getByRole('group', { name: '记录日常选项' }).getByRole('button', { name: choice, exact: true }).click()
    const form = page.getByRole('dialog', { name: title, exact: true })
    await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toBeEnabled()
    await settings().getByRole('switch', { name: '每天自动记录', exact: true }).click(); await expect(settings().locator('.daily-record-slot')).toHaveCount(1)
    await form.getByRole('button', { name: /^返回/ }).click(); await expect(form).toHaveCount(0)
  }
  expect(writes).toBe(0); expect(await (await page.request.get(`/api/routines/${memberId}/daily`, { headers })).json()).toEqual([])
  await page.evaluate(({ accountId, memberId }) => sessionStorage.setItem(`hoooho:daily:${accountId}:${memberId}:feeding`, JSON.stringify({ enabled: true, slots: null, revision: 0 })), { accountId, memberId })
  await page.getByRole('button', { name: '喂养/饮食', exact: true }).click()
  let form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
  await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toBeEnabled()
  await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toHaveAttribute('aria-checked', 'false')
  for (const kind of ['辅食', '正餐', '零食']) {
    await form.getByRole('radio', { name: '食物饮食', exact: true }).click(); await form.getByRole('radio', { name: kind, exact: true }).click()
    await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toBeEnabled()
    await settings().getByRole('switch', { name: '每天自动记录', exact: true }).click(); await expect(settings().locator('.daily-record-slot')).toHaveCount(1)
  }
  await form.getByRole('button', { name: '返回', exact: true }).click()
  const url = `**/api/routines/${memberId}/daily`
  await page.route(url, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '验收加载失败' } }) }))
  await page.getByRole('button', { name: '喂养/饮食', exact: true }).click(); form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
  await form.getByRole('radio', { name: '奶类喂养', exact: true }).click()
  await form.getByRole('radio', { name: '配方奶', exact: true }).click(); await form.getByRole('spinbutton', { name: /^喂奶量/ }).fill('150')
  await expect(settings().getByRole('alert')).toContainText('验收加载失败')
  await form.getByRole('button', { name: '保存记录', exact: true }).click(); await expect(form.getByText('每天设置尚未加载', { exact: false })).toBeVisible(); expect(writes).toBe(0)
  await page.unroute(url); await settings().getByRole('button', { name: '重试', exact: true }).click(); await expect(settings().getByRole('switch', { name: '每天自动记录', exact: true })).toBeEnabled()
})
async function shot(page: Page, name: string) { await mkdir('outputs/daily-records', { recursive: true }); await page.screenshot({ path: `outputs/daily-records/${name}.png` }) }
test('explicit manual association keeps provenance while feeding is ongoing and ends the same actual record', async ({ page }) => {
  const memberId = await prepare(page, '自动记录验收关联', 375, true)
  const day = localDay(-1)
  await page.getByLabel('选择日期', { exact: true }).fill(day)
  await expect(page.locator('[data-automatic-id]')).toHaveCount(3)
  const instances = await (await page.request.get(`/api/routines/${memberId}/daily/instances?day=${day}`, { headers })).json()
  const early = instances.find((value: any) => value.name === '早奶')
  await page.getByRole('button', { name: '喂养/饮食', exact: true }).click()
  const form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
  await form.getByRole('radio', { name: '配方奶', exact: true }).click()
  await form.getByLabel('本次名称（选填）').fill('早奶'); await form.getByRole('spinbutton', { name: /^喂奶量/ }).fill('160')
  await form.getByRole('textbox', { name: '记录时间', exact: true }).fill(`${day}T07:30`)
  await form.getByLabel('关联本次自动记录（选填）').selectOption(early.id)
  const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/quick-records' && r.request().method() === 'POST')
  await form.getByRole('button', { name: '开始喂养', exact: true }).click()
  const saved = await response; expect(saved.status()).toBe(201); const ids = await saved.json()
  await expect(form).toHaveCount(0); await expect(page.locator('[data-automatic-id]')).toHaveCount(2)
  const row = page.locator(`[data-record-id="${ids.recordId}"]`)
  await row.getByRole('button').click()
  const detail = page.getByRole('dialog', { name: '早奶记录详情', exact: true })
  await expect(detail.getByText('自动记录 · 已确认 · 早奶', { exact: true })).toBeVisible()
  await detail.getByLabel('实际结束时间').fill(`${day}T07:50`)
  await detail.getByRole('button', { name: '结束喂养', exact: true }).click()
  await expect(detail).toHaveCount(0); await expect(row).toContainText('早奶 · 共20分钟')
  expect((await (await page.request.get(`/api/events/${ids.eventId}/records?view=time`, { headers })).json()).length).toBe(1)
  expect((await (await page.request.get(`/api/routines/${memberId}/daily/source/${ids.recordId}`, { headers })).json()).id).toBe(early.id)
})
for (const width of [375, 390, 430]) {
  test(`one starter, independent slots, atomic actual save, next-day rule and reload at ${width}`, async ({ page }) => {
    const memberId = await prepare(page, `表单验收${width}`, width)
    await page.getByRole('button', { name: '喂养/饮食', exact: true }).click()
    const form = page.getByRole('dialog', { name: '喂养/饮食', exact: true }), settings = form.getByRole('region', { name: '每天自动记录设置' })
    await form.getByRole('radio', { name: '配方奶', exact: true }).click(); await form.getByRole('spinbutton', { name: /^喂奶量/ }).fill('150')
    await expect(settings.getByRole('switch', { name: '每天自动记录', exact: true })).toHaveAttribute('aria-checked', 'false')
    await expect(settings.locator('.daily-record-slot')).toHaveCount(0); await settings.scrollIntoViewIfNeeded(); await shot(page, `off-${width}`)
    await settings.getByRole('switch', { name: '每天自动记录', exact: true }).click()
    await expect(settings.locator('.daily-record-slot')).toHaveCount(1); await expect(settings.getByLabel('第1项名称')).toHaveValue('早奶')
    await settings.getByLabel('第1项时间').fill('07:30'); await expect(settings.getByLabel('第1项奶量（mL）')).toHaveValue('150')
    await settings.getByRole('button', { name: '添加一项', exact: true }).click(); await expect(settings.getByLabel('第2项名称')).toHaveValue('')
    await settings.getByLabel('第2项名称').fill('晚奶'); await settings.getByLabel('第2项时间').fill('21:00'); await settings.getByLabel('第2项喂养方式').selectOption('formula'); await settings.getByLabel('第2项奶量（mL）').fill('200')
    await settings.scrollIntoViewIfNeeded(); expect(await form.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true); await shot(page, `two-slots-${width}`)
    const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/quick-records' && r.request().method() === 'POST')
    await form.getByRole('button', { name: '保存记录并开启自动记录', exact: true }).click(); expect((await response).status()).toBe(201); await expect(form).toHaveCount(0)
    const rules = await (await page.request.get(`/api/routines/${memberId}/daily`, { headers })).json()
    expect(rules[0].slots.map((slot: any) => slot.fields.bottleMl)).toEqual(['150', '200']); expect(rules[0].effectiveFrom).toBe(localDay(1))
    expect(await (await page.request.get(`/api/routines/${memberId}/daily/instances?day=${localDay()}`, { headers })).json()).toEqual([])
    await page.reload(); await page.getByRole('button', { name: '喂养/饮食', exact: true }).click(); await expect(page.locator('.daily-record-slot')).toHaveCount(2)
    await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('button', { name: '返回', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
  })
  test(`pending separate from actual, adjust once, skip, provenance and batch review at ${width}`, async ({ page }) => {
    const memberId = await prepare(page, `自动记录验收${width}`, width, true)
    await page.getByLabel('选择日期', { exact: true }).fill(localDay(-1))
    await expect(page.locator('[data-automatic-id]')).toHaveCount(3); await expect(page.locator('[data-record-id]')).toHaveCount(0)
    await shot(page, `unconfirmed-${width}`)
    await page.locator('[data-automatic-id]').first().getByRole('button').click()
    const detail = page.getByRole('dialog', { name: '自动记录详情', exact: true })
    await expect(detail.getByText('自动记录 · 未确认', { exact: false })).toBeVisible()
    await detail.getByLabel('本次奶量（mL）').fill('190'); await shot(page, `confirm-${width}`)
    await detail.getByRole('button', { name: '确认已发生', exact: true }).click(); await expect(detail).toHaveCount(0)
    await expect(page.locator('[data-automatic-id]')).toHaveCount(2); await expect(page.locator('[data-record-id]')).toHaveCount(1)
    const instances = await (await page.request.get(`/api/routines/${memberId}/daily/instances?day=${localDay(-1)}`, { headers })).json()
    const item = instances.find((value: any) => value.status === 'confirmed')
    const actual = (await (await page.request.get(`/api/events/${item.eventId}/records?view=time`, { headers })).json()).find((value: any) => value.id === item.recordId)
    expect(actual.journal.diet.bottleMl).toBe(190)
    await page.locator('[data-record-id]').getByRole('button').click(); await expect(page.getByText('自动记录 · 已确认 · 晚奶')).toBeVisible(); await page.getByRole('dialog', { name: '症状记录详情' }).getByRole('button', { name: '关闭症状记录详情', exact: true }).click()
    await page.locator('[data-automatic-id]').first().getByRole('button').click(); await page.getByRole('button', { name: '本次未发生', exact: true }).click(); await expect(page.locator('[data-automatic-id]')).toHaveCount(1)
    await page.getByRole('button', { name: '调整作息', exact: true }).click(); await page.getByRole('button', { name: '管理每天自动记录', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '每天记录设置' })).toBeVisible(); await page.getByRole('button', { name: /早奶、午奶、晚奶/ }).click(); await expect(page.locator('.daily-record-slot')).toHaveCount(3)
    await shot(page, `manage-${width}`)
    await page.getByRole('dialog', { name: '每天记录设置' }).getByRole('button', { name: '关闭每天记录设置', exact: true }).click()
    await page.getByLabel('选择日期', { exact: true }).fill(localDay())
    await page.getByRole('button', { name: '核对今天的自动记录', exact: true }).click()
    const batch = page.getByRole('dialog', { name: '核对自动记录' })
    await expect(batch.getByRole('checkbox')).toHaveCount(2); await expect(batch.getByRole('button', { name: '确认选中的0项已发生' })).toBeDisabled()
    for (const checkbox of await batch.getByRole('checkbox').all()) await checkbox.check()
    await shot(page, `batch-${width}`); await batch.getByRole('button', { name: '确认选中的2项已发生' }).click()
    await expect(batch).toHaveCount(0); await expect(page.locator('[data-automatic-id]')).toHaveCount(0); await expect(page.locator('[data-record-id]')).toHaveCount(2)
  })
}
