import assert from 'node:assert/strict'
import test from 'node:test'
import { allergyReactionSummary, allergyTestResultLabel, allergyOptions, appendUniqueAllergyItems, buildTemporalStatement, createAllergyItem, createUnknownAllergyItem, formatElapsedSince, normalizeAllergyArchive, normalizeAllergyReports, readAllergyItems, testSupportsNumericValue, testSupportsStructuredResult } from './allergyProfile.ts'

test('旧过敏记录兼容迁移且绑定当前人物',()=>{const archive=normalizeAllergyArchive([{name:'猫毛',type:'环境',certainty:'怀疑中'}],'child-1','account-1');assert.equal(archive.version,2);assert.deepEqual({name:archive.items[0].name,category:archive.items[0].category,status:archive.items[0].currentStatus,memberId:archive.items[0].memberId},{name:'猫毛',category:'environment',status:'suspected',memberId:'child-1'})})
test('同分类同名去重但允许不同分类同名',()=>{const first=createAllergyItem('m1','food','自定义项');const next=appendUniqueAllergyItems([first],[createAllergyItem('m1','food','自定义项'),createAllergyItem('m1','contact','自定义项')]);assert.equal(next.length,2)})
test('六类常见选项独立且检查结果不改变状态',()=>{assert.equal(Object.keys(allergyOptions).length,6);assert.deepEqual(allergyOptions.food.slice(0,2),['牛奶','鸡蛋']);assert.deepEqual(allergyOptions.drug.slice(0,2),['青霉素类','头孢类']);const item=createAllergyItem('m1','food','牛奶');item.tests.push({id:'t',allergyItemId:item.id,memberId:'m1',testType:'血清特异性 IgE',result:'negative',value:'',unit:'',testedAt:'2026-09-01',institution:'',reportFiles:[],clinicianInterpretation:'',notes:''});assert.equal(item.currentStatus,'')})
test('日期持续时间和时间关联文案不声称因果',()=>{assert.equal(formatElapsedSince('2026-09-01',new Date('2026-09-11T00:00:00Z')),'10天');const statement=buildTemporalStatement('牛奶','饮用牛奶','皮肤发红','30分钟');assert.equal(statement,'饮用牛奶后约30分钟记录到皮肤发红');assert.doesNotMatch(statement,/导致/)})
test('无效报告被忽略且有效报告保留人工整理状态',()=>{const reports=normalizeAllergyReports([{id:'r1',name:'报告.pdf',dataUrl:'data:application/pdf;base64,AA',parsingStatus:'已识别'},{}]);assert.equal(reports.length,1);assert.equal(reports[0].parsingStatus,'待人工整理')})
test('读取过敏史只返回当前人物的数据',()=>{const current=createAllergyItem('member-current','food','牛奶','account-1');const other=createAllergyItem('member-other','drug','青霉素类','account-1');const items=readAllergyItems(JSON.stringify({version:2,items:[current,other]}),'member-current','account-1');assert.deepEqual(items.map(item=>item.memberId),['member-current']);assert.deepEqual(items.map(item=>item.name),['牛奶'])})
test('读取时同时隔离账户且纠正嵌套记录的成员归属',()=>{const current=createAllergyItem('member-current','food','牛奶','account-1');current.reactions.push({id:'r',allergyItemId:current.id,memberId:'member-other',symptomSystems:['皮肤'],symptoms:'发红',exposureAmount:'',latency:'立即',bodyLocations:'',handling:'',aggravatingFactors:'',relievingFactors:'',occurredAt:'2026-09-11T00:00:00Z',photos:[],notes:''});const otherAccount=createAllergyItem('member-current','drug','头孢类','account-2');const items=readAllergyItems(JSON.stringify([current,otherAccount]),'member-current','account-1');assert.equal(items.length,1);assert.equal(items[0].reactions[0].memberId,'member-current')})
test('尚未明确每次建立独立对象而其他分类继续去重',()=>{const first=createUnknownAllergyItem('m1');const second=createUnknownAllergyItem('m1');assert.equal(appendUniqueAllergyItems([first],[second]).length,2);assert.notEqual(first.id,second.id)})
test('症状摘要优先保留用户原文并如实回退到类别',()=>{const item=createAllergyItem('m1','food','牛奶');const base={id:'r',allergyItemId:item.id,memberId:'m1',symptomSystems:['皮肤'],symptoms:'',exposureAmount:'',latency:'说不清',bodyLocations:'',handling:'',aggravatingFactors:'',relievingFactors:'',occurredAt:'2026-09-11',photos:[],notes:''};assert.equal(allergyReactionSummary(base),'皮肤');assert.equal(allergyReactionSummary({...base,symptoms:'嘴角发红\n持续半小时'}),'嘴角发红\n持续半小时')})
test('检查类型按医学记录形态显示适用字段但不解释结果',()=>{assert.equal(testSupportsStructuredResult('血清特异性 IgE'),true);assert.equal(testSupportsNumericValue('血清特异性 IgE'),true);assert.equal(testSupportsStructuredResult('回避—再引入观察'),false);assert.equal(testSupportsNumericValue('皮肤点刺试验'),false);assert.equal(allergyTestResultLabel(''),'结果未填写')})
