import assert from 'node:assert/strict'
import test from 'node:test'
import { allergyOptions, appendUniqueAllergyItems, buildTemporalStatement, createAllergyItem, formatElapsedSince, normalizeAllergyArchive, normalizeAllergyReports, readAllergyItems } from './allergyProfile.ts'

test('旧过敏记录兼容迁移且绑定当前人物',()=>{const archive=normalizeAllergyArchive([{name:'猫毛',type:'环境',certainty:'怀疑中'}],'child-1','account-1');assert.equal(archive.version,2);assert.deepEqual({name:archive.items[0].name,category:archive.items[0].category,status:archive.items[0].currentStatus,memberId:archive.items[0].memberId},{name:'猫毛',category:'environment',status:'suspected',memberId:'child-1'})})
test('同分类同名去重但允许不同分类同名',()=>{const first=createAllergyItem('m1','food','自定义项');const next=appendUniqueAllergyItems([first],[createAllergyItem('m1','food','自定义项'),createAllergyItem('m1','contact','自定义项')]);assert.equal(next.length,2)})
test('六类常见选项独立且检查结果不改变状态',()=>{assert.equal(Object.keys(allergyOptions).length,6);assert.deepEqual(allergyOptions.food.slice(0,2),['牛奶','鸡蛋']);assert.deepEqual(allergyOptions.drug.slice(0,2),['青霉素类','头孢类']);const item=createAllergyItem('m1','food','牛奶');item.tests.push({id:'t',allergyItemId:item.id,memberId:'m1',testType:'血清特异性 IgE',result:'negative',value:'',unit:'',testedAt:'2026-09-01',institution:'',reportFiles:[],clinicianInterpretation:'',notes:''});assert.equal(item.currentStatus,'')})
test('日期持续时间和时间关联文案不声称因果',()=>{assert.equal(formatElapsedSince('2026-09-01',new Date('2026-09-11T00:00:00Z')),'10天');const statement=buildTemporalStatement('牛奶','饮用牛奶','皮肤发红','30分钟');assert.equal(statement,'饮用牛奶后约30分钟记录到皮肤发红');assert.doesNotMatch(statement,/导致/)})
test('无效报告被忽略且有效报告保留人工整理状态',()=>{const reports=normalizeAllergyReports([{id:'r1',name:'报告.pdf',dataUrl:'data:application/pdf;base64,AA',parsingStatus:'已识别'},{}]);assert.equal(reports.length,1);assert.equal(reports[0].parsingStatus,'待人工整理')})
test('读取过敏史只返回当前人物的数据',()=>{const current=createAllergyItem('member-current','food','牛奶','account-1');const other=createAllergyItem('member-other','drug','青霉素类','account-1');const items=readAllergyItems(JSON.stringify({version:2,items:[current,other]}),'member-current','account-1');assert.deepEqual(items.map(item=>item.memberId),['member-current']);assert.deepEqual(items.map(item=>item.name),['牛奶'])})
