import { FormEvent, useState } from 'react'
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { Button, WebPageHeader } from '../../components/common'
import { submitFeedback } from '../../services/feedback'
import { useAppStore } from '../../store/useAppStore'

export function FeedbackPage(){
  const token=useAppStore((state)=>state.authToken);const navigate=useNavigate();const [params]=useSearchParams()
  const [category,setCategory]=useState(params.get('category')??'故障排查');const [description,setDescription]=useState('');const [page,setPage]=useState(params.get('page')??'');const [device,setDevice]=useState<'手机'|'电脑'>('手机');const [contact,setContact]=useState('');const [includeDiagnostics,setIncludeDiagnostics]=useState(false);const [error,setError]=useState('');const [submitting,setSubmitting]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault();if(description.trim().length<10){setError('请至少用 10 个字符描述问题');return}if(!token){setError('登录状态已失效，请重新登录');return}setSubmitting(true);setError('');try{const result=await submitFeedback(token,{category,description:description.trim(),page:page.trim(),device,contact:contact.trim(),includeDiagnostics});navigate('/feedback/submitted',{state:{id:result.id,createdAt:result.createdAt}})}catch(cause){setError(cause instanceof Error?cause.message:'提交失败，请稍后重试')}finally{setSubmitting(false)}}
  return <main className="app-shell pb-0"><WebPageHeader title="反馈产品问题" fallback="/help"/><form className="space-y-4 px-4 py-4" onSubmit={submit}><p className="text-sm leading-6 text-text-secondary">请勿填写验证码、密码或完整健康详情。截图上传将在后续版本提供。</p><label className="hoho-field"><span className="hoho-text-label">问题分类</span><select className="hoho-input" value={category} onChange={(e)=>setCategory(e.target.value)}>{['账号与登录','家庭成员','健康事件','记录与时间线','健康档案','图片与附件','数据与隐私','故障排查'].map((item)=><option key={item}>{item}</option>)}</select></label><label className="hoho-field"><span className="hoho-text-label">问题描述</span><textarea className="hoho-textarea min-h-36" maxLength={2000} value={description} onChange={(e)=>setDescription(e.target.value)} placeholder="说明发生了什么、你期望看到什么结果"/></label><label className="hoho-field"><span className="hoho-text-label">出现问题的页面（选填）</span><input className="hoho-input" maxLength={100} value={page} onChange={(e)=>setPage(e.target.value)}/></label><fieldset><legend className="hoho-text-label mb-2">使用设备</legend><div className="flex gap-2">{(['手机','电脑'] as const).map((item)=><button className="min-h-11 rounded-control border bg-surface px-4 text-sm" aria-pressed={device===item} type="button" key={item} onClick={()=>setDevice(item)}>{item}</button>)}</div></fieldset><label className="hoho-field"><span className="hoho-text-label">联系方式（选填）</span><input className="hoho-input" maxLength={120} value={contact} onChange={(e)=>setContact(e.target.value)} placeholder="便于需要时联系你"/></label><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={includeDiagnostics} onChange={(e)=>setIncludeDiagnostics(e.target.checked)}/><span>允许附带非敏感设备和应用版本信息</span></label><div className="min-h-5" aria-live="polite">{error&&<p className="text-xs text-danger" role="alert">{error}</p>}</div><Button fullWidth type="submit" disabled={submitting}>{submitting?'提交中…':'提交反馈'}</Button></form></main>
}

export function FeedbackSubmittedPage(){const location=useLocation();const data=location.state as {id?:string;createdAt?:string}|null;return <main className="app-shell pb-0"><WebPageHeader title="反馈产品问题" fallback="/help"/><div className="space-y-4 px-4 py-5"><h2 className="text-lg font-semibold">反馈已收到</h2>{data?.id?<><p className="text-sm leading-6 text-text-secondary">反馈已真实保存，我们会根据问题影响安排处理。</p><p className="text-xs text-text-secondary">反馈编号：{data.id}</p></>:<p className="text-sm leading-6 text-text-secondary">无法确认本次反馈已经保存，请返回反馈页面重新提交。</p>}<Button fullWidth type="button" onClick={()=>history.back()}>返回</Button></div></main>}
