import {test,expect,type Page,type Locator} from '@playwright/test'
import {TokenService} from '../../server/auth/token-service.mjs'
const token=new TokenService('visit-sheet-e2e-secret',3600000).create({id:'visit-test'})
const headers={Authorization:`Bearer ${token}`},raw='吃了半碗粥，脸颊有点红，没有呕吐，午睡睡了一个小时'
const items=[['diet',[['food','粥'],['amount','半碗']]],['symptom',[['symptom','脸颊有点红，没有呕吐'],['location','脸颊']]],['sleep',[['quality','午睡睡了一个小时']]]].map(([category,fields])=>({category,title:category,timeText:null,archiveCategory:null,subject:'current',relationKey:null,fields:(fields as string[][]).map(([name,value])=>({name,value,quote:value,sourceId:'input',page:1}))}))
test.beforeEach(async({page,request})=>{
 await request.get('http://127.0.0.1:4198/success');await request.post('http://127.0.0.1:4198/draft-data',{data:{items}})
 await page.addInitScript(()=>{Object.defineProperty(window,'__spoken',{value:[],writable:true});Object.defineProperty(window,'SpeechSynthesisUtterance',{value:class{ text:string; constructor(text:string){this.text=text} }});Object.defineProperty(window,'speechSynthesis',{value:{cancel(){},getVoices(){return [{lang:'zh-CN',name:'Tingting'}]},speak(value:any){if(value.text.trim())(window as any).__spoken.push(value.text);value.onstart?.();setTimeout(()=>value.onend?.(),10)}}})});
 await page.addInitScript(token=>{sessionStorage.setItem('hoooho-auth-token',token);localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'visit-test'},currentMemberId:'empty-child',members:[],profile:null},version:5}))},token)
})
async function compact(page:Page,root:Locator){
 const row=root.locator('.hoho-dialogue-composer');await expect(row.getByRole('button',{name:'按住说话',exact:true})).toBeEnabled()
 for(const width of [320,390,430]){await page.setViewportSize({width,height:844});const sizes=await row.evaluate(e=>{const r=e.getBoundingClientRect();return {height:r.height,right:r.right,width:innerWidth}});expect(sizes.height).toBe(44);expect(sizes.right).toBeLessThanOrEqual(sizes.width);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await expect(row.getByRole('button',{name:'改用文字',exact:true})).toHaveText('');await expect(row.getByRole('button',{name:'拍照',exact:true})).toHaveText('');
 await expect(root.getByText('原话（可修改）',{exact:true})).toHaveCount(0);await expect(root.getByText('原件、时间与记录归属（选填）',{exact:true})).toHaveCount(0)
}
test('record composer is one row; unsent text and edited review survive close; saves three factual records',async({page,request})=>{
 await page.goto('/nurse-station');await page.getByRole('button',{name:'和护士说说',exact:true}).click();const panel=page.getByRole('dialog',{name:'智能记录',exact:true});await compact(page,panel)
 await panel.getByRole('button',{name:'改用文字',exact:true}).click();await panel.getByLabel('对话输入').fill(raw);await panel.getByRole('button',{name:'收起'}).click();await page.getByRole('button',{name:'和护士说说',exact:true}).click();await panel.getByRole('button',{name:'继续上次记录',exact:true}).click();await panel.getByRole('button',{name:'改用文字',exact:true}).click();await expect(panel.getByLabel('对话输入')).toHaveValue(raw)
 await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await panel.locator('.dialogue-review-item').first().getByText('编辑这条记录',{exact:true}).click();await panel.getByLabel('数量',{exact:true}).fill('小半碗');await page.reload();await page.getByRole('button',{name:'和护士说说',exact:true}).click();await panel.getByRole('button',{name:'继续上次记录',exact:true}).click();await panel.locator('.dialogue-review-item').first().getByText('编辑这条记录',{exact:true}).click();await expect(panel.getByLabel('数量',{exact:true})).toHaveValue('小半碗');await panel.getByRole('button',{name:'返回对话继续补充',exact:true}).click();await expect(panel.locator('.nurse-turn--user')).toContainText(raw);await panel.getByRole('button',{name:'核对 3 条记录',exact:true}).click();for(const row of await panel.locator('.dialogue-review-item').all())await row.getByText('编辑这条记录',{exact:true}).click()
 await page.screenshot({path:'test-results/dialogue/record-review.png'});for(const choice of await panel.getByRole('button',{name:'就是刚才',exact:true}).all())await choice.click();const save=panel.getByRole('button',{name:'确认保存 3 条',exact:true});await expect(save).toBeEnabled();const response=page.waitForResponse(r=>r.url().endsWith('/save')&&r.request().method()==='POST');await save.click();const result=await(await response).json();expect(result.result.records).toHaveLength(3);await expect(panel.getByText('已经记好了。',{exact:false})).toBeVisible()
})
test('press and release transcribes through Qwen; ASR failure keeps recording for retry after reload',async({page,request})=>{
 await request.get(`http://127.0.0.1:4198/voice?text=${encodeURIComponent(raw)}`);await page.goto('/smart-record');const panel=page.getByRole('dialog',{name:'智能记录',exact:true});const hold=panel.getByRole('button',{name:'按住说话',exact:true});await expect(hold).toBeEnabled();await hold.focus();await page.keyboard.down('Space');await expect(panel.getByRole('button',{name:'正在录音，松手发送'})).toBeVisible();await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await panel.getByRole('button',{name:'返回对话继续补充',exact:true}).click();await expect(panel.locator('.nurse-turn--user')).toContainText(raw)
 // A second release is a new bubble; the recording cue floats above the finger.
 const touch=await hold.boundingBox();await page.mouse.move(touch!.x+touch!.width/2,touch!.y+touch!.height/2);await page.mouse.down();const arc=page.locator('.hoho-dialogue-recording');await expect(arc).toBeVisible();await expect(arc).toContainText('正在录音');const cue=await arc.boundingBox(),button=await panel.locator('.hoho-dialogue-hold').boundingBox();expect(cue!.y+cue!.height).toBeLessThan(button!.y);await page.screenshot({path:'test-results/dialogue/recording-arc.png'});await page.waitForTimeout(900);await page.mouse.up();await expect(arc).toHaveCount(0);await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await panel.getByRole('button',{name:'返回对话继续补充',exact:true}).click();await expect(panel.locator('.nurse-turn--user')).toHaveCount(2);await expect(hold).toBeEnabled()
 await page.route('**/api/ai/audio/transcriptions',route=>route.fulfill({status:503,json:{error:{code:'ASR_TIMEOUT'}}}));await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toBeEnabled();await page.reload();await panel.getByRole('button',{name:'返回对话继续补充',exact:true}).click();await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toBeEnabled();await page.unroute('**/api/ai/audio/transcriptions');await panel.getByRole('button',{name:'再试一次',exact:true}).click();await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toHaveCount(0)
})
test('symptom nurse keeps dialogue and explicit organization inside bubbles',async({page})=>{
 await page.goto('/smart-record?taskId=dialogue-fixture');const form=page.getByRole('dialog',{name:'症状记录',exact:true});await form.getByRole('button',{name:/^智能记录/}).click();const panel=page.getByRole('dialog',{name:'智能记录',exact:true});await compact(page,panel);await panel.getByRole('button',{name:'改用文字',exact:true}).click();await panel.getByLabel('对话输入').fill('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。');await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>(window as any).__spoken)).toContain('有没有影响睡眠？');await expect(panel).toBeVisible();const organize=panel.getByRole('button',{name:'帮我整理',exact:true});await expect(organize.locator('xpath=ancestor::*[contains(@class,"nurse-turn-content")]')).toHaveCount(1);await page.screenshot({path:'test-results/dialogue/symptom-nurse.png'});await organize.click();await expect(panel).toHaveCount(0);await expect(form.getByLabel('哪里不舒服')).toHaveValue('脸颊发红发痒，没有发热')
})
test('product help uses compact input and in-bubble actions; retries preserve identity and direct feedback stays available',async({page})=>{
 await page.goto('/help?view=chat');await compact(page,page.locator('.help-chat'));await page.getByRole('button',{name:'改用文字',exact:true}).click();const input=page.getByLabel('对话输入');await input.fill('录音后转写失败');const requests:string[]=[];await page.route('**/api/help/sessions/*/turns',async route=>{requests.push(route.request().postDataJSON().requestId);if(requests.length===1)await route.fulfill({status:503,json:{error:{message:'合成网络中断'}}});else await route.continue()});await page.getByRole('button',{name:'发送',exact:true}).click();await expect(input).toHaveValue('录音后转写失败');await page.getByRole('button',{name:'再试一次',exact:true}).click();await expect(page.getByRole('button',{name:'解决了',exact:true})).toBeVisible();expect(requests[1]).toBe(requests[0]);await page.screenshot({path:'test-results/dialogue/help.png'})
 await page.goto('/feedback');await expect(page.locator('.feedback-form')).toBeVisible();await expect(page.locator('.feedback-interview')).toHaveCount(0);await expect(page.getByRole('button',{name:'确认提交反馈',exact:true})).toBeVisible()
})

test('photo icon opens distinct camera and album pickers; stored images recover without native FileReader data URL',async({page,request})=>{
 await page.addInitScript(()=>{FileReader.prototype.readAsDataURL=function(){throw new DOMException('Native file reference expired','NotReadableError')}})
 await page.goto('/smart-record');const panel=page.getByRole('dialog',{name:'智能记录',exact:true});const icon=panel.getByRole('button',{name:'拍照',exact:true});await icon.click()
 let chooser=page.waitForEvent('filechooser');await page.getByRole('menuitem',{name:'拍照',exact:true}).click();const camera=await chooser;expect(await camera.element().getAttribute('capture')).toBe('environment')
 await icon.click();chooser=page.waitForEvent('filechooser');await page.getByRole('menuitem',{name:'从相册选择',exact:true}).click();const album=await chooser;expect(await album.element().getAttribute('capture')).toBeNull();expect(album.isMultiple()).toBe(true)
 await album.setFiles({name:'测试照片.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aVf8AAAAASUVORK5CYII=','base64')});await expect(panel.locator('.dialogue-file')).toContainText('测试照片.png')
 await expect.poll(()=>page.evaluate(()=>new Promise<boolean>((resolve,reject)=>{const r=indexedDB.open('hoooho-smart-record-drafts',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('drafts'),q=t.objectStore('drafts').get('smart:visit-test:empty-child:new');q.onsuccess=()=>resolve(q.result?.files[0]?.kind==='bytes-v1');q.onerror=()=>reject(q.error);t.oncomplete=()=>db.close()}}))).toBe(true)
 await page.reload();await expect(panel.locator('.dialogue-file')).toContainText('测试照片.png');await panel.getByRole('button',{name:'改用文字',exact:true}).click();await panel.getByLabel('对话输入').fill(raw);await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await expect(panel.getByText('原件读取失败，请重试',{exact:true})).toHaveCount(0)
})

test('expired voice and record requests restore login once, keep raw bytes and do not append duplicate bubbles',async({page,request})=>{
 await request.get(`http://127.0.0.1:4198/voice?text=${encodeURIComponent(raw)}`);await page.goto('/smart-record');const panel=page.getByRole('dialog',{name:'智能记录',exact:true});const hold=panel.getByRole('button',{name:'按住说话',exact:true});await expect(hold).toBeEnabled()
 let recovered=0,asr=0,drafts=0;const audioBodies:string[]=[];page.on('request',r=>{if(r.url().endsWith('/api/auth/session'))recovered++})
 await page.route('**/api/ai/audio/transcriptions',route=>{audioBodies.push(route.request().postData()!);return ++asr===1?route.fulfill({status:401,json:{error:{code:'UNAUTHORIZED'}}}):route.continue()})
 await page.route('**/ai-drafts',route=>++drafts===1?route.fulfill({status:401,json:{error:{code:'UNAUTHORIZED'}}}):route.continue())
 await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await panel.getByRole('button',{name:'返回对话继续补充',exact:true}).click();await expect(panel.locator('.nurse-turn--user')).toHaveCount(1);expect(asr).toBe(2);expect(audioBodies[1]).toBe(audioBodies[0]);expect(recovered).toBe(2);await expect(panel.getByText('登录已过期，请重新登录后使用语音',{exact:true})).toHaveCount(0)
})

test('unreadable old recording has a working recovery action and does not erase earlier text',async({page})=>{
 await page.goto('/smart-record');const panel=page.getByRole('dialog',{name:'智能记录',exact:true});await expect(panel.getByRole('button',{name:'按住说话',exact:true})).toBeEnabled()
 await page.evaluate(()=>new Promise<void>((resolve,reject)=>{const r=indexedDB.open('hoooho-smart-record-drafts',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('drafts','readwrite'),file=new File(['not audio'],'旧录音.webm',{type:'audio/webm'});t.objectStore('drafts').put({text:'先前的文字记录',files:[file],pendingVoice:file,occurredAt:'2026-01-01T10:00',timeUnknown:false,requestId:'old-voice'},'smart:visit-test:empty-child:new');t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>reject(t.error)}}));await page.reload();await panel.getByRole('button',{name:'再试一次',exact:true}).click();await panel.getByRole('button',{name:'移除无法读取的录音',exact:true}).click();await expect(panel.getByRole('button',{name:'按住说话',exact:true})).toBeEnabled();await expect(panel.locator('.nurse-turn--user')).toContainText('先前的文字记录');await page.reload();await expect(panel.locator('.nurse-turn--user')).toContainText('先前的文字记录');await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toHaveCount(0)
})


test('help voice delivery failure survives reload and retries the saved transcript without another ASR request',async({page,request})=>{
 await request.get(`http://127.0.0.1:4198/voice?text=${encodeURIComponent('录音后转写失败')}`);await page.goto('/help?view=chat');const root=page.locator('.help-chat'),hold=root.getByRole('button',{name:'按住说话',exact:true});await expect(hold).toBeEnabled()
 await root.getByRole('button',{name:'新对话',exact:true}).click();await expect(root.locator('.nurse-turn--user')).toHaveCount(0);await expect(hold).toBeEnabled();
 let asr=0;const ids:string[]=[];page.on('request',r=>{if(r.url().endsWith('/api/ai/audio/transcriptions'))asr++});await page.route('**/api/help/sessions/*/turns',async route=>{ids.push(route.request().postDataJSON().requestId);if(ids.length===1)await route.fulfill({status:503,json:{error:{message:'合成网络中断'}}});else await route.continue()})
 await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(root.getByRole('button',{name:'再试一次',exact:true})).toBeEnabled();await page.reload();await root.getByRole('button',{name:'再试一次',exact:true}).click();await expect.poll(()=>ids.length).toBe(2);await expect(root.getByRole('button',{name:'解决了',exact:true})).toBeEnabled();await expect(hold).toBeEnabled();expect(asr).toBe(1);expect(ids[1]).toBe(ids[0]);await expect(root.locator('.nurse-turn--user')).toHaveCount(1)
})
