import {test,expect,type Page,type Locator} from '@playwright/test'
import {TokenService} from '../../server/auth/token-service.mjs'
const token=new TokenService('visit-sheet-e2e-secret',3600000).create({id:'visit-test'})
const headers={Authorization:`Bearer ${token}`},raw='吃了半碗粥，脸颊有点红，没有呕吐，午睡睡了一个小时'
const items=[['diet',[['food','粥'],['amount','半碗']]],['symptom',[['symptom','脸颊有点红，没有呕吐'],['location','脸颊']]],['sleep',[['quality','午睡睡了一个小时']]]].map(([category,fields])=>({category,title:category,timeText:null,archiveCategory:null,subject:'current',relationKey:null,fields:(fields as string[][]).map(([name,value])=>({name,value,quote:value,sourceId:'input',page:1}))}))
test.beforeEach(async({page,request})=>{
 await request.get('http://127.0.0.1:4198/success');await request.post('http://127.0.0.1:4198/draft-data',{data:{items}})
 await page.addInitScript(token=>{sessionStorage.setItem('hoooho-auth-token',token);localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'visit-test'},currentMemberId:'empty-child',members:[],profile:null},version:5}))},token)
})
async function compact(page:Page,root:Locator){
 const row=root.locator('.hoho-dialogue-composer');await expect(row.getByRole('button',{name:'按住说话',exact:true})).toBeEnabled()
 for(const width of [320,390,430]){await page.setViewportSize({width,height:844});const sizes=await row.evaluate(e=>{const r=e.getBoundingClientRect();return {height:r.height,right:r.right,width:innerWidth}});expect(sizes.height).toBe(44);expect(sizes.right).toBeLessThanOrEqual(sizes.width);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)}
 await expect(root.getByText('原话（可修改）',{exact:true})).toHaveCount(0);await expect(root.getByText('原件、时间与记录归属（选填）',{exact:true})).toHaveCount(0)
}
test('record composer is one row; unsent text and edited review survive close; saves three factual records',async({page,request})=>{
 await page.goto('/nurse-station');await page.getByRole('button',{name:'和护士说说',exact:true}).click();const panel=page.getByRole('dialog',{name:'智能记录',exact:true});await compact(page,panel)
 await panel.getByRole('button',{name:'改用文字',exact:true}).click();await panel.getByLabel('对话输入').fill(raw);await panel.getByRole('button',{name:'收起'}).click();await page.getByRole('button',{name:'和护士说说',exact:true}).click();await panel.getByRole('button',{name:'改用文字',exact:true}).click();await expect(panel.getByLabel('对话输入')).toHaveValue(raw)
 await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await panel.getByLabel('数量',{exact:true}).fill('小半碗');await page.reload();await page.getByRole('button',{name:'和护士说说',exact:true}).click();await expect(panel.getByLabel('数量',{exact:true})).toHaveValue('小半碗');await expect(panel.locator('.nurse-turn--user')).toContainText(raw)
 await page.screenshot({path:'test-results/dialogue/record-review.png'});for(const choice of await panel.getByRole('button',{name:'就是刚才',exact:true}).all())await choice.click();const save=panel.getByRole('button',{name:'确认保存',exact:true});await expect(save).toBeEnabled();const response=page.waitForResponse(r=>r.url().endsWith('/save')&&r.request().method()==='POST');await save.click();const result=await(await response).json();expect(result.result.records).toHaveLength(3);await expect(panel.getByText('已经记好了。',{exact:false})).toBeVisible()
})
test('press and release transcribes through Qwen; ASR failure keeps recording for retry after reload',async({page,request})=>{
 await request.get(`http://127.0.0.1:4198/voice?text=${encodeURIComponent(raw)}`);await page.goto('/smart-record');const panel=page.getByRole('dialog',{name:'智能记录',exact:true});const hold=panel.getByRole('button',{name:'按住说话',exact:true});await expect(hold).toBeEnabled();await hold.focus();await page.keyboard.down('Space');await expect(panel.getByRole('button',{name:'正在录音，松手发送'})).toBeVisible();await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(panel.locator('.dialogue-review-item')).toHaveCount(3);await expect(panel.locator('.nurse-turn--user')).toContainText(raw)
 await page.route('**/api/ai/audio/transcriptions',route=>route.fulfill({status:503,json:{error:{code:'ASR_TIMEOUT'}}}));await hold.focus();await page.keyboard.down('Space');await page.waitForTimeout(900);await page.keyboard.up('Space');await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toBeEnabled();await page.reload();await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toBeEnabled();await page.unroute('**/api/ai/audio/transcriptions');await panel.getByRole('button',{name:'再试一次',exact:true}).click();await expect(panel.getByRole('button',{name:'再试一次',exact:true})).toHaveCount(0)
})
test('symptom nurse keeps dialogue and explicit organization inside bubbles',async({page})=>{
 await page.goto('/smart-record?taskId=dialogue-fixture');const form=page.getByRole('dialog',{name:'症状记录',exact:true});await form.getByRole('button',{name:/^智能记录/}).click();const panel=page.getByRole('dialog',{name:'智能记录',exact:true});await compact(page,panel);await panel.getByRole('button',{name:'改用文字',exact:true}).click();await panel.getByLabel('对话输入').fill('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。');await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible();await expect(panel).toBeVisible();const organize=panel.getByRole('button',{name:'帮我整理',exact:true});await expect(organize.locator('xpath=ancestor::*[contains(@class,"nurse-turn-content")]')).toHaveCount(1);await page.screenshot({path:'test-results/dialogue/symptom-nurse.png'});await organize.click();await expect(panel).toHaveCount(0);await expect(form.getByLabel('哪里不舒服')).toHaveValue('脸颊发红发痒，没有发热')
})
test('product help and feedback use compact input and in-bubble actions; retries preserve request identity',async({page})=>{
 await page.goto('/help?view=chat');await compact(page,page.locator('.help-chat'));await page.getByRole('button',{name:'改用文字',exact:true}).click();const input=page.getByLabel('对话输入');await input.fill('录音后转写失败');const requests:string[]=[];await page.route('**/api/help/sessions/*/turns',async route=>{requests.push(route.request().postDataJSON().requestId);if(requests.length===1)await route.fulfill({status:503,json:{error:{message:'合成网络中断'}}});else await route.continue()});await page.getByRole('button',{name:'发送',exact:true}).click();await expect(input).toHaveValue('录音后转写失败');await page.getByRole('button',{name:'再试一次',exact:true}).click();await expect(page.getByRole('button',{name:'解决了',exact:true})).toBeVisible();expect(requests[1]).toBe(requests[0]);await page.screenshot({path:'test-results/dialogue/help.png'})
 await page.goto('/feedback');await compact(page,page.locator('.feedback-interview'));await page.getByRole('button',{name:'改用文字',exact:true}).click();await page.getByLabel('对话输入').fill('按钮太小，点不到');await page.route('**/api/feedback/interview',route=>route.fulfill({json:{reply:'哪个按钮比较难点？',problemType:'usability_issue',description:'问题或改进建议：按钮太小，点不到',fields:{page:'',actual:'按钮太小，点不到',expected:'',impact:'',reproduction:''}}}));await page.getByRole('button',{name:'发送',exact:true}).click();await expect(page.getByText('哪个按钮比较难点？')).toBeVisible();await page.getByRole('button',{name:'帮我整理',exact:true}).click();await expect(page.getByLabel('反馈意见',{exact:true})).toHaveValue('问题或改进建议：按钮太小，点不到');await expect(page.getByRole('button',{name:'确认并提交'})).toBeVisible()
})
