import { test, expect, type Page, type Locator } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'
const accountId = 'time-view-test-account'
const token = new TokenService('time-view-e2e-local-only-secret', 3600_000).create({ id: accountId })
const headers = { Authorization: `Bearer ${token}`, 'X-Hoooho-Timezone': 'Asia/Shanghai' }
async function prepare(page: Page, name: string, width = 375) {
  await page.setViewportSize({ width, height: 667 })
  page.on('pageerror', error => { throw error })
  const result = await page.request.post('/api/members', { headers, data: { name, birthday: '2025-01-01', gender: 'female', relationship: 'child' } })
  expect(result.ok()).toBe(true)
  const memberId = (await result.json()).id
  await page.addInitScript(({ token, accountId, memberId }) => {
    sessionStorage.setItem('hoooho-auth-token', token)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: accountId }, currentMemberId: memberId, members: [], profile: null }, version: 5 }))
  }, { token, accountId, memberId })
  await page.goto('/health-events')
  await expect(page.getByRole('button', { name: '记录日常', exact: true })).toBeEnabled()
  return memberId
}
async function day(page: Page, date: string) { await page.getByLabel('选择日期', { exact: true }).fill(date) }
async function shot(page: Page, name: string) {
  await mkdir('outputs/journal-single-occurrence', { recursive: true })
  await page.screenshot({ path: `outputs/journal-single-occurrence/${name}.png` })
}
async function create(page: Page, form: Locator, button = '保存记录') {
  const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/quick-records' && r.request().method() === 'POST')
  await form.getByRole('button', { name: button, exact: true }).click()
  const saved = await response
  expect(saved.status()).toBe(201)
  const ids = await saved.json()
  await expect(form).toHaveCount(0)
  return ids
}
async function records(page: Page, eventId: string) {
  const response = await page.request.get(`/api/events/${eventId}/records?view=time`, { headers })
  expect(response.ok()).toBe(true)
  return response.json()
}
for (const width of [375, 390, 430]) {
  test(`saved legacy routine windows load without crashing before or during setup at ${width}`, async ({ page }) => {
    const memberId = await prepare(page, '旧作息兼容验收', width)
    const items = {
      nightSleep: { enabled: true, time: '21:00', endTime: '07:00' },
      breakfast: { enabled: true, time: '07:30', endTime: '08:00' },
      napSleep: { enabled: true, time: '13:00', endTime: '15:00' },
      lunch: { enabled: true, time: '12:00', endTime: '12:30' },
      dinner: { enabled: true, time: '18:00', endTime: '18:30' },
      'custom:legacyEveningMilk': { enabled: true, title: '晚奶', time: '20:30', endTime: '21:00' }
    }
    const saved = await page.request.patch(`/api/routines/${memberId}`, { headers, data: { effectiveFrom: '2026-09-01', enabled: true, items } })
    expect(saved.ok()).toBe(true)
    let release!: () => void
    const responseGate = new Promise<void>(resolve => { release = resolve })
    await page.route(`**/api/routines/${memberId}?**`, async route => { await responseGate; await route.continue() })
    await page.reload()
    await page.getByRole('button', { name: '调整作息', exact: true }).click()
    release()
    await page.locator('.journal-grid-loading').waitFor({ state: 'hidden' })
    const setup = page.getByRole('dialog', { name: '设置日常作息', exact: true })
    await expect(setup.getByRole('switch')).toHaveCount(6)
    await expect(setup.getByLabel('早餐开始时间')).toHaveValue('07:30')
    await expect(setup.getByLabel('午睡通常醒来')).toHaveValue('15:00')
    await expect(setup.getByLabel('晚奶结束时间')).toHaveValue('21:00')
    await setup.getByLabel('早餐结束时间').fill('08:10')
    await setup.getByRole('button', { name: '保存作息', exact: true }).click()
    await expect(setup).toHaveCount(0)
    await page.unroute(`**/api/routines/${memberId}?**`)
    await page.reload()
    await page.locator('.journal-grid-loading').waitFor({ state: 'hidden' })
    await expect(page.getByText('Unexpected Application Error!', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '调整作息', exact: true }).click()
    await expect(setup.getByLabel('早餐结束时间')).toHaveValue('08:10')
    await expect(setup.getByRole('switch')).toHaveCount(6)
    await expect(page.locator('.journal-record')).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await shot(page, `legacy-routine-fixed-${width}`)
  })
  test(`usual windows never create facts, refill and isolate by child at ${width}`, async ({ page }) => {
    const memberId = await prepare(page, '安排验收', width)
    let writes = 0
    page.on('request', r => { if (r.method() === 'POST' && r.url().endsWith('/api/quick-records')) writes++ })
    await page.getByRole('button', { name: '调整作息', exact: true }).click()
    let setup = page.getByRole('dialog', { name: '设置日常作息', exact: true })
    await expect(setup.getByRole('switch')).toHaveCount(1)
    await setup.getByRole('switch', { name: '夜间睡眠作息', exact: true }).click()
    await setup.getByLabel('夜间睡眠通常入睡').fill('21:00')
    await setup.getByLabel('夜间睡眠通常醒来').fill('07:00')
    for (const [label, start, end] of [['早餐', '07:30', '08:00'], ['午睡', '13:00', '15:00'], ['晚奶', '20:30', '21:00']]) {
      await setup.getByRole('button', { name: '添加自定义作息' }).click()
      const custom = page.getByRole('dialog', { name: '添加自定义作息', exact: true })
      await custom.locator('input').fill(label)
      await custom.getByRole('button', { name: '添加', exact: true }).click()
      setup = page.getByRole('dialog', { name: '设置日常作息', exact: true })
      await setup.getByLabel(`${label}开始时间`).fill(start)
      await setup.getByLabel(`${label}结束时间`).fill(end)
    }
    await shot(page, `routine-${width}`)
    await setup.getByRole('button', { name: '保存作息', exact: true }).click()
    await expect(setup).toHaveCount(0)
    await expect(page.locator('.journal-record')).toHaveCount(0)
    await page.reload()
    await day(page, '2026-09-30')
    await expect(page.locator('.journal-record')).toHaveCount(0)
    await page.getByRole('button', { name: '调整作息', exact: true }).click()
    setup = page.getByRole('dialog', { name: '设置日常作息', exact: true })
    await expect(setup.getByLabel('夜间睡眠通常醒来')).toHaveValue('07:00')
    await expect(setup.getByLabel('午睡开始时间')).toHaveValue('13:00')
    await expect(setup.getByLabel('晚奶开始时间')).toHaveValue('20:30')
    expect(writes).toBe(0)
    const own = await (await page.request.get(`/api/routines/${memberId}?day=2026-10-06`, { headers })).json()
    expect(own.template.items).toHaveLength(4)
    const sibling = await (await page.request.get('/api/routines/child-two?day=2026-10-06', { headers })).json()
    expect(sibling.template).toBeNull()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  })
  test(`feeding keeps same ID, retries, crosses midnight and preserves details at ${width}`, async ({ page }) => {
    await prepare(page, '喂养验收', width)
    await day(page, '2026-09-30')
    await page.locator('.journal-record-actions').getByRole('button', { name: '喂养/饮食', exact: true }).click()
    const form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
    await form.getByRole('radio', { name: '配方奶', exact: true }).click()
    await form.getByLabel('本次名称（选填）').fill('晚奶')
    await form.getByLabel('备注（选填）').fill('测试备注保留')
    await form.getByRole('spinbutton', { name: /^喂奶量/ }).fill('180')
    await form.getByRole('textbox', { name: '记录时间', exact: true }).fill('2026-09-30T23:45')
    const ids = await create(page, form, '开始喂养')
    let row = page.locator(`[data-record-id="${ids.recordId}"]`)
    await expect(row).toHaveCount(1)
    await expect(row).toContainText('晚奶 · 持续中')
    await expect(row.locator('.journal-sleep-ongoing-dots span')).toHaveCount(3)
    await shot(page, `feeding-running-${width}`)
    await page.reload(); await day(page, '2026-09-30')
    await expect(row).toContainText('持续中') // Schedule/current time never completes it.
    await row.getByRole('button').click()
    let detail = page.getByRole('dialog', { name: '晚奶记录详情', exact: true })
    await expect(detail).toContainText('2026/9/30 23:45:00')
    await expect(detail.getByLabel('奶量（mL，选填）')).toHaveValue('180')
    await expect(detail.getByLabel('备注（选填）')).toHaveValue('测试备注保留')
    await detail.getByLabel('实际结束时间').fill('2026-10-01T00:15')
    await page.route(`**/api/records/${ids.recordId}`, route => route.request().method() === 'PATCH' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '保存失败，请重试' } }) }) : route.continue())
    await detail.getByRole('button', { name: '结束喂养', exact: true }).click()
    await expect(detail.getByRole('alert')).toContainText('保存失败')
    await expect(detail.getByLabel('实际结束时间')).toHaveValue('2026-10-01T00:15')
    await page.unroute(`**/api/records/${ids.recordId}`)
    const finished = page.waitForResponse(r => r.request().method() === 'PATCH' && r.url().endsWith(`/api/records/${ids.recordId}`))
    await detail.getByRole('button', { name: '结束喂养', exact: true }).click()
    expect((await finished).ok()).toBe(true)
    await expect(detail).toHaveCount(0)
    await expect(page.getByLabel('选择日期', { exact: true })).toHaveValue('2026-10-01')
    await expect(row).toHaveCount(1); await expect(row).toContainText('晚奶 · 共30分钟')
    await expect(row.locator('xpath=../..').locator(':scope > time')).toHaveText('00:15')
    const all = await records(page, ids.eventId)
    expect(all).toHaveLength(1); expect(all[0].id).toBe(ids.recordId)
    expect(all[0].journal.diet.bottleMl).toBe(180); expect(all[0].journal.diet.note).toBe('测试备注保留')
    await expect(row).toBeInViewport()
    await shot(page, `feeding-ended-${width}`)
    await row.getByRole('button').click()
    detail = page.getByRole('dialog', { name: '晚奶记录详情', exact: true })
    await expect(detail).toContainText('2026/9/30 23:45:00'); await expect(detail).toContainText('2026/10/1 00:15:00')
    await expect(detail).toContainText('0小时30分钟'); await expect(detail).toContainText('180'); await expect(detail).toContainText('测试备注保留')
    await shot(page, `feeding-detail-${width}`)
    await detail.getByRole('button', { name: '关闭晚奶记录详情', exact: true }).click()
    await day(page, '2026-09-30'); await expect(page.locator('.journal-record')).toHaveCount(0)
  })
}
test('manual running sleep explicitly finishes once at end date and completed sleep is one row', async ({ page }) => {
  await prepare(page, '睡眠验收')
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await page.getByRole('group', { name: '记录日常选项' }).getByRole('button', { name: '睡眠', exact: true }).click()
  const form = page.getByRole('dialog', { name: '记录睡眠', exact: true })
  await form.getByRole('radio', { name: '正在睡眠', exact: true }).click()
  await form.locator('.sleep-editor-card').first().click()
  await form.getByLabel('入睡日期').fill('2026-09-30'); await form.getByLabel('入睡时间', { exact: true }).fill('21:10')
  await form.locator('.sleep-editor-card').nth(1).click()
  await form.getByLabel('醒来日期').fill('2026-10-01'); await form.getByLabel('醒来时间', { exact: true }).fill('06:10')
  const ids = await create(page, form)
  let row = page.locator(`[data-record-id="${ids.recordId}"]`)
  await expect(row).toHaveCount(1); await expect(row).toContainText('睡眠 · 持续中')
  await page.reload(); await day(page, '2026-09-30'); await expect(row).toContainText('持续中')
  await row.getByRole('button').click()
  const active = page.getByRole('dialog', { name: '睡眠时间未补全', exact: true })
  await active.getByRole('button', { name: '核对时间', exact: true }).click()
  await active.getByLabel('实际结束时间').fill('2026-10-01T06:10')
  const ended = page.waitForResponse(r => r.url().endsWith(`/api/records/${ids.recordId}/sleep/end`))
  await active.getByRole('button', { name: '确认并结束睡眠', exact: true }).click()
  expect((await ended).ok()).toBe(true)
  await expect(row).toHaveCount(1); await expect(row).toContainText('睡眠 · 已醒 · 约9小时')
  await expect(row.locator('xpath=../..').locator(':scope > time')).toHaveText('06:10')
  expect(await records(page, ids.eventId)).toHaveLength(1)
  const retry = await page.request.post(`/api/records/${ids.recordId}/sleep/end`, { headers, data: { wakeAt: '2026-10-01T06:10:00+08:00' } })
  expect(retry.ok()).toBe(true); expect(await records(page, ids.eventId)).toHaveLength(1)
  await expect(row).toBeInViewport()
  await shot(page, 'sleep-ended-375')
  await row.getByRole('button').click()
  const detail = page.getByRole('dialog', { name: '睡眠记录详情', exact: true })
  await expect(detail).toContainText('2026/9/30 21:10:00'); await expect(detail).toContainText('2026/10/1 06:10:00')
  await expect(detail).toContainText('9小时0分钟')
  await shot(page, 'sleep-detail-375')
  await detail.getByRole('button', { name: '关闭睡眠记录详情', exact: true }).click()
  await day(page, '2026-09-30'); await expect(page.locator('.journal-record')).toHaveCount(0)
})
test('meal start/finish retains foods and unchanged exact endpoint seconds during editing', async ({ page }) => {
  await prepare(page, '用餐验收')
  await day(page, '2026-09-30')
  await page.locator('.journal-record-actions').getByRole('button', { name: '喂养/饮食', exact: true }).click()
  const form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
  await form.getByRole('radio', { name: '食物饮食', exact: true }).click()
  await form.getByRole('radio', { name: '正餐', exact: true }).click()
  await form.getByLabel('本次名称（选填）').fill('晚餐')
  await form.getByRole('button', { name: '米饭', exact: true }).click()
  await form.getByRole('textbox', { name: '记录时间', exact: true }).fill('2026-09-30T18:30')
  const ids = await create(page, form, '开始用餐')
  const row = page.locator(`[data-record-id="${ids.recordId}"]`)
  await expect(row).toContainText('晚餐 · 持续中')
  await row.getByRole('button').click()
  const active = page.getByRole('dialog', { name: '晚餐记录详情', exact: true })
  await expect(active).toContainText('米饭')
  await active.getByLabel('实际结束时间').fill('2026-09-30T19:00')
  await active.getByRole('button', { name: '结束用餐', exact: true }).click()
  await expect(active).toHaveCount(0); await expect(row).toContainText('晚餐 · 共30分钟')
  const [record] = await records(page, ids.eventId)
  expect(record.journal.diet.foods).toEqual(['米饭'])
  const precise = { ...record.journal, diet: { ...record.journal.diet, startedAt: '2026-09-30T18:30:17+08:00', endedAt: '2026-09-30T19:00:33+08:00' } }
  expect((await page.request.patch(`/api/records/${ids.recordId}`, { headers, data: { journal: precise } })).ok()).toBe(true)
  await page.reload(); await day(page, '2026-09-30'); await row.getByRole('button').click()
  const detail = page.getByRole('dialog', { name: '晚餐记录详情', exact: true })
  await expect(detail).toContainText('0小时30分钟16秒')
  await detail.getByRole('button', { name: '修改起止时间', exact: true }).click()
  await detail.getByLabel('晚餐结束时间').fill('2026-09-30T19:05')
  await detail.getByRole('button', { name: '保存时间', exact: true }).click(); await expect(detail).toHaveCount(0)
  const [edited] = await records(page, ids.eventId)
  expect(Date.parse(edited.journal.diet.startedAt)).toBe(Date.parse('2026-09-30T18:30:17+08:00'))
  expect(edited.id).toBe(ids.recordId)
})

test('no-duration milk and name-only stay compact, cancel creates no record', async ({ page }) => {
  const memberId = await prepare(page, '无时长验收')
  for (const milk of ['180', '']) {
    await page.locator('.journal-record-actions').getByRole('button', { name: '喂养/饮食', exact: true }).click()
    const form = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
    await form.getByRole('radio', { name: '配方奶', exact: true }).click()
    await form.getByLabel('本次名称（选填）').fill('晚奶')
    if (milk) await form.getByRole('spinbutton', { name: /^喂奶量/ }).fill(milk)
    await form.getByRole('textbox', { name: '记录时间', exact: true }).fill(`2026-09-30T${milk ? '20:30' : '21:30'}`)
    const ids = await create(page, form)
    await expect(page.locator(`[data-record-id="${ids.recordId}"] .journal-record-summary`)).toHaveText(milk ? '晚奶 · 180mL' : '晚奶')
    const [record] = await records(page, ids.eventId)
    expect(record.journal.diet.startedAt).toBeUndefined(); expect(record.journal.diet.endedAt).toBeUndefined()
  }
  await page.locator('.journal-record-actions').getByRole('button', { name: '喂养/饮食', exact: true }).click()
  await page.getByRole('dialog', { name: '喂养/饮食', exact: true }).getByRole('button', { name: '返回', exact: true }).click()
  const events = await (await page.request.get(`/api/events?memberId=${memberId}`, { headers })).json()
  expect(events.filter((e: any) => e.memberId === memberId)).toHaveLength(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
