import { test, expect, type Page } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'
import { mkdir, readFile } from 'node:fs/promises'
const token = new TokenService('visit-sheet-e2e-secret',3600000).create({id:'visit-test'})
const headers = {Authorization:'Bearer '+token}
async function init(page:Page){
 const draft = await (await page.request.post('/api/members/empty-child/nurse-drafts',{headers,data:{scope:'visit-test:empty-child:new:'}})).json()
 await page.request.patch('/api/members/empty-child/nurse-drafts/'+draft.id,{headers,data:{version:draft.version,discard:true}})
 await page.addInitScript(token=>{sessionStorage.setItem('hoooho-auth-token',token);if(!sessionStorage.getItem('nurse-initialized')){localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'visit-test'},currentMemberId:'empty-child',members:[],profile:null},version:5}));sessionStorage.setItem('nurse-initialized','true')}},token)
 await page.goto('/nurse-station');await page.goto('/smart-record')
}
test('文字对话、备注修改删除、草稿恢复、原子保存及同记录编辑',async({page,request},testInfo)=>{
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByRole('button',{name:'智能记录',exact:true}).click()
 const panel=page.getByRole('dialog',{name:'智能症状记录',exact:true})
 await expect(panel.getByText('你好，我是 Hoooho 的值班 AI 护士，可以帮你理清这次的症状并整理成记录。孩子哪里不舒服？你可以直接跟我说。',{exact:true})).toBeVisible()
 await panel.getByLabel('跟护士说').fill('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'先整理一下',exact:true}).click()
 await expect(panel).toHaveCount(0)
 await expect(form.getByLabel('哪里不舒服')).toHaveValue('脸颊发红发痒，没有发热')
 await expect(form.getByText('不确定或担心 · 家长原话整理').first()).toBeVisible()
 await form.getByLabel('哪里不舒服').fill('人工确认：脸颊发红，未发热。')
 await form.getByRole('textbox',{name:'内容',exact:true}).first().fill('人工确认：担心鸡蛋相关，尚未确认。')
 await form.getByRole('button',{name:'删除备注',exact:true}).last().click()
 await page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/nurse-drafts/'))
 await page.reload()
 const resumed=page.getByRole('dialog',{name:'症状记录',exact:true})
 await resumed.getByRole('button',{name:'智能记录',exact:true}).click()
 await panel.getByRole('button',{name:'继续核对上次草稿'}).click()
 await expect(resumed.getByLabel('哪里不舒服')).toHaveValue('人工确认：脸颊发红，未发热。')
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveCount(1)
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveValue('人工确认：担心鸡蛋相关，尚未确认。')
 await resumed.getByRole('button',{name:'智能记录',exact:true}).click()
 await panel.getByLabel('这次是更正上一条说明').check()
 await panel.getByLabel('跟护士说').fill('更正：目前还没有其他变化。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toHaveCount(2)
 await panel.getByRole('button',{name:'先整理一下',exact:true}).click()
 await expect(panel).toHaveCount(0)
 await expect(resumed.getByLabel('哪里不舒服')).toHaveValue('人工确认：脸颊发红，未发热。')
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveCount(1)
 await mkdir('outputs/ai-nurse',{recursive:true})
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-review.png`})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 let failed=true
 await page.route('**/api/members/empty-child/case-records',r=>failed?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'合成事务失败'}})}):r.continue())
 await resumed.getByRole('button',{name:'确认并保存',exact:true}).click()
 await expect(resumed.getByRole('alert')).toContainText('合成事务失败')
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveValue('人工确认：担心鸡蛋相关，尚未确认。')
 failed=false
 await resumed.getByRole('button',{name:'确认并保存',exact:true}).click()
 await expect(page).toHaveURL(/\/health-events\/[^/]+$/)
 const eventId=page.url().split('/').at(-1)
 const records=await(await request.get('/api/events/'+eventId+'/records',{headers})).json()
 expect(records).toHaveLength(1)
 expect(records[0].journal.aiNurse.professionalNotes).toHaveLength(1)
 expect(records[0].journal.aiNurse.turns.filter((t:any)=>t.role==='user')).toHaveLength(2)
 expect(records[0].journal.aiNurse.turns.filter((t:any)=>t.role==='user')[1].correctsTurnId).toBe(records[0].journal.aiNurse.turns[1].id)
 expect(records[0].journal.aiNurse.snapshots[0].notes).toHaveLength(2)
 expect(records[0].journal.aiNurse.editedFields).toContain('narrative')
 expect(records[0].journal.aiNurse.turns[1].text).toContain('涂过保湿霜')
 expect(records[0].journal.aiNurse.professionalNotes[0].editedByUser).toBe(true)
 const before=records[0].journal.aiNurse.turns
 const updated=await request.patch('/api/records/'+records[0].id,{headers,data:{content:'编辑同一条症状',journal:{...records[0].journal,aiNurse:{...records[0].journal.aiNurse,professionalNotes:records[0].journal.aiNurse.professionalNotes.map((n:any)=>({...n,text:'更新备注',editedByUser:true}))}}}})
 expect(updated.ok()).toBe(true)
 const after=await(await request.get('/api/events/'+eventId+'/records',{headers})).json()
  expect(after).toHaveLength(1);expect(after[0].journal.aiNurse.turns).toEqual(before)
  const state=await(await request.get('/api/members/empty-child/visit-sheet',{headers})).json()
  expect((await request.put('/api/members/empty-child/visit-sheet',{headers,data:{expectedVersion:state.report?.version??state.expectedVersion??0,requestId:crypto.randomUUID(),focus:{mode:'source',sourceId:'record:'+records[0].id},caseDetails:{},question:'',notes:{},selection:null,selectedPhotoIds:[]}})).ok()).toBe(true)
  await page.goto('/visit-summary');await page.getByRole('button',{name:'导出情况单',exact:true}).click()
  const exporter=page.getByRole('dialog',{name:'导出情况单'}),download=page.waitForEvent('download')
  await exporter.getByRole('button',{name:'保存离线情况单（HTML）',exact:true}).click();const path=testInfo.outputPath('nurse-source.html');await(await download).saveAs(path)
  const html=await readFile(path,'utf8');expect(html).toContain('智能记录对话原文（只读）');expect(html).toContain('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。');expect(html).toContain('更新备注');expect(html).not.toContain(token)
})
test('权限拒绝、供应商失败、未同步原话重试及空会话禁止整理',async({page})=>{
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByRole('button',{name:'智能记录'}).click()
 const panel=page.getByRole('dialog',{name:'智能症状记录',exact:true})
 await expect(panel.getByLabel('跟护士说')).toBeVisible()
 await panel.getByRole('button',{name:'先整理一下',exact:true}).click()
 await expect(panel.getByRole('alert')).toContainText('请先')
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('权限拒绝','NotAllowedError')}})
 await panel.getByRole('button',{name:'开启实时语音'}).click()
 await expect(panel.getByRole('alert')).toContainText('权限拒绝')
 let fail=true
 await page.route('**/nurse-drafts/*',r=>r.request().method()==='PATCH'&&fail?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'合成断网'}})}):r.continue())
 await panel.getByLabel('跟护士说').fill('脸颊发红发痒，我担心鸡蛋相关。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByRole('button',{name:'重试同步原话'})).toBeVisible()
 await expect(panel.locator('.nurse-conversation').getByText('脸颊发红发痒，我担心鸡蛋相关。',{exact:true})).toBeVisible()
 fail=false
 await panel.getByRole('button',{name:'重试同步原话'}).click()
 await expect(panel.getByRole('button',{name:'重试同步原话'})).toHaveCount(0)
 page.once('dialog',d=>d.accept())
 await panel.getByRole('button',{name:'放弃未保存草稿'}).click()
 await expect(panel).toHaveCount(0)
})
