import { test, expect, type Page } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'
import { mkdir, readFile } from 'node:fs/promises'
const token = new TokenService('visit-sheet-e2e-secret',3600000).create({id:'visit-test'})
const headers = {Authorization:'Bearer '+token}
async function init(page:Page){
 const draft = await (await page.request.post('/api/members/empty-child/nurse-drafts',{headers,data:{scope:'visit-test:empty-child:new:'}})).json()
 await page.request.patch('/api/members/empty-child/nurse-drafts/'+draft.id,{headers,data:{version:draft.version,discard:true}})
 await page.addInitScript(token=>{sessionStorage.setItem('hoooho-auth-token',token);if(!sessionStorage.getItem('nurse-initialized')){localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'visit-test'},currentMemberId:'empty-child',members:[],profile:null},version:5}));sessionStorage.setItem('nurse-initialized','true')}},token)
 await page.goto('/nurse-station');await page.goto('/smart-record')
}
test('文字对话、备注修改删除、草稿恢复、原子保存及同记录编辑',async({page,request},testInfo)=>{
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByRole('button',{name:/^智能记录/,exact:true}).click()
 const panel=page.getByRole('dialog',{name:'智能记录',exact:true})
 await expect(panel.getByText('你好，我是 Hoooho 的值班 AI 护士，可以帮你理清这次的症状并整理成记录。孩子哪里不舒服？你可以直接跟我说。',{exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await panel.getByLabel('跟护士说').fill('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'整理到表单',exact:true}).click()
 await expect(panel).toHaveCount(0)
 await expect(form.getByLabel('哪里不舒服')).toHaveValue('脸颊发红发痒，没有发热')
 await expect(form.getByText('不确定或担心 · 家长原话整理').first()).toBeVisible()
 await form.getByLabel('哪里不舒服').fill('人工确认：脸颊发红，未发热。')
 await form.getByRole('textbox',{name:'内容',exact:true}).first().fill('人工确认：担心鸡蛋相关，尚未确认。')
 await form.getByRole('button',{name:'删除备注',exact:true}).last().click()
 await page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/nurse-drafts/'))
 await page.reload()
 const resumed=page.getByRole('dialog',{name:'症状记录',exact:true})
 await resumed.getByRole('button',{name:/^智能记录/,exact:true}).click()
 await panel.getByRole('button',{name:'继续核对上次草稿'}).click()
 await expect(resumed.getByLabel('哪里不舒服')).toHaveValue('人工确认：脸颊发红，未发热。')
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveCount(1)
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveValue('人工确认：担心鸡蛋相关，尚未确认。')
 await resumed.getByRole('button',{name:/^智能记录/,exact:true}).click()
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await panel.getByLabel('跟护士说').fill('更正：目前还没有其他变化。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toHaveCount(2)
 await panel.getByRole('button',{name:'整理到表单',exact:true}).click()
 await expect(panel).toHaveCount(0)
 const conflict=page.getByRole('dialog',{name:'核对人工修改'});if(await conflict.count())await conflict.getByRole('button',{name:'保留我的修改，回填其他项',exact:true}).click()
 await expect(resumed.getByLabel('哪里不舒服')).toHaveValue('人工确认：脸颊发红，未发热。')
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveCount(1)
 await mkdir('outputs/ai-nurse',{recursive:true})
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-review.png`})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 let failed=true
 await page.route('**/api/members/empty-child/case-records',r=>failed?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'合成事务失败'}})}):r.continue())
 await resumed.getByRole('button',{name:'确认并保存',exact:true}).click()
 await expect(resumed.getByText('合成事务失败',{exact:true})).toBeVisible()
 await expect(resumed.getByRole('textbox',{name:'内容',exact:true})).toHaveValue('人工确认：担心鸡蛋相关，尚未确认。')
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-save-failed.png`})
 failed=false
 await resumed.getByRole('button',{name:'重试保存',exact:true}).click()
 await expect(page).toHaveURL(/\/health-events\/[^/]+$/)
 const eventId=page.url().split('/').at(-1)
 const records=await(await request.get('/api/events/'+eventId+'/records',{headers})).json()
 expect(records).toHaveLength(1)
 expect(records[0].journal.aiNurse.professionalNotes).toHaveLength(1)
 expect(records[0].journal.aiNurse.turns.filter((t:any)=>t.role==='user')).toHaveLength(2)
 expect(records[0].journal.aiNurse.turns.filter((t:any)=>t.role==='user')[1].text).toBe('更正：目前还没有其他变化。')
 expect(records[0].journal.aiNurse.snapshots[0].notes).toHaveLength(2)
 expect(records[0].journal.aiNurse.editedFields).toContain('narrative')
 expect(records[0].journal.aiNurse.turns[1].text).toContain('涂过保湿霜')
 expect(records[0].journal.aiNurse.professionalNotes[0].editedByUser).toBe(true)
 const before=records[0].journal.aiNurse.turns
 const updated=await request.patch('/api/records/'+records[0].id,{headers,data:{content:'编辑同一条症状',journal:{...records[0].journal,aiNurse:{...records[0].journal.aiNurse,professionalNotes:records[0].journal.aiNurse.professionalNotes.map((n:any)=>({...n,text:'更新备注',editedByUser:true}))}}}})
 expect(updated.ok()).toBe(true)
 const after=await(await request.get('/api/events/'+eventId+'/records',{headers})).json()
  expect(after).toHaveLength(1);expect(after[0].journal.aiNurse.turns).toEqual(before)
  const state=await(await request.get('/api/members/empty-child/visit-sheet',{headers})).json()
  expect((await request.put('/api/members/empty-child/visit-sheet',{headers,data:{expectedVersion:state.report?.version??state.expectedVersion??0,requestId:crypto.randomUUID(),focus:{mode:'source',sourceId:'record:'+records[0].id},caseDetails:{},question:'',notes:{},selection:null,selectedPhotoIds:[]}})).ok()).toBe(true)
  await page.goto('/visit-summary');await page.getByRole('button',{name:'导出情况单',exact:true}).click()
  const exporter=page.getByRole('dialog',{name:'导出情况单'})
  const briefDownload=page.waitForEvent('download');await exporter.getByRole('button',{name:'保存重点摘要（文本）',exact:true}).click();const briefPath=testInfo.outputPath('nurse-brief.txt');await(await briefDownload).saveAs(briefPath);const brief=await readFile(briefPath,'utf8');expect(brief).toContain('更新备注');expect(brief).not.toContain('有没有影响睡眠？');expect(brief).not.toContain(token)
  const download=page.waitForEvent('download')
  await exporter.getByRole('button',{name:'保存离线情况单（HTML）',exact:true}).click();const path=testInfo.outputPath('nurse-source.html');await(await download).saveAs(path)
  const html=await readFile(path,'utf8');expect(html).toContain('智能记录对话原文（只读）');expect(html).toContain('脸颊发红发痒，没有发热。我担心鸡蛋过敏，涂过保湿霜好像没变化。');expect(html).toContain('更新备注');expect(html).not.toContain(token)
})
test('权限拒绝、供应商失败、未同步原话重试及空会话禁止整理',async({page})=>{
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByRole('button',{name:/^智能记录/}).click()
 const panel=page.getByRole('dialog',{name:'智能记录',exact:true})
 await expect(panel.getByLabel('跟护士说')).toHaveCount(0)
 await expect(panel.getByRole('button',{name:'发送',exact:true})).toHaveCount(0)
 await panel.getByRole('button',{name:'整理到表单',exact:true}).click()
 await expect(panel.getByRole('alert')).toContainText('请先')
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('权限拒绝','NotAllowedError')}})
 await panel.getByRole('button',{name:'开始语音'}).click()
 await expect(panel.getByRole('alert')).toContainText('权限拒绝')
 let fail=true
 await page.route('**/nurse-drafts/*',r=>r.request().method()==='PATCH'&&fail?r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'合成断网'}})}):r.continue())
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await panel.getByLabel('跟护士说').fill('脸颊发红发痒，我担心鸡蛋相关。')
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByRole('button',{name:'重试同步原话'})).toBeVisible()
 await expect(panel.locator('.nurse-conversation').getByText('脸颊发红发痒，我担心鸡蛋相关。',{exact:true})).toBeVisible()
 fail=false
 await panel.getByRole('button',{name:'重试同步原话'}).click()
 await expect(panel.getByRole('button',{name:'重试同步原话'})).toHaveCount(0)
 page.once('dialog',d=>d.accept())
 await panel.getByRole('button',{name:'放弃未保存草稿'}).click()
 await expect(panel).toHaveCount(0)
})


test('fixed four inputs, ordinary voice confirmation, compact visual viewport, collapse/resume and disconnect',async({page},testInfo)=>{
 await page.addInitScript(()=>{
  const fake={_height:undefined as number|undefined,get height(){return this._height??innerHeight},get width(){return innerWidth},scale:1,offsetTop:0,offsetLeft:0,pageTop:0,pageLeft:0,listeners:new Map<string,Function[]>(),addEventListener(t:string,f:Function){this.listeners.set(t,[...(this.listeners.get(t)||[]),f])},removeEventListener(t:string,f:Function){this.listeners.set(t,(this.listeners.get(t)||[]).filter(v=>v!==f))},resize(h:number){this._height=h;this.listeners.get('resize')?.forEach(f=>f())}}
  Object.defineProperty(window,'visualViewport',{configurable:true,value:fake})
  ;(window as any).SpeechRecognition=class{onresult:any;onend:any;start(){this.onresult?.({results:[{0:{transcript:'脸上有些小疹子'},isFinal:true}]})}stop(){this.onend?.()}abort(){}}
  navigator.mediaDevices.getUserMedia=async()=>({getTracks:()=>[{stop(){}}]}) as unknown as MediaStream
 })
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true}),toolbar=form.getByRole('region',{name:'记录输入方式'})
 await form.getByLabel('哪里不舒服').fill('原有症状描述')
 await mkdir('outputs/ai-nurse',{recursive:true})
 const countBefore=await page.request.get('/api/events',{headers});const eventsBefore=await countBefore.json()
 await form.getByRole('button',{name:'语音输入',exact:true}).click()
 const voice=page.getByRole('dialog',{name:'普通语音输入'});await expect(voice.getByText('写入：症状描述',{exact:true})).toBeVisible();await expect(voice.getByLabel('语音转写文字')).toHaveValue('脸上有些小疹子')
 await expect(form.locator('.symptom-record-save')).toBeHidden();await voice.getByRole('button',{name:'结束语音',exact:true}).click();await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-ordinary-voice.png`});await voice.getByRole('button',{name:'使用这段文字',exact:true}).click()
 await expect(form.getByLabel('哪里不舒服')).toHaveValue('原有症状描述\n脸上有些小疹子');await expect(form.getByText('专业备注',{exact:true})).toHaveCount(0)
 await form.locator('.symptom-record-scroll').evaluate(el=>el.scrollTop=el.scrollHeight);for(const label of ['拍照','选照片','语音输入','智能记录'])await expect(form.getByRole('button',{name:label,exact:true})).toBeVisible()
 await form.getByLabel('哪里不舒服').fill('保留的长症状描述，变化尚不明确。'.repeat(40))
 await page.evaluate(()=>(window.visualViewport as any).resize(400))
 await expect(form).toHaveAttribute('data-keyboard','true')
 await expect.poll(async()=>Math.round((await toolbar.boundingBox())!.height)).toBe(44)
 expect((await form.locator('.symptom-record-save').boundingBox())!.y+(await form.locator('.symptom-record-save').boundingBox())!.height).toBeLessThanOrEqual(401)
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-keyboard.png`})
 await page.evaluate(()=>(window.visualViewport as any).resize(innerHeight))
 await expect(form).toHaveAttribute('data-keyboard','false')
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-fixed.png`})
 await form.getByRole('button',{name:'智能记录',exact:true}).click();const panel=page.getByRole('dialog',{name:'智能记录'});await expect(panel.locator('.nurse-turn--assistant')).toHaveCount(1)
 await expect(panel.getByRole('button',{name:'整理到表单',exact:true})).toBeVisible()
 await page.evaluate(()=>(window.visualViewport as any).resize(400))
 await expect.poll(async()=>Math.round((await panel.boundingBox())!.y+(await panel.boundingBox())!.height)).toBeLessThanOrEqual(400)
 await expect(panel.getByRole('button',{name:'整理到表单',exact:true})).toBeVisible()
 await expect(panel.getByRole('button',{name:'开始语音',exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await expect(panel.getByRole('button',{name:'发送',exact:true})).toBeVisible()
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-panel-keyboard.png`})
 await page.evaluate(()=>(window.visualViewport as any).resize(innerHeight))
 await panel.getByRole('button',{name:'改用语音',exact:true}).click()
 await panel.getByRole('button',{name:'收起',exact:true}).click();await expect(form.getByRole('button',{name:'智能记录 · 继续',exact:true})).toBeVisible()
 await form.getByRole('button',{name:'智能记录 · 继续',exact:true}).click();await expect(panel.locator('.nurse-turn--assistant')).toHaveCount(1)
 await page.evaluate(()=>window.dispatchEvent(new Event('offline')));await expect(panel.getByRole('alert')).toContainText('连接中断，已有文字仍在');await expect(panel.getByRole('button',{name:'改用文字',exact:true})).toBeVisible()
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-v2-disconnected.png`})
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await page.route('**/nurse-drafts/*/generate',async route=>{await new Promise(resolve=>setTimeout(resolve,1500));await route.fulfill({status:503,json:{error:{message:'合成迟到失败'}}}).catch(()=>{})})
 await panel.getByLabel('跟护士说').fill('合成关闭前的最终原话')
 const synced=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/nurse-drafts/'))
 await panel.getByRole('button',{name:'发送',exact:true}).click();await synced
 await panel.getByRole('button',{name:'收起',exact:true}).click()
 await expect(panel).toHaveCount(0,{timeout:1000})
 await form.getByRole('button',{name:'智能记录 · 继续',exact:true}).click()
 await expect(panel.locator('.nurse-turn--user').getByText('合成关闭前的最终原话',{exact:true})).toHaveCount(1)
 await panel.getByRole('button',{name:'收起',exact:true}).click()
 expect((await(await page.request.get('/api/events',{headers})).json()).length).toBe(eventsBefore.length)
})


test('manual body and exact time before nurse remain intact until an explicit suggestion is chosen',async({page,request})=>{
 await init(page);const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByLabel('哪里不舒服').fill('人工记录：左手有红点')
 await form.getByLabel('手动补充症状部位').fill('左手')
 await form.locator('input[type=datetime-local]').fill('2026-10-01T10:20')
 await form.getByRole('button',{name:/^智能记录/}).click();const panel=page.getByRole('dialog',{name:'智能记录'})
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await panel.getByLabel('跟护士说').fill('脸颊发红发痒，没有发热。我担心鸡蛋相关。')
 await panel.getByRole('button',{name:'发送',exact:true}).click();await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible()
 await panel.getByRole('button',{name:'整理到表单',exact:true}).click()
 const conflict=page.getByRole('dialog',{name:'核对人工修改'});await expect(conflict.getByText('当前：人工记录：左手有红点',{exact:true})).toBeVisible()
 await conflict.getByRole('button',{name:'保留我的修改，回填其他项',exact:true}).click()
 await expect(form.getByLabel('哪里不舒服')).toHaveValue('人工记录：左手有红点')
 await expect(form.getByLabel('手动补充症状部位')).toHaveValue('左手')
 await expect(form.locator('input[type=datetime-local]')).toHaveValue('2026-10-01T10:20')
 await expect(form.getByRole('checkbox',{name:'发生时间待确认（不会用原件上传时间代替）'})).not.toBeChecked()
 await form.getByRole('button',{name:'确认并保存',exact:true}).click();await expect(page).toHaveURL(/\/health-events\/[^/]+$/)
 const records=await(await request.get('/api/events/'+page.url().split('/').at(-1)+'/records',{headers})).json()
 expect(records[0].journal.symptom.narrative).toBe('人工记录：左手有红点');expect(records[0].journal.symptom.locationText).toBe('左手');expect(records[0].journal.timePrecision).toBe('exact');expect(records[0].occurredAt).toBe('2026-10-01T02:20:00.000Z')
})

test('voice-first composer uses one main action, preserves unsent text across modes and shows character avatars',async({page},testInfo)=>{
 await page.route('**/api/auth/session',async route=>{
   const response=await route.fetch(),session=await response.json()
   await route.fulfill({response,json:{...session,user:{...session.user,nickname:'刘（虚构验收）'}}})
 })
 await init(page)
 const form=page.getByRole('dialog',{name:'症状记录',exact:true})
 await form.getByRole('button',{name:'智能记录',exact:true}).click()
 const panel=page.getByRole('dialog',{name:'智能记录',exact:true})
 await expect(panel.getByRole('heading',{name:'智能记录',exact:true})).toBeVisible()
 await expect(panel.getByRole('button',{name:'开始语音',exact:true})).toBeEnabled()
 await expect(panel.getByRole('textbox')).toHaveCount(0)
 await expect(panel.getByRole('button',{name:'发送',exact:true})).toHaveCount(0)
 await expect(panel.locator('input[type=checkbox]')).toHaveCount(0)
 await panel.locator('.nurse-avatar--assistant img').evaluate((img:HTMLImageElement)=>img.decode())
 await mkdir('outputs/ai-nurse',{recursive:true})
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-smart-record-voice.png`})
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await expect(panel.getByLabel('跟护士说')).toBeFocused()
 const text='脸颊发红发痒，没有发热。我担心鸡蛋相关。'
 await panel.getByLabel('跟护士说').fill(text)
 await panel.getByRole('button',{name:'改用语音',exact:true}).click()
 await expect(panel.getByRole('textbox')).toHaveCount(0)
 await panel.getByRole('button',{name:'改用文字',exact:true}).click()
 await expect(panel.getByLabel('跟护士说')).toHaveValue(text)
 await panel.getByRole('button',{name:'发送',exact:true}).click()
 await expect(panel.getByText('有没有影响睡眠？',{exact:true})).toBeVisible()
 await expect(panel.locator('.nurse-avatar--user')).toHaveText('L')
 await expect(panel.locator('.nurse-turn strong')).toHaveCount(0)
 await panel.getByRole('button',{name:'改用语音',exact:true}).click()
 await expect(panel.getByRole('button',{name:'继续语音',exact:true})).toBeVisible()
 await page.screenshot({path:`outputs/ai-nurse/${testInfo.project.name}-smart-record-conversation.png`})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await panel.getByRole('button',{name:'收起',exact:true}).click()
 await form.getByRole('button',{name:'智能记录 · 继续',exact:true}).click()
 await expect(panel.locator('.nurse-turn--user').getByText(text,{exact:true})).toHaveCount(1)
 await expect(panel.getByRole('button',{name:'继续语音',exact:true})).toBeVisible()
})
