import { expect, test } from '@playwright/test'

const today = () => new Date().toLocaleDateString('sv-SE')

test('growth data hub saves, explains, preserves drafts and manages history', async ({ page }, testInfo) => {
  const suffix = Date.now().toString().slice(-8)
  await page.goto('/login')
  await page.getByRole('tab', { name: '注册' }).click()
  await page.locator('input').nth(0).fill(`成长${suffix}`)
  await page.locator('input').nth(1).fill('local-test-0927')
  await page.getByRole('button', { name: '注册并进入' }).click()
  await page.getByRole('button', { name: '添加第一个孩子' }).click()
  await page.getByLabel('姓名').fill('小禾')
  await page.getByLabel('出生日期').fill('2024-01-15')
  await page.getByText('女', { exact: true }).click()
  await page.getByLabel('你是孩子的谁？').selectOption({ label: '妈妈' })
  const created = page.waitForResponse((response) => response.url().includes('/api/members') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '添加家庭成员' }).click()
  expect((await created).ok()).toBe(true)

  await page.goto('/health-profile/basic')
  await expect(page.getByRole('heading', { name: '成长数据' })).toBeVisible()
  await expect(page.getByRole('tab', { name: '身高曲线' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByText(/保存第一次身长或身高测量/)).toBeVisible()
  await expect(page.getByText('成长解读')).toBeVisible()
  await expect(page.getByText(/当前没有数据，不能判断位置或趋势/)).toBeVisible()
  await expect(page.locator('.growth-step-card__heading time')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(testInfo.project.use.viewport?.width ?? 1280)

  const historyLength = await page.evaluate(() => history.length)
  await page.getByRole('tab', { name: '体重曲线' }).click()
  await expect(page.getByRole('tab', { name: '体重曲线' })).toHaveAttribute('aria-selected', 'true')
  expect(await page.evaluate(() => history.length)).toBe(historyLength)
  await page.getByRole('tab', { name: '身高曲线' }).click()

  await page.getByRole('button', { name: /— cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('82.0')
  await page.getByLabel('手动编辑身高 cm').blur()
  await page.getByRole('button', { name: /— kg/ }).click()
  await page.getByLabel('手动编辑体重 kg').fill('11.0')
  await page.getByLabel('手动编辑体重 kg').blur()
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()
  await expect(page.locator('.growth-data-latest')).toContainText('82.0 cm')
  await expect(page.locator('.growth-chart-record')).toHaveCount(1)
  for (const card of await page.locator('.growth-step-card').all()) {
    await expect(card.locator('time')).toHaveAttribute('datetime', today())
    await expect(card.locator('time')).toHaveText(today().slice(5).replace('-', '/'))
    expect(await card.evaluate(el => { const box=el.getBoundingClientRect(),date=el.querySelector('time')!.getBoundingClientRect(),label=el.querySelector('h2')!.getBoundingClientRect();return date.left>=label.right && date.right<=box.right })).toBe(true)
  }

  await page.getByRole('button', { name: '身高增加0.1厘米' }).click()
  await page.route('**/api/growth-measurements', async (route) => route.request().method() === 'POST' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: '测试保存失败' }) }) : route.continue())
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.locator('.growth-update-message--error')).toBeVisible()
  await expect(page.getByRole('button', { name: '82.1 cm', exact: true })).toBeVisible()
  await expect(page.locator('.growth-data-latest')).toContainText('82.0 cm')
  await page.unroute('**/api/growth-measurements')
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()

  const backfill = '2026-08-10'
  await page.getByLabel('测量日期').fill(backfill)
  // The editable new-measurement date must not relabel the last saved measurement.
  for (const date of await page.locator('.growth-step-card__heading time').all()) await expect(date).toHaveAttribute('datetime', today())
  await page.getByRole('button', { name: /— cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('80.0')
  await page.getByLabel('手动编辑身高 cm').blur()
  await page.getByRole('button', { name: /— kg/ }).click()
  await page.getByLabel('手动编辑体重 kg').fill('10.8')
  await page.getByLabel('手动编辑体重 kg').blur()
  await page.getByRole('tab', { name: '体重曲线' }).click()
  await expect(page.getByRole('button', { name: '10.8 kg', exact: true })).toBeVisible()
  await expect(page.locator('.growth-data-latest')).toContainText('11.0 kg')
  await page.getByRole('tab', { name: '身高曲线' }).click()
  await expect(page.getByRole('button', { name: '80.0 cm', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()
  await expect(page.locator('.growth-chart-record')).toHaveCount(2)
  await expect(page.locator('.growth-interpretation')).toContainText(/目前只有 2 条/)

  await page.locator('.growth-data-content').evaluate((element) => element.scrollTo({ top: 0 }))
  expect((await page.locator('.growth-data-curve').boundingBox())?.height).toBeGreaterThan(340)
  if (testInfo.project.name === 'iphone-se') await page.screenshot({ path: testInfo.outputPath('growth-height-iphone-se.png') })
  await page.getByRole('tab', { name: '体重曲线' }).click()
  await expect(page.locator('.growth-data-latest')).toContainText('11.0 kg')
  await page.locator('.growth-data-content').evaluate((element) => element.scrollTo({ top: 0 }))
  if (testInfo.project.name === 'iphone-se') await page.screenshot({ path: testInfo.outputPath('growth-weight-iphone-se.png') })
  await page.locator('.growth-chart-hit').last().click({ force: true })
  await expect(page.locator('.growth-chart-tooltip')).toBeVisible()
  await expect(page.locator('.growth-chart-tooltip')).toContainText(/kg/)
  if (testInfo.project.name === 'iphone-se') await page.screenshot({ path: testInfo.outputPath('growth-point-tooltip-iphone-se.png') })
  await page.locator('.growth-chart-hit').last().click({ force: true })
  await expect(page.locator('.growth-chart-tooltip')).toHaveCount(0)

  await page.reload()
  await expect(page.locator('.growth-chart-record')).toHaveCount(2)
  await expect(page.locator('.growth-data-latest')).toContainText('11.0 kg')
  await page.getByRole('button', { name: /记录列表.*2 条/ }).click()
  await expect(page.getByRole('heading', { name: '记录列表' })).toBeVisible()
  await expect(page.locator('.growth-record-row')).toHaveCount(2)
  await expect(page.locator('.growth-record-row').first()).toContainText(`最新 · ${today()}`)
  await expect(page.locator('.growth-record-row').nth(1)).toContainText(backfill)
  await expect(page.getByRole('button', { name: '编辑' })).toHaveCount(2)
  await expect(page.getByRole('button', { name: '删除' })).toHaveCount(2)
  if (testInfo.project.name === 'iphone-se') await page.screenshot({ path: testInfo.outputPath('growth-record-list-iphone-se.png'), fullPage: true })

  await page.evaluate(() => history.back())
  await expect(page.getByRole('heading', { name: '成长数据' })).toBeVisible()
  await expect(page.getByRole('tab', { name: '体重曲线' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.growth-chart-record')).toHaveCount(2)
  await page.getByRole('button', { name: /记录列表.*2 条/ }).click()

  await page.getByRole('button', { name: '编辑' }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog').getByLabel('体重（kg）')).toHaveValue('11.0')
  await page.getByRole('button', { name: '关闭' }).click()
  page.once('dialog', (dialog) => dialog.dismiss())
  await page.getByRole('button', { name: '删除' }).last().click()
  await expect(page.locator('.growth-record-row')).toHaveCount(2)
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: '删除' }).last().click()
  await expect(page.locator('.growth-record-row')).toHaveCount(1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(testInfo.project.use.viewport?.width ?? 1280)
})
