import { expect, test } from '@playwright/test'

const today = () => new Date().toLocaleDateString('sv-SE')

test('iPhone SE saves, backfills, persists and updates both curves', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByRole('tab', { name: '注册' }).click()
  await page.locator('input').nth(0).fill(`基础信息验收${Date.now()}`)
  await page.locator('input').nth(1).fill('local-test-0913')
  await page.getByRole('button', { name: '注册并进入' }).click()
  await page.getByRole('button', { name: '添加第一个孩子' }).click()
  await page.getByLabel('姓名').fill('小禾')
  await page.getByLabel('出生日期').fill('2024-01-15')
  await page.getByText('女', { exact: true }).click()
  await page.getByLabel('你是孩子的谁？').selectOption({ label: '妈妈' })
  const created = page.waitForResponse((response) => response.url().includes('/api/members') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '添加家庭成员' }).click()
  expect((await created).ok()).toBe(true)

  await page.goto('/health-profile/basic')
  await expect(page.getByRole('heading', { name: '基础信息' })).toBeVisible()
  await expect(page.getByRole('button', { name: /成长记录 查看记录与成长曲线/ })).toBeVisible()
  await expect(page.getByText(/今日成长落点|填写后自动保存/)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)

  await page.getByRole('button', { name: /— cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('82.0')
  await page.getByLabel('手动编辑身高 cm').blur()
  await page.getByRole('button', { name: /— g/ }).click()
  await page.getByLabel('手动编辑体重 g').fill('11000')
  await page.getByLabel('手动编辑体重 g').blur()
  await page.getByRole('button', { name: 'B', exact: true }).click()
  await page.getByRole('button', { name: 'Rh未知' }).click()
  await page.getByRole('dialog', { name: 'Rh血型' }).getByRole('button', { name: 'Rh+' }).click()
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()
  await expect(page.getByRole('button', { name: '保存本次更新' })).toBeDisabled()

  await page.reload()
  await expect(page.getByRole('button', { name: /82\.0 cm/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /11000 g/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'B', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '身高增加0.1厘米' }).click()
  await page.getByRole('button', { name: '身高减少0.1厘米' }).click()
  await expect(page.getByRole('button', { name: '身高减少0.1厘米' })).toBeDisabled()
  await page.getByRole('button', { name: /82\.0 cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('81.9')
  await page.getByLabel('手动编辑身高 cm').blur()
  await expect(page.getByRole('button', { name: /81\.9 cm/ })).toBeVisible()
  await page.getByRole('button', { name: /81\.9 cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('82.1')
  await page.getByLabel('手动编辑身高 cm').blur()
  await page.getByRole('button', { name: '体重减少1克' }).click()
  await page.getByRole('button', { name: '体重增加1克' }).click()
  await page.getByRole('button', { name: '体重增加1克' }).click()
  await expect(page.getByRole('button', { name: /11001 g/ })).toBeVisible()
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()

  const backfill = '2026-08-10'
  await page.getByLabel('测量日期').fill(backfill)
  await page.getByRole('button', { name: /82\.1 cm/ }).click()
  await page.getByLabel('手动编辑身高 cm').fill('80.0')
  await page.getByLabel('手动编辑身高 cm').blur()
  await page.getByRole('button', { name: /11001 g/ }).click()
  await page.getByLabel('手动编辑体重 g').fill('10800')
  await page.getByLabel('手动编辑体重 g').blur()
  await page.getByRole('button', { name: '保存本次更新' }).click()
  await expect(page.getByText('已保存，并加入成长记录')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('basic-info-iphone-se.png'), fullPage: true })

  await page.getByRole('button', { name: /成长记录 查看记录与成长曲线/ }).click()
  await expect(page.locator('.growth-record-row')).toHaveCount(2)
  await expect(page.locator('.growth-record-row').first()).toContainText(`最新 · ${today()}`)
  await expect(page.locator('.growth-record-row').first()).toContainText('11001 g')
  await expect(page.locator('.growth-record-row').nth(1)).toContainText(backfill)
  await page.getByRole('tab', { name: /身长曲线|身高曲线/ }).click()
  await expect(page.locator('.growth-chart-record')).toHaveCount(2)
  await page.getByRole('tab', { name: '体重曲线' }).click()
  await expect(page.locator('.growth-chart-record')).toHaveCount(2)
  await expect(page.getByText('体重（g）')).toBeVisible()

  for (const width of [390, 430]) {
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/health-profile/basic')
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
})
