import { expect, test, type Page } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'
const token = new TokenService('quick-record-mobile-e2e-secret', 3600_000).create({ id: 'quick-record-e2e-account' })
async function prepare(page: Page) { const response = await page.request.post('/api/members', { headers: { Authorization: `Bearer ${token}` }, data: { name: '测试宝宝', birthday: '2024-01-01', gender: 'male', avatar: '', relationship: 'child', primaryRecorderRelationship: 'father' } }); expect(response.ok()).toBe(true); const member = await response.json(); await page.addInitScript(({ authToken, memberId }) => { sessionStorage.setItem('hoooho-auth-token', authToken); localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'quick-record-e2e-account' }, currentMemberId: memberId, members: [], profile: null }, version: 5 })) }, { authToken: token, memberId: member.id }); await page.goto('/health-events'); await expect(page.getByRole('button', { name: '手动记录' })).toBeEnabled() }
test('iPhone SE 单药、多药标签、剂量、独立提醒、草稿与真实保存', async ({ page }) => {
  await prepare(page); await page.getByRole('button', { name: '手动记录' }).click(); await page.getByRole('button', { name: '用药' }).click(); await page.getByRole('button', { name: '开始记录' }).click()
  const form = page.getByRole('dialog', { name: '记录用药' }); await expect(form).toBeVisible(); await expect(form.getByRole('tab')).toHaveCount(0)
  await form.getByLabel('药品名称').fill('布洛芬混悬液'); await expect(form.getByText('—')).toBeVisible(); await form.getByRole('button', { name: '增加剂量' }).click(); await expect(form.getByRole('button', { name: '直接输入剂量' })).toHaveText('0.5')
  await form.getByRole('button', { name: '添加另一种药' }).click(); await expect(form.getByRole('tab')).toHaveCount(2); await expect(form.getByRole('tab', { name: '药品 2' })).toHaveAttribute('aria-selected', 'true')
  await form.getByLabel('药品名称').fill('对乙酰氨基酚'); await form.getByRole('button', { name: '1', exact: true }).first().click(); await form.getByRole('button', { name: '增加剂量' }).click(); await form.getByRole('button', { name: '片', exact: true }).click(); await form.getByRole('switch').check(); await expect(form.getByText('提醒周期')).toBeVisible()
  await form.getByRole('tab', { name: '布洛芬混悬液' }).click(); await expect(form.getByRole('switch')).not.toBeChecked(); await expect(form.getByLabel('药品名称')).toHaveValue('布洛芬混悬液'); expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
  await page.screenshot({ path: 'test-results/medication-record-iphone-se.png', fullPage: true })
  await form.getByRole('button', { name: '保存记录' }).click(); await expect(page.getByText('已记录').first()).toBeVisible(); await expect(page.getByText('用药 · 共2种')).toBeVisible(); await expect(page.getByText(/布洛芬混悬液 · 0.5 mL/)).toBeVisible()
})
