import { expect, test, type Page } from '@playwright/test'

async function prepare(page: Page) {
  await page.goto('/health-events')
  await page.getByRole('button', { name: '暂不登录，先体验' }).click()
  await page.getByRole('button', { name: '添加第一个孩子' }).click()
  await page.getByLabel('姓名').fill('疫苗测试宝宝')
  await page.getByLabel('出生日期').fill('2024-01-01')
  await page.getByRole('button', { name: '男' }).click()
  await page.getByLabel('你是孩子的谁？').selectOption({ label: '爸爸' })
  await page.getByRole('button', { name: '添加家庭成员' }).click()
  await page.getByRole('button', { name: '跳过' }).click()
  await page.goto('/health-events')
}

test('iPhone SE 疫苗入口、多疫苗、观察互斥、草稿和真实保存', async ({ page }) => {
  await prepare(page)
  await page.getByRole('button', { name: '手动记录' }).click()
  const entry = page.getByRole('dialog', { name: '记录新情况' })
  await expect(entry.getByRole('button', { name: '就医' })).toBeVisible()
  await entry.getByRole('button', { name: '疫苗' }).click()
  await expect(entry.getByRole('button', { name: '疫苗' })).toHaveAttribute('aria-pressed', 'true')
  await entry.getByRole('button', { name: '开始记录' }).click()
  const form = page.getByRole('dialog', { name: '记录疫苗接种' })
  await expect(form).toBeVisible()
  await form.getByPlaceholder('搜索疫苗名称，或手动填写').first().fill('流感疫苗（三价）')
  await form.getByRole('button', { name: '第2剂' }).click()
  await form.getByRole('button', { name: '添加同次接种的其他疫苗' }).click()
  await form.getByPlaceholder('搜索疫苗名称，或手动填写').nth(1).fill('百白破疫苗')
  await form.getByRole('button', { name: '加强剂' }).nth(1).click()
  await form.getByRole('button', { name: /再补充一点/ }).click()
  await form.getByRole('button', { name: '暂未观察' }).click()
  await form.getByRole('button', { name: '发热' }).click()
  await expect(form.getByRole('button', { name: '暂未观察' })).toHaveAttribute('aria-pressed', 'false')
  await expect(form.getByRole('button', { name: '发热' })).toHaveAttribute('aria-pressed', 'true')
  expect(await page.evaluate(() => ({ width: document.documentElement.scrollWidth, nested: [...document.querySelectorAll('.vaccination-record-scroll *:not(textarea)')].filter((node) => { const style = getComputedStyle(node); return /(auto|scroll)/.test(style.overflowY) }).length }))).toEqual({ width: 375, nested: 0 })
  await form.getByRole('button', { name: '保存记录' }).click()
  await expect(page.getByText('已记录').first()).toBeVisible()
  await expect(page.getByText(/疫苗接种 · 共2种/)).toBeVisible()
})
