import { expect, test } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'

const token = new TokenService('time-view-e2e-local-only-secret', 60 * 60_000).create({ id: 'time-view-test-account' })

for (const width of [375, 390, 430, 1280]) test(`direct merged diet form returns to journal at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1280 ? 800 : 667 })
  await page.addInitScript((authToken) => {
    sessionStorage.setItem('hoooho-auth-token', authToken)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'time-view-test-account' }, currentMemberId: 'child-one', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/health-events')
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  const daily = page.getByRole('group', { name: '记录日常选项' })
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await daily.screenshot({ path: `test-results/record-daily-back-${width}.png` })
  await daily.getByRole('button', { name: '喂养/饮食' }).click()
  const diet = page.getByRole('dialog', { name: '喂养/饮食', exact: true })
  await expect(diet.getByRole('button', { name: '返回', exact: true })).toBeVisible()
  await diet.screenshot({ path: `test-results/record-diet-back-${width}.png` })
  await diet.getByRole('button', { name: '返回', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '记录日常', exact: true })).toBeVisible()
})

for (const width of [375, 430]) test(`complementary food controls stay compact at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 667 })
  await page.addInitScript((authToken) => {
    sessionStorage.setItem('hoooho-auth-token', authToken)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'time-view-test-account' }, currentMemberId: 'child-one', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/health-events')
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await page.getByRole('group', { name: '记录日常选项' }).getByRole('button', { name: '喂养/饮食' }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '食物饮食', exact: true }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '辅食', exact: true }).click()

  const form = page.getByRole('dialog', { name: '喂养/饮食' })
  const input = form.getByRole('textbox', { name: '输入食物名称' })
  await expect(form.getByRole('button', { name: '添加食物' })).toHaveCount(0)
  await expect(form.getByRole('group', { name: '食物形态' })).toHaveCount(0)
  await expect(form.getByRole('slider', { name: '吃了多少' })).toHaveCount(0)
  await input.fill('香蕉泥')
  const add = form.getByRole('button', { name: '添加食物' })
  await expect(add).toBeVisible()
  const inputBox = await input.boundingBox()
  const addBox = await add.boundingBox()
  expect(inputBox && addBox && addBox.x >= inputBox.x && addBox.x + addBox.width <= inputBox.x + inputBox.width + 1).toBeTruthy()
  await add.click()
  await expect(add).toHaveCount(0)
  const commonRow = form.locator('.diet-common-foods')
  await expect(commonRow.getByRole('button', { name: '编辑' })).toBeVisible()
  await form.screenshot({ path: `test-results/complementary-compact-${width}.png` })
})

test('meal omits removed controls while retaining food entry and time', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.addInitScript((authToken) => {
    sessionStorage.setItem('hoooho-auth-token', authToken)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'time-view-test-account' }, currentMemberId: 'child-one', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/health-events')
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await page.getByRole('group', { name: '记录日常选项' }).getByRole('button', { name: '喂养/饮食' }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '食物饮食', exact: true }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '正餐', exact: true }).click()

  const form = page.getByRole('dialog', { name: '喂养/饮食' })
  await expect(form.getByRole('group', { name: '餐次' })).toHaveCount(0)
  await expect(form.getByRole('slider', { name: '吃了多少' })).toHaveCount(0)
  await expect(form.getByRole('group', { name: '食欲' })).toHaveCount(0)
  await expect(form.getByLabel('结束时间（可选）')).toHaveCount(0)
  await expect(form.getByText('记录时间')).toBeVisible()
  await expect(form.getByRole('button', { name: '添加食物' })).toHaveCount(0)
  await form.getByRole('textbox', { name: '输入食物名称' }).fill('米饭')
  await expect(form.getByRole('button', { name: '添加食物' })).toBeVisible()
  await expect(form.locator('.diet-common-foods').getByRole('button', { name: '编辑' })).toBeVisible()
  await form.screenshot({ path: 'test-results/meal-compact-375.png' })
})

test('snack uses the same compact food entry without an intake slider', async ({ page }) => {
  await page.addInitScript((authToken) => {
    sessionStorage.setItem('hoooho-auth-token', authToken)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'time-view-test-account' }, currentMemberId: 'child-one', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/health-events')
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await page.getByRole('group', { name: '记录日常选项' }).getByRole('button', { name: '喂养/饮食' }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '食物饮食', exact: true }).click()
  await page.getByRole('dialog', { name: '喂养/饮食' }).getByRole('radio', { name: '零食', exact: true }).click()
  const form = page.getByRole('dialog', { name: '喂养/饮食' })
  await expect(form.getByRole('slider', { name: '吃了多少' })).toHaveCount(0)
  await expect(form.getByRole('button', { name: '添加食物' })).toHaveCount(0)
  await form.getByRole('textbox', { name: '输入食物名称' }).fill('苹果')
  await expect(form.getByRole('button', { name: '添加食物' })).toBeVisible()
  await expect(form.locator('.diet-common-foods').getByRole('button', { name: '编辑' })).toBeVisible()
  await form.screenshot({ path: 'test-results/snack-compact-375.png' })
})

for (const width of [375, 430, 1280]) test(`supplement keeps dose and units on one line at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1280 ? 800 : 667 })
  await page.addInitScript((authToken) => {
    sessionStorage.setItem('hoooho-auth-token', authToken)
    localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'time-view-test-account' }, currentMemberId: 'child-one', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/health-events')
  await page.getByRole('button', { name: '记录补剂', exact: true }).click()
  const form = page.getByRole('dialog', { name: '记录补剂' })
  await expect(form.getByRole('button', { name: '添加补剂' })).toHaveCount(0)
  await form.getByRole('textbox', { name: '输入补剂名称' }).fill('维生素D')
  await expect(form.getByRole('button', { name: '添加补剂' })).toBeVisible()
  const doseBox = await form.getByRole('spinbutton', { name: '用量' }).boundingBox()
  const unitBox = await form.getByRole('group', { name: '单位' }).boundingBox()
  expect(doseBox && unitBox && Math.abs(doseBox.y - unitBox.y) < 36).toBeTruthy()
  const timeBox = await form.locator('.supplement-record-time-group').boundingBox()
  expect(timeBox && timeBox.height <= 72).toBeTruthy()
  await form.screenshot({ path: `test-results/supplement-compact-${width}.png` })
})
