import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'

const token = new TokenService('visit-sheet-e2e-secret', 60 * 60_000).create({ id: 'visit-test' })
test('当前成员本地整理、AI 成功/失败/重试、重新生成和离线导出', async ({ page, request }) => {
  await page.addInitScript(token => {
    sessionStorage.setItem('hoooho-auth-token', token)
    if (!localStorage.getItem('hoooho-app')) localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'visit-test' }, currentMemberId: 'child-a', members: [], profile: null }, version: 5 }))
  }, token)
  await page.goto('/visit-summary')
  await expect(page.getByRole('heading', { name: '病情数据', exact: true })).toBeVisible()
  await expect(page.getByText(/本地事实整理 · 资料截至/)).toBeVisible()
  await expect(page.getByRole('region', { name: 'AI 病情摘要', exact: true })).toHaveCount(0)
  expect((await (await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(0)
  await page.screenshot({ path: 'outputs/ai-medical-summary/iphone-se-local.png' })
  await request.get('http://127.0.0.1:4198/failure')
  await page.getByRole('button', { name: '生成 AI 病情摘要', exact: true }).click()
  await expect(page.getByRole('button', { name: '正在生成 AI 病情摘要', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '重试 AI 摘要', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'AI 病情摘要', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '导出情况单', exact: true }).click()
  const localEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '保存重点摘要（文本）', exact: true }).click()
  const localText = await readFile((await (await localEvent).path())!, 'utf8')
  expect(localText).toContain('本地事实整理')
  expect(localText).not.toContain('AI 病情摘要（固定生成快照）')
  await page.getByRole('dialog', { name: '导出情况单', exact: true }).getByRole('button', { name: '关闭导出情况单', exact: true }).click()
  await request.get('http://127.0.0.1:4198/success')
  await page.getByRole('button', { name: '重试 AI 摘要', exact: true }).click()
  const ai = page.getByRole('region', { name: 'AI 病情摘要', exact: true })
  await expect(ai).toContainText('测试替身摘要：')
  await expect(ai).toContainText('待核对信息')
  await page.reload()
  await expect(ai).toContainText('测试替身摘要：')
  await ai.scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'outputs/ai-medical-summary/iphone-se-ai-success.png' })

  const current = await (await request.get('/api/members/child-a/visit-sheet', { headers: { Authorization: `Bearer ${token}` } })).json()
  await request.get('http://127.0.0.1:4198/failure')
  await page.getByRole('button', { name: '重新生成 AI 病情摘要', exact: true }).click()
  await expect(page.getByRole('button', { name: '重试 AI 摘要', exact: true })).toBeVisible()
  await expect(ai).toContainText('测试替身摘要：')
  await expect(page.getByText(/原报告仍可阅读/)).toBeVisible()
  const after = await (await request.get('/api/members/child-a/visit-sheet', { headers: { Authorization: `Bearer ${token}` } })).json()
  expect(after.report).toEqual(current.report)
  await page.getByRole('button', { name: '重试 AI 摘要', exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: 'outputs/ai-medical-summary/iphone-se-ai-failure.png' })

  await page.getByRole('button', { name: '导出情况单', exact: true }).click()
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '保存重点摘要（文本）', exact: true }).click()
  const download = await downloadEvent
  const text = await readFile((await download.path())!, 'utf8')
  expect(text).toContain('测试替身摘要：')
  expect(text).toContain('本地事实整理')
  await page.getByRole('dialog', { name: '导出情况单', exact: true }).getByRole('button', { name: '关闭导出情况单', exact: true }).click()
  await request.get('http://127.0.0.1:4198/success')
  await page.getByRole('button', { name: '重试 AI 摘要', exact: true }).click()
  await expect(ai).toContainText('测试替身摘要：')
  const regenerated = await (await request.get('/api/members/child-a/visit-sheet', { headers: { Authorization: `Bearer ${token}` } })).json()
  expect(regenerated.report.aiSummary.generatedAt).not.toBe(current.report.aiSummary.generatedAt)
  expect(regenerated.report.version).toBeGreaterThan(current.report.version)
  expect((await (await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(4)
  for (const width of [320, 375, 390, 430, 1280]) {
    await page.setViewportSize({ width, height: width === 320 ? 568 : 800 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 320, height: 568 })
  await page.getByRole('button', { name: '导出情况单', exact: true }).click()
  const htmlEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '保存完整离线报告（HTML）', exact: true }).click()
  const htmlDownload = await htmlEvent
  const html = await readFile((await htmlDownload.path())!, 'utf8')
  expect(html).toContain('测试替身摘要：')
  expect(html).toContain('固定快照')
  expect(html).not.toContain('fixture-only-not-a-real-key')
  await page.screenshot({ path: 'outputs/ai-medical-summary/iphone-se-export.png' })
  await page.getByRole('dialog', { name: '导出情况单', exact: true }).getByRole('button', { name: '关闭导出情况单', exact: true }).click()
  await page.evaluate(() => {
    const stored = JSON.parse(localStorage.getItem('hoooho-app')!)
    stored.state.currentMemberId = 'empty-child'
    localStorage.setItem('hoooho-app', JSON.stringify(stored))
  })
  await page.reload()
  await expect(page.getByRole('region', { name: 'AI 病情摘要', exact: true })).toHaveCount(0)
  await expect(page.getByText('当前孩子尚无已保存资料。', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '生成 AI 病情摘要', exact: true })).toHaveCount(0)
  expect((await (await request.get('http://127.0.0.1:4198/status')).json()).calls).toBe(4)
})
