import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { TokenService } from '../../server/auth/token-service.mjs';
const token = new TokenService('visit-sheet-e2e-secret', 3600000).create({ id: 'visit-test' }), headers = { Authorization: 'Bearer ' + token };
test('当前成员整理、模型成功失败重试、确认不重复调用和当前版导出', async ({ page, request }, info) => {
    const status = async () => (await (await request.get('http://127.0.0.1:4198/status')).json()).calls, before = await status(), read = async () => (await (await request.get('/api/members/child-a/visit-sheet', { headers })).json()).report;
    await page.addInitScript(token => { sessionStorage.setItem('hoooho-auth-token', token); if (!localStorage.getItem('hoooho-app')) localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: 'visit-test' }, currentMemberId: 'child-a', members: [], profile: null }, version: 5 })); }, token);
    await page.goto('/visit-summary');
    await expect(page.locator('#chapter-overview h1')).toBeVisible();
    const open = async () => { await page.getByRole('button', { name: '更新情况单', exact: true }).click(); return page.getByRole('dialog', { name: '更新情况单', exact: true }); };
    const local = await open();
    await local.getByRole('button', { name: '整理并查看草稿' }).click();
    await local.getByRole('button', { name: '确认替换情况单' }).click();
    await expect(local).toHaveCount(0);
    expect(await status() - before).toBe(0);
    const initial = await read();
    await request.get('http://127.0.0.1:4198/failure');
    const d = await open();
    await d.getByRole('checkbox', { name: /使用现有 AI/ }).check();
    await d.getByRole('button', { name: '整理并查看草稿' }).click();
    await expect(d.getByRole('alert')).toBeVisible();
    if (info.config.metadata.provider === 'bailian')
        await expect(d.getByRole('alert')).toContainText('百炼免费额度已用尽');
    expect((await read()).version).toBe(initial.version);
    await request.get('http://127.0.0.1:4198/success');
    await d.getByRole('button', { name: '整理并查看草稿' }).click();
    await expect(d.getByRole('button', { name: '确认替换情况单' })).toBeVisible();
    expect((await read()).aiSummary).toBe(initial.aiSummary);
    await d.getByRole('button', { name: '确认替换情况单' }).click();
    await expect(d).toHaveCount(0);
    const current = await read();
    expect(current.aiSummary.provider).toBe(info.config.metadata.provider === 'bailian' ? 'bailian' : 'openai');
    expect(current.aiSummary.overview).toContain('测试替身摘要：');
    expect(await status() - before).toBe(2);
    await page.reload();
    await expect(page.locator('#chapter-overview h1')).toBeVisible();
    expect((await read()).aiSummary).toEqual(current.aiSummary);
    await request.get('http://127.0.0.1:4198/failure');
    await open();
    await d.getByRole('checkbox', { name: /使用现有 AI/ }).check();
    await d.getByRole('button', { name: '整理并查看草稿' }).click();
    await expect(d.getByRole('alert')).toBeVisible();
    expect(await read()).toEqual(current);
    await page.screenshot({ path: info.outputPath('ai-failed-old-confirmed-kept.png') });
    await d.getByRole('button', { name: '返回更新情况单' }).click();
    await page.getByRole('button', { name: '导出情况单', exact: true }).click();
    const exports = page.getByRole('dialog', { name: '导出情况单' }), download = page.waitForEvent('download');
    await exports.getByRole('button', { name: '保存重点摘要（文本）' }).click();
    const text = await readFile((await (await download).path())!, 'utf8');
    expect(text).toContain('测试替身摘要：');
    expect(text).toContain('本地事实整理');
    await exports.getByRole('button', { name: '返回导出情况单' }).click();
    await request.get('http://127.0.0.1:4198/success');
    await open();
    await d.getByRole('button', { name: '整理并查看草稿' }).click();
    await d.getByRole('button', { name: '确认替换情况单' }).click();
    await expect(d).toHaveCount(0);
    const after = await read();
    expect(after.aiSummary.generatedAt).not.toBe(current.aiSummary.generatedAt);
    expect(after.version).toBeGreaterThan(current.version);
    expect(await status() - before).toBe(4);
    for (const width of [320, 375, 393, 430, 1280]) {
        await page.setViewportSize({ width, height: 852 });
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    }
    await page.getByRole('button', { name: '导出情况单', exact: true }).click();
    const htmlDownload = page.waitForEvent('download');
    await exports.getByRole('button', { name: '保存离线情况单（HTML）' }).click();
    const html = await readFile((await (await htmlDownload).path())!, 'utf8');
    expect(html).toContain('测试替身摘要：');
    expect(html).toContain('固定快照');
    expect(html).not.toContain('fixture-only-not-a-real-key');
    await exports.getByRole('button', { name: '返回导出情况单' }).click();
    await page.evaluate(() => { const data = JSON.parse(localStorage.getItem('hoooho-app')!); data.state.currentMemberId = 'empty-child'; localStorage.setItem('hoooho-app', JSON.stringify(data)); });
    await page.reload();
    await expect(page.locator('.visit-reading-person')).toContainText('空资料（虚构）');
    await expect(page.getByRole('region', { name: 'AI 病情摘要', exact: true })).toHaveCount(0);
    expect(await status() - before).toBe(4);
});
