import { ArrowLeft, ChevronRight, Utensils } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react'
import { useBlocker, useNavigate } from 'react-router-dom'
import { Avatar } from '../../components/common'
import { HohoButton } from '../../components/design-system'
import { useCurrentMember } from '../../hooks/useCurrentMember'
import { desensitizationTestService, type FrequentFoodSuggestion } from '../../services/desensitizationTests'
import { useAppStore } from '../../store/useAppStore'
import './desensitization.css'

const knownCategories: Array<[RegExp,string]> = [[/^(牛肉|牛肉泥|炖牛肉)$/,'牛肉类'],[/^(牛奶|纯牛奶|全脂牛奶|酸奶|奶酪)$/,'牛奶类'],[/^(鸡蛋|蛋黄|蛋白|鸡蛋黄|鸡蛋白)$/,'鸡蛋类'],[/^(小麦|小麦粉)$/,'小麦类'],[/^(花生|花生酱)$/,'花生类'],[/^(大豆|黄豆|豆浆|豆腐)$/,'大豆类']]

export function DesensitizationTestNewPage() {
  const navigate = useNavigate(), member = useCurrentMember(), token = useAppStore((state) => state.authToken) ?? ''
  const [name,setName]=useState(''), [suggestions,setSuggestions]=useState<FrequentFoodSuggestion[]>([]), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState(''), [scopeOpen,setScopeOpen]=useState(false)
  const allowLeave=useRef(false), dirty=Boolean(name.trim())
  const blocker=useBlocker(dirty&&!allowLeave.current&&!saving)
  useEffect(()=>{ const controller=new AbortController(); setLoading(true); desensitizationTestService.list(member.id,token,controller.signal).then((data)=>setSuggestions(data.suggestions)).catch(()=>setError('常吃食物暂时没有加载，不影响手动填写')).finally(()=>setLoading(false)); return()=>controller.abort() },[member.id,token])
  useEffect(()=>{ const before=(event:BeforeUnloadEvent)=>{ if(!dirty||allowLeave.current)return; event.preventDefault(); event.returnValue='' }; window.addEventListener('beforeunload',before); return()=>window.removeEventListener('beforeunload',before) },[dirty])
  const normalized=name.trim(), category=useMemo(()=>knownCategories.find(([rule])=>rule.test(normalized))?.[1]??'',[normalized])
  const leave=()=>{ if(dirty&&!window.confirm('还没有开始观察，离开后已填写的名称不会保存。'))return; allowLeave.current=true; navigate('/nurse-station',{replace:true}) }
  const save=async(event:FormEvent)=>{ event.preventDefault(); if(!normalized)return setError('请输入食物名称'); if(normalized==='牛')return setError('请先选择牛肉或牛奶'); if(saving)return; setSaving(true);setError('');try{const result=await desensitizationTestService.create(member.id,normalized,token);let task=result.task,notice=result.existing?'已打开已有观察':'已开始观察';if(task.status==='archived'){const restore=window.confirm(`已经有一项“${task.displayName}”观察在归档中。要恢复继续记录吗？`);if(restore){task=await desensitizationTestService.restore(task.id,task.version,token);notice='已恢复已有观察'}else notice='已有观察保留在归档中'}allowLeave.current=true;navigate(`/nurse-station?desensitization=${encodeURIComponent(task.id)}`,{replace:true,state:{desensitizationNotice:notice}})}catch(value){setError(value instanceof Error?value.message:'保存没有完成，已填写的内容仍在，请重试')}finally{setSaving(false)}}
  return <main className="app-shell desensitization-new-page"><header className="desensitization-new-header"><button aria-label="返回护士站" onClick={leave} type="button"><ArrowLeft/></button><h1>新增排敏测试</h1><span/></header><form onSubmit={save}><section className="desensitization-member"><Avatar name={member.name} size="md" src={member.avatar}/><span><small>当前孩子</small><strong>{member.name}</strong></span></section><section className="desensitization-new-main"><Utensils aria-hidden="true"/><h2>想观察哪种食物？</h2><p>只填名称即可开始，记录会和这个孩子的健康随记保持关联。</p><label><span>食物名称</span><input aria-describedby="desensitization-category" autoFocus maxLength={30} onChange={(event)=>{setName(event.target.value);setError('');setScopeOpen(false)}} placeholder="输入食物名称，如牛肉" value={name}/></label>{normalized==='牛'?<div className="desensitization-disambiguation"><span>你指的是？</span><button onClick={()=>setName('牛肉')} type="button">牛肉</button><button onClick={()=>setName('牛奶')} type="button">牛奶</button></div>:<button className="desensitization-category-preview" disabled={!category} id="desensitization-category" onClick={()=>setScopeOpen((value)=>!value)} type="button">{category?<>自动归入{category} · 查看范围<ChevronRight/></>:normalized?'暂按这个食物单独观察，相关成分待核实':'名称明确后会显示归类范围'}</button>}{scopeOpen&&category&&<div className="desensitization-inline-scope"><strong>{category}的关联原则</strong><p>明确记录为该食物的随记会自动关联；复合食品或配料不明的记录需要核对，不会据名称猜测成分。</p></div>}{!loading&&suggestions.length>0&&<div className="desensitization-frequent"><span>近30天常吃</span><div>{suggestions.map((item)=><button aria-pressed={normalized===item.name} key={item.name} onClick={()=>{setName(item.name);setError('')}} type="button">{item.name}</button>)}</div><small>来自健康随记中至少3次的实际摄入记录</small></div>}{error&&<p className="desensitization-form-error" role="alert">{error}</p>}</section><footer><HohoButton disabled={saving||!normalized} fullWidth size="large" type="submit">{saving?'正在开始…':'开始观察'}</HohoButton></footer></form>{blocker.state==='blocked'&&<div className="desensitization-leave-layer" role="presentation"><section aria-modal="true" role="dialog" aria-label="离开新增排敏测试"><h2>保留当前填写？</h2><p>这个页面还没有保存。继续离开会丢失食物名称。</p><div><button onClick={()=>blocker.reset()} type="button">继续填写</button><button onClick={()=>{allowLeave.current=true;blocker.proceed()}} type="button">离开</button></div></section></div>}</main>
}
