import { ArrowLeft, Bell, Camera, Check, ChevronDown, Clock3, Pause, Pill, RotateCcw, SkipForward, X } from 'lucide-react'
import { useMemo, useRef, useState } from 'react'
import type { MedicationReminderPlan, NurseStationItem } from '../../features/nurse-station/state'
import { HohoButton } from '../../components/design-system'
import { atLocal, clock, formatOccurrence, localDate, nextOccurrences, planLabel, routeLabel } from './medicationReminderLogic'

type Draft = Omit<MedicationReminderPlan, 'nextOccurrenceAt' | 'occurrenceKey' | 'confirmedOccurrenceKeys' | 'timezone'>
const typeOptions = [['drops', '滴剂', '滴'], ['syrup', '糖浆', 'mL'], ['tablet', '片剂', '片'], ['spray', '喷雾剂', '喷'], ['ointment', '软膏', '次'], ['other', '其他', '']] as const
const routes = [['oral', '口服'], ['topical', '外用'], ['inhaled', '吸入'], ['nasal', '鼻用'], ['ophthalmic', '眼用'], ['other', '其他']] as const
const blank = (): Draft => ({ medicationName: '', medicationType: 'drops', amount: 5, unit: '滴', route: 'oral', mode: 'daily', times: ['08:00', '20:00'], startDate: localDate(), durationDays: 5, reminderTargets: ['我'] })

export function MedicationReminderFlow({ memberName, initial, onClose, onSave }: { memberName: string; initial?: NurseStationItem; onClose: () => void; onSave: (plan: MedicationReminderPlan) => void }) {
  const [step, setStep] = useState(initial ? 2 : 1)
  const [draft, setDraft] = useState<Draft>(() => initial?.medicationPlan ? { ...initial.medicationPlan } : blank())
  const [error, setError] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const upcoming = useMemo(() => nextOccurrences(draft, new Date(), 3), [draft])
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => { setDraft((value0) => ({ ...value0, [key]: value })); setError('') }
  const next = () => {
    if (step === 1 && (!draft.medicationName.trim() || !(draft.amount > 0) || !draft.unit.trim())) return setError('请完整填写药品名称和每次用量')
    if (step === 2 && !upcoming.length) return setError('当前设置没有可用的下一次提醒时间')
    setStep((value) => Math.min(3, value + 1))
  }
  const save = () => {
    const first = upcoming[0]
    if (!first) return setError('请设置有效的提醒时间')
    onSave({ ...draft, medicationName: draft.medicationName.trim(), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, nextOccurrenceAt: first.toISOString(), occurrenceKey: first.toISOString(), confirmedOccurrenceKeys: initial?.medicationPlan?.confirmedOccurrenceKeys ?? [] })
  }
  const summary = draft.mode === 'daily' ? `从${draft.startDate === localDate() ? '今天' : draft.startDate}开始，每天${draft.times.join('、')}提醒；每次${draft.amount}${draft.unit}，${routeLabel(draft.route)}，${draft.longTerm ? '长期' : `持续${draft.durationDays}天`}。` : draft.mode === 'interval' ? `从${draft.startDate} ${draft.times[0]}开始，每${draft.intervalHours}小时提醒；每次${draft.amount}${draft.unit}，${routeLabel(draft.route)}。` : `${draft.startDate} ${draft.times[0]}提醒一次；每次${draft.amount}${draft.unit}，${routeLabel(draft.route)}。`
  return <div className="med-reminder-layer"><section aria-label={initial ? '调整用药提醒' : '新增用药提醒'} aria-modal="true" className="med-reminder-flow" role="dialog">
    <header><button aria-label="返回" onClick={step === 1 ? onClose : () => setStep(step - 1)} type="button"><ArrowLeft /></button><h1>{initial ? '调整用药提醒' : step === 1 ? '药品和每次用量' : step === 2 ? '提醒规律' : '确认提醒'}</h1><span>{step}/3</span></header>
    <div className="med-reminder-body">
      {step === 1 && <><div className="med-member-strip"><Pill /><span><strong>为{memberName}设置</strong><small>请按药袋、处方或医生交代填写</small></span></div><label className="med-field"><span>药品名称</span><div><input aria-label="药品名称" onChange={(e) => update('medicationName', e.target.value)} placeholder="搜索已有药品或手动输入" value={draft.medicationName}/><button aria-label="拍照或上传药品图片" onClick={() => fileRef.current?.click()} type="button"><Camera /></button></div></label><input ref={fileRef} accept="image/*" hidden type="file"/><div className="med-recent"><span>最近使用</span>{['西替利嗪滴剂','布洛芬混悬液'].map(x=><button key={x} onClick={()=>update('medicationName',x)} type="button">{x}</button>)}</div><fieldset><legend>药品类型</legend><div className="med-choice-grid med-type-grid">{typeOptions.map(([value,label,unit])=><button aria-pressed={draft.medicationType===value} key={value} onClick={()=>{update('medicationType',value);update('unit',unit)}} type="button">{label}</button>)}</div></fieldset><div className="med-dose-row"><label><span>每次用量</span><input aria-label="每次用量" inputMode="decimal" min="0" onChange={e=>update('amount',Number(e.target.value))} type="number" value={draft.amount}/></label><label><span>剂量单位</span><input aria-label="剂量单位" disabled={draft.medicationType!=='other'} onChange={e=>update('unit',e.target.value)} value={draft.unit}/></label></div><fieldset><legend>使用方式</legend><div className="med-choice-grid">{routes.map(([value,label])=><button aria-pressed={draft.route===value} key={value} onClick={()=>update('route',value)} type="button">{label}</button>)}</div></fieldset></>}
      {step === 2 && <><div className="med-plan-summary"><Pill/><span><strong>{draft.medicationName}</strong><small>每次{draft.amount}{draft.unit} · {routeLabel(draft.route)}</small></span></div><fieldset><legend>提醒方式</legend><div className="med-mode-grid">{([['daily','每天固定时间'],['interval','每隔一段时间'],['once','仅提醒一次']] as const).map(([value,label])=><button aria-pressed={draft.mode===value} key={value} onClick={()=>{update('mode',value); if(value==='once') update('times',[draft.times[0]||'20:00'])}} type="button">{label}</button>)}</div></fieldset>{draft.mode==='daily'&&<label className="med-field"><span>提醒时间</span><div className="med-times">{draft.times.map((time,index)=><input aria-label={`第${index+1}次提醒时间`} key={index} onChange={e=>update('times',draft.times.map((x,i)=>i===index?e.target.value:x))} type="time" value={time}/>)}<button onClick={()=>update('times',[...draft.times,clock(new Date(Date.now()+3600000))])} type="button">+ 添加</button></div></label>}{draft.mode==='interval'&&<div className="med-dose-row"><label><span>间隔小时数</span><input aria-label="间隔小时数" min="1" onChange={e=>update('intervalHours',Number(e.target.value))} type="number" value={draft.intervalHours??6}/></label><label><span>首次提醒</span><input aria-label="首次提醒时间" onChange={e=>update('times',[e.target.value])} type="time" value={draft.times[0]}/></label></div>}{draft.mode==='once'&&<div className="med-dose-row"><label><span>提醒日期</span><input aria-label="提醒日期" min={localDate()} onChange={e=>update('startDate',e.target.value)} type="date" value={draft.startDate}/></label><label><span>提醒时间</span><input aria-label="提醒时间" onChange={e=>update('times',[e.target.value])} type="time" value={draft.times[0]}/></label></div>}{draft.mode!=='once'&&<><label className="med-field"><span>开始日期</span><input min={localDate()} onChange={e=>update('startDate',e.target.value)} type="date" value={draft.startDate}/></label><fieldset><legend>持续时间</legend><div className="med-choice-grid">{[3,5,7].map(days=><button aria-pressed={!draft.longTerm&&draft.durationDays===days} key={days} onClick={()=>{update('durationDays',days);update('longTerm',false)}} type="button">{days}天</button>)}<button aria-pressed={draft.longTerm} onClick={()=>update('longTerm',true)} type="button">长期</button><button aria-pressed={Boolean(draft.endDate)} onClick={()=>{update('longTerm',false);update('endDate',draft.endDate||localDate(new Date(Date.now()+7*86400000)))}} type="button">自定义</button></div>{draft.endDate&&<input aria-label="结束日期" min={draft.startDate} onChange={e=>update('endDate',e.target.value)} type="date" value={draft.endDate}/>}</fieldset></>}<label className="med-field"><span>提醒对象</span><select aria-label="提醒对象" value={draft.reminderTargets[0]} onChange={e=>update('reminderTargets',[e.target.value])}><option>我</option><option>所有照护者</option></select></label><p className="med-care-note">一位照护者确认已服用后，同一次提醒会同步完成。</p></>}
      {step === 3 && <><div className="med-confirm-member"><span>{memberName}</span><small>当前人物</small></div><section className="med-confirm-card"><strong>{draft.medicationName}</strong><p>{summary}</p><div><span>每次{draft.amount}{draft.unit}</span><span>{routeLabel(draft.route)}</span><span>{planLabel({ ...draft } as MedicationReminderPlan)}</span></div></section><section className="med-upcoming"><h2>接下来三次</h2>{upcoming.map((date,index)=><p key={date.toISOString()}><span>{index+1}</span><strong>{formatOccurrence(date.toISOString())}</strong></p>)}</section><div className="med-reminder-target"><Bell/><span><strong>提醒{draft.reminderTargets.join('、')}</strong><small>通知权限未开启时会在列表提示</small></span></div></>}
      {error&&<p className="med-reminder-error" role="alert">{error}</p>}
    </div><footer><HohoButton fullWidth onClick={step===3?save:next} size="large">{step===1?'下一步：设置规律':step===2?'下一步：确认':'确认并开启提醒'}</HohoButton></footer>
  </section></div>
}

export function MedicationActionSheet({ item, onClose, onAction }: { item: NurseStationItem; onClose:()=>void; onAction:(action:'taken'|'snooze'|'skip'|'adjust'|'cancel_snooze'|'pause'|'resume'|'end', detail?:string)=>void }) {
  const plan=item.medicationPlan!; const [screen,setScreen]=useState<'actions'|'skip'|'adjust'>('actions'); const [reason,setReason]=useState('')
  return <div className="med-action-layer" role="dialog" aria-modal="true" aria-label={screen==='skip'?'跳过本次':screen==='adjust'?'调整计划':'用药提醒'}><section className="med-action-sheet"><button aria-label="关闭" className="med-action-close" onClick={onClose} type="button"><X/></button>{screen==='actions'&&<><i/><h2>{item.status==='paused'?'提醒已暂停':item.status==='ended'?'计划已结束':'这次用药怎么样？'}</h2><div className="med-action-drug"><Pill/><span><strong>{plan.medicationName} · {plan.amount}{plan.unit}</strong><small>计划时间 {clock(new Date(plan.originalOccurrenceAt??plan.nextOccurrenceAt))}</small></span></div>{item.status==='paused'?<HohoButton fullWidth onClick={()=>onAction('resume')}>恢复提醒</HohoButton>:item.status==='ended'?null:item.status==='snoozed'?<div className="med-action-grid"><button onClick={()=>onAction('taken')} type="button"><Check/>现在已服用</button><button onClick={()=>onAction('cancel_snooze')} type="button"><X/>取消推迟</button></div>:<div className="med-action-grid"><button onClick={()=>onAction('taken')} type="button"><Check/>已服用</button><button onClick={()=>onAction('snooze')} type="button"><Clock3/>10分钟后提醒</button><button onClick={()=>setScreen('skip')} type="button"><SkipForward/>跳过本次</button><button onClick={()=>setScreen('adjust')} type="button"><RotateCcw/>调整计划</button></div>}</>}{screen==='skip'&&<><h2>跳过本次</h2><p>原因选填，后续提醒保持不变。</p>{['医生临时调整','孩子已睡或暂时不方便','药品不在身边','其他原因'].map(x=><label className="med-reason" key={x}><input checked={reason===x} name="reason" onChange={()=>setReason(x)} type="radio"/>{x}</label>)}<HohoButton fullWidth onClick={()=>onAction('skip',reason)}>确认跳过本次</HohoButton></>}{screen==='adjust'&&<><h2>调整用药计划</h2><button className="med-adjust-option" onClick={()=>onAction('adjust')} type="button">只修改本次提醒<small>不影响明天及之后的计划</small></button><button className="med-adjust-option" onClick={()=>onAction('adjust','future')} type="button">修改后续计划<small>从下一次提醒开始生效</small></button><button className="med-adjust-option" onClick={()=>onAction('pause')} type="button"><Pause/>暂停提醒<small>保留计划和历史记录</small></button><button className="med-adjust-option" onClick={()=>onAction('end')} type="button">提前结束计划<small>停止后续提醒，保留已有记录</small></button></>}</section></div>
}
