import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const styles = readFileSync(new URL('./nurseStation.css', import.meta.url), 'utf8')
const source = readFileSync(new URL('./index.tsx', import.meta.url), 'utf8')
const taskSource = readFileSync(new URL('./GuardianTaskListPage.tsx', import.meta.url), 'utf8')
const taskStyles = readFileSync(new URL('./guardianTasks.css', import.meta.url), 'utf8')

test('顶部白卡保留人物信息和真实视频并在底部加入三项成长摘要', () => {
  assert.match(source, /className="nurse-station-hero"/)
  assert.match(source, /<NurseStationFactTypewriter \/>/)
  assert.match(source, /<NurseTriageDesk/)
  assert.match(styles, /\.nurse-station-hero\s*\{[^}]*height:\s*202px[^}]*grid-template-rows:\s*minmax\(0, 1fr\) 64px[^}]*border:\s*1px solid #dcedea[^}]*border-radius:\s*19px[^}]*background:\s*#fff/)
  assert.match(styles, /\.nurse-station-guarded\s*\{[^}]*margin-top:\s*8px/)
  assert.match(styles, /\.nurse-station-fact\s*\{[^}]*height:\s*36px[^}]*margin-top:\s*4px[^}]*overflow:\s*hidden/)
  assert.match(styles, /\.nurse-station-fact\s*>\s*span\s*\{[^}]*white-space:\s*nowrap/)
  assert.match(styles, /\.nurse-station-visual\s*\{[^}]*height:\s*114px[^}]*background:\s*#fff/)
  assert.match(styles, /\.nurse-station-growth-data\s*\{[^}]*grid-template-columns:\s*repeat\(3,/)
  assert.match(source, /查看\$\{member\.name\}的成长数据/)
  assert.match(source, /身高，\$\{growthValue/)
  assert.match(source, /血型，\$\{formatBloodTypeDisplay/)
  assert.match(source, /setBloodEditorMemberId\(member\.id\)/)
  assert.doesNotMatch(styles, /\.nurse-station-visual\s*\{[^}]*(?:gradient|mask-image)/)
  assert.doesNotMatch(source, /今天想让我们帮你做什么|容易忘、需要持续观察/)
})

test('首页六入口使用等高双列卡片和独立图文层', () => {
  assert.match(styles, /\.nurse-home-entries\s*\{[^}]*grid-template-columns:\s*repeat\(2,[^}]*gap:\s*10px/)
  assert.match(styles, /\.nurse-home-entry\s*\{[^}]*height:\s*88px[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*58px/)
  assert.match(styles, /\.nurse-home-entry__copy strong\s*\{[^}]*font-size:\s*14px[^}]*font-weight:\s*500/)
  assert.match(styles, /\.nurse-home-entry__copy small\s*\{[^}]*font-size:\s*11px[^}]*line-height:\s*16px/)
  assert.match(styles, /\.nurse-home-entry__visual img\s*\{[^}]*object-fit:\s*contain/)
  assert.match(source, /健康随记.*记录日常与身体变化.*healthDiaryImage.*\/health-events/)
  assert.match(source, /健康档案.*整理家人的健康信息.*healthProfileImage.*\/health-profile/)
  assert.match(source, /就诊情况单.*就诊前，一页理清病情.*visitSummaryImage.*\/visit-summary/)
  assert.match(source, /忌口出示卡.*哪些不能吃，出示就懂.*dietaryCardImage/)
  assert.match(source, /title: '用药提醒'[\s\S]*medicationRemindersImage[\s\S]*\/medication-reminders/)
  assert.match(source, /title: '排敏测试'[\s\S]*desensitizationTestsImage[\s\S]*\/desensitization-tests/)
  assert.match(source, /`\$\{count\} 个\$\{noun\}任务`/)
  assert.match(source, /<Link aria-label=\{`\$\{entry\.title\}，\$\{entry\.subtitle\}`\}/)
  assert.match(source, /<img alt=""[^>]*onError=/)
  assert.doesNotMatch(source, /健康事件记录|更多服务|过敏出示|能不能吃|附近就医/)
  assert.doesNotMatch(source, /nurse-primary-entries|nurse-more-services/)
})

test('任务管理迁移到两个独立二级页并常驻进行中与已归档', () => {
  assert.match(taskStyles, /\.guardian-task-page__tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,/)
  assert.match(taskSource, /role="tablist"/)
  assert.match(taskSource, /进行中/)
  assert.match(taskSource, /已归档/)
  assert.match(taskSource, /管理.*左滑卡片/)
  assert.match(taskSource, /export function MedicationReminderListPage/)
  assert.match(taskSource, /export function DesensitizationTestListPage/)
  assert.doesNotMatch(source, /guardian-tasks|guardian-task-tabs|新增提醒|新增测试/)
})

test('任务卡展示真实下次时间、可换行标题和可读详情', () => {
  const medicationCard = readFileSync(new URL('./MedicationReminderCard.tsx', import.meta.url), 'utf8')
  assert.match(medicationCard, /下次：\{archived[\s\S]*formatReminderOccurrence/)
  assert.match(medicationCard, /疗程：/)
  assert.match(medicationCard, /用法：/)
  assert.match(medicationCard, /今日：/)
  assert.match(medicationCard, /medication-course-card__week/)
  assert.match(medicationCard, /task-management__trigger/)
})
