import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const styles = readFileSync(new URL('./nurseStation.css', import.meta.url), 'utf8')
const source = readFileSync(new URL('./index.tsx', import.meta.url), 'utf8')
const taskSource = readFileSync(new URL('./GuardianTaskListPage.tsx', import.meta.url), 'utf8')
const taskStyles = readFileSync(new URL('./guardianTasks.css', import.meta.url), 'utf8')

test('紧凑人物资料保留头像和成长操作，护士素材传入新模块', () => {
  assert.match(source, /className="nurse-station-hero nurse-station-hero--compact"/)
  assert.match(source, /<Avatar name=\{member.name\} src=\{member.avatar\} size="lg"/)
  assert.match(source, /<HomeFlows[^>]*nurseVisual=\{<NurseTriageDesk/)
  assert.match(source, /<NurseTriageDesk/)
  assert.doesNotMatch(source, /<NurseStationFactTypewriter \/>/)
  assert.match(styles, /\.nurse-station-hero--compact\s*\{[^}]*min-height:\s*0[^}]*grid-template-rows:\s*minmax\(68px, auto\) minmax\(54px, auto\)/)
  assert.match(styles, /\.nurse-station-guarded\s*\{[^}]*margin-left:\s*51px[^}]*font-size:\s*12\.5px[^}]*white-space:\s*nowrap[^}]*font-variant-numeric:\s*tabular-nums/)
  assert.match(styles, /\.nurse-station-guarded strong\s*\{[^}]*color:\s*rgb\(var\(--hoho-color-primary\)\)[^}]*font-size:\s*inherit/)
  assert.match(styles, /\.nurse-station-visual\s*\{[^}]*height:\s*104px[^}]*background:\s*#fff/)
  assert.match(styles, /\.nurse-station-growth-data\s*\{[^}]*grid-template-columns:\s*repeat\(3,/)
  assert.match(styles, /\.nurse-station-hero--compact \.nurse-station-growth-data > button\s*\{[^}]*min-height:\s*53px/)
  assert.match(styles, /\.nurse-station-growth-data > button:not\(:last-child\)\s*\{[^}]*border-right:\s*1px solid #d6e8e3/)
  assert.match(source, /选择孩子，当前\$\{member\.name\}/)
  assert.match(source, /openGrowthData\('height'\)/)
  assert.match(source, /openGrowthData\('weight'\)/)
  assert.match(source, /state: \{ selectedMeasure, returnTo:/)
  assert.doesNotMatch(source, /<GrowthDate|测于/)
  const growthPage = readFileSync(new URL('../HealthProfile/BasicHealthProfilePage.tsx', import.meta.url), 'utf8')
  assert.match(growthPage, /savedDate=\{savedGrowth\.heightMeasuredAt\}/)
  assert.match(growthPage, /savedDate=\{savedGrowth\.weightMeasuredAt\}/)
  assert.match(growthPage, /growth-step-card__heading[\s\S]*<time dateTime=\{savedDate\}/)
  assert.match(source, /身高，\$\{growthValue/)
  assert.match(source, /血型，\$\{formatAboBloodType/)
  assert.match(source, /className="nurse-station-blood-type"/)
  assert.match(styles, /\.nurse-station-hero--compact \.nurse-station-growth-data \.nurse-station-blood-type > span\s*\{[^}]*flex-direction:\s*row/)
  assert.match(source, /setBloodEditorMemberId\(member\.id\)/)
  assert.doesNotMatch(source, /nurse-station-allergy-index|useFoodAllergyIndex|食物过敏记录指数/)
  assert.doesNotMatch(styles, /\.nurse-station-allergy-index/)
  assert.doesNotMatch(styles, /\.nurse-station-visual\s*\{[^}]*(?:gradient|mask-image)/)
  assert.doesNotMatch(source, /今天想让我们帮你做什么|容易忘、需要持续观察/)
})

test('首页信息板与三个单列入口，快速查找进入顶栏', () => {
  const flows = readFileSync(new URL('./HomeFlows.tsx', import.meta.url), 'utf8')
  const flowStyles = readFileSync(new URL('./HomeFlows.css', import.meta.url), 'utf8')
  const drawer = readFileSync(new URL('../../components/navigation/SideDrawer.tsx', import.meta.url), 'utf8')
  assert.equal((flows.match(/<HealthCard /g) ?? []).length, 3)
  for(const title of ['正在跟进','健康随记','准备和医生说清楚']) assert.ok(flows.includes(title))
  assert.doesNotMatch(flows, /aria-label="快速查找"/)
  assert.ok(flows.indexOf('aria-label="正在跟进"') < flows.indexOf('aria-label="健康随记"'))
  assert.match(source, /action=\{quickSearchAction\} showInstallApp=\{false\}/)
  assert.match(source, /navigate\('\/quick-search'\)/)
  assert.match(flowStyles, /\.home-flows\{display:grid;gap:/)
  assert.doesNotMatch(source, /HomeEntries|fixedHomeEntries|nurse-home-entry/)
  assert.match(flows, /<time dateTime=/)
  assert.match(flows, /navigate\('\/visit-summary'\)/)
  for(const route of ['/health-events','/health-profile','/food-label','/dietary-card','/medication-reminders']) assert.ok(drawer.includes(route))
})

test('任务管理迁移到两个独立二级页并常驻进行中与已归档', () => {
  assert.match(taskStyles, /\.guardian-task-page__tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,/)
  assert.match(taskSource, /role="tablist"/)
  assert.match(taskSource, /进行中/)
  assert.match(taskSource, /已归档/)
  assert.match(taskSource, /管理.*左滑卡片/)
  assert.match(taskSource, /export function MedicationReminderListPage/)
  assert.match(taskSource, /export function DesensitizationTestListPage/)
  assert.doesNotMatch(source, /guardian-tasks|guardian-task-tabs|新增提醒|新增测试/)
})

test('任务卡展示真实下次时间、可换行标题和可读详情', () => {
  const medicationCard = readFileSync(new URL('./MedicationReminderCard.tsx', import.meta.url), 'utf8')
  assert.match(medicationCard, /下次：\{archived[\s\S]*formatReminderOccurrence/)
  assert.match(medicationCard, /疗程：/)
  assert.match(medicationCard, /用法：/)
  assert.match(medicationCard, /今日计划：/)
  assert.match(medicationCard, /medication-course-card__week/)
  assert.match(medicationCard, /task-management__trigger/)
})
