import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const styles = readFileSync(new URL('./nurseStation.css', import.meta.url), 'utf8')
const source = readFileSync(new URL('./index.tsx', import.meta.url), 'utf8')
const taskSource = readFileSync(new URL('./GuardianTaskListPage.tsx', import.meta.url), 'utf8')
const taskStyles = readFileSync(new URL('./guardianTasks.css', import.meta.url), 'utf8')

test('紧凑人物资料保留头像和成长操作，护士素材传入新模块', () => {
  assert.match(source, /className="nurse-station-hero nurse-station-hero--compact"/)
  assert.match(source, /<Avatar name=\{member.name\} src=\{member.avatar\} size="lg"/)
  assert.match(source, /<HomeNurseDialogue[^>]*nurseVisual=\{<NurseTriageDesk/)
  assert.match(source, /<NurseTriageDesk/)
  assert.doesNotMatch(source, /<NurseStationFactTypewriter \/>/)
  assert.match(styles, /\.nurse-station-hero--compact\s*\{[^}]*min-height:\s*0[^}]*grid-template-rows:\s*minmax\(68px, auto\) minmax\(54px, auto\)/)
  assert.match(styles, /\.nurse-station-guarded\s*\{[^}]*margin-left:\s*51px[^}]*font-size:\s*12\.5px[^}]*white-space:\s*nowrap[^}]*font-variant-numeric:\s*tabular-nums/)
  assert.match(styles, /\.nurse-station-guarded strong\s*\{[^}]*color:\s*rgb\(var\(--hoho-color-primary\)\)[^}]*font-size:\s*inherit/)
  assert.match(styles, /\.nurse-station-visual\s*\{[^}]*height:\s*104px[^}]*background:\s*#fff/)
  assert.match(styles, /\.nurse-station-growth-data\s*\{[^}]*grid-template-columns:\s*repeat\(3,/)
  assert.match(styles, /\.nurse-station-hero--compact \.nurse-station-growth-data > button\s*\{[^}]*min-height:\s*53px/)
  assert.match(styles, /\.nurse-station-growth-data > button:not\(:last-child\)\s*\{[^}]*border-right:\s*1px solid #d6e8e3/)
  assert.match(source, /选择孩子，当前\$\{member\.name\}/)
  assert.match(source, /openGrowthData\('height'\)/)
  assert.match(source, /openGrowthData\('weight'\)/)
  assert.match(source, /state: \{ selectedMeasure, returnTo:/)
  assert.doesNotMatch(source, /<GrowthDate|测于/)
  const growthPage = readFileSync(new URL('../HealthProfile/BasicHealthProfilePage.tsx', import.meta.url), 'utf8')
  assert.match(growthPage, /savedDate=\{savedGrowth\.heightMeasuredAt\}/)
  assert.match(growthPage, /savedDate=\{savedGrowth\.weightMeasuredAt\}/)
  assert.match(growthPage, /growth-step-card__heading[\s\S]*<time dateTime=\{savedDate\}/)
  assert.match(source, /身高，\$\{growthValue/)
  assert.match(source, /血型，\$\{formatAboBloodType/)
  assert.match(source, /className="nurse-station-blood-type"/)
  assert.match(styles, /\.nurse-station-hero--compact \.nurse-station-growth-data \.nurse-station-blood-type > span\s*\{[^}]*flex-direction:\s*row/)
  assert.match(source, /setBloodEditorMemberId\(member\.id\)/)
  assert.doesNotMatch(source, /nurse-station-allergy-index|useFoodAllergyIndex|食物过敏记录指数/)
  assert.doesNotMatch(styles, /\.nurse-station-allergy-index/)
  assert.doesNotMatch(styles, /\.nurse-station-visual\s*\{[^}]*(?:gradient|mask-image)/)
  assert.doesNotMatch(source, /今天想让我们帮你做什么|容易忘、需要持续观察/)
})

test('首页六入口使用等高双列卡片和独立图文层', () => {
  assert.match(styles, /\.nurse-home-entries\s*\{[^}]*grid-template-columns:\s*repeat\(2,[^}]*gap:\s*10px/)
  assert.match(styles, /\.nurse-home-entry\s*\{[^}]*height:\s*88px[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*58px/)
  assert.match(styles, /\.nurse-home-entry__copy strong\s*\{[^}]*font-size:\s*14px[^}]*font-weight:\s*500/)
  assert.match(styles, /\.nurse-home-entry__copy small\s*\{[^}]*font-size:\s*11px[^}]*line-height:\s*16px/)
  assert.match(styles, /\.nurse-home-entry__visual img\s*\{[^}]*object-fit:\s*contain/)
  assert.match(source, /健康日记.*记录日常与身体变化.*healthDiaryImage.*\/health-events/)
  assert.match(source, /孩子档案.*整理家人的健康信息.*healthProfileImage.*\/health-profile/)
  assert.match(source, /配料表扫描.*拍配料表，对照过敏史.*foodLabelImage.*\/food-label/)
  assert.match(styles, /\.nurse-home-entry--food-label\s*\{[^}]*border-color:\s*#f2dcc8[^}]*background:\s*#fff4ea/)
  assert.match(source, /就诊情况单.*就诊前，一页理清病情.*visitSummaryImage.*\/visit-summary/)
  assert.match(source, /忌口出示卡.*哪些不能吃，出示就懂.*dietaryCardImage/)
  assert.match(source, /title: '用药安排'[\s\S]*medicationRemindersImage[\s\S]*\/medication-reminders/)
  assert.doesNotMatch(source, /desensitizationTestsImage|desensitizationTestService|title: '排敏测试'/)
  assert.match(source, /`\$\{count\} 个\$\{noun\}任务`/)
  assert.match(source, /<Link aria-label=\{`\$\{entry\.title\}，\$\{entry\.subtitle\}`\}/)
  assert.match(source, /<img alt=""[^>]*onError=/)
  assert.doesNotMatch(source, /健康事件记录|更多服务|过敏出示|能不能吃|附近就医/)
  assert.doesNotMatch(source, /nurse-primary-entries|nurse-more-services/)
})

test('任务管理迁移到两个独立二级页并常驻进行中与已归档', () => {
  assert.match(taskStyles, /\.guardian-task-page__tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,/)
  assert.match(taskSource, /role="tablist"/)
  assert.match(taskSource, /进行中/)
  assert.match(taskSource, /已归档/)
  assert.match(taskSource, /管理.*左滑卡片/)
  assert.match(taskSource, /export function MedicationReminderListPage/)
  assert.match(taskSource, /export function DesensitizationTestListPage/)
  assert.doesNotMatch(source, /guardian-tasks|guardian-task-tabs|新增提醒|新增测试/)
})

test('任务卡展示真实下次时间、可换行标题和可读详情', () => {
  const medicationCard = readFileSync(new URL('./MedicationReminderCard.tsx', import.meta.url), 'utf8')
  assert.match(medicationCard, /下次：\{archived[\s\S]*formatReminderOccurrence/)
  assert.match(medicationCard, /疗程：/)
  assert.match(medicationCard, /用法：/)
  assert.match(medicationCard, /今日计划：/)
  assert.match(medicationCard, /medication-course-card__week/)
  assert.match(medicationCard, /task-management__trigger/)
})
