import { test, expect, type Page } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'
const accountId = 'time-view-test-account'
const token = new TokenService('time-view-e2e-local-only-secret', 3600_000).create({ id: accountId })
const headers = { Authorization: `Bearer ${token}` }
async function prepare(page: Page, url = '/health-events', memberId = 'child-one') {
  page.on('pageerror', error => { throw error })
  await page.addInitScript(({ token, accountId, memberId }) => {
    sessionStorage.setItem('hoooho-auth-token', token)
    if (!sessionStorage.getItem('calendar-fixture-initialized')) {
      localStorage.setItem('hoooho-app', JSON.stringify({ state: { authUser: { id: accountId }, currentMemberId: memberId, members: [], profile: null }, version: 5 }))
      sessionStorage.setItem('calendar-fixture-initialized', 'true')
    }
  }, { token, accountId, memberId })
  await page.goto(url)
  await expect(page.getByRole('heading', { name: '健康日历', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '记录日常', exact: true })).toBeEnabled()
  await expect(page.getByText('正在加载时间轴…', { exact: true })).toHaveCount(0)
}
async function view(page: Page, value: '日历' | '月历') {
  await page.getByRole('button', { name: '切换日历视图', exact: true }).click()
  await page.getByRole('menuitemradio', { name: value, exact: true }).click()
}
async function shot(page: Page, name: string) {
  await mkdir('outputs/unified-health-calendar', { recursive: true })
  await page.screenshot({ path: `outputs/unified-health-calendar/${name}.png` })
}
test('dense filtered previews, holidays, today and zero/error states remain accurate and readable', async ({ page }) => {
  const member = await page.request.post('/api/members', { headers, data: { name: '密集月历测试对象', birthday: '2025-01-01', gender: 'female', relationship: 'child' } })
  const memberId = (await member.json()).id
  for (const category of ['symptom', 'medication', 'diet']) for (let index = 0; index < 5; index++) {
    const data = { memberId, title: '日历可控测试', content: `${category}很长的测试记录${index}，详情保留完整原文`, occurredAt: `2026-03-08T10:${String(index).padStart(2, '0')}:00+08:00`, inputChannel: 'text', idempotencyKey: `calendar-${category}-${index}`, journal: { categories: [category], timePrecision: 'exact' } }
    const checked = await page.request.post('/api/quick-records/duplicate-check', { headers, data })
    expect(checked.ok()).toBe(true)
    const { duplicate } = await checked.json()
    const saved = await page.request.post('/api/quick-records', { headers, data: { ...data, ...(duplicate ? { duplicateAction: 'create', duplicateEventId: duplicate.eventId } : {}) } })
    expect(saved.status(), await saved.text()).toBe(201)
  }
  await prepare(page, '/health-events?view=month&day=2026-03-08&month=2026-03', memberId)
  await expect(page.getByRole('button', { name: /^2026-03-08，/ })).toHaveAccessibleName(/15条记录/)
  for (const [width, height] of [[320, 568], [375, 667], [390, 844], [430, 932]]) {
    await page.setViewportSize({ width, height })
    for (const [category, count] of [['', 15], ['symptom', 5], ['medication', 5], ['diet', 5], ['vaccination', 0]] as const) {
      await page.getByLabel('筛选记录类型').selectOption(category)
      const cell = page.getByRole('button', { name: /^2026-03-08，/ })
      await expect(cell).toHaveAccessibleName(new RegExp(`${count}条记录`))
      const geometry = await cell.evaluate(el => {
        const previews = Array.from(el.querySelectorAll<HTMLElement>('.health-calendar__preview')), more = el.querySelector<HTMLElement>('.health-calendar__more')
        return { shown: previews.length, hidden: Number(more?.textContent?.slice(1) ?? 0), fits: [...previews, ...(more ? [more] : [])].every(item => item.getBoundingClientRect().bottom <= el.getBoundingClientRect().bottom + 1), width: el.clientWidth / parseFloat(getComputedStyle(el).fontSize) }
      })
      expect(geometry.shown + geometry.hidden).toBe(count); expect(geometry.fits).toBe(true); expect(geometry.width).toBeGreaterThanOrEqual(4)
    }
    await page.getByLabel('筛选记录类型').selectOption('')
    await page.getByRole('heading', { name: '健康日历', exact: true }).click()
    await shot(page, `dense-six-weeks-${width}x${height}-local`)
  }
  await page.getByLabel('选择月份').fill('2026-10')
  await expect(page.locator('.health-calendar__weekday[data-weekend=true]')).toHaveText(['六', '日'])
  await expect(page.getByRole('button', { name: /^2026-10-01，/ }).locator('.health-calendar__festival')).toHaveText('国庆')
  await expect(page.getByRole('button', { name: /^2026-10-10，/ }).locator('.health-calendar__holiday-marker')).toHaveText('班')
  await expect(page.locator('[aria-current=date]')).toHaveCount(1)
  await expect(page.getByRole('button', { name: /^2026-10-01，/ })).not.toHaveAttribute('aria-current', 'date')
  await page.getByLabel('筛选记录类型').selectOption('symptom'); await view(page, '日历')
  await expect(page.getByText('这一天还没有健康记录。可以在下方记一下；未记录不代表没有发生。')).toHaveCount(0)
  await page.route('**/api/events?view=time', route => route.fulfill({ status: 503, json: { error: { message: '可控加载失败' } } }))
  await page.evaluate(() => window.dispatchEvent(new Event('hoooho-data-changed')))
  await expect(page.getByRole('alert')).toBeVisible()
  await page.unroute('**/api/events?view=time'); await page.getByRole('button', { name: '重新加载', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
})
test('member navigation and data are isolated; search returns to the same scrolled day', async ({ page }) => {
  await prepare(page, '/health-events?view=day&day=2026-10-10&sort=desc')
  await expect.poll(() => page.locator('.journal-record').count()).toBeGreaterThan(0)
  await page.locator('.journal-scroll-region').evaluate(el => { el.scrollTop = 250 })
  const offset = await page.locator('.journal-scroll-region').evaluate(el => el.scrollTop)
  await page.getByRole('button', { name: '搜索健康日历' }).click()
  await page.getByRole('searchbox', { name: '搜索健康日历' }).fill('疹子')
  await expect(page.locator('.journal-search-results')).toBeVisible()
  await page.getByRole('button', { name: '返回健康日历' }).click()
  await expect(page.getByLabel('选择日期')).toHaveValue('2026-10-10')
  await expect.poll(() => page.locator('.journal-scroll-region').evaluate(el => el.scrollTop)).toBe(offset)
  await view(page, '月历'); await view(page, '日历')
  await expect.poll(() => page.locator('.journal-scroll-region').evaluate(el => el.scrollTop)).toBe(offset)
  await view(page, '月历'); await page.getByLabel('筛选记录类型').selectOption('symptom')
  await page.getByRole('button', { name: '打开菜单' }).click(); await page.getByRole('button', { name: '打开我的孩子' }).click()
  await page.getByRole('button', { name: '切换到隔离对象', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '我的孩子', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '切换日历视图' })).toHaveText('日历')
  await expect(page.getByLabel('筛选记录类型')).toHaveValue('')
  await page.getByLabel('选择日期').fill('2026-10-10'); await expect(page.locator('.journal-record')).toHaveCount(1)
  await expect(page.locator('.journal-record')).toContainText('隔离对象专属记录')
  await page.getByRole('button', { name: '打开菜单' }).click(); await page.getByRole('button', { name: '打开我的孩子' }).click()
  await page.getByRole('button', { name: '切换到安安', exact: true }).click()
  await expect(page.getByRole('button', { name: '切换日历视图' })).toHaveText('月历')
  await expect(page.getByLabel('筛选记录类型')).toHaveValue('symptom')
})
test('entry forms remain distinct in either view, cancel does not write, no duplicate daily choices', async ({ page }) => {
  await prepare(page)
  let writes = 0
  page.on('request', request => { if (request.method() === 'POST' && new URL(request.url()).pathname === '/api/quick-records') writes++ })
  for (const mode of ['日历', '月历'] as const) {
    if (mode === '月历') await view(page, mode)
    for (const [label, title] of [['喂养/饮食', '喂养/饮食'], ['补剂', '记录补剂'], ['记录用药', '记录用药'], ['记录症状', '记录症状']]) {
      await page.locator('.journal-record-actions').getByRole('button', { name: label, exact: true }).click()
      const form = page.getByRole('dialog', { name: title, exact: true }); await expect(form).toBeVisible()
      if (label === '喂养/饮食') await expect(form.getByRole('radiogroup', { name: '喂养/饮食分类' })).toBeVisible()
      if (label === '补剂') await expect(form.getByRole('radiogroup', { name: '喂养/饮食分类' })).toHaveCount(0)
      await form.getByRole('button', { name: /^返回/ }).click(); await expect(form).toHaveCount(0)
    }
    for (const [label, title] of [['睡眠', '记录睡眠'], ['排便', '记录排便'], ['身体涂抹', '记录身体涂抹']]) {
      await page.getByRole('button', { name: '记录日常', exact: true }).click()
      const daily = page.getByRole('group', { name: '记录日常选项' })
      await expect(daily.getByRole('button')).toHaveText(['睡眠', '排便', '身体涂抹'])
      await daily.getByRole('button', { name: label, exact: true }).click()
      const form = page.getByRole('dialog', { name: title, exact: true }); await expect(form).toBeVisible()
      await form.getByRole('button', { name: /^返回/ }).click()
    }
  }
  expect(writes).toBe(0)
})
test('real saved sleep moves between dates on edit and disappears from both projections on delete', async ({ page }) => {
  const member = await page.request.post('/api/members', { headers, data: { name: '日月联动测试对象', birthday: '2025-01-01', gender: 'female', relationship: 'child' } })
  expect(member.ok()).toBe(true); const memberId = (await member.json()).id
  await prepare(page, '/health-events?day=2026-09-30', memberId)
  await page.getByRole('button', { name: '记录日常', exact: true }).click(); await page.getByRole('button', { name: '睡眠', exact: true }).click()
  const form = page.getByRole('dialog', { name: '记录睡眠', exact: true })
  await form.locator('.sleep-editor-card').first().click()
  await form.getByLabel('入睡日期').fill('2026-09-30'); await form.getByLabel('入睡时间', { exact: true }).fill('21:10')
  await form.locator('.sleep-editor-card').nth(1).click()
  await form.getByLabel('醒来日期').fill('2026-10-01'); await form.getByLabel('醒来时间', { exact: true }).fill('06:10')
  const response = page.waitForResponse(r => r.request().method() === 'POST' && new URL(r.url()).pathname === '/api/quick-records')
  await form.getByRole('button', { name: '保存记录', exact: true }).click()
  const saved = await response; expect(saved.status()).toBe(201); const ids = await saved.json()
  await expect(form).toHaveCount(0); await expect(page.getByLabel('选择日期')).toHaveValue('2026-10-01')
  const row = page.locator(`[data-record-id="${ids.recordId}"]`)
  await expect(row).toContainText('睡眠 · 已醒 · 约9小时')
  await view(page, '月历'); await expect(page.getByRole('button', { name: /^2026-10-01，/ })).toHaveAccessibleName(/1条记录/)
  await page.getByLabel('选择月份').fill('2026-09'); await expect(page.getByRole('button', { name: /^2026-09-30，/ })).toHaveAccessibleName(/0条记录/)
  await page.getByLabel('选择月份').fill('2026-10'); await page.getByRole('button', { name: /^2026-10-01，/ }).click()
  await row.getByRole('button').click(); const detail = page.getByRole('dialog', { name: '睡眠记录详情', exact: true })
  await detail.getByRole('button', { name: '修改起止时间' }).click()
  await detail.getByLabel('睡眠开始时间').fill('2026-10-01T21:10'); await detail.getByLabel('睡眠结束时间').fill('2026-10-02T06:10')
  const patch = page.waitForResponse(r => r.request().method() === 'PATCH' && r.url().endsWith(`/api/records/${ids.recordId}`))
  await detail.getByRole('button', { name: '保存时间' }).click(); expect((await patch).ok()).toBe(true)
  await expect(detail).toHaveCount(0); await expect(page.getByLabel('选择日期')).toHaveValue('2026-10-02'); await expect(row).toHaveCount(1)
  await view(page, '月历'); await expect(page.getByRole('button', { name: /^2026-10-01，/ })).toHaveAccessibleName(/0条记录/); await expect(page.getByRole('button', { name: /^2026-10-02，/ })).toHaveAccessibleName(/1条记录/)
  await page.getByRole('button', { name: /^2026-10-02，/ }).click(); await row.getByRole('button').click()
  page.once('dialog', dialog => dialog.accept())
  const deleted = page.waitForResponse(r => r.request().method() === 'DELETE' && r.url().endsWith(`/api/records/${ids.recordId}`))
  await detail.getByRole('button', { name: '删除这条记录' }).click(); expect((await deleted).ok()).toBe(true)
  await expect(row).toHaveCount(0); await view(page, '月历'); await expect(page.getByRole('button', { name: /^2026-10-02，/ })).toHaveAccessibleName(/0条记录/)
  const rows = await (await page.request.get(`/api/events/${ids.eventId}/records?view=time`, { headers })).json()
  expect(rows).toHaveLength(0)
})
test('one shell, ordered toolbar, common entry kinds, accessible dropdown and one sidebar item', async ({ page }) => {
  await prepare(page)
  await expect(page.locator('.health-events-member,.health-events-toolbar,.journal-date-navigation')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '搜索健康日历', exact: true })).toHaveCount(1)
  await expect(page.locator('.hoho-main-header').getByRole('button', { name: '搜索健康日历', exact: true })).toBeVisible()
  const toolbar = page.getByLabel('健康日历工具栏')
  expect(await toolbar.evaluate(el => Array.from(el.children).map(node => node.className || node.tagName))).toEqual(['calendar-date-navigation', 'SELECT', expect.stringContaining('hoho-button'), 'calendar-view-menu', expect.stringContaining('hoho-button')])
  await page.getByRole('button', { name: /^记录顺序：/ }).click()
  await expect(page.getByRole('button', { name: /^记录顺序：最新在下/ })).toBeVisible()
  await page.getByLabel('筛选记录类型').selectOption('sleep')
  await view(page, '月历')
  await expect(page.getByRole('button', { name: /^记录顺序：/ })).toHaveCount(0)
  await expect(page.getByLabel('筛选记录类型')).toHaveValue('sleep')
  await expect(page.locator('.journal-record-actions .record-entry-grid button')).toHaveText(['喂养/饮食', '补剂', '记录日常', '记录用药'])
  await expect(page.locator('.health-calendar__add')).toHaveCount(0)
  await page.getByRole('button', { name: '切换日历视图' }).click()
  await page.keyboard.press('ArrowDown'); await expect(page.getByRole('menuitemradio', { name: '日历', exact: true })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(page.getByRole('button', { name: '切换日历视图' })).toBeFocused()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await page.getByRole('button', { name: '调整作息' }).click()
  await expect(page.getByRole('dialog', { name: '设置日常作息', exact: true })).toBeVisible()
  await page.getByRole('dialog', { name: '设置日常作息', exact: true }).getByRole('button', { name: '关闭设置日常作息' }).click()
  await view(page, '日历')
  await expect(page.getByRole('button', { name: /^记录顺序：最新在下/ })).toBeVisible()
  await page.getByRole('button', { name: '打开菜单' }).click()
  await expect(page.getByRole('button', { name: '健康日历', exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: '健康日历', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.getByRole('button', { name: /^(健康随记|健康月历)$/ })).toHaveCount(0)
  await shot(page, 'sidebar-375x667-local')
})
for (const [width, height] of [[320, 568], [375, 667], [390, 844], [430, 932], [1280, 900]]) test(`real month grids and shared footer fit ${width}x${height}`, async ({ page }) => {
  await page.setViewportSize({ width, height }); await prepare(page)
  await page.getByLabel('选择日期', { exact: true }).fill('2026-10-10')
  await page.getByRole('heading', { name: '健康日历', exact: true }).click()
  await shot(page, `day-${width}x${height}-local`)
  await page.getByRole('button', { name: '切换日历视图' }).click()
  await shot(page, `view-menu-${width}x${height}-local`)
  await page.getByRole('menuitemradio', { name: '月历', exact: true }).click()
  for (const [month, count] of [['2021-02', 28], ['2026-10', 31], ['2026-03', 31]] as const) {
    await page.getByLabel('选择月份', { exact: true }).fill(month)
    await expect(page.locator('.health-calendar__day')).toHaveCount(count)
    const geometry = await page.evaluate(() => {
      const main = document.querySelector('.unified-health-calendar')!, grid = document.querySelector('.health-calendar__grid')!, footer = document.querySelector('.journal-record-actions')!, toolbar = document.querySelector('.calendar-toolbar')!
      return { overflow: document.documentElement.scrollWidth > innerWidth, pageScroll: main.scrollHeight - main.clientHeight, gridBottom: grid.getBoundingClientRect().bottom, footerTop: footer.getBoundingClientRect().top, footerBottom: footer.getBoundingClientRect().bottom, height: innerHeight, controlsFit: Array.from(toolbar.children).every(item => item.getBoundingClientRect().right <= toolbar.getBoundingClientRect().right + 1), dateHeight: document.querySelector('.health-calendar__day')!.getBoundingClientRect().height }
    })
    expect(geometry.overflow).toBe(false); expect(geometry.pageScroll).toBeLessThanOrEqual(1); expect(geometry.gridBottom).toBeLessThanOrEqual(geometry.footerTop)
    expect(geometry.footerBottom).toBeLessThanOrEqual(geometry.height + 1); expect(geometry.controlsFit).toBe(true); expect(geometry.dateHeight).toBeGreaterThan(35)
    await expect(page.locator('.health-calendar__day').last()).toBeInViewport()
    await page.getByRole('heading', { name: '健康日历', exact: true }).click()
    await shot(page, `month-${month}-${width}x${height}-local`)
  }
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await expect(page.getByRole('group', { name: '记录日常选项' }).getByRole('button')).toHaveText(['睡眠', '排便', '身体涂抹'])
  await expect(page.getByRole('button', { name: '记录症状', exact: true })).toBeInViewport()
  await shot(page, `daily-open-${width}x${height}-local`)
  await page.getByRole('button', { name: '记录日常', exact: true }).click()
  await page.getByRole('button', { name: '打开菜单' }).click()
  await shot(page, `sidebar-${width}x${height}-local`)
})
test('legacy URL, day/month boundaries, search, detail and browser history restore navigation', async ({ page }) => {
  await prepare(page, '/health-calendar?day=2026-03-08&category=other&sort=asc&source=legacy')
  await expect(page).toHaveURL(/health-events\?.*view=month/)
  expect(new URL(page.url()).searchParams.get('source')).toBe('legacy')
  await page.getByRole('button', { name: '上个月', exact: true }).click(); await expect(page.getByLabel('选择月份')).toHaveValue('2026-02')
  await page.getByRole('button', { name: '下个月', exact: true }).click(); await expect(page.getByLabel('选择月份')).toHaveValue('2026-03')
  await page.getByRole('button', { name: '搜索健康日历' }).click()
  await expect(page.getByRole('searchbox', { name: '搜索健康日历' })).toBeVisible()
  await page.getByRole('button', { name: '返回健康日历' }).click()
  await expect(page.getByLabel('选择月份')).toHaveValue('2026-03'); await expect(page.getByLabel('筛选记录类型')).toHaveValue('other')
  expect(new URL(page.url()).searchParams.get('source')).toBe('legacy')
  await page.getByRole('button', { name: /^2026-03-07，/ }).click()
  await expect(page.getByLabel('选择日期')).toHaveValue('2026-03-07')
  await page.goBack(); await expect(page.getByLabel('选择月份')).toHaveValue('2026-03')
  await page.goForward(); await expect(page.getByLabel('选择日期')).toHaveValue('2026-03-07')
  await page.getByRole('button', { name: '前一天' }).click(); await expect(page.getByLabel('选择日期')).toHaveValue('2026-03-06')
  await view(page, '月历'); await page.getByLabel('选择月份').fill('2024-02'); await expect(page.locator('.health-calendar__day')).toHaveCount(29)
  await view(page, '日历'); await expect(page.getByLabel('选择日期')).toHaveValue('2024-02-01')
  await page.getByLabel('选择日期').fill('2025-12-31'); await page.getByRole('button', { name: '后一天' }).click(); await expect(page.getByLabel('选择日期')).toHaveValue('2026-01-01')
  await page.goto('/health-events?view=broken&day=2026-02-30&month=2099-10&category=measurement'); await expect(page.getByRole('heading', { name: '健康日历' })).toBeVisible()
  await expect(page.getByLabel('筛选记录类型')).toHaveValue('')
  await page.goto('/health-events/new?day=2026-10-01&source=legacy-new#return')
  await expect(page.getByLabel('选择日期')).toHaveValue('2026-10-01')
  expect(new URL(page.url()).searchParams.get('source')).toBe('legacy-new')
  expect(new URL(page.url()).hash).toBe('#return')
})
