import { useEffect, useMemo, useState } from 'react'
import { Check, MoreHorizontal, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Avatar, WebPageHeader } from '../../components/common'
import { calculateGrowthPosition, exactAgeInMonths, heightMeasureLabel } from '../../features/health-profile/utils/childGrowthReference'
import { decorateGrowthRecords, GROWTH_STANDARDS, growthTrend } from '../../features/health-profile/utils/growthTrend'
import { useCurrentMember } from '../../hooks/useCurrentMember'
import { growthMeasurementService } from '../../services/growthMeasurements'
import { useAppStore } from '../../store/useAppStore'
import type { GrowthMeasurementApiDto } from '../../types'
import { GrowthCurveChart } from './GrowthCurveChart'
import { validHeight } from './growthCardForm'
import { gramsToKg, kgToGrams, validWeightGrams } from './growthUpdateForm'

type Tab = 'list' | 'height' | 'weight'
const today = () => new Date().toISOString().slice(0, 10)
const ageText = (birthday: string | undefined, date: string) => { const months = exactAgeInMonths(birthday, date); return months == null ? '年龄未知' : `${Math.floor(months / 12)}岁${Math.floor(months % 12)}个月` }

export function GrowthRecordsPage() {
  const member = useCurrentMember(), token = useAppStore((state) => state.authToken), navigate = useNavigate(), location = useLocation()
  const requestedTab = (location.state as { tab?: Tab } | null)?.tab
  const [records, setRecords] = useState<GrowthMeasurementApiDto[]>([]), [tab, setTab] = useState<Tab>(requestedTab === 'height' || requestedTab === 'weight' ? requestedTab : 'list'), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [editing, setEditing] = useState<GrowthMeasurementApiDto | null | 'new'>(null), [menuId, setMenuId] = useState(''), [standardOpen, setStandardOpen] = useState(false), [standardNotice, setStandardNotice] = useState(''), [replayKey, setReplayKey] = useState(0)
  const decorated = useMemo(() => decorateGrowthRecords(records, member), [member, records]), trend = useMemo(() => growthTrend(decorated), [decorated])
  const load = () => { if (!token) return; setLoading(true); growthMeasurementService.list(member.id, token).then(setRecords).catch((reason) => setError(reason instanceof Error ? reason.message : '成长记录加载失败')).finally(() => setLoading(false)) }
  useEffect(load, [member.id, token])
  const remove = async (record: GrowthMeasurementApiDto) => {
    if (!token || !window.confirm(`确认删除 ${record.measuredAt} 的成长记录吗？`)) return
    try { await growthMeasurementService.delete(record.id, token); setRecords((items) => items.filter((item) => item.id !== record.id)); setMenuId('') } catch { setError('删除失败，请检查网络后重试') }
  }
  const latest = decorated.at(-1), previous = decorated.at(-2)
  return <main className="app-shell health-profile-detail-shell growth-records-page"><WebPageHeader fallback="/health-profile/basic" title="成长记录" action={<button className="growth-header-add" onClick={() => setEditing('new')} type="button"><Plus size={15} />添加</button>} /><div className="page-content growth-records-content">
    <div className="growth-tabs" role="tablist"><button aria-selected={tab === 'list'} onClick={() => setTab('list')} role="tab">记录列表</button><button aria-selected={tab === 'height'} onClick={() => setTab('height')} role="tab">{heightMeasureLabel(member.birthday, latest?.measuredAt ?? today())}曲线</button><button aria-selected={tab === 'weight'} onClick={() => setTab('weight')} role="tab">体重曲线</button></div>
    {loading ? <p className="growth-loading">正在加载成长记录…</p> : error ? <button className="growth-retry" onClick={load} type="button">{error}，点击重试</button> : tab === 'list' ? <section className="growth-record-list">
      {!records.length ? <div className="growth-empty-state"><h2>还没有成长记录</h2><p>添加第一次测量，看看孩子今天长到哪里了。</p><button onClick={() => setEditing('new')} type="button">添加记录</button></div> : <>{records.map((record, index) => {
        const h = record.heightCm == null ? null : calculateGrowthPosition({ birthday: member.birthday, gender: member.gender, measuredAt: record.measuredAt, measure: 'height', value: record.heightCm })
        const w = record.weightKg == null ? null : calculateGrowthPosition({ birthday: member.birthday, gender: member.gender, measuredAt: record.measuredAt, measure: 'weight', value: record.weightKg })
        return <article className="growth-record-row" key={record.id}><div className="growth-record-row__date"><strong>{index === 0 ? '最新 · ' : ''}{record.measuredAt}</strong><small>{ageText(member.birthday, record.measuredAt)}</small></div><button aria-label="记录菜单" onClick={() => setMenuId(menuId === record.id ? '' : record.id)} type="button"><MoreHorizontal /></button>{menuId === record.id && <div className="growth-record-menu"><button onClick={() => { setEditing(record); setMenuId('') }} type="button">编辑</button><button onClick={() => void remove(record)} type="button"><Trash2 size={14} />删除</button></div>}<div className="growth-record-values"><span>{heightMeasureLabel(member.birthday, record.measuredAt)}<strong>{record.heightCm ?? '—'} cm {h ? `· ${h.percentileLabel}` : ''}</strong></span><span>体重<strong>{record.weightKg == null ? '—' : kgToGrams(record.weightKg)} g {w ? `· ${w.percentileLabel}` : ''}</strong></span></div>{record.dataStatus === 'pending_confirmation' && <em>待确认</em>}<small>参考：世界卫生组织儿童生长标准 2006</small></article>
      })}{records.length === 1 ? <aside className="growth-first-record"><h3>第一次成长落点已建立</h3><p>下次再记录，就能看到长高和体重变化</p><button onClick={() => setTab('height')} type="button">查看成长曲线</button></aside> : trend.days && <aside className="growth-delta-summary"><strong>距上次记录 {trend.days} 天</strong><span>{trend.heightDelta == null ? '身高变化待补充' : `较上次${trend.heightDelta >= 0 ? '长高' : '变化'} ${Math.abs(trend.heightDelta)} cm`}</span><span>{trend.weightDelta == null ? '体重变化待补充' : `体重${trend.weightDelta >= 0 ? '增加' : '减少'} ${Math.round(Math.abs(trend.weightDelta) * 1000)} g`}</span></aside>}</>}
    </section> : <section className="growth-curve-view"><header><span><h2>{tab === 'height' ? `${heightMeasureLabel(member.birthday, latest?.measuredAt ?? today())}（cm）` : '体重（g）'}</h2><p>{latest ? `${latest.measuredAt} · ${ageText(member.birthday, latest.measuredAt)}` : ''}</p></span><button aria-label="重看成长轨迹" onClick={() => setReplayKey((value) => value + 1)} type="button"><RefreshCw size={17} />重看轨迹</button></header><GrowthCurveChart measure={tab} member={member} records={records} replayKey={replayKey} />{latest && <div className="growth-current-reading"><Avatar name={member.name} size="md" src={member.avatar} /><span><strong>{trend.label}</strong><small>{trend.kind === 'insufficient' ? '再记录一次，才能看见自己的连续轨迹' : '先看孩子自己的变化，再看参考位置'}</small></span></div>}<button className="growth-standard-row" onClick={() => setStandardOpen(true)} type="button">参考标准：世界卫生组织儿童生长标准 2006 <span>⌄</span></button><p className="growth-standard-source">数据来源：WHO Child Growth Standards，适用 0–5 岁。</p><p className="growth-chart-note">单次位置不代表成长趋势，建议持续记录观察。</p>{latest && <button className="growth-reassurance-link" onClick={() => navigate('/health-profile/growth/reassurance')} type="button">成长安心解读</button>}</section>}
    {standardNotice && <div className="growth-standard-toast" role="status"><Check size={16} />{standardNotice}</div>}
  </div>{editing && <GrowthRecordEditor initial={editing === 'new' ? null : editing} memberId={member.id} onClose={() => setEditing(null)} onSaved={(saved) => { setRecords((items) => [saved, ...items.filter((item) => item.id !== saved.id)].sort((a,b) => b.measuredAt.localeCompare(a.measuredAt))); setEditing(null) }} token={token ?? ''} birthday={member.birthday} />}{standardOpen && <div className="growth-standard-backdrop" onClick={() => setStandardOpen(false)}><section aria-modal="true" className="growth-standard-sheet" onClick={(event) => event.stopPropagation()} role="dialog"><header><button onClick={() => setStandardOpen(false)} type="button">取消</button><h2>选择参考标准</h2><button onClick={() => { setStandardOpen(false); setStandardNotice('参考标准已更新，成长位置已重新计算'); window.setTimeout(() => setStandardNotice(''), 2600) }} type="button">确定</button></header>{GROWTH_STANDARDS.map((standard) => <button aria-pressed="true" className="growth-standard-option" key={standard.id} type="button"><span><strong>{standard.name}</strong><small>{standard.version} · 适用 {standard.ageRange}</small></span><Check /></button>)}<p>切换标准后，百分位和参考区间将重新计算，原始测量数据不会改变。</p></section></div>}</main>
}

function GrowthRecordEditor({ birthday, initial, memberId, onClose, onSaved, token }: { birthday?: string; initial: GrowthMeasurementApiDto | null; memberId: string; onClose: () => void; onSaved: (value: GrowthMeasurementApiDto) => void; token: string }) {
  const [date, setDate] = useState(initial?.measuredAt ?? today()), [height, setHeight] = useState(initial?.heightCm?.toString() ?? ''), [weight, setWeight] = useState(kgToGrams(initial?.weightKg ?? null)), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const save = async () => { setSaving(true); setError(''); try { const input = { memberId, measuredAt: date, measurementType: heightMeasureLabel(birthday, date) === '身长' ? 'length' as const : 'height' as const, heightCm: validHeight(height) ? Number(height) : null, weightKg: validWeightGrams(weight) ? gramsToKg(weight) : null, dataStatus: initial?.dataStatus ?? 'confirmed' as const, standardId: 'who-2006' as const }; onSaved(initial ? await growthMeasurementService.update(initial.id, input, token) : await growthMeasurementService.upsert(input, token)) } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败') } finally { setSaving(false) } }
  return <div className="growth-editor-backdrop"><section aria-modal="true" className="growth-editor-sheet" role="dialog"><header><h2>{initial ? '编辑成长记录' : '添加成长记录'}</h2><button aria-label="关闭" onClick={onClose} type="button"><X /></button></header><label>测量日期<input max={today()} onChange={(event) => setDate(event.target.value)} type="date" value={date} /></label><div><label>{heightMeasureLabel(birthday, date)}<input inputMode="decimal" onChange={(event) => setHeight(event.target.value)} step="0.1" type="number" value={height} /></label><label>体重（g）<input inputMode="numeric" max="500000" min="1000" onChange={(event) => setWeight(event.target.value)} step="1" type="number" value={weight} /></label></div>{error && <p role="alert">{error}</p>}<button disabled={saving || (!validHeight(height) && !validWeightGrams(weight))} onClick={() => void save()} type="button">{saving ? '保存中…' : '保存记录'}</button></section></div>
}
