import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Check, ChevronRight, ClipboardList, Info, MapPin, Ruler, Stethoscope, TrendingUp } from 'lucide-react'
import { Avatar, WebPageHeader } from '../../components/common'
import { calculateGrowthPosition } from '../../features/health-profile/utils/childGrowthReference'
import { decorateGrowthRecords, growthTrend } from '../../features/health-profile/utils/growthTrend'
import { useCurrentMember } from '../../hooks/useCurrentMember'
import { growthMeasurementService } from '../../services/growthMeasurements'
import { healthEventService } from '../../services/healthEvents'
import { readProfileSection, saveProfileSection } from '../../services/profileSectionStorage'
import { useAppStore } from '../../store/useAppStore'
import type { GrowthMeasurementApiDto, HealthEventApiDto } from '../../types'
import { GrowthCurveChart } from './GrowthCurveChart'

type View = 'overview' | 'confirm' | 'trajectory' | 'context' | 'summary'
const contextItems = ['近期回避了奶、蛋、小麦等主要食物', '已经安排等价替代食物', '出现呕吐、腹泻或便血', '有拒食或进食量下降', '症状影响睡眠或进食']
const measurementChecks = ['脱鞋或平躺测量', '身长板/身高尺位置正确', '体重已去除厚衣物影响', '测量日期填写正确']

export function GrowthReassurancePage() {
  const navigate = useNavigate()
  const member = useCurrentMember(), token = useAppStore((state) => state.authToken)
  const [records, setRecords] = useState<GrowthMeasurementApiDto[]>([]), [events, setEvents] = useState<HealthEventApiDto[]>([]), [view, setView] = useState<View>('overview'), [checked, setChecked] = useState<string[]>([]), [measurementChecked, setMeasurementChecked] = useState<string[]>([]), [actionNotice, setActionNotice] = useState('')
  useEffect(() => { if (!token) return; const controller = new AbortController(); Promise.all([growthMeasurementService.list(member.id, token, controller.signal), healthEventService.list(token, controller.signal)]).then(([growth, allEvents]) => { setRecords(growth); setEvents(allEvents.filter((event) => event.memberId === member.id)) }).catch(() => undefined); return () => controller.abort() }, [member.id, token])
  const decorated = useMemo(() => decorateGrowthRecords(records, member), [member, records]), trend = useMemo(() => growthTrend(decorated), [decorated]), latest = decorated.at(-1)
  const position = latest?.heightPosition ?? latest?.weightPosition, positionText = !position ? '位置待补充' : position.percentile < 3 || position.percentile > 97 ? '接近或超出参考区间边缘' : position.percentile < 15 ? '参考区间中下部' : position.percentile > 85 ? '参考区间中上部' : '参考区间中部'
  const allergyProfile = useMemo(() => { try { return JSON.parse(readProfileSection(`hoho-health-profile:${member.id}:allergy`)) as unknown[] } catch { return [] } }, [member.id])
  const allergyEvents = events.filter((event) => event.category === 'allergy'), symptomEvents = events.filter((event) => /腹泻|呕吐|便血|拒食|进食/.test(`${event.title} ${event.eventSummary?.displayedResult.summary ?? ''}`))
  const confirmLatest = async () => { if (!token || !latest) return; const saved = await growthMeasurementService.update(latest.id, { dataStatus: 'confirmed' }, token); setRecords((items) => items.map((item) => item.id === saved.id ? saved : item)); setView('trajectory') }
  const addWatchTask = async () => {
    await saveProfileSection(`hoho-health-profile:${member.id}:growth-watch`, [{ createdAt: new Date().toISOString(), action: 'continue-observation', position: positionText, trend: trend.label }])
    setActionNotice('已加入守护任务')
  }
  const title = view === 'summary' ? '成长情况整理' : view === 'confirm' ? '先确认这次测量' : view === 'trajectory' ? `${member.name}的成长轨迹` : view === 'context' ? '看看可能影响成长的因素' : '成长安心解读'
  return <main className="app-shell health-profile-detail-shell growth-reassurance-page"><WebPageHeader fallback="/health-profile/growth" title={title} />
    {view === 'overview' && <div className="page-content reassurance-content"><section className="reassurance-member"><Avatar name={member.name} size="lg" src={member.avatar} /><span><strong>{member.name}</strong><small>{member.age}</small></span></section><h1>位置偏下，不等于长得不好</h1><p>每个孩子都有自己的生长节奏，更重要的是看连续的变化。</p>{latest && <GrowthCurveChart compact measure="height" member={member} records={records} />}<div className="reassurance-questions"><button onClick={() => setView('trajectory')} type="button"><MapPin /><span><strong>现在在哪里</strong><small>{positionText}</small></span><ChevronRight /></button><button onClick={() => setView('trajectory')} type="button"><TrendingUp /><span><strong>最近怎么走</strong><small>{trend.label}</small></span><ChevronRight /></button><button onClick={() => setView(trend.kind === 'confirm' || latest?.dataStatus === 'pending_confirmation' ? 'confirm' : 'context')} type="button"><Info /><span><strong>接下来做什么</strong><small>先确认测量，再看连续变化</small></span><ChevronRight /></button></div><aside>成长曲线不是考试排名，重要的是孩子自己的连续轨迹。</aside>{(trend.kind === 'confirm' || latest?.dataStatus === 'pending_confirmation') && <button className="reassurance-primary" onClick={() => setView('confirm')} type="button">看看这次测得准不准</button>}</div>}
    {view === 'confirm' && <div className="page-content reassurance-content"><section className="measurement-warning"><Ruler /><span><strong>本次数据与上次差异较大，先排除测量误差。</strong><small>请检查下面项目，确保测量方法正确。</small></span></section><div className="measurement-checks">{measurementChecks.map((item) => <label key={item}><span>{item}</span><input checked={measurementChecked.includes(item)} onChange={() => setMeasurementChecked((items) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item])} type="checkbox" /></label>)}</div>{latest && <GrowthCurveChart measure="height" member={member} records={records} />}<p className="growth-chart-note">未确认前，这个点以虚线显示，不参与强趋势提醒。</p><button className="reassurance-primary" disabled={measurementChecked.length < measurementChecks.length} onClick={() => void confirmLatest()} type="button">数据确认无误</button><button className="reassurance-secondary" onClick={() => history.back()} type="button">重新测量</button></div>}
    {view === 'trajectory' && <div className="page-content reassurance-content"><h1>{trend.kind === 'stable' ? '位置偏下，轨迹稳定' : trend.kind === 'attention' ? '最近的成长速度值得留意' : '还需要更多记录'}</h1><p>{decorated.length >= 2 ? `最近 ${Math.min(3, decorated.length)} 次记录沿着孩子自己的成长轨迹前进。` : '再记录一次，才能判断连续变化。'}</p><GrowthCurveChart measure="height" member={member} records={records} />{trend.days && <div className="growth-trajectory-summary"><span>过去<strong>{trend.days}天</strong></span><span>身高变化<strong>{trend.heightDelta == null ? '—' : `${trend.heightDelta >= 0 ? '+' : ''}${trend.heightDelta}cm`}</strong></span><span>体重变化<strong>{trend.weightDelta == null ? '—' : `${trend.weightDelta >= 0 ? '+' : ''}${trend.weightDelta}kg`}</strong></span></div>}<aside>不需要和排在中间的孩子比较，继续看自己的速度。</aside><button className="reassurance-primary" onClick={() => setView('context')} type="button">看看可能影响成长的因素</button></div>}
    {view === 'context' && <div className="page-content reassurance-content"><p className="reassurance-lead">成长位置偏下不一定由过敏造成，我们先把近期情况理清。</p><div className="context-checks">{contextItems.map((item) => <label key={item}><span>{item}</span><input checked={checked.includes(item)} onChange={() => setChecked((items) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item])} type="checkbox" /></label>)}</div><section className="linked-health-records"><h2>已关联的真实记录</h2><span>过敏与反应记录<strong>{allergyEvents.length + allergyProfile.length} 条</strong></span><span>消化道或进食相关记录<strong>{symptomEvents.length} 条</strong></span></section><button className="reassurance-primary" onClick={() => setView('summary')} type="button">生成给医生看的整理</button></div>}
    {view === 'summary' && <div className="page-content reassurance-content"><section className="growth-summary-member"><Avatar name={member.name} size="md" src={member.avatar} /><strong>{member.name} · {member.age}</strong></section><div className="growth-doctor-summary"><p>成长轨迹：{positionText}，{trend.label}</p>{trend.days && <p>近 {trend.days} 天：身高 {trend.heightDelta == null ? '未完整记录' : `${trend.heightDelta >= 0 ? '+' : ''}${trend.heightDelta} cm`}，体重 {trend.weightDelta == null ? '未完整记录' : `${trend.weightDelta >= 0 ? '+' : ''}${trend.weightDelta} kg`}</p>}<p>参考标准：世界卫生组织儿童生长标准 2006</p><p>过敏相关：已关联 {allergyEvents.length + allergyProfile.length} 条记录</p><p>近期情况：已确认 {checked.length} 项背景；消化道或进食相关记录 {symptomEvents.length} 条</p></div><h2>接下来怎么做</h2><div className="growth-next-actions"><button onClick={() => navigate('/health-profile/growth')} type="button"><TrendingUp /><span>继续观察<small>按下一次测量继续记录</small></span></button><button onClick={() => navigate('/health-events')} type="button"><ClipboardList /><span>补充饮食替代<small>记录正在使用的替代食物</small></span></button><button onClick={() => navigate('/health-events')} type="button"><Stethoscope /><span>需要时带给医生<small>将这份整理用于就医准备</small></span></button></div><div className="growth-summary-actions"><button onClick={() => void addWatchTask()} type="button">加入守护任务</button><button onClick={() => navigate('/health-events')} type="button">用于就医准备</button></div>{actionNotice && <p aria-live="polite" className="growth-action-notice">{actionNotice}</p>}<p className="growth-disclaimer"><Info size={14} />这是成长信息整理，不替代医生判断。</p></div>}
  </main>
}
