import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

const home = readFileSync(new URL('./index.tsx', import.meta.url), 'utf8')
const healthEvents = readFileSync(new URL('../HealthEvents/index.tsx', import.meta.url), 'utf8')
const subjectHeader = readFileSync(new URL('../../components/health/HealthRecordSubjectHeader.tsx', import.meta.url), 'utf8')
const nurseStation = readFileSync(new URL('../NurseStation/index.tsx', import.meta.url), 'utf8')
const bloodTypeEditor = readFileSync(new URL('../NurseStation/BloodTypeEditorSheet.tsx', import.meta.url), 'utf8')
const editor = readFileSync(new URL('./BasicHealthProfilePage.tsx', import.meta.url), 'utf8')
const polish = readFileSync(new URL('../../styles/product-polish.css', import.meta.url), 'utf8')

test('健康档案首页复用健康随记的记录对象页头并直接衔接过敏记录', () => {
  assert.match(home, /HealthRecordSubjectHeader className="health-profile-record-subject"/)
  assert.match(healthEvents, /HealthRecordSubjectHeader className="health-events-member mx-4 mt-2"/)
  assert.match(subjectHeader, /journal-subject-row/)
  assert.match(subjectHeader, /就诊情况单/)
  assert.match(subjectHeader, /formatAgeFromBirthday/)
  assert.match(home, /待排查 \$\{pending\} · 已明确 \$\{confirmed\}/)
  assert.match(home, /数量暂不可用/)
  assert.doesNotMatch(home, /建议优先补充|搜索健康档案|重要健康事实/)
  assert.doesNotMatch(home, /已建立|growth-identity-card|更新成长数据|铸造成长身份卡|growth-identity-card__metrics|growth-identity-card__action|growth-identity-card__updated/)
  assert.match(home, /health-profile-record-subject[\s\S]*health-profile-entries/)
  assert.match(nurseStation, /nurse-station-growth-data/)
  assert.match(nurseStation, /openGrowthData[\s\S]*\/health-profile\/basic/)
  assert.match(nurseStation, /BloodTypeEditorSheet/)
  assert.doesNotMatch(bloodTypeEditor, /ProfileChoiceGroup label="RhD"/)
  assert.doesNotMatch(bloodTypeEditor, /当前：/)
  assert.match(bloodTypeEditor, /blood-type-sheet__heading/)
  assert.doesNotMatch(home, /makeMemberProfileOpenState|openMember/)
})

test('成长数据合并曲线、录入和记录列表入口', () => {
  assert.match(editor, /title="成长数据"/)
  assert.match(editor, /growth-record-list-entry/)
  assert.match(editor, /查看历史 · 编辑 · 删除/)
  assert.match(editor, /保存本次更新/)
  assert.match(editor, /已保存，并加入成长记录/)
  assert.match(editor, /growthMeasurementService\.upsert/)
  assert.match(editor, /heightMeasureLabel\(member\.birthday, measuredAt\)/)
  assert.match(editor, /<small>kg<\/small>/)
  assert.match(editor, /aria-label="测量日期"/)
  assert.doesNotMatch(editor, /growth-update-member|点击数值可手动编辑|<label>测量日期|<small>g<\/small>|血型/)
  assert.match(polish, /\.growth-data-content \{[^}]*align-content: start/)
  assert.doesNotMatch(editor, /今日成长落点|填写后自动保存|查看完整成长曲线|头围|腰围|体脂率/)
  assert.doesNotMatch(editor, /积分|签到|连续填写|超过.*用户/)
})

test('五类档案顺序固定，入口真实导航，智能记录合并报告入口', () => {
  assert.match(home, /title: '过敏史'[\s\S]*title: '慢性病史'[\s\S]*title: '家族史'[\s\S]*title: '手术史'[\s\S]*title: '疫苗接种记录'/)
  assert.match(home, /navigate\(`\/health-profile\/\$\{id\}`\)/)
  assert.match(home, /navigate\('\/health-profile\/smart-record'\)/)
  assert.match(home, /上传报告、回执或病历[\s\S]*自动整理到各项档案/)
  assert.doesNotMatch(home, /aria-disabled="true"|LockKeyhole|暂未开放|health-profile-allergy-card|检查 \/ 体检报告|住院 \/ 急诊史|家族遗传史|title="健康档案"/)
})
