import type { HelpArticle } from './types.js'

const updatedAt = '2026-08-27'

export const HELP_ARTICLES: HelpArticle[] = [
  { id:'email-code-missing', title:'为什么收不到邮箱验证码？', summary:'检查邮箱地址、垃圾邮件和重新发送间隔。', category:'账号与登录', keywords:['邮箱','验证码','登录','收不到'], aliases:['邮箱那个码没来','验证码一直不发','邮件码没收到'], conclusion:'多数情况下可通过核对邮箱、检查垃圾邮件并等待发送间隔解决。', steps:['确认邮箱地址没有输入错误。','检查垃圾邮件或广告邮件目录。','等待 60 秒后重新发送。','如果申请过多个验证码，以最后一次收到的验证码为准。'], commonCauses:['邮箱地址输入错误','邮件被邮箱服务商归入垃圾邮件','短时间内重复发送触发限制'], relatedArticleIds:['email-code-expired','change-login-email'], actions:[{label:'返回登录页面',to:'/login'}], updatedAt,status:'published',priority:100 },
  { id:'email-code-expired', title:'验证码显示已过期怎么办？', summary:'重新获取验证码，并使用最后一次收到的邮件。', category:'账号与登录', keywords:['验证码','过期','失效'], aliases:['码过期了','验证码不能用'], conclusion:'验证码过期后需要重新获取。', steps:['返回登录页面。','重新发送验证码。','使用最后一次收到的验证码完成登录。'], commonCauses:['验证码超过有效时间','使用了较早邮件中的验证码'], relatedArticleIds:['email-code-missing'], actions:[{label:'返回登录页面',to:'/login'}], updatedAt,status:'published',priority:70 },
  { id:'change-login-email', title:'如何修改登录邮箱？', summary:'当前版本暂不提供登录邮箱自助修改。', category:'账号与登录', keywords:['修改','登录','邮箱'], aliases:['换邮箱','邮箱写错了'], conclusion:'当前版本暂不支持自助修改登录邮箱，请通过产品反馈说明情况。', steps:['确认当前登录邮箱。','打开产品反馈。','不要在反馈描述中填写验证码或密码。'], actions:[{label:'反馈产品问题',to:'/feedback?category=账号与登录&page=帮助中心'}], relatedArticleIds:['email-code-missing'], updatedAt,status:'published' },
  { id:'login-session-expired', title:'登录状态失效后怎么办？', summary:'重新登录即可恢复访问，未提交内容可能需要重新填写。', category:'账号与登录', keywords:['登录','失效','退出','过期'], aliases:['突然退出了','让我重新登录'], conclusion:'登录状态过期后需要重新登录。', steps:['返回登录页面。','重新获取验证码并登录。','登录后返回原页面继续操作。'], actions:[{label:'重新登录',to:'/login'}], updatedAt,status:'published' },

  { id:'record-for-family', title:'如何为家人记录健康情况？', summary:'先切换到对应家庭成员，再创建或补充健康事件。', category:'家庭成员', keywords:['家人','家庭成员','记录','切换'], aliases:['给家里人记','帮孩子记录'], conclusion:'记录前先确认当前记录对象是正确的家庭成员。', steps:['进入家庭成员页面。','选择要记录的家庭成员。','返回健康事件并创建记录。'], actions:[{label:'查看家庭成员',to:'/family'}], relatedArticleIds:['change-record-member'], updatedAt,status:'published',priority:90 },
  { id:'add-family-member', title:'如何添加家庭成员？', summary:'在家庭成员页面添加姓名等必要信息。', category:'家庭成员', keywords:['添加','家人','家庭成员'], aliases:['新增家人','加孩子'], conclusion:'可从家庭成员页面添加新的记录对象。', steps:['打开家庭成员页面。','选择添加家庭成员。','填写必要信息并保存。'], actions:[{label:'添加家庭成员',to:'/family/new'}], updatedAt,status:'published' },
  { id:'edit-family-member', title:'如何修改家庭成员信息？', summary:'在家庭成员页面选择成员后编辑资料。', category:'家庭成员', keywords:['修改','家人','成员','资料'], aliases:['家人名字错了','修改孩子信息'], conclusion:'家庭成员资料可在成员详情中修改。', steps:['打开家庭成员页面。','选择需要修改的成员。','修改信息并保存。'], actions:[{label:'查看家庭成员',to:'/family'}], updatedAt,status:'published' },
  { id:'change-record-member', title:'如何修改记录所属的家庭成员？', summary:'当前版本不支持直接迁移记录，请先核对后再重新记录。', category:'家庭成员', keywords:['记录','写错人','所属','成员'], aliases:['我写错人了','记录放到家人那里了','记到别人名下'], conclusion:'当前版本暂不支持把既有记录直接迁移给另一位成员。', steps:['打开原记录核对内容。','为正确的家庭成员重新记录。','确认新记录无误后，再决定是否删除原记录。'], commonCauses:['记录前未核对当前成员','切换成员后页面仍停留在原流程'], actions:[{label:'查看家庭成员',to:'/family'}], relatedArticleIds:['delete-record'], updatedAt,status:'published',priority:95 },

  { id:'continue-health-event', title:'如何持续记录一个健康事件？', summary:'进入同一个健康事件，在时间线中继续补充变化。', category:'健康事件', keywords:['持续','健康事件','补充','变化'], aliases:['继续记','同一个事情接着写'], conclusion:'同一问题的后续变化应继续记录在原健康事件中。', steps:['打开健康事件列表。','进入对应健康事件。','在记录区域补充新的变化。'], actions:[{label:'查看健康事件',to:'/health-events'}], relatedArticleIds:['find-missing-record'], updatedAt,status:'published',priority:100 },
  { id:'create-health-event', title:'如何创建健康事件？', summary:'从健康事件首页开始，选择记录对象并描述情况。', category:'健康事件', keywords:['创建','新增','健康事件'], aliases:['新建事件','开始记录'], conclusion:'可从健康事件首页创建一项新的健康事件。', steps:['打开健康事件首页。','选择新建健康事件。','确认记录对象并描述情况。'], actions:[{label:'创建健康事件',to:'/health-events/new'}], updatedAt,status:'published' },
  { id:'edit-health-event', title:'如何修改健康事件？', summary:'进入健康事件详情，修改当前支持编辑的内容。', category:'健康事件', keywords:['修改','编辑','健康事件'], aliases:['事件写错了','改事件'], conclusion:'进入事件详情后可修改当前版本支持编辑的字段。', steps:['打开健康事件。','进入需要修改的事件详情。','选择可编辑内容并保存。'], actions:[{label:'查看健康事件',to:'/health-events'}], updatedAt,status:'published' },
  { id:'delete-health-event', title:'如何删除健康事件？', summary:'在事件详情确认对象和内容后执行删除。', category:'健康事件', keywords:['删除','健康事件'], aliases:['删掉事件','不要这个事件'], conclusion:'删除前请确认事件和记录对象，删除后可能无法恢复。', steps:['进入健康事件详情。','核对事件和所属成员。','使用页面提供的删除操作并确认。'], actions:[{label:'查看健康事件',to:'/health-events'}], updatedAt,status:'published' },

  { id:'find-missing-record', title:'如何查找健康事件或时间线记录？', summary:'先确认成员，再分别检查健康事件和事件详情时间线。', category:'记录与时间线', keywords:['找不到','记录','健康事件','时间线','不见了'], aliases:['我的记录不见了','昨天写的脚疼没了','记录去哪了'], conclusion:'记录可能位于其他成员或某个健康事件的时间线中。', steps:['确认当前选择的家庭成员。','在健康事件列表查找对应事件。','进入事件详情查看时间线记录。'], commonCauses:['当前查看的是另一位家庭成员','记录被补充在已有事件中','网络加载暂时失败'], actions:[{label:'查看健康事件',to:'/health-events'}], relatedArticleIds:['data-not-showing','change-record-member'], updatedAt,status:'published',priority:95 },
  { id:'change-record-time', title:'如何修改记录的时间？', summary:'在记录详情中修改实际发生时间，不能选择未来时间。', category:'记录与时间线', keywords:['修改','时间','发生时间','填错'], aliases:['时间填错了','日期写错了','改时间'], conclusion:'记录时间应按实际发生时间修改，未来时间不会被接受。', steps:['进入健康事件详情。','找到需要修改的时间线记录。','编辑发生时间并保存。'], commonCauses:['把创建时间误认为发生时间','选择了未来时间'], actions:[{label:'查看健康事件',to:'/health-events'}], updatedAt,status:'published',priority:90 },
  { id:'delete-record', title:'如何修改或删除一条记录？', summary:'在健康事件详情中找到该记录，再使用编辑或删除操作。', category:'记录与时间线', keywords:['修改','删除','记录','时间线'], aliases:['删记录','改一条记录'], conclusion:'单条记录的操作入口位于对应健康事件详情。', steps:['打开所属健康事件。','在时间线中找到目标记录。','选择编辑或删除并确认。'], actions:[{label:'查看健康事件',to:'/health-events'}], relatedArticleIds:['change-record-time'], updatedAt,status:'published',priority:80 },

  { id:'health-profile-missing', title:'为什么健康档案内容不完整？', summary:'健康档案来自已记录内容，先检查成员和原始记录。', category:'健康档案', keywords:['健康档案','不完整','缺少'], aliases:['档案少东西','档案没更新'], conclusion:'健康档案仅整理当前已有记录，不会自动补充未记录的信息。', steps:['确认当前家庭成员。','检查相关健康事件和记录是否存在。','返回健康档案重新查看。'], actions:[{label:'查看健康档案',to:'/health-profile'}], updatedAt,status:'published' },
  { id:'view-health-profile', title:'如何查看健康档案？', summary:'从主导航进入健康档案，查看当前成员的信息。', category:'健康档案', keywords:['查看','健康档案'], aliases:['档案在哪','我的档案'], conclusion:'健康档案按当前选择的家庭成员展示。', steps:['确认当前家庭成员。','打开健康档案。','选择需要查看的档案部分。'], actions:[{label:'查看健康档案',to:'/health-profile'}], updatedAt,status:'published' },
  { id:'data-not-showing', title:'为什么健康数据没有显示？', summary:'检查成员、记录位置和页面加载状态。', category:'健康档案', keywords:['数据','没有显示','空白','加载'], aliases:['页面什么都没有','数据不见了','一片空白'], conclusion:'先确认成员和记录是否正确；如果页面加载失败，可刷新后重试。', steps:['确认当前选择的家庭成员。','检查健康事件中是否已有对应记录。','刷新页面后重新进入健康档案。'], commonCauses:['当前成员没有相关记录','网络异常','记录位于其他成员名下'], actions:[{label:'查看健康档案',to:'/health-profile'}], relatedArticleIds:['find-missing-record'], updatedAt,status:'published',priority:90 },

  { id:'add-attachment', title:'如何添加图片或检查结果？', summary:'在健康事件详情中选择附件并上传支持的图片。', category:'图片与附件', keywords:['添加','图片','附件','检查结果','上传'], aliases:['传检查单','加照片'], conclusion:'图片和检查结果应添加到对应健康事件中。', steps:['打开对应健康事件。','进入附件区域。','选择支持的图片并确认上传。'], actions:[{label:'查看健康事件',to:'/health-events'}], relatedArticleIds:['attachment-upload-failed'], updatedAt,status:'published',priority:85 },
  { id:'attachment-upload-failed', title:'为什么附件上传失败？', summary:'检查图片格式、大小、网络和登录状态后重试。', category:'图片与附件', keywords:['附件','图片','上传','失败','没反应'], aliases:['图片点了没反应','照片传不上去','附件上传失败'], conclusion:'上传失败通常与文件格式、大小或网络状态有关。', steps:['确认文件为页面支持的图片格式。','检查网络连接和登录状态。','返回事件详情后重新选择文件。'], commonCauses:['文件格式不支持','文件过大','网络中断','登录状态已过期'], actions:[{label:'查看健康事件',to:'/health-events'}], relatedArticleIds:['add-attachment'], updatedAt,status:'published',priority:95 },
  { id:'attachment-privacy', title:'谁可以看到我上传的附件？', summary:'附件属于当前账户和对应记录，不用于公开展示。', category:'图片与附件', keywords:['附件','隐私','谁能看'], aliases:['照片会公开吗','图片安全吗'], conclusion:'附件仅用于 Hoooho 内对应记录，不应公开分享敏感链接。', steps:['确认附件所属的健康事件。','不要在反馈中粘贴附件地址。','如需删除，请进入原事件检查可用操作。'], relatedArticleIds:['privacy-data'], updatedAt,status:'published' },

  { id:'privacy-data', title:'Hoooho 如何保护我的数据？', summary:'产品仅按功能需要处理数据，帮助搜索不会自动读取健康记录。', category:'数据与隐私', keywords:['隐私','数据','安全','读取'], aliases:['数据安全吗','会看我的记录吗'], conclusion:'帮助中心只使用你主动输入的问题和非敏感页面信息，不会自动读取健康记录。', steps:['避免在帮助搜索中输入完整病情或验证码。','提交反馈前检查描述和截图。','在隐私设置中查看当前可用选项。'], actions:[{label:'查看隐私设置',to:'/settings/privacy'}], updatedAt,status:'published',priority:80 },
  { id:'export-data', title:'如何导出我的健康数据？', summary:'当前版本尚未提供可确认的自助导出能力。', category:'数据与隐私', keywords:['导出','数据','下载','拿出来'], aliases:['怎么把数据拿出来','下载我的数据','数据备份'], conclusion:'当前版本尚未提供经过验证的自助导出入口。', steps:['打开隐私设置确认当前可用能力。','如确有需要，通过产品反馈说明导出范围。','不要在反馈中复制完整健康详情。'], actions:[{label:'查看隐私设置',to:'/settings/privacy'},{label:'反馈产品问题',to:'/feedback?category=数据与隐私&page=帮助中心'}], updatedAt,status:'published',priority:85 },
  { id:'delete-data', title:'如何删除我的数据？', summary:'先在原记录中检查删除入口；账户级删除暂不自动执行。', category:'数据与隐私', keywords:['删除','数据','账号'], aliases:['清空数据','删掉所有东西'], conclusion:'单条记录可在对应页面处理；帮助中心不会自动执行账户级删除。', steps:['确认要删除的是单条记录、事件还是账户数据。','单条内容请回到原页面操作。','账户级请求请通过产品反馈说明范围。'], actions:[{label:'查看隐私设置',to:'/settings/privacy'},{label:'反馈产品问题',to:'/feedback?category=数据与隐私&page=帮助中心'}], relatedArticleIds:['delete-record','delete-health-event'], updatedAt,status:'published',priority:75 },
  { id:'no-diagnosis', title:'Hoooho 会不会给出诊断？', summary:'Hoooho 用于记录和整理信息，不提供诊断或用药建议。', category:'数据与隐私', keywords:['诊断','医疗建议','用药'], aliases:['能看病吗','帮我诊断'], conclusion:'Hoooho 不提供疾病诊断、处方、剂量或停药建议。', steps:['记录当前情况和实际发生时间。','整理已有检查与记录。','如情况紧急，及时联系当地急救服务或专业医疗人员。'], actions:[{label:'记录当前情况',to:'/health-events/new'},{label:'查看健康事件',to:'/health-events'}], updatedAt,status:'published',priority:100 },

  { id:'page-load-failed', title:'页面加载失败或一直空白怎么办？', summary:'检查网络和登录状态，刷新后仍失败可提交反馈。', category:'故障排查', keywords:['页面','加载','空白','失败','网络'], aliases:['页面什么都没有','一直转圈','打不开'], conclusion:'先排除网络和登录问题；持续失败时记录页面和非敏感错误码。', steps:['检查网络是否可用。','刷新页面并重新登录。','记录出错页面和非敏感错误码后提交反馈。'], actions:[{label:'反馈产品问题',to:'/feedback?category=故障排查&page=帮助中心'}], relatedArticleIds:['data-not-showing'], updatedAt,status:'published',priority:80 },
  { id:'operation-not-saved', title:'操作后内容没有保存怎么办？', summary:'确认网络和登录状态，避免连续重复提交。', category:'故障排查', keywords:['保存','失败','没反应','重复提交'], aliases:['点了没保存','内容丢了'], conclusion:'保存失败时先保留当前内容，再检查网络和登录状态。', steps:['不要连续点击提交。','复制尚未提交的文字以免丢失。','检查网络和登录状态后重试。'], actions:[{label:'反馈产品问题',to:'/feedback?category=故障排查&page=帮助中心'}], updatedAt,status:'published' },
  { id:'browser-compatibility', title:'哪些浏览器可以使用 Hoooho？', summary:'请使用较新的主流浏览器，并允许页面所需权限。', category:'故障排查', keywords:['浏览器','兼容','微信'], aliases:['微信里不能用','浏览器不支持'], conclusion:'较新的主流浏览器通常可正常使用；内置浏览器的权限能力可能不同。', steps:['更新当前浏览器。','检查浏览器权限设置。','仍失败时换用系统浏览器并提交反馈。'], actions:[{label:'反馈产品问题',to:'/feedback?category=故障排查&page=帮助中心'}], updatedAt,status:'published' }
]

export const PUBLISHED_HELP_ARTICLES = HELP_ARTICLES.filter((article) => article.status === 'published')
