import { expect,test,type Page } from '@playwright/test'
import { TokenService } from '../../server/auth/token-service.mjs'
const token=new TokenService('help-e2e-local-only-secret',60*60_000).create({id:'help-test'})
test.beforeEach(async({page})=>{
  await page.addInitScript(token=>{
    sessionStorage.setItem('hoooho-auth-token',token)
    localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:'help-test'},members:[],currentMemberId:'self'},version:5}))
  },token)
})
async function chat(page:Page){
  await page.goto('/help?view=chat')
  await expect(page.getByLabel('描述遇到的问题')).toBeVisible()
  await page.getByRole('button',{name:'新对话',exact:true}).click()
  await expect(page.getByRole('button',{name:'录音没有成功',exact:true})).toBeVisible()
}
test('single sidebar entry, two pages, relevant search and existing guide redirect',async({page})=>{
  await page.goto('/help')
  await page.getByRole('button',{name:'打开菜单'}).click()
  await expect(page.getByRole('button',{name:'帮助',exact:true})).toHaveCount(1)
  await expect(page.getByRole('button',{name:'说明',exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'帮助',exact:true}).click()
  await page.getByLabel('搜索教程和问题').fill('宇宙飞船发动机')
  await expect(page.getByText('暂时没有找到相关内容。',{exact:false})).toBeVisible()
  await page.getByLabel('搜索教程和问题').fill('录音')
  await expect(page.getByText('录音没反应或转写失败怎么办？',{exact:true})).toBeVisible()
  await page.getByRole('radio',{name:'用户手册',exact:true}).click()
  await expect(page.getByText('认识 Hoooho 的功能',{exact:true})).toBeVisible()
  await page.getByRole('radio',{name:'帮助',exact:true}).click()
  await expect(page.getByLabel('搜索教程和问题')).toHaveValue('录音')
  await page.goto('/guide')
  await expect(page).toHaveURL(/\/help\?tab=manual/)
  await page.getByText('智能记录',{exact:true}).click()
  await expect(page.getByText('为什么设计这个功能',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'查看操作帮助',exact:true}).click()
  await expect(page.getByRole('heading',{name:'怎么做',exact:true})).toBeVisible()
  await expect(page.getByRole('link',{name:'去智能记录',exact:true})).toHaveAttribute('href','/smart-record')
})
test('conversation, draft and article return survive switching; unresolved feedback survives reload',async({page})=>{
  await chat(page)
  await page.getByRole('button',{name:'录音没有成功',exact:true}).click()
  await expect(page.getByRole('button',{name:'录音后转写失败',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'录音后转写失败',exact:true}).click()
  await expect(page.getByRole('button',{name:'还没解决',exact:true})).toBeVisible()
  await page.getByLabel('描述遇到的问题').fill('补充内容尚未发送')
  await page.getByRole('radio',{name:'用户手册',exact:true}).click()
  await page.getByRole('radio',{name:'帮助',exact:true}).click()
  await expect(page.getByLabel('描述遇到的问题')).toHaveValue('补充内容尚未发送')
  await page.getByRole('button',{name:'录音没反应或转写失败怎么办？',exact:true}).last().click()
  await expect(page.getByRole('heading',{name:'怎么做',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'返回',exact:true}).click()
  await expect(page.getByLabel('描述遇到的问题')).toHaveValue('补充内容尚未发送')
  await page.getByRole('button',{name:'还没解决',exact:true}).click()
  await expect(page.getByText('那我们继续排查。',{exact:false})).toBeVisible()
  await page.reload()
  await expect(page.getByText('那我们继续排查。',{exact:false})).toBeVisible()
  await expect(page.getByText('还没解决',{exact:true})).toBeVisible()
})
test('failed send preserves input and explicit retry uses same request identifier once',async({page})=>{
  await chat(page)
  const requests:string[]=[]
  await page.route('**/api/help/sessions/*/turns',async route=>{
    requests.push(route.request().postDataJSON().requestId)
    if(requests.length===1)await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'测试网络中断'}})})
    else await route.continue()
  })
  await page.getByLabel('描述遇到的问题').fill('录音后转写失败')
  await page.getByRole('button',{name:'发送问题'}).click()
  await expect(page.getByText('测试网络中断')).toBeVisible()
  await expect(page.getByLabel('描述遇到的问题')).toHaveValue('录音后转写失败')
  await page.getByRole('button',{name:'重试',exact:true}).click()
  await expect(page.getByRole('button',{name:'解决了',exact:true})).toBeVisible()
  expect(requests).toHaveLength(2);expect(requests[1]).toBe(requests[0])
  await expect(page.locator('.help-chat-turn[data-role="user"]')).toHaveCount(1)
  await page.getByRole('button',{name:'解决了',exact:true}).click()
  await expect(page.getByText('感谢你告诉我结果。',{exact:false})).toBeVisible()
})
test('help, manual and chat fit 320–430px mobile viewports',async({page})=>{
  for(const width of [320,390,430]){
    await page.setViewportSize({width,height:844})
    for(const [name,url]of [['home','/help'],['manual','/help?tab=manual&manual=smart'],['chat','/help?view=chat']]){
      await page.goto(url)
      if(name==='chat')await expect(page.getByLabel('描述遇到的问题')).toBeVisible()
      await expect(page.getByRole('radio',{name:'用户手册',exact:true})).toBeVisible()
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
      expect(await page.locator('.help-content').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true)
      await page.locator('.help-content').evaluate(e=>e.scrollTop=e.scrollHeight)
      await expect(page.getByRole('radio',{name:'用户手册',exact:true})).toBeInViewport()
      await page.screenshot({path:`test-results/help-center/${name}-${width}.png`,fullPage:true})
    }
  }
})
