import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { HohoButton } from '../../components/design-system'
import { RecordOriginals } from '../ai-business/RecordOriginals'
import type { HealthEventRecordApiDto } from '../../types'
import { useCases } from './useCases'
import { caseService } from './api'
import './cases.css'
export const identityLabels = { parent: '家长原话', medical_consultation: '医生问诊消息', examination_report: '检查报告', external_ai: '外部AI参考答复（不是医嘱）', pending: '资料身份待核对' }
const resultLabels = { improved: '改善', unchanged: '无变化', worse: '加重', not_observed: '未观察' }
export function CaseActions({ eventId, records }: { eventId: string; records: HealthEventRecordApiDto[] }) {
  const { data, error, reload, memberId, token } = useCases(), [busy, setBusy] = useState(false), [failure, setFailure] = useState(''), pending = useRef(false)
  const item = [...(data?.active ?? []), ...(data?.archived ?? [])].find(c => c.event.id === eventId)
  async function act(operation: () => Promise<unknown>) { if (pending.current) return; pending.current = true; setBusy(true); setFailure(''); try { await operation(); reload() } catch (e) { setFailure(e instanceof Error ? e.message : '操作未完成，请重试') } finally { pending.current = false; setBusy(false) } }
  return <section aria-label="这次情况的跟进操作">
    <div className="continuity-actions"><Link to={`/smart-record?eventId=${eventId}`}>接着这次记</Link><Link to={`/cases/${eventId}/materials`}>带回问诊资料</Link><Link to={`/visit-summary/${eventId}`}>就诊情况单</Link><Link to="/cases/compare">对比两次情况</Link>{!item?.event.caseArchivedAt && <Link to={`/cases/${eventId}/observation`}>安排观察</Link>}{item && <HohoButton variant="text" disabled={busy} onClick={() => { if (window.confirm(`${item.event.caseArchivedAt ? '恢复跟进' : '归档'}“${item.event.title}”？${item.event.caseArchivedAt ? '不会自动恢复已暂停或到期的观察。' : '保留记录并暂停本次观察；不表示康复，也不会改变用药提醒。'}`)) void act(() => caseService.archive(memberId, token, eventId, !item.event.caseArchivedAt)) }}>{item.event.caseArchivedAt ? '恢复跟进' : '归档情况'}</HohoButton>}</div>
    {(failure || error) && <p role="alert">{failure || error}<HohoButton variant="text" onClick={reload}>重试加载</HohoButton></p>}
    {item?.observations.map(task => <article className="continuity-card" key={task.id}><h3>观察：{task.item}</h3><p>每天{task.timesPerDay}次 · {task.startsOn}至{task.endsOn}</p><small>{task.source === 'doctor_confirmed' ? `医生已确认要求：${task.sourceReference?.quote} · 第${task.sourceReference?.page}页` : '家长自行安排，非医嘱'}</small><p>{task.state === 'active' ? task.todayRecorded ? `今日已记录${task.todayRecorded}/${task.todayTarget}` : '今日待记录' : ({ expired:'观察已到期', scheduled:'尚未开始', paused:'已暂停', ended:'已结束' } as const)[task.state]}</p>{!item.event.caseArchivedAt && <div className="continuity-card__links">{task.state === 'active' && <Link to={`/smart-record?eventId=${eventId}&taskId=${task.id}`}>记录今天的变化</Link>}<Link to={`/cases/${eventId}/observation?taskId=${task.id}`}>调整／延长</Link>{task.status !== 'ended' && <HohoButton variant="text" disabled={busy} onClick={() => { if (window.confirm(`结束观察“${task.item}”？保留既有记录，不代表情况已恢复。`)) void act(() => caseService.observation(memberId, token, eventId, { id: task.id, action: 'end' })) }}>结束</HohoButton>}{task.status === 'active' && <HohoButton variant="text" disabled={busy} onClick={() => { if (window.confirm(`暂停“${task.item}”？`)) void act(() => caseService.observation(memberId, token, eventId, { id: task.id, action: 'pause' })) }}>暂停</HohoButton>}</div>}</article>)}
    {records.filter(r => r.caseContext).map(record => <details className="continuity-card" key={record.id}><summary>{identityLabels[record.caseContext!.identity]}{record.caseContext!.confirmed ? ' · 已核对' : ' · 原始记录'}{record.caseContext?.result ? ` · ${resultLabels[record.caseContext.result]}` : ''}</summary><p>{record.caseContext?.timeUnknown ? '发生时间未提供' : new Date(record.occurredAt).toLocaleString()}</p>{record.caseContext?.supplement && <p>{record.caseContext.supplement}</p>}{!!record.caseContext?.bodyLocations?.length && <p>部位：{record.caseContext.bodyLocations.join('、')}</p>}<p className="continuity-source">{record.sourceText || record.caseContext?.originalText || record.content}</p><div className="continuity-originals"><RecordOriginals eventId={eventId} attachmentIds={record.caseContext!.attachmentIds}/></div>{<Link to={`/cases/${eventId}/materials?recordId=${record.id}`}>整理记录／核对来源</Link>}</details>)}
  </section>
}
