import { useState } from 'react'
import { BottomSheetSurface, HohoButton } from '../../components/design-system'
import type { VisitSheetUpdate } from '../../services/visitSheets'
import { localDateTimeToIso, localDateTimeValue } from '../../utils/healthOccurredAt'
import { useCases } from './useCases'
export function ReportScopeSheet({ initial, onClose, onSave, busy, error }: { initial?: VisitSheetUpdate['selection']; onClose:()=>void; onSave:(selection:NonNullable<VisitSheetUpdate['selection']>)=>Promise<void>; busy:boolean; error:string }) {
  const { data, error:loadError,reload } = useCases(), items = [...(data?.active ?? []), ...(data?.archived ?? [])]
  const [eventIds,setEventIds] = useState(initial?.eventIds ?? []), [background,setBackground] = useState(initial?.includeBackground ?? false), [from,setFrom] = useState(initial?.from ? localDateTimeValue(new Date(initial.from)) : ''), [to,setTo] = useState(initial?.to ? localDateTimeValue(new Date(initial.to)) : '')
  return <BottomSheetSurface open title="选择本次资料范围" label="选择本次资料范围" onClose={onClose} footer={<HohoButton disabled={busy || !data || !eventIds.length} loading={busy} fullWidth onClick={()=>void onSave({eventIds,includeBackground:background,...(from?{from:localDateTimeToIso(from)!}:{}),...(to?{to:localDateTimeToIso(to)!}:{})})}>确认范围并更新情况单</HohoButton>}><div className="continuity-form p-4"><p>仅纳入所选情况与时间；资料范围变化需确认。</p>{loadError?<button onClick={reload}>重试加载情况</button>:!data?<p>加载中…</p>:items.map(item=><label key={item.event.id}><span><input style={{width:'auto'}} type="checkbox" checked={eventIds.includes(item.event.id)} onChange={e=>setEventIds(ids=>e.target.checked?[...ids,item.event.id]:ids.filter(id=>id!==item.event.id))}/>{item.event.title}{item.event.caseArchivedAt?'（已归档）':''}</span></label>)}<label>从（选填）<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>到（选填）<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label><label><span><input style={{width:'auto'}} type="checkbox" checked={background} onChange={e=>setBackground(e.target.checked)}/> 纳入当前人物的既往资料、成长数据及独立计划（可不选）</span></label>{error&&<p role="alert">{error}</p>}</div></BottomSheetSurface>
}
