import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = read('./index.tsx')
const firstMember = read('./FirstMemberFrontDesk.tsx')
const nurse = read('./NurseQuickRecord.tsx')
const trigger = read('../../components/health/QuickRecordTrigger.tsx')
const desk = read('./NurseTriageDesk.tsx')
const idleVisual = read('./IdleNurseVisual.tsx')
const flow = read('../HealthEventDetail/components/QuickVoiceRecordFlow.tsx')
const photos = read('../HealthEventDetail/components/QuickRecordPhotos.tsx')
const photoStyles = read('./NurseQuickRecord.css')
const dietFlow = read('./DietRecordFlow.tsx')
const journalRecorder = read('./JournalRecorder.tsx')
const family = read('../Family/index.tsx')
const login = read('../Login/index.tsx')
const router = read('../../app/router.tsx')
const requireAuth = read('../../components/auth/RequireAuth.tsx')
const styles = read('../../styles/index.css')

test('前台视图成为默认主入口并保留显式列表切换', () => {
  assert.match(router, /path: '\/', element: <Navigate to="\/health-events" replace/)
  assert.match(page, /DEFAULT_HEALTH_EVENTS_VIEW_MODE/)
  assert.match(page, /health-events-view-switch/)
  assert.match(page, /\['triage', 'list'\]/)
  assert.doesNotMatch(page, /FirstUseHome|health-events-view-select__menu/)
})

test('零成员在前台内分流且不会预先创建空健康事件', () => {
  assert.match(firstMember, /先添加一位需要记录健康情况的人/)
  assert.match(firstMember, /为过敏儿童设计的健康连续记录/)
  assert.match(firstMember, /孩子发生什么，就记录什么/)
  assert.match(firstMember, /不用一次说完，有空了再补上/)
  assert.match(firstMember, /添加孩子信息/)
  assert.doesNotMatch(firstMember, /可以是你自己，也可以是家人|添加第一个家人|我是为自己记录/)
  assert.doesNotMatch(page, /familyMemberService\.createSelf|createSelfAndRecord/)
  assert.match(page, /entryState\.familyMemberCount === 0/)
  assert.doesNotMatch(page, /!state\.data\.entryState\.hasValidHealthRecord/)
  assert.doesNotMatch(page, /healthEventService\.create|pendingTriageEventRef|ensurePendingTriageEvent/)
  assert.match(family, /state: \{ openQuickRecord: true \}/)
  assert.doesNotMatch(family, /healthEventService\.create/)
})

test('快速记录留在前台核对并只在确认保存时调用原子接口', () => {
  assert.match(trigger, /快速记录/)
  assert.match(flow, /if \(!onPreviewRef\.current\)[\s\S]*setState\('review'\)/)
  assert.match(flow, />确认保存</)
  assert.match(flow, /继续核对/)
  assert.match(flow, />结束听写</)
  assert.match(page, /quickRecordService\.create/)
  assert.match(page, /idempotencyKey: submissionKeyRef\.current/)
  assert.match(page, /return '已记录'/)
  assert.doesNotMatch(page, /已为 \$\{currentMember\.name\} 保存/)
  assert.match(nurse, /setSavedNotice\('已记录'\)/)
  assert.doesNotMatch(nurse, /onPreview=/)
})

test('喂养饮食使用四类确认页、独立记录页和结构化真实保存', () => {
  assert.match(journalRecorder, /记录喂养\/饮食/)
  assert.match(journalRecorder, /母乳 \/ 配方奶/)
  assert.match(journalRecorder, /泥糊 \/ 颗粒 \/ 手指食物/)
  assert.match(journalRecorder, /早餐 \/ 午餐 \/ 晚餐/)
  assert.match(journalRecorder, /点心 \/ 水果 \/ 饮品/)
  assert.doesNotMatch(journalRecorder, /推荐|已按年龄优先显示/)
  assert.match(dietFlow, /记录喂养/)
  assert.match(dietFlow, /记录辅食/)
  assert.match(dietFlow, /记录正餐/)
  assert.match(dietFlow, /记录零食/)
  assert.match(dietFlow, /firstTryFoods/)
  assert.match(dietFlow, /useQuickRecordPhotos/)
  assert.match(dietFlow, /getSpeechRecognitionConstructor/)
  assert.match(dietFlow, /记录时间不能晚于现在/)
  assert.match(page, /journal,/)
  assert.match(page, /showJournalSavedNotice/)
})

test('快捷记录全过程保留连续待机视频且成功视频就绪后再交接', () => {
  assert.match(nurse, /idleActive=\{active\}/)
  assert.match(nurse, /state="idle"/)
  assert.doesNotMatch(nurse, /idleActive=\{!open\}|state=\{triageState\}/)
  assert.match(desk, /\{activeAsset && <img/)
  assert.doesNotMatch(desk, /allNurseTriageAssets\.map|preloadNurseTriageAssets/)
  assert.doesNotMatch(idleVisual, /poster=|<img|onLoadedData=|onPlaying=/)
  assert.match(idleVisual, /preload="none"/)
  assert.match(idleVisual, /createNursePlayback/)
  assert.match(idleVisual, /saved\(saveSuccessSequence\)/)
})

test('听写与核对态共享同一照片草稿且不改变护士视频状态机', () => {
  assert.equal((flow.match(/<QuickRecordPhotos model=\{photoModel\}/g) ?? []).length, 3)
  assert.match(flow, /presentation === 'nurse-inline'[\s\S]*setState\('text_entry'\)/)
  assert.match(flow, /navigator\.mediaDevices\.getUserMedia\(\{ audio: true \}\)/)
  assert.match(flow, /startingSessionRef\.current !== null \|\| recognitionRef\.current/)
  assert.match(flow, /photoModelRef\.current\.payload\(\)/)
  assert.doesNotMatch(flow, /\}, \[photoModel, presentation, scheduleClose\]\)/)
  assert.match(flow, /restartListening[\s\S]*startListening\(\)/)
  assert.doesNotMatch(flow, /restartListening[\s\S]{0,180}photoModel\.(cancel|clearAfterSave)/)
  assert.match(flow, /photoModel\.blocked/)
  assert.match(photos, /sessionStorage\.getItem/)
  assert.match(photos, /multiple/)
  assert.match(photos, /accept="image\/jpeg,image\/png,image\/webp"/)
  assert.match(photos, /QUICK_RECORD_PHOTO_LIMIT = 10/)
  assert.match(photos, /最多上传10张照片/)
  assert.match(photos, /重试上传/)
  assert.match(photos, /照片预览/)
  assert.match(flow, /catch \(reason\) \{[\s\S]*setState\(presentation === 'nurse-inline' \? 'review' : 'text_entry'\)[\s\S]*setInputError/)
  assert.match(flow, /setState\('saved'\)[\s\S]*photoModelRef\.current\.clearAfterSave\(\)/)
  assert.match(photoStyles, /quick-record-photos__rail[\s\S]*overflow-x:\s*auto/)
  assert.match(photoStyles, /quick-record-text-actions[\s\S]*grid-column:\s*1 \/ -1/)
  assert.match(photoStyles, /quick-record-keyboard-inset/)
  assert.match(nurse, /nurse-quick-record-backdrop/)
  assert.match(nurse, /data-hidden=\{open\}/)
  assert.doesNotMatch(nurse, /setState\(|pause\(|load\(/)
})

test('底部保留快速记录主动作和右侧下一步 Logo 按钮', () => {
  assert.match(nurse, /nurse-next-action-trigger/)
  assert.match(nurse, /aria-label="打开当前健康随记的下一步"/)
  assert.match(nurse, /<HealthTrace/)
  assert.doesNotMatch(nurse, /nurse-next-action-link|查看当前事件下一步/)
  assert.match(styles, /health-events-content--triage[\s\S]*min-height:\s*0/)
})

test('登录等待反馈只在服务端成功后开始且成功后安全返回原页面', () => {
  assert.match(login, /const result = await authService\.sendEmailCode[\s\S]*setCountdown\(result\.retryAfter\)/)
  assert.match(login, /autoComplete="one-time-code"/)
  assert.match(login, /18_000/)
  assert.match(login, /检查垃圾邮件/)
  assert.match(login, /location\.state\?\.from/)
  assert.match(login, /requestedPath\.startsWith\('\/'\)/)
  assert.doesNotMatch(login, /familyMemberService\.list/)
  assert.match(requireAuth, /location\.pathname\}\$\{location\.search\}\$\{location\.hash/)
  assert.match(login, /preload="metadata"/)
})

test('健康随记永久删除必须经过共享确认弹窗', () => {
  const card = read('../../components/health/HealthEventCard.tsx')
  const confirm = read('../../components/design-system/ConfirmDialog.tsx')
  assert.match(card, /<ConfirmDialog/)
  assert.match(card, /删除后无法恢复/)
  assert.match(confirm, /useDialogFocus/)
  assert.match(confirm, /usePageScrollLock/)
  assert.match(confirm, /Escape/)
})
