import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = read('./index.tsx')
const firstMember = read('./FirstMemberFrontDesk.tsx')
const nurse = read('./NurseQuickRecord.tsx')
const trigger = read('../../components/health/QuickRecordTrigger.tsx')
const desk = read('./NurseTriageDesk.tsx')
const idleVisual = read('./IdleNurseVisual.tsx')
const stationIdleVideo = read('./NurseStationIdleVideo.tsx')
const flow = read('../HealthEventDetail/components/QuickVoiceRecordFlow.tsx')
const photos = read('../HealthEventDetail/components/QuickRecordPhotos.tsx')
const photoStyles = read('./NurseQuickRecord.css')
const dietFlow = read('./DietRecordFlow.tsx')
const journalRecorder = read('./JournalRecorder.tsx')
const journalCategoryIcon = read('./JournalCategoryIcon.tsx')
const timeView = read('./TimeView.tsx')
const journalSearch = read('./JournalSearchPage.tsx')
const timeViewModel = read('./timeViewModel.ts')
const family = read('../Family/index.tsx')
const login = read('../Login/index.tsx')
const router = read('../../app/router.tsx')
const requireAuth = read('../../components/auth/RequireAuth.tsx')
const styles = read('../../styles/index.css')
const station = read('../NurseStation/index.tsx')

test('健康随身记与前台护士站共用就医准备按钮', () => {
  assert.match(page, /<MedicalPrepButton aria-label="就医准备" className="journal-subject-summary" label="就诊情况单"/)
  assert.doesNotMatch(page, />摘要生成<\/HohoButton>/)
  assert.match(station, /<MedicalPrepButton[^>]*disabled=\{unavailable\}/)
  assert.doesNotMatch(page, /journal-quick-record-action|aria-label="快捷记录"/)
  assert.doesNotMatch(station, />摘要生成<\/HohoButton>/)
})

test('前台护士站成为默认首页且健康随记保持独立', () => {
  assert.match(router, /path: '\/', element: <Navigate to="\/nurse-station" replace/)
  assert.match(router, /path: '\/nurse-station'/)
  assert.doesNotMatch(page, /health-events-view-switch|DEFAULT_HEALTH_EVENTS_VIEW_MODE/)
  assert.match(station, /<MainAppHeader title="前台"/)
})

test('零成员在护士站内分流且不会预先创建空健康事件', () => {
  assert.match(station, /欢迎来到 Hoooho/)
  assert.match(station, /把孩子零散的健康变化，<span>整理成连续记录<\/span>/)
  assert.match(station, /记下症状、用药和就医经过，<span>自动整理成时间线和问诊摘要。<\/span>/)
  assert.match(station, /随手记录[\s\S]*自动整理[\s\S]*就医时带走/)
  assert.match(station, /添加第一个孩子/)
  assert.match(station, /添加后即可开始记录/)
  assert.match(station, /<MainAppHeader title="前台" \/>[\s\S]*nurse-station-empty-member/)
  assert.doesNotMatch(station, /先添加孩子，护士站才能为TA提供服务/)
  assert.doesNotMatch(page, /familyMemberService\.createSelf|createSelfAndRecord/)
  assert.match(page, /entryState\.familyMemberCount === 0/)
  assert.doesNotMatch(page, /!state\.data\.entryState\.hasValidHealthRecord/)
  assert.doesNotMatch(page, /healthEventService\.create|pendingTriageEventRef|ensurePendingTriageEvent/)
  assert.doesNotMatch(family, /healthEventService\.create/)
})

test('护士站待确认事项不会停止前台空闲动画', () => {
  assert.match(station, /idleActive[^>]*state="idle"/)
  assert.equal((station.match(/stationIdleOnly/g) ?? []).length, 2)
  assert.doesNotMatch(station, /pending\.length \? 'awaitingConfirmation'/)
})

test('前台护士站只加载待机1并使用单视频原生无缝循环', () => {
  assert.match(stationIdleVideo, /nurse-station-idle-1\.mp4/)
  assert.match(stationIdleVideo, /nurse-station-idle-1-poster\.webp/)
  assert.equal((stationIdleVideo.match(/<video/g) ?? []).length, 1)
  assert.match(stationIdleVideo, /autoPlay=\{active && !reducedMotion\}/)
  assert.match(stationIdleVideo, /loop/)
  assert.match(stationIdleVideo, /muted/)
  assert.match(stationIdleVideo, /playsInline/)
  assert.match(stationIdleVideo, /preload="auto"/)
  assert.match(stationIdleVideo, /data-video-phase="idle1"/)
  assert.match(stationIdleVideo, /removeAttribute\('src'\)[\s\S]*video\.load\(\)/)
  assert.match(stationIdleVideo, /pointerdown[\s\S]*retryAfterGesture/)
  assert.doesNotMatch(stationIdleVideo, /intro|idle-loop-2|setInterval|onEnded|transition/)
})

test('快速记录留在前台核对并只在确认保存时调用原子接口', () => {
  assert.match(trigger, /快速记录/)
  assert.match(flow, /if \(!onPreviewRef\.current\)[\s\S]*setState\('review'\)/)
  assert.match(flow, />确认保存</)
  assert.match(flow, /继续核对/)
  assert.match(flow, />结束听写</)
  assert.match(page, /quickRecordService\.create/)
  assert.match(page, /idempotencyKey: submissionKeyRef\.current/)
  assert.match(page, /message: '已记录'/)
  assert.doesNotMatch(page, /已为 \$\{currentMember\.name\} 保存/)
  assert.match(nurse, /setSavedNotice\('已记录'\)/)
  assert.doesNotMatch(nurse, /onPreview=/)
})

test('日常入口只保留八种真实表单并支持补充症状', () => {
  for (const label of ['饮食', '母乳亲喂', '配方奶', '瓶喂母乳', '辅食', '营养补剂', '睡眠', '排便']) assert.match(journalRecorder, new RegExp(`title: '${label}'`))
  assert.match(journalRecorder, /initialFeedingMethod=/)
  assert.match(dietFlow, /补充症状信息/)
  assert.match(dietFlow, /实际发生时间/)
  assert.doesNotMatch(dietFlow, /feedingStatusOptions|reactionOptions|firstTryFoods/)
  assert.match(page, /journal,/)
  assert.match(page, /showJournalSavedNotice/)
})

test('进食入口保留通用勺子且时间线按具体饮食类型显示语义图标', () => {
  assert.match(timeViewModel, /\['diet', '进食'\]/)
  assert.doesNotMatch(timeViewModel, /\['diet', '喂养\/饮食'\]/)
  assert.match(journalCategoryIcon, /kind === 'feeding'[\s\S]*<FeedingBottleIcon/)
  assert.match(journalCategoryIcon, /kind === 'snack'[\s\S]*<Apple/)
  assert.match(journalCategoryIcon, /kind === 'meal'[\s\S]*<CookingPot/)
  assert.match(journalCategoryIcon, /kind === 'supplement'[\s\S]*<SupplementBottleIcon/)
  assert.match(journalCategoryIcon, /return <SpoonIcon/)
  assert.match(journalCategoryIcon, /journal-category-icon--spoon/)
  assert.match(timeView, /dietKind=\{entry\.diet\?\.kind\}/)
  assert.match(journalSearch, /dietKind=\{entry\.diet\?\.kind\}/)
  assert.match(journalRecorder, /title: '母乳亲喂'/)
})

test('健康随记日期栏只保留单日导航并直接切换列表与缩略图', () => {
  assert.doesNotMatch(timeView, /'day' \| 'month'|切换到月视图|切换到日视图|这个月还没有记录|shiftMonth/)
  assert.match(timeView, /const groups = journalDayGroups\(entries, day, localSortOrder\)/)
  assert.match(timeView, /aria-label="前一天"/)
  assert.match(timeView, /aria-label="后一天"/)
  assert.match(timeView, /当前为列表视图，点击切换为缩略图视图/)
  assert.match(timeView, /当前为缩略图视图，点击切换为列表视图/)
  assert.match(timeView, /已切换为列表视图/)
  assert.match(timeView, /已切换为缩略图视图/)
  assert.match(timeView, /data-layout-mode=\{layoutMode\}/)
  assert.match(timeView, /data-record-id=\{entry\.id\}/)
})

test('快捷记录全过程保留连续待机视频且成功视频就绪后再交接', () => {
  assert.match(nurse, /idleActive=\{active\}/)
  assert.match(nurse, /state="idle"/)
  assert.doesNotMatch(nurse, /idleActive=\{!open\}|state=\{triageState\}/)
  assert.match(desk, /\{activeAsset && <img/)
  assert.doesNotMatch(desk, /allNurseTriageAssets\.map|preloadNurseTriageAssets/)
  assert.doesNotMatch(idleVisual, /poster=|<img|onLoadedData=|onPlaying=/)
  assert.match(idleVisual, /preload="none"/)
  assert.match(idleVisual, /createNursePlayback/)
  assert.match(idleVisual, /saved\(saveSuccessSequence\)/)
})

test('听写与核对态共享同一照片草稿且不改变护士视频状态机', () => {
  assert.equal((flow.match(/<QuickRecordPhotos model=\{photoModel\}/g) ?? []).length, 3)
  assert.match(flow, /presentation === 'nurse-inline'[\s\S]*setState\('text_entry'\)/)
  assert.match(flow, /navigator\.mediaDevices\.getUserMedia\(\{ audio: true \}\)/)
  assert.match(flow, /startingSessionRef\.current !== null \|\| recognitionRef\.current/)
  assert.match(flow, /photoModelRef\.current\.payload\(\)/)
  assert.doesNotMatch(flow, /\}, \[photoModel, presentation, scheduleClose\]\)/)
  assert.match(flow, /restartListening[\s\S]*startListening\(\)/)
  assert.doesNotMatch(flow, /restartListening[\s\S]{0,180}photoModel\.(cancel|clearAfterSave)/)
  assert.match(flow, /photoModel\.blocked/)
  assert.match(photos, /sessionStorage\.getItem/)
  assert.match(photos, /multiple/)
  assert.match(photos, /accept="image\/jpeg,image\/png,image\/webp"/)
  assert.match(photos, /QUICK_RECORD_PHOTO_LIMIT = 10/)
  assert.match(photos, /最多上传10张照片/)
  assert.match(photos, /重试上传/)
  assert.match(photos, /照片预览/)
  assert.match(flow, /catch \(reason\) \{[\s\S]*setState\(presentation === 'nurse-inline' \? 'review' : 'text_entry'\)[\s\S]*setInputError/)
  assert.match(flow, /setState\('saved'\)[\s\S]*photoModelRef\.current\.clearAfterSave\(\)/)
  assert.match(photoStyles, /quick-record-photos__rail[\s\S]*overflow-x:\s*auto/)
  assert.match(photoStyles, /quick-record-text-actions[\s\S]*grid-column:\s*1 \/ -1/)
  assert.match(photoStyles, /quick-record-keyboard-inset/)
  assert.match(nurse, /nurse-quick-record-backdrop/)
  assert.match(nurse, /data-hidden=\{open\}/)
  assert.doesNotMatch(nurse, /setState\(|pause\(|load\(/)
})

test('底部保留快速记录主动作和右侧下一步 Logo 按钮', () => {
  assert.match(nurse, /nurse-next-action-trigger/)
  assert.match(nurse, /aria-label="打开当前健康随记的下一步"/)
  assert.match(nurse, /<HealthTrace/)
  assert.doesNotMatch(nurse, /nurse-next-action-link|查看当前事件下一步/)
  assert.match(styles, /health-events-content--triage[\s\S]*min-height:\s*0/)
})

test('登录注册只在服务端成功后建立会话且安全返回原页面', () => {
  assert.match(login, /const result = await authService\.sendEmailCode[\s\S]*setCountdown\(result\.retryAfter\)/)
  assert.match(login, /autoComplete="one-time-code"/)
  assert.match(login, /authService\.register/)
  assert.match(login, /authService\.loginWithPassword/)
  assert.match(login, /location\.state\?\.from/)
  assert.match(login, /requested\.startsWith\('\/'\)/)
  assert.doesNotMatch(login, /familyMemberService\.list/)
  assert.match(requireAuth, /location\.pathname\}\$\{location\.search\}\$\{location\.hash/)
  assert.doesNotMatch(login, /login-family-care|<video/)
})

test('健康随记永久删除必须经过共享确认弹窗', () => {
  const card = read('../../components/health/HealthEventCard.tsx')
  const confirm = read('../../components/design-system/ConfirmDialog.tsx')
  assert.match(card, /<ConfirmDialog/)
  assert.match(card, /删除后无法恢复/)
  assert.match(confirm, /useDialogFocus/)
  assert.match(confirm, /usePageScrollLock/)
  assert.match(confirm, /Escape/)
})
