import { ArrowLeft, Bell, Camera, Check, ChevronRight, Circle, Minus, Pill, Plus, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { BottomSheetSurface, HohoButton } from '../../components/design-system'
import type { JournalMedicationDetails, JournalMedicationItem, JournalMetadata, MedicationReminder } from '../../types/journal'
import { localDateTimeValue } from '../../utils/healthOccurredAt'
import { QuickRecordPhotos, useQuickRecordPhotos, type QuickRecordPhotoPayload } from '../HealthEventDetail/components/QuickRecordPhotos'
import { medicationSummary, medicationUnits, normalizeDose } from './medicationRecordLogic'

type SaveRecord = (content: string, occurredAt: string, channel: 'text', photos: QuickRecordPhotoPayload, journal: JournalMetadata) => Promise<string>
type DraftDrug = JournalMedicationItem & { photoLocalIds?: string[] }
type Draft = { medications: DraftDrug[]; activeId: string; occurredAt: string }
const newReminder = (): MedicationReminder => ({ enabled: false, frequency: 'daily', timesPerDay: 3, times: ['08:00', '14:00', '20:00'], durationDays: 5 })
const newDrug = (): DraftDrug => ({ id: crypto.randomUUID(), medicationName: '', amountValue: 0, amountUnit: 'mL', dosageStep: 0.5, reminder: newReminder(), recognitionStatus: 'not_used' })
const blankDraft = (): Draft => { const item = newDrug(); return { medications: [item], activeId: item.id, occurredAt: localDateTimeValue() } }
const keyFor = (memberId: string) => `hoooho-medication-record-v2:${memberId}`
const frequencies = [['daily', '每天'], ['interval_hours', '每隔几小时'], ['weekly', '每周'], ['custom', '自定义']] as const
const units = medicationUnits.filter((unit) => ['mL', 'mg', '片', '粒', '袋', '滴', '揿'].includes(unit))
const complete = (item: DraftDrug) => Boolean(item.medicationName.trim() && item.amountValue > 0 && item.amountUnit)

function formatOccurredAt(value: string) {
  const date = new Date(value); if (!Number.isFinite(date.getTime())) return '请选择时间'
  const now = new Date(); const clock = `${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
  return date.toDateString() === now.toDateString() ? `今天 ${clock}` : `${date.getFullYear()}年${date.getMonth() + 1}月${date.getDate()}日 ${clock}`
}

export function MedicationRecordFlow({ memberId, token, initialMedication, initialOccurredAt, onBack, onClose, onConfirm, onSaved }: { memberId: string; token: string; initialMedication?: JournalMedicationDetails; initialOccurredAt?: string; onBack: () => void; onClose: () => void; onConfirm: SaveRecord; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(() => { if (initialMedication) { const medications = initialMedication.medications?.length ? initialMedication.medications : [{ id: crypto.randomUUID(), medicationName: initialMedication.medicationName, amountValue: initialMedication.amountValue ?? 0, amountUnit: initialMedication.amountUnit ?? 'mL', dosageStep: 0.5 as const, reminder: newReminder() }]; return { medications, activeId: medications[0].id, occurredAt: initialOccurredAt ? localDateTimeValue(new Date(initialOccurredAt)) : localDateTimeValue() } } try { const saved = JSON.parse(sessionStorage.getItem(keyFor(memberId)) ?? 'null'); return saved?.medications?.length ? saved : blankDraft() } catch { return blankDraft() } })
  const [reminderOpen, setReminderOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const cameraRef = useRef<HTMLInputElement>(null); const timeRef = useRef<HTMLInputElement>(null)
  const photos = useQuickRecordPhotos(memberId, token, 6, 'medication-v2')
  const active = draft.medications.find((item) => item.id === draft.activeId) ?? draft.medications[0]
  const reminder = { ...newReminder(), ...active.reminder }
  useEffect(() => { sessionStorage.setItem(keyFor(memberId), JSON.stringify(draft)) }, [draft, memberId])
  const updateActive = (changes: Partial<DraftDrug>) => { setDraft((current) => ({ ...current, medications: current.medications.map((item) => item.id === current.activeId ? { ...item, ...changes } : item) })); setError('') }
  const updateReminder = (changes: Partial<MedicationReminder>) => updateActive({ reminder: { ...newReminder(), ...active.reminder, ...changes } })
  const addDrug = () => { const item = newDrug(); setDraft((current) => ({ ...current, medications: [...current.medications, item], activeId: item.id })); setReminderOpen(false); setError('') }
  const removeDrug = () => { if (draft.medications.length === 1 || !window.confirm('删除当前药品？已填写的内容将不会保存。')) return; setDraft((current) => { const medications = current.medications.filter((item) => item.id !== current.activeId); return { ...current, medications, activeId: medications[0].id } }); setError('') }
  const choosePackage = (files: FileList | null) => { const localIds = photos.chooseFiles(files); if (localIds.length) updateActive({ photoLocalIds: [...(active.photoLocalIds ?? []), ...localIds], recognitionSource: 'camera', recognitionStatus: 'draft_unverified' }) }
  const changeCount = (delta: number) => { const count = Math.min(12, Math.max(1, reminder.timesPerDay + delta)); const defaults = ['08:00', '14:00', '20:00', '22:00']; updateReminder({ timesPerDay: count, times: Array.from({ length: count }, (_, index) => reminder.times[index] ?? defaults[index] ?? '08:00') }) }
  const save = async () => {
    const invalid = draft.medications.find((item) => !complete(item)); if (invalid) { setDraft((current) => ({ ...current, activeId: invalid.id })); setError(!invalid.medicationName.trim() ? '请选择或填写药品' : '请填写本次用量'); return }
    const timestamp = Date.parse(draft.occurredAt); if (!Number.isFinite(timestamp) || timestamp > Date.now()) { setError('记录时间不能晚于现在'); return }
    setSaving(true); setError('')
    try { const medications = draft.medications.map(({ photoLocalIds = [], ...item }) => ({ ...item, medicationName: item.medicationName.trim(), photoIds: photos.photos.filter((photo) => photoLocalIds.includes(photo.localId) && photo.serverId).map((photo) => photo.serverId!) })); const first = medications[0]; const details: JournalMedicationDetails = { medications, medicationName: first.medicationName, amountValue: first.amountValue, amountUnit: first.amountUnit, administrationRoute: 'oral' }; await onConfirm(medicationSummary(details), new Date(timestamp).toISOString(), 'text', photos.payload(), { categories: ['medication'], medication: details }); photos.clearAfterSave(); if (!initialMedication) sessionStorage.removeItem(keyFor(memberId)); onSaved('已记录'); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败，请重试') } finally { setSaving(false) }
  }
  const activePhoto = photos.photos.find((photo) => active.photoLocalIds?.includes(photo.localId))
  return <div className="medication-record-page-layer"><section aria-label="记录用药" aria-modal="true" className="medication-record-page medication-record-compact" role="dialog">
    <header><button aria-label="返回记录新情况" disabled={saving} onClick={onBack} type="button"><ArrowLeft /></button><h1>记录用药</h1><button aria-label="关闭" disabled={saving} onClick={onClose} type="button"><X /></button></header>
    <div className="medication-tab-bar"><div className="medication-tabs" role="tablist" aria-label="药品列表">{draft.medications.map((item, index) => <button aria-selected={item.id === active.id} key={item.id} onClick={() => { setDraft((current) => ({ ...current, activeId: item.id })); setReminderOpen(false); setError('') }} role="tab" type="button"><span>{item.medicationName.trim().slice(0, 6) || `药品 ${index + 1}`}</span>{complete(item) ? <Check aria-label="已填写完整" /> : <Circle aria-label="待填写" />}</button>)}</div><button aria-label="添加另一种药" className="medication-tab-add" onClick={addDrug} type="button"><Plus /></button></div>
    <div className="medication-record-scroll">
      <section className="medication-compact-section"><h2>药品</h2><div className="medication-picker"><span className="medication-package-thumb">{activePhoto ? <img alt="药品图片" src={activePhoto.previewUrl} /> : <Pill />}</span><input aria-label="药品名称" onChange={(event) => updateActive({ medicationName: event.target.value, recognitionStatus: active.recognitionSource ? 'user_edited' : 'not_used' })} placeholder="搜索或选择药品" value={active.medicationName} /><button aria-label="拍照识别药盒" onClick={() => cameraRef.current?.click()} type="button"><Camera /></button></div><input ref={cameraRef} accept="image/*" capture="environment" hidden onChange={(event) => { choosePackage(event.target.files); event.currentTarget.value = '' }} type="file" />{active.recognitionSource && <small className="medication-recognition-note">图片已上传，识别结果需核对</small>}{photos.photos.length > 0 && <QuickRecordPhotos limit={6} model={photos} />}</section>
      <section className="medication-compact-section"><h2>本次用量</h2><div className="medication-amount-row"><button aria-label="减少用量" onClick={() => updateActive({ amountValue: normalizeDose(active.amountValue - active.dosageStep, active.dosageStep) })} type="button"><Minus /></button><input aria-label="本次用量" inputMode="decimal" min="0" onChange={(event) => updateActive({ amountValue: Math.max(0, Number(event.target.value)) })} step="any" type="number" value={active.amountValue || ''} /><button aria-label="增加用量" onClick={() => updateActive({ amountValue: normalizeDose(active.amountValue + active.dosageStep, active.dosageStep) })} type="button"><Plus /></button><select aria-label="用量单位" onChange={(event) => updateActive({ amountUnit: event.target.value, dosageStep: ['片', '粒', '袋', '揿'].includes(event.target.value) ? 1 : 0.5 })} value={active.amountUnit}>{units.map((unit) => <option key={unit}>{unit}</option>)}</select></div><p>请按实际使用量记录</p></section>
      <label className="medication-time-row-main"><strong>记录时间</strong><span>{formatOccurredAt(draft.occurredAt)}</span><ChevronRight /><input ref={timeRef} aria-label="记录时间" max={localDateTimeValue()} onChange={(event) => setDraft((current) => ({ ...current, occurredAt: event.target.value }))} type="datetime-local" value={draft.occurredAt} /></label>
      <section className="medication-reminder-main"><label><Bell /><strong>设置用药提醒</strong><input checked={reminder.enabled} onChange={(event) => { updateReminder({ enabled: event.target.checked }); setReminderOpen(event.target.checked) }} role="switch" type="checkbox" /></label>{reminder.enabled && <button className="medication-reminder-summary" onClick={() => setReminderOpen(true)} type="button"><span>{`每天 ${reminder.timesPerDay} 次 · ${reminder.times.join(' / ')} · 共 ${reminder.durationDays} 天`}</span><em>编辑</em></button>}</section>
      {draft.medications.length > 1 && <button className="medication-remove-current" onClick={removeDrug} type="button">删除当前药品</button>}
      {error && <p className="medication-save-error" role="alert">{error}</p>}
    </div>
    <footer className="medication-fixed-save"><HohoButton disabled={saving || photos.blocked} fullWidth loading={saving} onClick={() => void save()} size="large">保存记录</HohoButton></footer>
    <BottomSheetSurface label="设置用药提醒" onClose={() => setReminderOpen(false)} open={reminderOpen} title="设置用药提醒"><div className="medication-reminder-sheet"><span>提醒周期</span><div className="medication-sheet-options">{frequencies.map(([value, label]) => <button aria-pressed={reminder.frequency === value} key={value} onClick={() => updateReminder({ frequency: value })} type="button">{label}</button>)}</div><span>每天提醒几次</span><div className="medication-mini-stepper"><button aria-label="减少提醒次数" onClick={() => changeCount(-1)} type="button"><Minus /></button><strong>{reminder.timesPerDay}</strong><button aria-label="增加提醒次数" onClick={() => changeCount(1)} type="button"><Plus /></button></div><span>提醒时间</span><div className="medication-time-inputs">{reminder.times.map((time, index) => <input aria-label={`第${index + 1}次提醒时间`} key={index} onChange={(event) => updateReminder({ times: reminder.times.map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} type="time" value={time} />)}</div><span>持续天数</span><div className="medication-sheet-options">{[1, 3, 5, 7].map((days) => <button aria-pressed={reminder.durationDays === days} key={days} onClick={() => updateReminder({ durationDays: days })} type="button">{days}天</button>)}</div><HohoButton fullWidth onClick={() => setReminderOpen(false)}>完成设置</HohoButton></div></BottomSheetSurface>
  </section></div>
}
