import { ArrowLeft, Camera, ChevronDown, ImagePlus, Pill, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { HohoButton, HohoInput } from '../../components/design-system'
import { BodyLocationPicker } from '../../components/health'
import type { BodyLocationSelection } from '../../features/body-location'
import type { JournalMedicationDetails, JournalMetadata, MedicationObservation, MedicationRoute } from '../../types/journal'
import { localDateTimeValue } from '../../utils/healthOccurredAt'
import { QuickRecordPhotos, useQuickRecordPhotos, type QuickRecordPhotoPayload } from '../HealthEventDetail/components/QuickRecordPhotos'
import { toSymptomLocations } from './symptomRecordLogic'
import { medicationRoutes, medicationSummary, medicationUnits, validMedicationAmount } from './medicationRecordLogic'

type SaveRecord = (content: string, occurredAt: string, channel: 'text', photos: QuickRecordPhotoPayload, journal: JournalMetadata) => Promise<string>
interface Draft { medicationName: string; dosageForm: string; strengthText: string; amount: string; unit: string; customUnit: string; route?: MedicationRoute; routeDrafts: Record<string, Record<string, string | number | boolean>>; locations: BodyLocationSelection[]; reasons: string[]; suggestedBy?: JournalMedicationDetails['suggestedBy']; observation?: MedicationObservation; note: string; occurredAt: string; recognitionSource?: 'camera' | 'album'; recognitionStatus?: JournalMedicationDetails['recognitionStatus'] }
const blankDraft = (): Draft => ({ medicationName: '', dosageForm: '', strengthText: '', amount: '', unit: 'mL', customUnit: '', routeDrafts: {}, locations: [], reasons: [], note: '', occurredAt: localDateTimeValue(), recognitionStatus: 'not_used' })
const keyFor = (memberId: string) => `hoooho-medication-record-draft:${memberId}`
const reasons = ['过敏相关表现', '发热', '咳嗽或呼吸不适', '疼痛', '消化道不适', '皮肤不适', '按医生要求', '其他']
const suggesters: Array<[NonNullable<Draft['suggestedBy']>, string]> = [['doctor', '医生'], ['pharmacist', '药师'], ['original_instruction', '按原医嘱'], ['caregiver_record', '家长记录'], ['other', '其他']]
const observations: Array<[MedicationObservation, string]> = [['not_observed_yet', '暂未观察'], ['some_relief', '有所缓解'], ['no_obvious_change', '没有明显变化'], ['discomfort_observed', '出现不适']]
const toggle = (items: string[], item: string) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item]

export function MedicationRecordFlow({ memberId, token, onBack, onClose, onConfirm, onSaved }: { memberId: string; token: string; onBack: () => void; onClose: () => void; onConfirm: SaveRecord; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(() => { try { return { ...blankDraft(), ...JSON.parse(sessionStorage.getItem(keyFor(memberId)) ?? '{}') } } catch { return blankDraft() } })
  const [supplementOpen, setSupplementOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [confirmEmptyAmount, setConfirmEmptyAmount] = useState(false)
  const cameraRef = useRef<HTMLInputElement>(null); const albumRef = useRef<HTMLInputElement>(null)
  const photos = useQuickRecordPhotos(memberId, token, 6, 'medication')
  useEffect(() => { sessionStorage.setItem(keyFor(memberId), JSON.stringify(draft)) }, [draft, memberId])
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setError('') }
  const routeData = draft.route ? draft.routeDrafts[draft.route] ?? {} : {}
  const updateRoute = (key: string, value: string | number | boolean) => draft.route && update('routeDrafts', { ...draft.routeDrafts, [draft.route]: { ...routeData, [key]: value } })
  const choosePackage = (source: 'camera' | 'album', files: FileList | null) => { photos.chooseFiles(files); if (files?.length) setDraft((current) => ({ ...current, recognitionSource: source, recognitionStatus: current.medicationName ? 'user_edited' : 'draft_unverified' })) }
  const save = async (confirmed = false) => {
    if (!draft.medicationName.trim()) { setError('请填写药品名称'); return }
    if (!draft.route) { setError('请选择实际使用方式'); return }
    if (!validMedicationAmount(draft.amount)) { setError('本次用量必须大于0'); return }
    if (draft.unit === '其他' && draft.amount && !draft.customUnit.trim()) { setError('请填写本次使用的单位'); return }
    const timestamp = Date.parse(draft.occurredAt)
    if (!Number.isFinite(timestamp) || timestamp > Date.now()) { setError('记录时间不能晚于现在'); return }
    if (!draft.amount && !confirmed) { setConfirmEmptyAmount(true); return }
    setSaving(true); setError('')
    try {
      const details: JournalMedicationDetails = { medicationName: draft.medicationName.trim(), administrationRoute: draft.route, ...(draft.dosageForm.trim() ? { dosageForm: draft.dosageForm.trim() } : {}), ...(draft.strengthText.trim() ? { strengthText: draft.strengthText.trim() } : {}), ...(draft.amount ? { amountValue: Number(draft.amount), amountUnit: draft.unit === '其他' ? draft.customUnit.trim() : draft.unit } : {}), ...(Object.keys(routeData).length ? { routeDetails: routeData } : {}), ...(draft.locations.length ? { bodyLocations: toSymptomLocations(draft.locations) } : {}), ...(draft.reasons.length ? { reasons: draft.reasons } : {}), ...(draft.suggestedBy ? { suggestedBy: draft.suggestedBy } : {}), ...(draft.observation ? { observationAfterUse: draft.observation } : {}), ...(draft.note.trim() ? { note: draft.note.trim() } : {}), ...(draft.recognitionSource ? { recognitionSource: draft.recognitionSource, recognitionStatus: draft.recognitionStatus } : {}) }
      await onConfirm(medicationSummary(details), new Date(timestamp).toISOString(), 'text', photos.payload(), { categories: ['medication'], medication: details })
      photos.clearAfterSave(); sessionStorage.removeItem(keyFor(memberId)); onSaved('已记录'); onClose()
    } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败，请重试') } finally { setSaving(false) }
  }
  return <div className="medication-record-page-layer"><section aria-label="记录用药" aria-modal="true" className="medication-record-page" role="dialog">
    <header><button aria-label="返回记录新情况" disabled={saving} onClick={onBack} type="button"><ArrowLeft size={22} /></button><h1>记录用药</h1><button aria-label="关闭" disabled={saving} onClick={onClose} type="button"><X size={21} /></button></header>
    <div className="medication-record-scroll">
      <section className="medication-section"><h2>用了什么药？</h2><HohoInput label="药品名称" onChange={(event) => { update('medicationName', event.target.value); if (draft.recognitionSource) update('recognitionStatus', 'user_edited') }} placeholder="搜索或手动填写药品名称" value={draft.medicationName} /><div className="medication-identity-row"><HohoInput label="剂型（选填）" onChange={(event) => update('dosageForm', event.target.value)} placeholder="如片剂、糖浆" value={draft.dosageForm} /><HohoInput label="规格或浓度（选填）" onChange={(event) => update('strengthText', event.target.value)} placeholder="如10mg" value={draft.strengthText} /></div><div className="medication-photo-actions"><button onClick={() => cameraRef.current?.click()} type="button"><Camera size={19} />拍药盒</button><button onClick={() => albumRef.current?.click()} type="button"><ImagePlus size={19} />从相册选择</button></div><input ref={cameraRef} accept="image/*" capture="environment" hidden onChange={(event) => { choosePackage('camera', event.target.files); event.currentTarget.value = '' }} type="file" /><input ref={albumRef} accept="image/jpeg,image/png,image/webp" hidden multiple onChange={(event) => { choosePackage('album', event.target.files); event.currentTarget.value = '' }} type="file" />{draft.recognitionSource && <div className="medication-recognition"><Pill size={18} /><span><strong>识别结果待核对</strong><small>请根据药品包装核对，也可以直接修改</small></span></div>}{photos.photos.length > 0 && <QuickRecordPhotos limit={6} model={photos} />}</section>
      <fieldset className="medication-fieldset"><legend>这一次用了多少？</legend><div className="medication-amount"><HohoInput label="本次用量" inputMode="decimal" min="0" onChange={(event) => update('amount', event.target.value)} placeholder="可暂不填写" step="any" type="number" value={draft.amount} /><select aria-label="用量单位" onChange={(event) => update('unit', event.target.value)} value={draft.unit}>{medicationUnits.map((unit) => <option key={unit}>{unit}</option>)}</select></div>{draft.unit === '其他' && <HohoInput label="实际单位" maxLength={12} onChange={(event) => update('customUnit', event.target.value)} value={draft.customUnit} />}</fieldset>
      <fieldset className="medication-fieldset"><legend>怎么使用？</legend><div className="medication-choice-grid">{medicationRoutes.map(([value, label]) => <button aria-pressed={draft.route === value} key={value} onClick={() => update('route', value)} type="button">{label}</button>)}</div></fieldset>
      {draft.route === 'topical' && <section className="medication-section"><h2>涂在哪里？<span>（可选）</span></h2><BodyLocationPicker buttonLabel={draft.locations.length ? '修改身体部位' : '标记身体部位'} confirmLabel="完成并返回用药记录" inputLike label="涂药位置" showEmptyState={false} value={draft.locations} onChange={(value) => update('locations', value)} /><div className="medication-choice-grid">{['少量', '薄薄一层', '按实际填写'].map((item) => <button aria-pressed={routeData.topicalAmount === item} key={item} onClick={() => updateRoute('topicalAmount', item)} type="button">{item}</button>)}</div></section>}
      {(draft.route === 'nebulized' || draft.route === 'inhaled') && <section className="medication-section"><h2>使用详情<span>（可选）</span></h2>{draft.route === 'nebulized' ? <HohoInput inputMode="numeric" label="雾化持续时间（分钟）" onChange={(event) => updateRoute('durationMinutes', event.target.value)} value={String(routeData.durationMinutes ?? '')} /> : <HohoInput inputMode="numeric" label="本次使用次数（揿或次）" onChange={(event) => updateRoute('useCount', event.target.value)} value={String(routeData.useCount ?? '')} />}</section>}
      {(draft.route === 'nasal' || draft.route === 'ophthalmic') && <section className="medication-section"><h2>使用位置</h2><div className="medication-choice-grid">{(draft.route === 'nasal' ? ['左侧', '右侧', '双侧'] : ['左眼', '右眼', '双眼']).map((item) => <button aria-pressed={routeData.side === item} key={item} onClick={() => updateRoute('side', item)} type="button">{item}</button>)}</div><HohoInput inputMode="decimal" label="每侧用了多少？（滴）" onChange={(event) => updateRoute('dropsPerSide', event.target.value)} value={String(routeData.dropsPerSide ?? '')} /></section>}
      {draft.route === 'other' && <HohoInput label="写下实际使用方式" maxLength={100} onChange={(event) => updateRoute('description', event.target.value)} value={String(routeData.description ?? '')} />}
      <section className="medication-supplement"><button aria-expanded={supplementOpen} onClick={() => setSupplementOpen((value) => !value)} type="button"><span><strong>再补充一点（选填）</strong><small>{draft.reasons.length || draft.suggestedBy || draft.observation || draft.note ? `已补充${[draft.reasons.length > 0, draft.suggestedBy, draft.observation, draft.note].filter(Boolean).length}项` : '使用原因、建议来源和用后观察都可以以后补充'}</small></span><ChevronDown data-open={supplementOpen} size={18} /></button>{supplementOpen && <div className="medication-supplement-body"><fieldset className="medication-fieldset"><legend>为什么使用？<span>（可选，可多选）</span></legend><div className="medication-choice-grid">{reasons.map((item) => <button aria-pressed={draft.reasons.includes(item)} key={item} onClick={() => update('reasons', toggle(draft.reasons, item))} type="button">{item}</button>)}</div></fieldset><fieldset className="medication-fieldset"><legend>谁建议使用？<span>（可选）</span></legend><div className="medication-choice-grid">{suggesters.map(([value, label]) => <button aria-pressed={draft.suggestedBy === value} key={value} onClick={() => update('suggestedBy', draft.suggestedBy === value ? undefined : value)} type="button">{label}</button>)}</div></fieldset><fieldset className="medication-fieldset"><legend>用后观察<span>（可选）</span></legend><div className="medication-choice-grid">{observations.map(([value, label]) => <button aria-pressed={draft.observation === value} key={value} onClick={() => update('observation', draft.observation === value ? undefined : value)} type="button">{label}</button>)}</div>{draft.observation === 'discomfort_observed' && <button className="medication-reaction-link" type="button">记录用后反应</button>}</fieldset><label className="medication-note"><span>备注（可选）</span><textarea maxLength={200} onChange={(event) => update('note', event.target.value)} placeholder="还可以记录其他需要说明的情况" rows={3} value={draft.note} /></label></div>}</section>
      <HohoInput label="记录时间" max={localDateTimeValue()} onChange={(event) => update('occurredAt', event.target.value)} type="datetime-local" value={draft.occurredAt} />{error && <p className="medication-save-error" role="alert">{error}</p>}<div className="medication-record-save"><HohoButton disabled={saving || photos.blocked} fullWidth loading={saving} onClick={() => void save()} size="large">保存记录</HohoButton></div>
    </div>
    {confirmEmptyAmount && <div className="medication-confirm-layer" role="dialog" aria-modal="true" aria-label="确认保存"><div><h2>还没有填写本次用量</h2><p>仍要保存吗？</p><HohoButton fullWidth onClick={() => { setConfirmEmptyAmount(false); void save(true) }}>仍要保存</HohoButton><HohoButton fullWidth variant="secondary" onClick={() => setConfirmEmptyAmount(false)}>继续填写</HohoButton></div></div>}
  </section></div>
}
