import { ArrowLeft, Bell, Camera, ImagePlus, Minus, Plus, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { HohoButton, HohoInput } from '../../components/design-system'
import { apiRequest } from '../../services/apiClient'
import type { HealthEventApiDto, HealthEventRecordApiDto } from '../../types'
import type { JournalMedicationDetails, JournalMedicationItem, JournalMetadata, MedicationReminder } from '../../types/journal'
import { localDateTimeValue } from '../../utils/healthOccurredAt'
import { QuickRecordPhotos, useQuickRecordPhotos, type QuickRecordPhotoPayload } from '../HealthEventDetail/components/QuickRecordPhotos'
import { medicationDoseSteps, medicationSummary, medicationUnits, normalizeDose } from './medicationRecordLogic'

type SaveRecord = (content: string, occurredAt: string, channel: 'text', photos: QuickRecordPhotoPayload, journal: JournalMetadata) => Promise<string>
type DraftDrug = JournalMedicationItem & { photoLocalIds?: string[] }
type Draft = { medications: DraftDrug[]; activeId: string; occurredAt: string }
const newReminder = (): MedicationReminder => ({ enabled: false, frequency: 'daily', timesPerDay: 3, times: ['08:00', '14:00', '20:00'], durationDays: 5 })
const newDrug = (): JournalMedicationItem => ({ id: crypto.randomUUID(), medicationName: '', amountValue: 0, amountUnit: 'mL', dosageStep: 0.5, reminder: newReminder(), recognitionStatus: 'not_used' })
const blankDraft = (): Draft => { const drug = newDrug(); return { medications: [drug], activeId: drug.id, occurredAt: localDateTimeValue() } }
const keyFor = (memberId: string) => `hoooho-medication-record-v2:${memberId}`
const frequencies = [['daily', '每天'], ['interval_hours', '每隔几小时'], ['weekly', '每周'], ['custom', '自定义']] as const

export function MedicationRecordFlow({ memberId, token, initialMedication, initialOccurredAt, onBack, onClose, onConfirm, onSaved }: { memberId: string; token: string; initialMedication?: JournalMedicationDetails; initialOccurredAt?: string; onBack: () => void; onClose: () => void; onConfirm: SaveRecord; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(() => { if (initialMedication) { const medications = initialMedication.medications?.length ? initialMedication.medications : [{ id: crypto.randomUUID(), medicationName: initialMedication.medicationName, amountValue: initialMedication.amountValue ?? 0, amountUnit: initialMedication.amountUnit ?? 'mL', dosageStep: 0.5 as const, reminder: newReminder() }]; return { medications, activeId: medications[0].id, occurredAt: initialOccurredAt ? localDateTimeValue(new Date(initialOccurredAt)) : localDateTimeValue() } } try { const saved = JSON.parse(sessionStorage.getItem(keyFor(memberId)) ?? 'null'); return saved?.medications?.length ? saved : blankDraft() } catch { return blankDraft() } })
  const [reminderOpen, setReminderOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [directInput, setDirectInput] = useState(false)
  const [recent, setRecent] = useState<string[]>([])
  const cameraRef = useRef<HTMLInputElement>(null); const albumRef = useRef<HTMLInputElement>(null)
  const photos = useQuickRecordPhotos(memberId, token, 6, 'medication-v2')
  const active = draft.medications.find((item) => item.id === draft.activeId) ?? draft.medications[0]
  useEffect(() => { sessionStorage.setItem(keyFor(memberId), JSON.stringify(draft)) }, [draft, memberId])
  useEffect(() => { const controller = new AbortController(); void (async () => { try { const events = (await apiRequest<HealthEventApiDto[]>('/api/events?view=time', { token, signal: controller.signal })).filter((event) => event.memberId === memberId); const rows = await Promise.all(events.map((event) => apiRequest<HealthEventRecordApiDto[]>(`/api/events/${encodeURIComponent(event.id)}/records?view=time`, { token, signal: controller.signal }))); const names = rows.flat().flatMap((record) => record.journal?.medication?.medications?.map((item) => item.medicationName) ?? (record.journal?.medication?.medicationName ? [record.journal.medication.medicationName] : [])); setRecent([...new Set(names)].slice(0, 3)) } catch { if (!controller.signal.aborted) setRecent([]) } })(); return () => controller.abort() }, [memberId, token])
  const updateActive = (changes: Partial<DraftDrug>) => { setDraft((current) => ({ ...current, medications: current.medications.map((item) => item.id === current.activeId ? { ...item, ...changes } : item) })); setError('') }
  const updateReminder = (changes: Partial<MedicationReminder>) => updateActive({ reminder: { ...newReminder(), ...active.reminder, ...changes } })
  const addDrug = () => { const item = newDrug(); setDraft((current) => ({ ...current, medications: [...current.medications, item], activeId: item.id })); setReminderOpen(false) }
  const removeDrug = (id: string) => { if (draft.medications.length === 1 || !window.confirm('删除这个未保存的药品？')) return; setDraft((current) => { const medications = current.medications.filter((item) => item.id !== id); return { ...current, medications, activeId: current.activeId === id ? medications[0].id : current.activeId } }) }
  const choosePackage = (source: 'camera' | 'album', files: FileList | null) => { const localIds = photos.chooseFiles(files); if (localIds.length) updateActive({ photoLocalIds: [...(active.photoLocalIds ?? []), ...localIds], recognitionSource: source, recognitionStatus: 'draft_unverified' }) }
  const changeCount = (delta: number) => { const count = Math.min(12, Math.max(1, (active.reminder?.timesPerDay ?? 3) + delta)); const current = active.reminder?.times ?? []; const defaults = ['08:00', '14:00', '20:00', '22:00']; updateReminder({ timesPerDay: count, times: Array.from({ length: count }, (_, index) => current[index] ?? defaults[index] ?? '08:00') }) }
  const save = async () => {
    const invalid = draft.medications.find((item) => !item.medicationName.trim() || !Number.isFinite(item.amountValue) || item.amountValue <= 0)
    if (invalid) { setDraft((current) => ({ ...current, activeId: invalid.id })); setError(!invalid.medicationName.trim() ? '请填写药品名称' : '本次用量必须大于0'); return }
    const timestamp = Date.parse(draft.occurredAt); if (!Number.isFinite(timestamp) || timestamp > Date.now()) { setError('记录时间不能晚于现在'); return }
    setSaving(true); setError('')
    try {
      const medications = draft.medications.map(({ photoLocalIds = [], ...item }) => ({ ...item, medicationName: item.medicationName.trim(), photoIds: photos.photos.filter((photo) => photoLocalIds.includes(photo.localId) && photo.serverId).map((photo) => photo.serverId!) }))
      const first = medications[0]; const details: JournalMedicationDetails = { medications, medicationName: first.medicationName, amountValue: first.amountValue, amountUnit: first.amountUnit, administrationRoute: 'oral' }
      await onConfirm(medicationSummary(details), new Date(timestamp).toISOString(), 'text', photos.payload(), { categories: ['medication'], medication: details })
      photos.clearAfterSave(); if (!initialMedication) sessionStorage.removeItem(keyFor(memberId)); onSaved('已记录'); onClose()
    } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败，请重试') } finally { setSaving(false) }
  }
  const reminder = { ...newReminder(), ...active.reminder }
  return <div className="medication-record-page-layer"><section aria-label="记录用药" aria-modal="true" className="medication-record-page medication-record-v2" role="dialog">
    <header><button aria-label="返回记录新情况" disabled={saving} onClick={onBack} type="button"><ArrowLeft size={22} /></button><h1>记录用药</h1><button aria-label="关闭" disabled={saving} onClick={onClose} type="button"><X size={21} /></button></header>
    {draft.medications.length > 1 && <div className="medication-tabs" role="tablist" aria-label="药品列表">{draft.medications.map((item, index) => <span className="medication-tab-wrap" key={item.id}><button aria-selected={item.id === active.id} onClick={() => { setDraft((current) => ({ ...current, activeId: item.id })); setReminderOpen(false) }} role="tab" type="button">{item.medicationName.trim().slice(0, 6) || `药品 ${index + 1}`}</button><button aria-label={`删除药品 ${index + 1}`} className="medication-tab-remove" onClick={() => removeDrug(item.id)} type="button"><X size={12} /></button></span>)}<button aria-label="添加另一种药" className="medication-tab-add" onClick={addDrug} type="button"><Plus size={18} /></button></div>}
    <div className="medication-record-scroll">
      <section className="medication-drug-row"><div className="medication-package-thumb">{photos.photos.find((photo) => active.photoLocalIds?.includes(photo.localId)) ? <img alt="药品图片" src={photos.photos.find((photo) => active.photoLocalIds?.includes(photo.localId))!.previewUrl} /> : <span>药</span>}</div><HohoInput label="药品名称" onChange={(event) => updateActive({ medicationName: event.target.value, recognitionStatus: active.recognitionSource ? 'user_edited' : 'not_used' })} placeholder="搜索或选择药品" value={active.medicationName} /><button aria-label="拍药盒" onClick={() => cameraRef.current?.click()} type="button"><Camera size={19} /></button><button aria-label="从相册选择" onClick={() => albumRef.current?.click()} type="button"><ImagePlus size={19} /></button></section>
      <input ref={cameraRef} accept="image/*" capture="environment" hidden onChange={(event) => { choosePackage('camera', event.target.files); event.currentTarget.value = '' }} type="file" /><input ref={albumRef} accept="image/jpeg,image/png,image/webp" hidden onChange={(event) => { choosePackage('album', event.target.files); event.currentTarget.value = '' }} type="file" />
      {active.recognitionSource && <p className="medication-recognition-note">图片已上传，请核对或手动修改药品名称</p>}{photos.photos.length > 0 && <QuickRecordPhotos limit={6} model={photos} />}
      {recent.length > 0 && <section className="medication-recent"><strong>最近使用</strong><div className="medication-chip-row">{recent.map((name) => <button key={name} onClick={() => updateActive({ medicationName: name })} type="button">{name}</button>)}</div></section>}
      <fieldset className="medication-fieldset"><legend>剂量</legend><div className="medication-dose-stepper"><button aria-label="减少剂量" onClick={() => updateActive({ amountValue: normalizeDose(active.amountValue - active.dosageStep, active.dosageStep) })} type="button"><Minus /></button>{directInput ? <input autoFocus inputMode="decimal" min="0.01" onBlur={() => setDirectInput(false)} onChange={(event) => updateActive({ amountValue: Number(event.target.value) })} type="number" value={active.amountValue || ''} /> : <button aria-label="直接输入剂量" className="medication-dose-value" onClick={() => setDirectInput(true)} type="button">{active.amountValue || '—'}</button>}<button aria-label="增加剂量" onClick={() => updateActive({ amountValue: normalizeDose(active.amountValue + active.dosageStep, active.dosageStep) })} type="button"><Plus /></button></div><input aria-label="拖动调整剂量" className="medication-dose-range" max="5" min="0" onChange={(event) => updateActive({ amountValue: normalizeDose(Number(event.target.value), active.dosageStep) })} step={active.dosageStep} type="range" value={Math.min(5, active.amountValue)} /><span className="medication-field-label">调整步长</span><div className="medication-chip-row">{medicationDoseSteps.map((step) => <button aria-pressed={active.dosageStep === step} key={step} onClick={() => updateActive({ dosageStep: step, amountValue: normalizeDose(active.amountValue, step) })} type="button">{step}</button>)}</div><span className="medication-field-label">单位</span><div className="medication-chip-row medication-unit-row">{medicationUnits.filter((unit) => ['mL', 'mg', '片', '粒', '袋', '滴', '揿'].includes(unit)).map((unit) => <button aria-pressed={active.amountUnit === unit} key={unit} onClick={() => updateActive({ amountUnit: unit })} type="button">{unit}</button>)}</div><button className="medication-direct-input" onClick={() => setDirectInput(true)} type="button">直接输入</button><p className="medication-dose-note">记录实际使用量，不提供剂量建议。</p></fieldset>
      {draft.medications.length === 1 && <button className="medication-add-secondary" onClick={addDrug} type="button"><Plus size={17} />添加另一种药</button>}
      <section className="medication-reminder"><label><Bell size={19} /><strong>设置用药提醒</strong><input checked={reminder.enabled} onChange={(event) => { updateReminder({ enabled: event.target.checked }); setReminderOpen(event.target.checked) }} role="switch" type="checkbox" /></label>{reminder.enabled && <><button aria-expanded={reminderOpen} className="medication-reminder-summary" onClick={() => setReminderOpen((value) => !value)} type="button">每天{reminder.timesPerDay}次 · {reminder.times.join(' / ')} · {reminder.durationDays}天</button>{reminderOpen && <div className="medication-reminder-panel"><span className="medication-field-label">提醒周期</span><div className="medication-chip-row">{frequencies.map(([value, label]) => <button aria-pressed={reminder.frequency === value} key={value} onClick={() => updateReminder({ frequency: value })} type="button">{label}</button>)}</div><span className="medication-field-label">每天提醒几次？</span><div className="medication-mini-stepper"><button aria-label="减少提醒次数" onClick={() => changeCount(-1)} type="button"><Minus /></button><strong>{reminder.timesPerDay}</strong><button aria-label="增加提醒次数" onClick={() => changeCount(1)} type="button"><Plus /></button></div><span className="medication-field-label">提醒时间</span><div className="medication-time-row">{reminder.times.map((time, index) => <input aria-label={`第${index + 1}次提醒时间`} key={index} onChange={(event) => updateReminder({ times: reminder.times.map((item, itemIndex) => itemIndex === index ? event.target.value : item) })} type="time" value={time} />)}</div><span className="medication-field-label">持续多久？</span><div className="medication-chip-row">{[1, 3, 5, 7].map((days) => <button aria-pressed={reminder.durationDays === days} key={days} onClick={() => updateReminder({ durationDays: days })} type="button">{days}天</button>)}</div><p className="medication-nurse-note">提醒可在前台护士站查看和管理</p></div>}</>}</section>
      <div className="medication-event-footer"><HohoInput label="记录时间" max={localDateTimeValue()} onChange={(event) => setDraft((current) => ({ ...current, occurredAt: event.target.value }))} type="datetime-local" value={draft.occurredAt} />{error && <p className="medication-save-error" role="alert">{error}</p>}<HohoButton disabled={saving || photos.blocked} fullWidth loading={saving} onClick={() => void save()} size="large">保存记录</HohoButton></div>
    </div>
  </section></div>
}
