import { ArrowLeft, Camera, ChevronDown, ImagePlus, Plus, Syringe, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { HohoButton, HohoInput } from '../../components/design-system'
import type { JournalMetadata, JournalVaccinationDetails, JournalVaccinationItem, VaccinationDose, VaccinationObservation, VaccinationSite } from '../../types/journal'
import { localDateTimeValue } from '../../utils/healthOccurredAt'
import { QuickRecordPhotos, useQuickRecordPhotos, type QuickRecordPhotoPayload } from '../HealthEventDetail/components/QuickRecordPhotos'

type SaveRecord = (content: string, occurredAt: string, channel: 'text', photos: QuickRecordPhotoPayload, journal: JournalMetadata) => Promise<string>
interface Draft { items: JournalVaccinationItem[]; institutionName: string; observations: VaccinationObservation[]; note: string; occurredAt: string; recognitionSource?: 'camera' | 'album'; recognitionStatus?: JournalVaccinationDetails['recognitionStatus'] }
const newItem = (): JournalVaccinationItem => ({ id: globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random()}`, vaccineName: '', doseSequence: 'unknown' })
const blankDraft = (): Draft => ({ items: [newItem()], institutionName: '', observations: [], note: '', occurredAt: localDateTimeValue(), recognitionStatus: 'not_used' })
const draftKey = (memberId: string) => `hoooho-vaccination-record-draft:${memberId}`
const recentKey = (memberId: string) => `hoooho-vaccination-recent:${memberId}`
const doses: Array<[VaccinationDose, string]> = [['dose_1', '第1剂'], ['dose_2', '第2剂'], ['dose_3', '第3剂'], ['dose_4', '第4剂'], ['booster', '加强剂'], ['unknown', '不清楚']]
const sites: Array<[VaccinationSite, string]> = [['left_upper_arm', '左上臂'], ['right_upper_arm', '右上臂'], ['left_thigh', '左大腿'], ['right_thigh', '右大腿'], ['other', '其他'], ['not_recorded', '未记录']]
const observationChoices: Array<[VaccinationObservation, string]> = [['not_observed_yet', '暂未观察'], ['nothing_notable', '没有特别表现'], ['injection_site_redness_or_pain', '接种处红肿或疼痛'], ['fever', '发热'], ['energy_or_appetite_change', '精神或食欲变化'], ['other', '其他']]
const doseLabel = (dose: VaccinationDose) => doses.find(([value]) => value === dose)?.[1] ?? '不清楚'
const observationLabel = (value: VaccinationObservation) => observationChoices.find(([key]) => key === value)?.[1] ?? value

export function VaccinationRecordFlow({ memberId, token, onBack, onClose, onConfirm, onSaved }: { memberId: string; token: string; onBack: () => void; onClose: () => void; onConfirm: SaveRecord; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(() => { try { const saved = JSON.parse(sessionStorage.getItem(draftKey(memberId)) ?? '{}'); return { ...blankDraft(), ...saved, items: saved.items?.length ? saved.items : [newItem()] } } catch { return blankDraft() } })
  const [supplementOpen, setSupplementOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const cameraRef = useRef<HTMLInputElement>(null); const albumRef = useRef<HTMLInputElement>(null)
  const photos = useQuickRecordPhotos(memberId, token, 6, 'vaccination')
  const recent: Array<Pick<JournalVaccinationItem, 'vaccineName' | 'commonAbbreviation' | 'manufacturerName'>> = (() => { try { return JSON.parse(localStorage.getItem(recentKey(memberId)) ?? '[]') } catch { return [] } })()
  useEffect(() => { sessionStorage.setItem(draftKey(memberId), JSON.stringify(draft)) }, [draft, memberId])
  const updateItem = (id: string, change: Partial<JournalVaccinationItem>) => { setDraft((current) => ({ ...current, items: current.items.map((item) => item.id === id ? { ...item, ...change } : item), ...(current.recognitionSource ? { recognitionStatus: 'user_edited' as const } : {}) })); setError('') }
  const chooseCertificate = (source: 'camera' | 'album', files: FileList | null) => { photos.chooseFiles(files); if (files?.length) setDraft((current) => ({ ...current, recognitionSource: source, recognitionStatus: current.items[0].vaccineName ? 'user_edited' : 'draft_unverified' })) }
  const toggleObservation = (value: VaccinationObservation) => setDraft((current) => {
    if (current.observations.includes(value)) return { ...current, observations: current.observations.filter((item) => item !== value) }
    if (value === 'not_observed_yet' || value === 'nothing_notable') return { ...current, observations: [value] }
    return { ...current, observations: [...current.observations.filter((item) => item !== 'not_observed_yet' && item !== 'nothing_notable'), value] }
  })
  const save = async () => {
    if (draft.items.some((item) => !item.vaccineName.trim())) { setError('请填写每种疫苗的名称'); return }
    if (draft.items.some((item) => !item.doseSequence)) { setError('请选择每种疫苗的剂次'); return }
    const timestamp = Date.parse(draft.occurredAt)
    if (!Number.isFinite(timestamp) || timestamp > Date.now()) { setError('接种时间不能晚于现在'); return }
    setSaving(true); setError('')
    try {
      const details: JournalVaccinationDetails = { items: draft.items.map((item) => ({ ...item, vaccineName: item.vaccineName.trim(), ...(item.manufacturerName?.trim() ? { manufacturerName: item.manufacturerName.trim() } : {}), ...(item.batchNumber?.trim() ? { batchNumber: item.batchNumber } : {}) })), ...(draft.institutionName.trim() ? { institutionName: draft.institutionName.trim() } : {}), ...(draft.observations.length ? { observations: draft.observations } : {}), ...(draft.note.trim() ? { note: draft.note.trim() } : {}), ...(draft.recognitionSource ? { recognitionSource: draft.recognitionSource, recognitionStatus: draft.recognitionStatus } : {}) }
      const content = details.items.length > 1 ? `疫苗接种 · 共${details.items.length}种 · ${details.items.map((item) => `${item.vaccineName} · ${doseLabel(item.doseSequence)}`).join('；')}` : `疫苗接种 · ${details.items[0].vaccineName} · ${doseLabel(details.items[0].doseSequence)}`
      await onConfirm(content, new Date(timestamp).toISOString(), 'text', photos.payload(), { categories: ['vaccination'], vaccination: details })
      const nextRecent = [...details.items.map(({ vaccineName, commonAbbreviation, manufacturerName }) => ({ vaccineName, commonAbbreviation, manufacturerName })), ...recent].filter((item, index, all) => all.findIndex((candidate) => candidate.vaccineName === item.vaccineName) === index).slice(0, 6)
      localStorage.setItem(recentKey(memberId), JSON.stringify(nextRecent)); photos.clearAfterSave(); sessionStorage.removeItem(draftKey(memberId)); onSaved('已记录'); onClose()
    } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败，请重试') } finally { setSaving(false) }
  }
  const supplemented = [draft.institutionName, draft.items.some((item) => item.manufacturerName), draft.items.some((item) => item.batchNumber), draft.items.some((item) => item.injectionSite), photos.photos.length, draft.observations.length, draft.note].filter(Boolean).length
  return <div className="medication-record-page-layer"><section aria-label="记录疫苗接种" aria-modal="true" className="medication-record-page vaccination-record-page" role="dialog">
    <header><button aria-label="返回记录新情况" disabled={saving} onClick={onBack} type="button"><ArrowLeft size={22} /></button><h1>记录疫苗接种</h1><button aria-label="关闭" disabled={saving} onClick={onClose} type="button"><X size={21} /></button></header>
    <div className="medication-record-scroll vaccination-record-scroll">
      {draft.items.map((item, index) => <section className="vaccination-item" key={item.id}><div className="vaccination-item-heading"><h2>{index === 0 ? '接种了什么疫苗？' : `同次接种的疫苗 ${index + 1}`}</h2>{index > 0 && <button aria-label={`删除疫苗 ${index + 1}`} onClick={() => setDraft((current) => ({ ...current, items: current.items.filter((row) => row.id !== item.id) }))} type="button"><Trash2 size={17} />删除</button>}</div><HohoInput label="疫苗名称" onChange={(event) => updateItem(item.id, { vaccineName: event.target.value })} placeholder="搜索疫苗名称，或手动填写" value={item.vaccineName} />{index === 0 && <><div className="medication-photo-actions"><button onClick={() => cameraRef.current?.click()} type="button"><Camera size={19} />拍接种凭证</button><button onClick={() => albumRef.current?.click()} type="button"><ImagePlus size={19} />从相册选择</button></div>{recent.length > 0 && <div className="vaccination-recent"><span>最近记录</span>{recent.map((row) => <button key={row.vaccineName} onClick={() => updateItem(item.id, { vaccineName: row.vaccineName, commonAbbreviation: row.commonAbbreviation, manufacturerName: row.manufacturerName })} type="button">{row.vaccineName}</button>)}</div>}</>}<fieldset className="medication-fieldset"><legend>第几剂？</legend><div className="medication-choice-grid">{doses.map(([value, label]) => <button aria-pressed={item.doseSequence === value} key={value} onClick={() => updateItem(item.id, { doseSequence: value })} type="button">{label}</button>)}</div></fieldset></section>)}
      <button className="vaccination-add" onClick={() => setDraft((current) => ({ ...current, items: [...current.items, newItem()] }))} type="button"><Plus size={18} />添加同次接种的其他疫苗</button>
      <input ref={cameraRef} accept="image/*" capture="environment" hidden onChange={(event) => { chooseCertificate('camera', event.target.files); event.currentTarget.value = '' }} type="file" /><input ref={albumRef} accept="image/jpeg,image/png,image/webp" hidden multiple onChange={(event) => { chooseCertificate('album', event.target.files); event.currentTarget.value = '' }} type="file" />{draft.recognitionSource && <div className="medication-recognition"><Syringe size={18} /><span><strong>识别结果待核对</strong><small>请按接种凭证核对，也可以直接修改</small></span></div>}
      <section className="medication-supplement"><button aria-expanded={supplementOpen} onClick={() => setSupplementOpen((value) => !value)} type="button"><span><strong>再补充一点（选填）</strong><small>{supplemented ? `已补充${supplemented}项` : '接种机构、批号、部位和接种后观察都可以以后补充'}</small></span><ChevronDown data-open={supplementOpen} size={18} /></button>{supplementOpen && <div className="medication-supplement-body"><HohoInput label="接种机构（可选）" onChange={(event) => setDraft((current) => ({ ...current, institutionName: event.target.value }))} placeholder="搜索或输入接种机构名称" value={draft.institutionName} />{draft.items.map((item, index) => <section className="vaccination-details" key={item.id}><h3>{draft.items.length > 1 ? item.vaccineName || `疫苗 ${index + 1}` : '疫苗信息'}</h3><HohoInput label="疫苗厂家（可选）" onChange={(event) => updateItem(item.id, { manufacturerName: event.target.value })} value={item.manufacturerName ?? ''} /><HohoInput label="疫苗批号（可选）" onChange={(event) => updateItem(item.id, { batchNumber: event.target.value })} value={item.batchNumber ?? ''} /><fieldset className="medication-fieldset"><legend>接种部位<span>（可选）</span></legend><div className="medication-choice-grid">{sites.map(([value, label]) => <button aria-pressed={item.injectionSite === value} key={value} onClick={() => updateItem(item.id, { injectionSite: value })} type="button">{label}</button>)}</div>{item.injectionSite === 'other' && <HohoInput label="其他接种部位" onChange={(event) => updateItem(item.id, { injectionSiteOtherText: event.target.value })} value={item.injectionSiteOtherText ?? ''} />}</fieldset></section>)}<section className="medication-section"><h2>接种凭证<span>（可选，{photos.photos.length}/6）</span></h2>{photos.photos.length > 0 ? <QuickRecordPhotos limit={6} model={photos} /> : <button className="vaccination-certificate-empty" onClick={() => albumRef.current?.click()} type="button"><ImagePlus size={20} />上传照片</button>}</section><fieldset className="medication-fieldset"><legend>接种后观察<span>（可选，可多选）</span></legend><div className="medication-choice-grid vaccination-observations">{observationChoices.map(([value, label]) => <button aria-pressed={draft.observations.includes(value)} key={value} onClick={() => toggleObservation(value)} type="button">{label}</button>)}</div><small className="vaccination-causality">这里只记录时间上的先后，不代表由疫苗引起</small>{draft.observations.some((item) => !['not_observed_yet', 'nothing_notable'].includes(item)) && <button className="medication-reaction-link" type="button">记录具体症状</button>}</fieldset><label className="medication-note"><span>备注（可选）</span><textarea maxLength={200} onChange={(event) => setDraft((current) => ({ ...current, note: event.target.value }))} placeholder="还可以记录其他需要说明的情况" rows={3} value={draft.note} /></label></div>}</section>
      <HohoInput label="接种时间" max={localDateTimeValue()} onChange={(event) => setDraft((current) => ({ ...current, occurredAt: event.target.value }))} type="datetime-local" value={draft.occurredAt} />{error && <p className="medication-save-error" role="alert">{error}</p>}<div className="medication-record-save"><HohoButton disabled={saving || photos.blocked} fullWidth loading={saving} onClick={() => void save()} size="large">保存记录</HohoButton></div>
    </div>
  </section></div>
}

export { doseLabel, observationLabel }
