import { ArrowLeft, Camera, ChevronDown, ImagePlus, Link2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { HohoButton, HohoInput } from '../../components/design-system'
import type { JournalMetadata, JournalVisitDetails, VisitFollowUpAction, VisitType } from '../../types/journal'
import { localDateTimeValue } from '../../utils/healthOccurredAt'
import { QuickRecordPhotos, useQuickRecordPhotos, type QuickRecordPhotoPayload } from '../HealthEventDetail/components/QuickRecordPhotos'
import { useJournal } from './useJournal'
import { visitSummary } from './visitRecordLogic'

type SaveRecord = (content: string, occurredAt: string, channel: 'text', photos: QuickRecordPhotoPayload, journal: JournalMetadata) => Promise<string>
type Draft = {
  visitType?: VisitType; visitTypeOtherText: string; reasonText: string; linkedSymptomRecordIds: string[]; linkedVisitRecordId: string
  institutionName: string; platformName: string; department: string; departmentOtherText: string; doctorName: string
  doctorStatement: string; examinationTypes: string[]; examinationOtherText: string; followUpActions: VisitFollowUpAction[]
  followUpAt: string; followUpRelativeText: string; expectedResultAt: string; referralInstitution: string; referralDepartment: string; referralReason: string
  admittedAt: string; dischargedAt: string; isCurrentlyHospitalized: boolean; admissionNumber: string; emergencyArrivalAt: string; emergencyDepartureAt: string
  documentTypes: JournalVisitDetails['documentTypes']; recognitionStatus: JournalVisitDetails['recognitionStatus']; note: string; occurredAt: string
}

const blankDraft = (): Draft => ({ visitTypeOtherText: '', reasonText: '', linkedSymptomRecordIds: [], linkedVisitRecordId: '', institutionName: '', platformName: '', department: '', departmentOtherText: '', doctorName: '', doctorStatement: '', examinationTypes: [], examinationOtherText: '', followUpActions: [], followUpAt: '', followUpRelativeText: '', expectedResultAt: '', referralInstitution: '', referralDepartment: '', referralReason: '', admittedAt: '', dischargedAt: '', isCurrentlyHospitalized: false, admissionNumber: '', emergencyArrivalAt: '', emergencyDepartureAt: '', documentTypes: [], recognitionStatus: 'not_used', note: '', occurredAt: localDateTimeValue() })
const draftKey = (memberId: string) => `hoooho-visit-record-draft:${memberId}`
const visitTypes: Array<[VisitType, string]> = [['outpatient', '门诊'], ['emergency', '急诊'], ['inpatient', '住院'], ['online_consultation', '线上问诊'], ['follow_up', '复诊'], ['other', '其他']]
const departments = ['儿科', '急诊科', '皮肤科', '呼吸科', '消化科', '耳鼻喉科', '眼科', '过敏相关门诊', '其他', '不清楚']
const examinations = ['抽血', '尿液检查', '便检', '影像检查', '过敏相关检查', '呼吸相关检查', '其他']
const followUps: Array<[VisitFollowUpAction, string]> = [['home_observation', '居家观察'], ['medication_as_instructed', '按医嘱用药'], ['awaiting_results', '等待结果'], ['follow_up', '复诊'], ['referral', '转诊'], ['hospitalization', '住院'], ['other', '其他']]
const documentTypes: Array<[NonNullable<JournalVisitDetails['documentTypes']>[number], string]> = [['medical_record', '病历'], ['prescription', '处方'], ['examination_report', '检查报告'], ['receipt', '费用单'], ['other', '其他']]
const toggle = <T,>(items: T[], item: T) => items.includes(item) ? items.filter((value) => value !== item) : [...items, item]
const iso = (value: string) => value ? new Date(value).toISOString() : undefined
export function VisitRecordFlow({ memberId, token, onBack, onClose, onConfirm, onSaved }: { memberId: string; token: string; onBack: () => void; onClose: () => void; onConfirm: SaveRecord; onSaved: (message: string) => void }) {
  const [draft, setDraft] = useState<Draft>(() => { try { return { ...blankDraft(), ...JSON.parse(sessionStorage.getItem(draftKey(memberId)) ?? '{}') } } catch { return blankDraft() } })
  const [resultsOpen, setResultsOpen] = useState(false)
  const [symptomsOpen, setSymptomsOpen] = useState(false)
  const [reasonOpen, setReasonOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [confirmSparse, setConfirmSparse] = useState(false)
  const cameraRef = useRef<HTMLInputElement>(null); const albumRef = useRef<HTMLInputElement>(null)
  const photos = useQuickRecordPhotos(memberId, token, 6, 'visit')
  const { entries } = useJournal(memberId, token, 0)
  const symptomEntries = entries.filter((entry) => entry.categories?.includes('symptom')).slice(0, 12)
  const recentVisits = entries.filter((entry) => entry.categories?.includes('visit') && entry.visit?.institutionName).slice(0, 3)
  useEffect(() => { sessionStorage.setItem(draftKey(memberId), JSON.stringify(draft)) }, [draft, memberId])
  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setError('') }
  const symptomLabels = draft.linkedSymptomRecordIds.map((id) => symptomEntries.find((entry) => entry.id === id)?.content ?? '原关联记录已删除')
  const chooseFiles = (_source: 'camera' | 'album', files: FileList | null) => { photos.chooseFiles(files); if (files?.length) update('recognitionStatus', 'draft_unverified') }
  const supplementalCount = [photos.photos.length > 0, draft.doctorStatement, draft.examinationTypes.length, draft.followUpActions.length, draft.followUpAt || draft.followUpRelativeText, draft.note].filter(Boolean).length
  const save = async (confirmed = false) => {
    if (!draft.visitType) { setError('请选择怎么就医'); return }
    if (draft.visitType === 'other' && !draft.visitTypeOtherText.trim()) { setError('请填写实际就医方式'); return }
    const timestamp = Date.parse(draft.occurredAt)
    if (!Number.isFinite(timestamp) || timestamp > Date.now()) { setError('就医时间不能晚于现在'); return }
    if (!draft.reasonText.trim() && !draft.linkedSymptomRecordIds.length && !photos.photos.length && !confirmed) { setConfirmSparse(true); return }
    setSaving(true); setError('')
    try {
      const details: JournalVisitDetails = {
        visitType: draft.visitType,
        ...(draft.visitTypeOtherText.trim() ? { visitTypeOtherText: draft.visitTypeOtherText.trim() } : {}),
        ...(draft.reasonText.trim() ? { reasonText: draft.reasonText.trim() } : {}),
        ...(draft.linkedSymptomRecordIds.length ? { linkedSymptomRecordIds: draft.linkedSymptomRecordIds } : {}),
        ...(draft.linkedVisitRecordId ? { linkedVisitRecordId: draft.linkedVisitRecordId } : {}),
        ...(draft.visitType === 'online_consultation' && draft.platformName.trim() ? { platformName: draft.platformName.trim() } : {}),
        ...(draft.visitType !== 'online_consultation' && draft.institutionName.trim() ? { institutionName: draft.institutionName.trim() } : {}),
        ...(draft.department ? { department: draft.department } : {}), ...(draft.departmentOtherText.trim() ? { departmentOtherText: draft.departmentOtherText.trim() } : {}),
        ...(draft.doctorName.trim() ? { doctorName: draft.doctorName.trim() } : {}), ...(draft.doctorStatement.trim() ? { doctorStatement: draft.doctorStatement.trim() } : {}),
        ...(draft.examinationTypes.length ? { examinationTypes: draft.examinationTypes } : {}), ...(draft.examinationOtherText.trim() ? { examinationOtherText: draft.examinationOtherText.trim() } : {}),
        ...(draft.followUpActions.length ? { followUpActions: draft.followUpActions } : {}), ...(iso(draft.followUpAt) ? { followUpAt: iso(draft.followUpAt) } : {}), ...(draft.followUpRelativeText.trim() ? { followUpRelativeText: draft.followUpRelativeText.trim() } : {}),
        ...(iso(draft.expectedResultAt) ? { expectedResultAt: iso(draft.expectedResultAt) } : {}), ...(draft.referralInstitution.trim() ? { referralInstitution: draft.referralInstitution.trim() } : {}), ...(draft.referralDepartment.trim() ? { referralDepartment: draft.referralDepartment.trim() } : {}), ...(draft.referralReason.trim() ? { referralReason: draft.referralReason.trim() } : {}),
        ...(iso(draft.admittedAt) ? { admittedAt: iso(draft.admittedAt) } : {}), ...(iso(draft.dischargedAt) ? { dischargedAt: iso(draft.dischargedAt) } : {}), ...(draft.visitType === 'inpatient' ? { isCurrentlyHospitalized: draft.isCurrentlyHospitalized } : {}), ...(draft.admissionNumber.trim() ? { admissionNumber: draft.admissionNumber.trim() } : {}),
        ...(iso(draft.emergencyArrivalAt) ? { emergencyArrivalAt: iso(draft.emergencyArrivalAt) } : {}), ...(iso(draft.emergencyDepartureAt) ? { emergencyDepartureAt: iso(draft.emergencyDepartureAt) } : {}),
        ...(draft.documentTypes?.length ? { documentTypes: draft.documentTypes } : {}), ...(photos.photos.length ? { recognitionStatus: draft.recognitionStatus } : {}), ...(draft.note.trim() ? { note: draft.note.trim() } : {})
      }
      await onConfirm(visitSummary(details, symptomLabels), new Date(timestamp).toISOString(), 'text', photos.payload(), { categories: ['visit'], visit: details })
      photos.clearAfterSave(); sessionStorage.removeItem(draftKey(memberId)); onSaved('已记录'); onClose()
    } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败，请重试') } finally { setSaving(false) }
  }
  return <div className="medication-record-page-layer"><section aria-label="记录就医" aria-modal="true" className="medication-record-page visit-record-page" role="dialog">
    <header><button aria-label="返回记录新情况" disabled={saving} onClick={onBack} type="button"><ArrowLeft size={22} /></button><h1>记录就医</h1><button aria-label="关闭" disabled={saving} onClick={onClose} type="button"><X size={21} /></button></header>
    <div className="medication-record-scroll visit-record-scroll">
      <fieldset className="medication-fieldset"><legend>怎么就医？</legend><div className="visit-choice-grid">{visitTypes.map(([value, label]) => <button aria-pressed={draft.visitType === value} key={value} onClick={() => update('visitType', value)} type="button">{label}</button>)}</div>{draft.visitType === 'other' && <HohoInput label="实际就医方式" maxLength={80} onChange={(event) => update('visitTypeOtherText', event.target.value)} placeholder="写下实际就医方式" value={draft.visitTypeOtherText} />}</fieldset>
      {draft.visitType === 'inpatient' && <section className="visit-dynamic-fields"><div className="visit-datetime-row"><HohoInput label="入院时间" max={localDateTimeValue()} onChange={(event) => update('admittedAt', event.target.value)} type="datetime-local" value={draft.admittedAt} /><HohoInput disabled={draft.isCurrentlyHospitalized} label="出院时间（选填）" max={localDateTimeValue()} onChange={(event) => update('dischargedAt', event.target.value)} type="datetime-local" value={draft.dischargedAt} /></div><label className="visit-check"><input checked={draft.isCurrentlyHospitalized} onChange={(event) => { update('isCurrentlyHospitalized', event.target.checked); if (event.target.checked) update('dischargedAt', '') }} type="checkbox" />仍在住院</label><HohoInput label="住院号（选填）" onChange={(event) => update('admissionNumber', event.target.value)} value={draft.admissionNumber} /></section>}
      {draft.visitType === 'emergency' && <div className="visit-datetime-row"><HohoInput label="到达急诊时间（选填）" max={localDateTimeValue()} onChange={(event) => update('emergencyArrivalAt', event.target.value)} type="datetime-local" value={draft.emergencyArrivalAt} /><HohoInput label="离开急诊时间（选填）" max={localDateTimeValue()} onChange={(event) => update('emergencyDepartureAt', event.target.value)} type="datetime-local" value={draft.emergencyDepartureAt} /></div>}
      {draft.visitType === 'follow_up' && recentVisits.length > 0 && <section className="medication-section"><h2>关联上一次就医记录<span>（选填）</span></h2><div className="visit-symptom-list">{recentVisits.map((entry) => <label key={entry.id}><input checked={draft.linkedVisitRecordId === entry.id} onChange={() => { const selected = draft.linkedVisitRecordId === entry.id ? '' : entry.id; update('linkedVisitRecordId', selected); if (selected) { update('institutionName', entry.visit?.institutionName ?? ''); update('department', entry.visit?.department ?? '') } }} name="linked-visit" type="radio" /><span><strong>{entry.content}</strong><small>{new Date(entry.occurredAt).toLocaleDateString('zh-CN')}</small></span></label>)}</div></section>}
      <section className="medication-section"><h2>为什么去？</h2><div className="visit-primary-actions"><button aria-expanded={symptomsOpen} onClick={() => setSymptomsOpen((value) => !value)} type="button"><Link2 size={18} />关联已有症状</button><button aria-expanded={reasonOpen} onClick={() => setReasonOpen((value) => !value)} type="button">简单写一句</button></div>{symptomsOpen && <div className="visit-symptom-list">{symptomEntries.length ? symptomEntries.map((entry) => <label key={entry.id}><input checked={draft.linkedSymptomRecordIds.includes(entry.id)} onChange={() => update('linkedSymptomRecordIds', toggle(draft.linkedSymptomRecordIds, entry.id))} type="checkbox" /><span><strong>{entry.content}</strong><small>{new Date(entry.occurredAt).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</small></span></label>) : <p>当前人物还没有可关联的症状记录</p>}</div>}{draft.linkedSymptomRecordIds.length > 0 && <div className="visit-linked-tags">{symptomLabels.map((label, index) => <button key={draft.linkedSymptomRecordIds[index]} onClick={() => update('linkedSymptomRecordIds', draft.linkedSymptomRecordIds.filter((_, itemIndex) => itemIndex !== index))} type="button">{label}<X size={13} /></button>)}</div>}{reasonOpen && <HohoInput label="就医原因" maxLength={240} onChange={(event) => update('reasonText', event.target.value)} placeholder="简单说明这次为什么就医" value={draft.reasonText} />}</section>
      <section className="medication-section"><h2>{draft.visitType === 'online_consultation' ? '平台或机构（可选）' : '去了哪里？'}</h2><HohoInput label={draft.visitType === 'online_consultation' ? '平台或机构' : '医院或诊所'} onChange={(event) => update(draft.visitType === 'online_consultation' ? 'platformName' : 'institutionName', event.target.value)} placeholder={draft.visitType === 'online_consultation' ? '填写平台或机构（可选）' : '搜索或填写医院、诊所名称'} value={draft.visitType === 'online_consultation' ? draft.platformName : draft.institutionName} />{recentVisits.length > 0 && draft.visitType !== 'online_consultation' && <div className="visit-recent"><span>最近就医</span>{recentVisits.map((entry) => <button key={entry.id} onClick={() => { const visit = entry.visit!; update('institutionName', visit.institutionName ?? ''); update('department', visit.department ?? '') }} type="button">{entry.visit!.institutionName}</button>)}</div>}</section>
      <fieldset className="medication-fieldset"><legend>看了哪个科？<span>（选填）</span></legend><div className="visit-department-grid">{departments.map((item) => <button aria-pressed={draft.department === item} key={item} onClick={() => update('department', draft.department === item ? '' : item)} type="button">{item}</button>)}</div>{draft.department === '其他' && <HohoInput label="实际科室" onChange={(event) => update('departmentOtherText', event.target.value)} placeholder="填写科室名称" value={draft.departmentOtherText} />}<HohoInput label="医生姓名（选填）" onChange={(event) => update('doctorName', event.target.value)} placeholder="请输入医生姓名" value={draft.doctorName} /></fieldset>
      <section className="medication-supplement visit-results"><button aria-expanded={resultsOpen} onClick={() => setResultsOpen((value) => !value)} type="button"><span><strong>就医结果与资料（选填）</strong><small>{supplementalCount ? `已补充${supplementalCount}项` : '病历、检查、医生说明和后续安排都可以以后补充'}</small></span><ChevronDown data-open={resultsOpen} size={18} /></button>{resultsOpen && <div className="medication-supplement-body visit-results-body">
        <section><h3>上传资料（可选）</h3><div className="medication-photo-actions"><button onClick={() => cameraRef.current?.click()} type="button"><Camera size={18} />拍病历或处方</button><button onClick={() => albumRef.current?.click()} type="button"><ImagePlus size={18} />从相册选择</button></div><input ref={cameraRef} accept="image/*" capture="environment" hidden onChange={(event) => { chooseFiles('camera', event.target.files); event.currentTarget.value = '' }} type="file" /><input ref={albumRef} accept="image/jpeg,image/png,image/webp" hidden multiple onChange={(event) => { chooseFiles('album', event.target.files); event.currentTarget.value = '' }} type="file" />{photos.photos.length > 0 && <><div className="visit-document-types">{documentTypes.map(([value, label]) => <button aria-pressed={draft.documentTypes?.includes(value)} key={value} onClick={() => update('documentTypes', toggle(draft.documentTypes ?? [], value))} type="button">{label}</button>)}</div><div className="medication-recognition"><span><strong>识别结果待核对</strong><small>请按原始资料核对，也可以直接修改</small></span></div><QuickRecordPhotos limit={6} model={photos} /></>}</section>
        <label className="medication-note"><span>医生怎么说？（选填）</span><textarea maxLength={500} onChange={(event) => { update('doctorStatement', event.target.value); if (photos.photos.length) update('recognitionStatus', 'user_edited') }} placeholder="按病历原文或家长记得的内容填写" rows={3} value={draft.doctorStatement} /></label>
        <fieldset className="medication-fieldset"><legend>做了什么检查？<span>（选填）</span></legend><div className="visit-department-grid">{examinations.map((item) => <button aria-pressed={draft.examinationTypes.includes(item)} key={item} onClick={() => update('examinationTypes', toggle(draft.examinationTypes, item))} type="button">{item}</button>)}</div>{draft.examinationTypes.includes('其他') && <HohoInput label="其他检查" onChange={(event) => update('examinationOtherText', event.target.value)} value={draft.examinationOtherText} />}</fieldset>
        <fieldset className="medication-fieldset"><legend>接下来怎么处理？<span>（选填，可多选）</span></legend><small className="visit-fact-hint">请按本次就医实际情况记录</small><div className="visit-department-grid">{followUps.map(([value, label]) => <button aria-pressed={draft.followUpActions.includes(value)} key={value} onClick={() => update('followUpActions', toggle(draft.followUpActions, value))} type="button">{label}</button>)}</div>{draft.followUpActions.includes('medication_as_instructed') && <button className="visit-secondary-link" type="button">保存后补充用药记录</button>}{draft.followUpActions.includes('awaiting_results') && <HohoInput label="预计何时出结果（选填）" onChange={(event) => update('expectedResultAt', event.target.value)} type="datetime-local" value={draft.expectedResultAt} />}{draft.followUpActions.includes('follow_up') && <><HohoInput label="复诊时间（可选）" onChange={(event) => update('followUpAt', event.target.value)} type="datetime-local" value={draft.followUpAt} /><HohoInput label="或写下大约时间" onChange={(event) => update('followUpRelativeText', event.target.value)} placeholder="如大约3天后、尚未确定" value={draft.followUpRelativeText} /></>}{draft.followUpActions.includes('referral') && <><HohoInput label="转诊机构（选填）" onChange={(event) => update('referralInstitution', event.target.value)} value={draft.referralInstitution} /><HohoInput label="转诊科室（选填）" onChange={(event) => update('referralDepartment', event.target.value)} value={draft.referralDepartment} /><HohoInput label="转诊原因（选填）" onChange={(event) => update('referralReason', event.target.value)} value={draft.referralReason} /></>}</fieldset>
        <label className="medication-note"><span>备注（选填）</span><textarea maxLength={300} onChange={(event) => update('note', event.target.value)} placeholder="还可以记录其他需要说明的情况" rows={3} value={draft.note} /></label>
      </div>}</section>
      <HohoInput label="就医时间" max={localDateTimeValue()} onChange={(event) => update('occurredAt', event.target.value)} type="datetime-local" value={draft.occurredAt} />{error && <p className="medication-save-error" role="alert">{error}</p>}<div className="medication-record-save"><HohoButton disabled={saving || photos.blocked} fullWidth loading={saving} onClick={() => void save()} size="large">保存记录</HohoButton></div>
    </div>
    {confirmSparse && <div className="medication-confirm-layer" role="dialog" aria-modal="true" aria-label="确认保存"><div><h2>还没有记录本次为什么就医，仍要保存吗？</h2><p>可以保存后再继续补充。</p><HohoButton fullWidth onClick={() => { setConfirmSparse(false); void save(true) }}>仍要保存</HohoButton><HohoButton fullWidth variant="secondary" onClick={() => setConfirmSparse(false)}>返回补充</HohoButton></div></div>}
  </section></div>
}
