import { expect, test, type Page } from '@playwright/test'

async function registerMember(page: Page) {
  await page.goto('/login')
  await page.getByPlaceholder('给自己起个昵称').fill('护士站测试')
  await page.getByPlaceholder('设置一个密码').fill('12345678')
  await page.getByRole('button', { name: '注册并进入' }).click()
  await page.getByRole('button', { name: '进入 Hoooho' }).click()
  await page.goto('/family/new')
  await page.getByRole('textbox', { name: '姓名' }).fill('123')
  await page.getByRole('textbox', { name: '出生日期' }).pressSequentially('20260901')
  await page.getByRole('button', { name: '男', exact: true }).click()
  await page.getByRole('combobox', { name: '你是孩子的谁？' }).selectOption({ label: '妈妈' })
  await page.getByRole('button', { name: '添加家庭成员', exact: true }).click()
  await page.goto('/nurse-station')
}

test('护士站服务排序、开放状态和用药入口符合移动端方案', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await registerMember(page)
  await expect(page.locator('.nurse-station-member')).toHaveCSS('height', '52px')
  await expect(page.locator('.nurse-station-member')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(page.getByRole('button', { name: '就医准备', exact: true })).toHaveCSS('height', '52px')
  const services = page.locator('.nurse-service-entry')
  await expect(services).toHaveCount(5)
  await expect(services).toHaveText(['症状观察', '提醒服务', '排敏测试', '医嘱跟进', '冲突提醒'])
  for (let index = 0; index < 3; index += 1) await expect(services.nth(index)).toBeEnabled()
  for (let index = 3; index < 5; index += 1) {
    await expect(services.nth(index)).toBeDisabled()
    await expect(services.nth(index)).toHaveAttribute('aria-disabled', 'true')
  }
  await expect(page.locator('.nurse-station-visual')).toHaveCSS('border-top-width', '0px')
  await expect(page.locator('.nurse-station-visual')).toHaveCSS('box-shadow', 'none')
  await expect(page.getByText('守护任务', { exact: true })).toBeVisible()
  await expect(page.locator('.guardian-task-list')).toBeInViewport()
  expect(await page.locator('.idle-nurse-visual video').count()).toBe(3)
  await services.first().click()
  await expect(page).toHaveURL(/\/health-events$/)
  await expect(page.getByRole('dialog', { name: '记录症状' })).toBeVisible()
  await page.getByRole('button', { name: '关闭' }).click()
  await page.goto('/nurse-station')
  await page.locator('.nurse-service-entry').nth(2).click()
  await expect(page).toHaveURL(/\/health-profile\/allergy$/)
  await page.goto('/nurse-station')
  const currentServices = page.locator('.nurse-service-entry')
  await currentServices.nth(1).click()
  const reminders = page.getByRole('dialog', { name: '提醒服务' })
  await expect(reminders).toBeVisible()
  await expect(reminders.getByRole('button', { name: /用药提醒/ })).toContainText('按计划提醒用药，并记录是否已经完成')
  await reminders.getByRole('button', { name: /用药提醒/ }).click()
  await expect(page).toHaveURL(/\/health-events/)
  await expect(page.getByRole('dialog', { name: /记录用药/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
  for (const viewport of [{ width: 390, height: 844 }, { width: 320, height: 667 }, { width: 430, height: 932 }]) {
    await page.setViewportSize(viewport)
    await page.goto('/nurse-station')
    await expect(page.locator('.nurse-service-entry')).toHaveCount(5)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(viewport.width)
  }
  expect(errors).toEqual([])
})
