import { expect,test,type Page,type Locator } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { TokenService } from '../../server/auth/token-service.mjs'
import source from '../../src/features/body-location/child-data/locations.json' with { type: 'json' }
const accountId='body-locator-test-account'
const token=()=>new TokenService('body-locator-local-test-only',60*60_000).create({id:accountId})
// Deployed UI and assets are real; all business traffic is explicitly isolated.
test.beforeEach(async({context})=>{
  if(!process.env.BODY_BASE_URL)return
  await context.route('**/api/**',async route=>{
    const url=new URL(route.request().url())
    const response=await context.request.fetch(`http://127.0.0.1:4197${url.pathname}${url.search}`,{method:route.request().method(),headers:route.request().headers(),data:route.request().postData()??undefined})
    await route.fulfill({response})
  })
})
async function prepare(page:Page,memberId='body-girl'){
  memberId = `${memberId}-${test.info().project.name}`
  page.on('pageerror',error=>{throw error})
  const authToken=token()
  await page.addInitScript(({authToken,memberId,accountId})=>{
    sessionStorage.setItem('hoooho-auth-token',authToken)
    if(!sessionStorage.getItem('body-locator-initialized')){
      localStorage.setItem('hoooho-app',JSON.stringify({state:{authUser:{id:accountId},currentMemberId:memberId,members:[],profile:null},version:5}))
      sessionStorage.setItem('body-locator-initialized','true')
    }
  },{authToken,memberId,accountId})
  await page.goto('/health-events')
  await page.getByRole('button',{name:'记一下',exact:true}).click()
  await page.getByRole('dialog',{name:'记一下',exact:true}).getByRole('button',{name:'记录症状',exact:true}).click()
  const form=page.getByRole('dialog',{name:'记录症状',exact:true})
  await expect(form).toBeVisible()
  return form
}
const picker=(page:Page)=>page.getByRole('dialog',{name:'身体部位定位器',exact:true})
const item=(p:Locator,id:string)=>p.locator(`[data-location-id="${id}"]`)
async function openRegion(p:Locator,id:string){await p.locator(`[data-region-id="${id}"]`).click()}
async function back(p:Locator){await p.getByRole('button',{name:'返回全身',exact:true}).first().click();await expect(p.locator('[data-region-id="face"]')).toBeAttached()}
async function snapshot(page:Page,name:string,project:string){
  if(await picker(page).count()) await picker(page).locator('.hoho-bottom-sheet__body').evaluate(el=>{el.scrollTop=0})
  const dir=`outputs/body-locator/${process.env.BODY_EVIDENCE || 'local'}/${project}`
  await mkdir(dir,{recursive:true});await page.screenshot({path:`${dir}/${name}.png`})
}
async function noOverflow(page:Page,p:Locator){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await p.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)}

test('two-level selection, surfaces, cancellation, clearing, persisted edit and session refresh',async({page},info)=>{
  const form=await prepare(page)
  await form.getByLabel('哪里不舒服',{exact:true}).fill(`定位器验收${info.project.name}：眼下发红，足弓发痒`)
  await form.getByLabel('手动补充症状部位').fill('旧手工位置保留')
  await form.locator('.child-body-open').click()
  const p=picker(page)
  await expect(p.locator('[data-asset="assets/girl-front.png"]')).toBeVisible()
  await snapshot(page,'girl-front',info.project.name)
  await openRegion(p,'face')
  await expect(p.getByText('已选 0 个部位')).toBeVisible()
  await item(p,'face_lower_eyelid_left').click()
  await expect(item(p,'face_lower_eyelid_left')).toHaveAttribute('aria-pressed','true')
  await snapshot(page,'face-selected',info.project.name)
  await back(p);await openRegion(p,'foot_left')
  await item(p,'foot_left_arch').click()
  await expect(p.locator('[data-location-marker="foot_left_arch"]')).toHaveCount(0)
  await p.getByRole('button',{name:'足底',exact:true}).click()
  await expect(p.locator('[data-location-marker="foot_left_arch"]')).toHaveCount(1)
  await snapshot(page,'foot-selected',info.project.name)
  await p.getByRole('button',{name:'脚背',exact:true}).click()
  await expect(p.locator('[data-location-marker="foot_left_arch"]')).toHaveCount(0)
  await expect(p.getByLabel('本次已选部位')).toContainText('左足弓区域')
  await back(p);await p.getByRole('button',{name:'背面',exact:true}).click()
  await expect(p.locator('[data-asset="assets/girl-back.png"]')).toBeVisible()
  await snapshot(page,'girl-back-multiselect',info.project.name)
  await openRegion(p,'head');await expect(p.locator('[data-asset="assets/girl-back.png"]')).toBeVisible();await back(p)
  await openRegion(p,'hand_right');await expect(p.locator('[data-asset="assets/hand-right.png"]')).toBeVisible()
  await item(p,'hand_right_thumb_whole').click();await item(p,'hand_right_index_whole').click()
  await expect(p.getByText('已选 4 个部位')).toBeVisible()
  await snapshot(page,'right-hand',info.project.name)
  await item(p,'hand_right_whole').click();await expect(p.getByText('已选 3 个部位')).toBeVisible()
  await item(p,'hand_right_index_nail').click();await expect(item(p,'hand_right_whole')).toHaveAttribute('aria-pressed','false')
  await p.getByRole('button',{name:'手背',exact:true}).click()
  await expect(p.locator('[data-angle="dorsal"]')).toBeVisible()
  await snapshot(page,'right-hand-dorsal',info.project.name)
  await noOverflow(page,p)
  await p.getByRole('button',{name:'完成并返回症状记录',exact:true}).click()
  await expect(p).toHaveCount(0);await expect(form.locator('.symptom-location-tags')).toContainText('左下眼睑')
  await snapshot(page,'form-result',info.project.name)
  await form.locator('.child-body-open').click()
  await p.getByRole('button',{name:'清空全部',exact:true}).click()
  await p.getByRole('button',{name:'关闭身体部位定位器',exact:true}).click()
  await expect(form.locator('.symptom-location-tags')).toContainText('左足弓区域')
  await page.route('**/api/quick-records',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'验收保存失败'}})}),{times:1})
  await form.getByRole('button',{name:'保存',exact:true}).click()
  await expect(form.getByRole('alert')).toBeVisible()
  await expect(form).toBeVisible();await expect(form.locator('.symptom-location-tags')).toContainText('左下眼睑')
  const saving=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/quick-records')
  await form.getByRole('button',{name:'保存',exact:true}).click()
  const response=await saving;expect(response.status()).toBe(201)
  const saved=await response.json()
  const read=await page.request.get(`http://127.0.0.1:4197/api/events/${saved.eventId}/records?view=time`,{headers:{Authorization:`Bearer ${token()}`}})
  expect(read.ok()).toBe(true)
  const records=await read.json(),record=records.find((r:any)=>r.journal?.symptom?.narrative?.includes(`定位器验收${info.project.name}`))
  expect(record.journal.symptom.locations.map((v:any)=>v.id)).toEqual(['face_lower_eyelid_left','foot_left_arch','hand_right_index_nail'])
  expect(record.journal.symptom.locations[1]).toMatchObject({surface:'plantar',bodySide:'left',coverage:'specific',schemaVersion:'1.0.0',modelAtSelection:'girl'})
  await expect(form).toHaveCount(0)
  await page.reload()
  await page.locator(`[data-record-id="${record.id}"]`).click()
  const detail=page.getByRole('dialog',{name:'症状记录详情',exact:true})
  await expect(detail).toContainText('左足弓区域')
  await detail.getByRole('button',{name:'编辑症状记录',exact:true}).click()
  const editor=page.getByRole('dialog',{name:'编辑症状记录',exact:true})
  await editor.getByRole('textbox',{name:'记录内容',exact:true}).fill('历史编辑草稿保留')
  await editor.locator('.child-body-open').click()
  await expect(p.getByText('已选 3 个部位')).toBeVisible()
  await openRegion(p,'face');await item(p,'face_lower_eyelid_right').click()
  // Actual bootstrap focus recovery rotates the signed session, then reloads event/profile data.
  await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')))
  await page.waitForTimeout(800)
  await expect(p.getByText('已选 4 个部位')).toBeVisible()
  await p.getByRole('button',{name:'清空全部',exact:true}).click()
  await p.getByRole('button',{name:'完成并返回症状记录',exact:true}).click()
  await expect(editor.getByRole('textbox',{name:'记录内容',exact:true})).toHaveValue('历史编辑草稿保留')
  await editor.getByRole('button',{name:'保存',exact:true}).click()
  await expect(editor).toHaveCount(0)
  const updated=await page.request.get(`http://127.0.0.1:4197/api/events/${saved.eventId}/records?view=time`,{headers:{Authorization:`Bearer ${token()}`}})
  const result=(await updated.json()).find((r:any)=>r.id===record.id)
  expect(result.journal.symptom.locations).toEqual([]);expect(result.journal.symptom.locationText).toBe('旧手工位置保留')
})

test('direct symptom save without locator closes',async({page},info)=>{
  test.skip(info.project.name!=='iphone-se')
  const form=await prepare(page,'body-boy')
  await form.getByLabel('哪里不舒服',{exact:true}).fill('仅保存不打开定位器')
  await form.getByRole('button',{name:'保存',exact:true}).click()
  await expect(form).toHaveCount(0)
})

for(const model of ['boy','girl'] as const) test(`all ${model} dictionary regions and applicable fine entries are reachable, assets and keyboard back`,async({page},info)=>{
  test.skip(info.project.name!=='iphone-se','Complete dictionary traversal on SE; responsive flow covered in each project')
  const form=await prepare(page,`body-${model}`);await form.locator('.child-body-open').click()
  const p=picker(page);await expect(p.locator(`[data-asset="assets/${model}-front.png"]`)).toBeVisible()
  await snapshot(page,`${model}-front`,info.project.name)
  await p.getByRole('button',{name:'背面',exact:true}).click()
  await expect(p.locator(`[data-asset="assets/${model}-back.png"]`)).toBeVisible()
  await snapshot(page,`${model}-back`,info.project.name)
  let reached=0
  for(const region of source.regions){
    await openRegion(p,region.id)
    const expected=region.items.filter(i=>i.sex.includes(model)).map(i=>i.id)
    await expect(p.locator('[data-location-id]')).toHaveCount(expected.length)
    expect(await p.locator('[data-location-id]').evaluateAll(nodes=>nodes.map(node=>node.getAttribute('data-location-id')))).toEqual(expect.arrayContaining(expected))
    expect(await p.locator('[data-location-id]').count()).toBe(expected.length)
    expect(await p.locator('[data-location-id]').evaluateAll(nodes=>nodes.every(node=>node.getBoundingClientRect().height>=44))).toBe(true)
    await noOverflow(page,p)
    await item(p,expected.at(-1)!).click();await expect(item(p,expected.at(-1)!)).toHaveAttribute('aria-pressed','true')
    await item(p,expected.at(-1)!).click()
    if(['face','hand_left','foot_right'].includes(region.id))await snapshot(page,`${model}-${region.id}`,info.project.name)
    reached+=expected.length
    await back(p)
  }
  expect(reached).toBe(model==='boy'?561:562)
  await openRegion(p,'face');await page.keyboard.press('Escape');await expect(p.locator('[data-region-id="face"]')).toBeAttached()
  await page.keyboard.press('Escape');await expect(p).toHaveCount(0);await expect(form).toBeVisible()
})

test('image failure retains text selection and profile completion keeps the existing form',async({page},info)=>{
  test.skip(info.project.name!=='iphone-se','Error cases on SE')
  const form=await prepare(page,'body-unknown');await form.getByLabel('哪里不舒服',{exact:true}).fill('补全档案时保留')
  await form.locator('.child-body-open').click();const p=picker(page)
  await expect(p.getByRole('link',{name:'补全孩子档案'})).toHaveAttribute('href','/family/body-unknown-iphone-se/edit')
  await expect(p.getByRole('group',{name:'身体视图'})).toHaveCount(0)
  const popupPromise=page.waitForEvent('popup');await p.getByRole('link',{name:'补全孩子档案'}).click();const popup=await popupPromise
  await expect(popup).toHaveURL(/\/family\/body-unknown-iphone-se\/edit/)
  await popup.getByRole('button',{name:'女',exact:true}).click()
  await popup.getByRole('button',{name:'保存修改',exact:true}).click()
  await expect(popup).toHaveURL(/\/nurse-station/)
  await popup.close();await page.bringToFront();await p.getByRole('button',{name:'已补全，重新读取'}).click()
  await expect(p.locator('[data-asset="assets/girl-front.png"]')).toBeVisible()
  await page.route('**/body-locator/v1/girl-face.png',route=>route.abort())
  await openRegion(p,'face');await expect(p.getByText(/图片加载失败/)).toBeVisible()
  await item(p,'face_lower_eyelid_left').click();await expect(p.getByText('已选 1 个部位')).toBeVisible()
  await page.unroute('**/body-locator/v1/girl-face.png');await p.getByRole('button',{name:'重新加载图片'}).click()
  await expect(p.locator('[data-asset="assets/girl-face.png"]')).toBeVisible()
  await p.getByRole('button',{name:'完成并返回症状记录'}).click();await expect(form.getByLabel('哪里不舒服',{exact:true})).toHaveValue('补全档案时保留')
})

test('changing children isolates confirmed locations and preserves each form draft',async({page},info)=>{
  test.skip(info.project.name!=='iphone-se','Child isolation on SE')
  const form=await prepare(page)
  await form.getByLabel('哪里不舒服',{exact:true}).fill('女孩专属未保存描述')
  await form.locator('.child-body-open').click();const p=picker(page)
  await openRegion(p,'face');await item(p,'face_lower_eyelid_left').click()
  await p.getByRole('button',{name:'完成并返回症状记录'}).click()
  page.on('dialog',dialog=>dialog.accept())
  await form.getByRole('button',{name:'关闭',exact:true}).click();await expect(form).toHaveCount(0)
  const switchChild=async(name:string)=>{
    await page.getByRole('button',{name:'打开菜单',exact:true}).click()
    await page.getByRole('button',{name:'打开我的孩子',exact:true}).click()
    await page.getByRole('dialog',{name:'我的孩子',exact:true}).getByRole('button',{name:`切换到${name}`,exact:true}).first().click()
    await page.getByRole('button',{name:'记一下',exact:true}).click()
    await page.getByRole('dialog',{name:'记一下',exact:true}).getByRole('button',{name:'记录症状',exact:true}).click()
  }
  await switchChild('男孩验收')
  await expect(form.getByLabel('哪里不舒服',{exact:true})).toHaveValue('')
  await form.locator('.child-body-open').click();await expect(p.locator('[data-asset="assets/boy-front.png"]')).toBeVisible()
  await expect(p.getByText('已选 0 个部位')).toBeVisible()
  await p.getByRole('button',{name:'取消选择',exact:true}).click()
  await form.getByRole('button',{name:'关闭',exact:true}).click();await expect(form).toHaveCount(0)
  await switchChild('女孩验收')
  await expect(form.getByLabel('哪里不舒服',{exact:true})).toHaveValue('女孩专属未保存描述')
  await expect(form.locator('.symptom-location-tags')).toContainText('左下眼睑')
})

test('legacy unknown IDs, manual location and original marked area survive historical editing',async({page},info)=>{
  test.skip(info.project.name!=='iphone-se','Legacy round-trip on SE')
  await prepare(page,'body-boy')
  const legacy={id:'unknown-legacy-point',label:'旧图原部位',locationNumber:1,locationLayer:'surface',bodyRegion:'old-region',bodySide:'left',bodyView:'front',localRegion:'旧图原坐标描述',markedArea:'旧图 x=12 y=34'}
  const response=await page.request.post('http://127.0.0.1:4197/api/quick-records',{headers:{Authorization:`Bearer ${token()}`},data:{memberId:'body-boy-iphone-se',content:'旧部位兼容验收',occurredAt:new Date(Date.now()-5000).toISOString(),inputChannel:'text',idempotencyKey:crypto.randomUUID(),title:'旧部位兼容',journal:{categories:['symptom'],symptom:{narrative:'旧部位兼容验收',symptomCategory:'skin',keywords:[],locations:[legacy],locationText:'衣领接触处',descriptors:[],linkedRecordIds:{}}}}})
  expect(response.status()).toBe(201);const saved=await response.json()
  await page.goto(`/health-events?eventId=${saved.eventId}&recordId=${saved.recordId}`)
  const detail=page.getByRole('dialog',{name:'症状记录详情',exact:true})
  await expect(detail).toContainText('衣领接触处');await expect(detail).toContainText('旧图原部位')
  await detail.getByRole('button',{name:'编辑症状记录',exact:true}).click()
  const editor=page.getByRole('dialog',{name:'编辑症状记录',exact:true})
  await editor.locator('.child-body-open').click();const p=picker(page)
  await expect(p.locator('[data-asset="assets/boy-front.png"]')).toBeVisible()
  await expect(p.getByLabel('本次已选部位')).toContainText('旧图原部位')
  await expect(p.locator('[data-location-marker="unknown-legacy-point"]')).toHaveCount(0)
  await p.getByRole('button',{name:'完成并返回症状记录'}).click()
  await editor.getByRole('button',{name:'保存',exact:true}).click();await expect(editor).toHaveCount(0)
  const read=await page.request.get(`http://127.0.0.1:4197/api/events/${saved.eventId}/records?view=time`,{headers:{Authorization:`Bearer ${token()}`}})
  const record=(await read.json()).find((value:any)=>value.id===saved.recordId)
  expect(record.journal.symptom.locations).toEqual([legacy]);expect(record.journal.symptom.locationText).toBe('衣领接触处')
})
